#include "pch.h"
#include "./DxEffect/EffAni/DxEffAni.cpp"
#include "./DxEffect/EffAni/DxEffAniFaceOff.cpp"
//#include "./DxEffect/EffAni/DxEffAniGhosting.cpp"
#include "./DxEffect/EffAni/DxEffAniPlayer.cpp"
//#include "./DxEffect/EffAni/DxEffAniSingle.cpp"
#include "./DxEffect/EffAni/DxEffAniTrace.cpp"
