//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QuestEdit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QUESTEDIT_DIALOG            102
#define IDS_PROPSHT_CAPTION             102
#define IDD_FORMVIEW_QUEST              103
#define IDD_FORMVIEW_QUESTSTEP          104
#define IDD_INPUTIDDLG                  105
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAINFRAME              130
#define IDD_DIALOG_NPC                  130
#define ID_MENUITEM_NEW                 131
#define IDD_DIALOG_ITEM                 131
#define ID_MENUITEM_LOAD                132
#define IDD_DIALOG_SKILL                132
#define ID_MENUITEM_SAVE                133
#define IDD_DIALOG_MAP                  133
#define ID_MENUITEM_EXIT                134
#define IDD_QUESTTREE_DIALOG            135
#define IDR_MENU_QUEST_POPUP            136
#define IDR_MENU_QUEST_POPU             137
#define IDR_MENU_QUEST_POPUP1           138
#define IDD_FORMVIEW_QUEST2             139
#define IDD_DLG_INVEN_ELEMENT_EDIT      140
#define IDD_DIALOG_MOBGEN_ITEM          141
#define ID_MENUITEM_ADD                 143
#define ID_MENUITEM_DEL                 144
#define IDR_TOOLBAR1                    145
#define IDD_FORMVIEW_QUEST5             146
#define IDD_DIALOG_NPC_ACTION           146
#define IDD_LIST_DIALOG                 150
#define IDD_QUESTTREE_DIALOG1           153
#define IDC_STATIC_CONTROL              1001
#define IDC_TREE_ITEM                   1002
#define IDC_EDIT_QUEST_NID              1006
#define IDC_EDIT_TALKNPC_NAME           1007
#define IDC_EDIT_QUEST_FILENAME         1007
#define IDC_EDIT_DIEMOB_NAME            1008
#define IDC_EDIT_GUARDNPC_NAME          1009
#define IDC_EDIT_MID                    1009
#define IDC_EDIT_DIEMOB_NUM             1010
#define IDC_EDIT_NAME                   1010
#define IDC_CHECK_LIMIT_NONDIE          1011
#define IDC_EDIT_REACH_MAP_NAME         1011
#define IDC_EDIT_FIRE                   1011
#define IDC_CHECK_REPEAT                1012
#define IDC_EDIT_REACH_PX               1012
#define IDC_LIST_STEP                   1013
#define IDC_EDIT_ICE                    1013
#define IDC_CHECK_AGAIN                 1014
#define IDC_EDIT_REACH_PY               1014
#define IDC_EDIT_ELECTRIC               1014
#define IDC_EDIT_BEGIN_PARTYNUM         1015
#define IDC_EDIT_REACH_RADIUS           1015
#define IDC_EDIT_DEFENSE                1016
#define IDC_CHECK_PARTY                 1017
#define IDC_EDIT_GUARD_MAP_NAME         1017
#define IDC_EDIT_POISON                 1017
#define IDC_CHECK_ONLYONE_PROG          1018
#define IDC_EDIT_GUARD_PX               1018
#define IDC_EDIT_DAMAGE                 1018
#define IDC_CHECK_GIVEUP                1019
#define IDC_EDIT_GUARD_PY               1019
#define IDC_EDIT_SID                    1019
#define IDC_BUTTON_TALKNPC              1020
#define IDC_CHECK_PARTYQUEST            1020
#define IDC_EDIT_GIFT_EXP               1021
#define IDC_BUTTON_DIEMOB               1021
#define IDC_EDIT_TURNNUM                1021
#define IDC_EDIT_GIFT_MONEY             1022
#define IDC_BUTTON_GUARDNPC             1022
#define IDC_EDIT_SPIRIT                 1022
#define IDC_EDIT_GIFT_ELEMENT           1023
#define IDC_BUTTON_REACH_MAP            1023
#define IDC_EDIT_GIFT_LIFEP             1024
#define IDC_BUTTON_GUARD_MAP            1024
#define IDC_EDIT_GIFT_DISPK             1025
#define IDC_EDIT_GUARD_RADIUS           1025
#define IDC_EDIT_GIFT_QUEST             1026
#define IDC_EDIT_GIFT_STATP             1027
#define IDC_EDIT_GUARD_TIME             1027
#define IDC_BUTTON_REQ_QITEM_NEW        1028
#define IDC_BUTTON_REQ_QITEM_DEL        1029
#define IDC_BUTTON_NEXT                 1030
#define IDC_EDIT_STEP_COMMENT           1031
#define IDC_LIST_REQ_QITEM              1032
#define IDC_BUTTON_GIFT_SKILL_NEW       1033
#define IDC_BUTTON_STEP_NEW             1033
#define IDC_BUTTON_GIFT_SKILL_DEL       1034
#define IDC_BUTTON_REQ_STEP_DEL         1034
#define IDC_LIST_DEL_QITEM              1035
#define IDC_BUTTON_DEL_QITEM_NEW        1036
#define IDC_EDIT_TITLE                  1037
#define IDC_BUTTON_DEL_QITEM_DEL        1037
#define IDC_EDIT_COMMENT                1038
#define IDC_BUTTON_REQ_QITEM_EDIT       1038
#define IDC_EDIT_BEGIN_MONEY            1039
#define IDC_EDIT_TALKNPC_COMMENT        1039
#define IDC_EDIT_GIFT_SKILLP            1040
#define IDC_BUTTON_GIFT_QITEM_EDIT      1040
#define IDC_LIST_GIFT_ITEM              1041
#define IDC_EDIT_DIEMOB_COMMENT         1041
#define IDC_LIST_GIFT_SKILL             1042
#define IDC_EDIT_GUARDNPC_COMMENT       1042
#define IDC_BUTTON_GIFT_ITEM_NEW        1043
#define IDC_LIST_GIFT_QITEM             1043
#define IDC_BUTTON_GIFT_ITEM_DEL        1044
#define IDC_BUTTON_GIFT_QITEM_NEW       1044
#define IDC_BUTTON_GIFT_ITEM_EDIT       1045
#define IDC_BUTTON_GIFT_QITEM_DEL       1045
#define IDC_EDIT_LIMIT_PARTYNUM         1046
#define IDC_EDIT_REACH_MAP_COMMENT      1046
#define IDC_EDIT_LIMIT_TIME             1047
#define IDC_EDIT_GUARD_MAP_COMMENT      1047
#define IDC_BUTTON_PREV                 1048
#define IDC_EDIT_REQ_QITEM_COMMENT      1049
#define IDC_LIST_NPC                    1051
#define IDC_BUTTON_EDITCOMPLATE         1051
#define IDC_LIST_ITEM                   1052
#define IDC_BUTTON_QUEST_AREA           1052
#define IDC_LIST_MAP                    1053
#define IDC_LIST_SKILL                  1054
#define IDC_BUTTON_TALKNPC_DEL          1055
#define IDC_CHECK_FIGHETER              1055
#define IDC_BUTTON_DIEMOB_DEL           1056
#define IDC_CHECK_SPIRIT                1056
#define IDC_BUTTON_GUARDNPC_DEL         1057
#define IDC_CHECK_ARCHER                1057
#define IDC_BUTTON_REACH_MAP_DEL        1058
#define IDC_CHECK_FIGHETER_W            1058
#define IDC_BUTTON_GUARD_MAP_DEL        1059
#define IDC_CHECK_EXTREME_W             1059
#define IDC_STATIC_COMMENT              1060
#define IDC_CHECK_ARCHER_W              1060
#define IDC_STATIC_REQ_QITEM            1061
#define IDC_CHECK_SPIRIT_W              1061
#define IDC_STATIC_RESET_QITEM          1062
#define IDC_CHECK_SCIENTIST_W           1062
#define IDC_STATIC_REACH                1063
#define IDC_CHECK_ASSASSIN_W            1063
#define IDC_STATIC_COMMENT2             1064
#define IDC_CHECK_ETC_W                 1064
#define IDC_CHECK_EXTREME_W3            1064
#define IDC_CHECK_ARMS                  1065
#define IDC_CHECK_ETC_W2                1065
#define IDC_STATIC_DEFENSE              1066
#define IDC_CHECK_ARMS_W                1066
#define IDC_STATIC_REACH_R              1067
#define IDC_STATIC_DEFENSE_R            1068
#define IDC_STATIC_DEFENSE_T            1069
#define IDC_BUTTON_STEP_OK              1070
#define IDC_EDIT_GEN_NUM                1071
#define IDC_STATIC_GIFT_QITEM           1072
#define IDC_EDIT_GEN_RATE               1072
#define IDC_BUTTON_GEN_MOB_ADD          1073
#define IDC_BUTTON_GEN_MOB_DEL          1075
#define IDC_LIST_GEN_MOB                1076
#define IDC_BUTTON_GENITEM              1077
#define IDC_EDIT_GENITEM                1078
#define IDC_EDIT_EDITVERSION            1079
#define IDC_EDIT_STEP_TITLE             1080
#define IDC_BUTTON_UP                   1081
#define IDC_BUTTON_DOWN                 1082
#define IDC_EDIT_START_ITEM_MID         1082
#define IDC_EDIT_START_ITEM_SID         1083
#define IDC_EDIT1                       1083
#define IDC_EDIT_LEVEL                  1083
#define IDC_EDIT_NEW_ID                 1083
#define IDC_EDIT_START_SKILL_MID        1084
#define IDC_STATIC_LEVEL                1084
#define IDC_EDIT_START_SKILL_SID        1085
#define IDC_EDIT_STEP_NUM               1085
#define IDC_EDIT_START_QUEST_MAP_MID    1086
#define IDC_EDIT_TALKNPC_NUM            1086
#define IDC_EDIT_START_QUEST_MAP_SID    1087
#define IDC_EDIT_TALKNPC_NUM2           1087
#define IDC_EDIT_START_QUEST_MAP_X      1088
#define IDC_EDIT_TALKNPC_NUM3           1088
#define IDC_EDIT_START_QUEST_MAP_Y      1089
#define IDC_EDIT_STEP_ALLNUM            1089
#define IDC_EDIT_START_LEVEL            1090
#define IDC_BUTTON_FIND                 1090
#define IDC_EDIT_START_QUEST_MAP_RADIUS 1091
#define IDC_COMBO_SCHOOL                1092
#define IDC_EDIT_QUEST_AREA_NAME        1092
#define IDC_CHECK_EXTREME_M             1093
#define IDC_BUTTON_EDITCANCEL           1094
#define IDC_CHECK_FIGHETER_M            1095
#define IDC_CHECK_ARCHER_M              1096
#define IDC_CHECK_ARMS_M                1097
#define IDC_CHECK_SPIRIT_M              1098
#define IDC_STATE_COMBO1                1099
#define IDC_STATE_COMBO2                1100
#define IDC_STATE_COMBO3                1101
#define IDC_FAIL_CHECK1                 1102
#define IDC_FAIL_CHECK2                 1103
#define IDC_FAIL_CHECK3                 1104
#define IDC_MAP_SELECT_COMBO            1105
#define IDC_CHECK_SCIENTIST_M           1105
#define IDC_MAP_EDIT_BUTTON             1106
#define IDC_MAP_MID_EDIT                1107
#define IDC_MAP_SID_EDIT                1108
#define IDC_LIST_MAP_SELECT             1108
#define IDC_MAP_XPOS_EDIT               1109
#define IDC_MAP_YPOS_EDIT               1110
#define IDC_MAP_GATE_EDIT               1111
#define IDC_USE_PROGRESS_CHECK          1112
#define IDC_STEP_MAP_EDIT_BUTTON        1112
#define IDC_BUTTON_MOVEMAP              1113
#define IDC_STEP_MAP_MID_EDIT           1113
#define IDC_CHECK_ASSASSIN_M            1113
#define IDC_STEP_MAP_SID_EDIT           1114
#define IDC_MAP_EDIT_BUTTON2            1114
#define IDC_STEP_MAP_XPOS_EDIT          1115
#define IDC_MAP_MID_EDIT2               1115
#define IDC_STEP_MAP_YPOS_EDIT          1116
#define IDC_MAP_SID_EDIT2               1116
#define IDC_STEP_MAP_GATE_EDIT          1117
#define IDC_MAP_XPOS_EDIT2              1117
#define IDC_STEP_MAPID_STATIC           1118
#define IDC_MAP_YPOS_EDIT2              1118
#define IDC_STEP_XY_STATIC              1119
#define IDC_MAP_GATE_EDIT2              1119
#define IDC_STEP_GATE_STATIC            1120
#define IDC_MAP_EDIT_BUTTON3            1120
#define IDC_RADIO_ALL                   1121
#define IDC_RADIO_MAN                   1122
#define IDC_RADIO_WOMAN                 1123
#define IDC_LISTCTR_GIFT_ITEM           1124
#define IDC_MAP_MID_EDIT3               1125
#define IDC_STATIC_MOVEMAP              1125
#define IDC_MAP_SID_EDIT3               1126
#define IDC_STATIC_CONDITION            1126
#define IDC_MAP_XPOS_EDIT3              1127
#define IDC_MAP_YPOS_EDIT3              1128
#define IDC_MAP_GATE_EDIT3              1129
#define IDC_RADIO_SCHOOL1               1130
#define IDC_RADIO_SCHOOL2               1131
#define IDC_RADIO_SCHOOL3               1132
#define IDC_RADIO_SCHOOL_ALL            1133
#define IDC_CHECK_ETC_M                 1134
#define IDC_LIST1                       1136
#define IDC_LIST_NPC_ACTION_SUMMARY     1136
#define IDC_STATIC_NPC_ACTION1          1137
#define IDC_LIST_NPC_ACTION_NOTE        1138
#define IDC_STATIC_QUEST_SCHOOL         1140
#define IDC_RADIO_QUEST_SCHOOL          1141
#define IDC_RADIO2                      1142
#define IDC_RADIO3                      1143
#define IDC_RADIO4                      1144
#define IDC_CHECK_CLASS_FIGHT           1145
#define IDC_EDIT_FINDMID                1146
#define IDC_CHECK_CLASS_ARCHER          1146
#define IDC_EDIT_FINDSID                1147
#define IDC_CHECK_CLASS_FENCING         1147
#define IDC_CHECK_CLASS_SPIRIT          1148
#define IDC_CHECK_CLASS_EXTREAM         1149
#define IDC_CHECK_CLASS_SCIENTIST       1150
#define IDC_CHECK_CLASS_ASSASSIN        1151
#define IDC_CHECK8                      1152
#define IDC_CHECK_CLASS_ETC             1152
#define IDC_CHECK_DAYOFWEEK_PRIORITY_ALL 1152
#define IDC_RADIO_TIMEOVER1             1153
#define IDC_RADIO_TIMEOVER2             1154
#define IDC_CHECK_PAST_ON_ONLINE        1155
#define IDC_CHECK_TOKILLPLAYER          1157
#define IDC_EDIT_ITEMUSE_COMMENT        1158
#define IDC_BUTTON_ITEMUSE              1159
#define IDC_EDIT_ITEMUSE_NAME           1160
#define IDC_EDIT_ITEMUSE_ID             1161
#define IDC_BUTTON_ITEMUSE_DEL          1162
#define IDC_EDIT_ITEMUSE_NUM            1163
#define IDC_RADIO_ITEMGRINDING1         1164
#define IDC_EDIT_ITEMGRINDING_COMMENT   1165
#define IDC_BUTTON_ITEMGRINDING         1166
#define IDC_EDIT_ITEMGRINDING_NAME      1167
#define IDC_EDIT_ITEMGRINDING_ID        1168
#define IDC_BUTTON_ITEMGRINDING_DEL     1169
#define IDC_EDIT_ITEMGRINDING_NUM       1170
#define IDC_RADIO_ITEMGRINDING2         1171
#define IDC_RADIO_ITEMGRINDING3         1172
#define IDC_RADIO_ITEMGRINDING4         1173
#define IDC_CHECK_CONSECUTION           1174
#define IDC_RADIO_CONFTING1             1176
#define IDC_EDIT_CONFTING_NUM           1177
#define IDC_EDIT_CONFTING_COMMENT       1178
#define IDC_RADIO_CONFTING2             1179
#define IDC_RADIO_CONFTING3             1180
#define IDC_RADIO_CONFTING4             1181
#define IDC_BUTTON_CONFTING_DEL         1182
#define IDC_RADIO_CONFTING5             1183
#define IDC_STATIC_CONFTING             1184
#define IDC_CHECK_DAILY                 1185
#define IDC_RADIO_AUTO_START_NONE       1186
#define IDC_RADIO_AUTO_START_ATTENDANCE 1187
#define IDC_RADIO_AUTO_START_JOIN_START 1188
#define IDC_COMBO_ATTENDANCE_TYPE       1189
#define IDC_EDIT_LEVEL_LIMIT_MIN        1190
#define IDC_EDIT_LEVEL_LIMIT_MAX        1191
#define IDC_CHECK_DAYOFWEEK_PRIORITY_SUN 1192
#define IDC_CHECK_DAYOFWEEK_PRIORITY_MON 1193
#define IDC_CHECK_DAYOFWEEK_PRIORITY_TUE 1194
#define IDC_CHECK_DAYOFWEEK_PRIORITY_WED 1195
#define IDC_CHECK_DAYOFWEEK_PRIORITY_THU 1196
#define IDC_SELECT_LIST                 1197
#define IDC_CHECK_DAYOFWEEK_PRIORITY_FRI 1197
#define IDC_CHECK_DAYOFWEEK_PRIORITY_SAT 1198
#define IDC_COMBO_START_YEAR            1200
#define IDC_COMBO_START_MONTH           1201
#define IDC_COMBO_START_DAY             1202
#define IDC_COMBO_END_YEAR              1203
#define IDC_COMBO_END_MONTH             1204
#define IDC_EDIT_LEVEL_UP_COMMENT       1204
#define IDC_COMBO_END_DAY               1205
#define IDC_BUTTON_LEVEL_UP_DEL         1205
#define IDC_EDIT_LEVEL_UP_NUM           1206
#define IDC_CHECK1                      1208
#define IDC_CHECK_ADDITIONALQUEST       1208
#define IDC_CHECK_CLASS_TRICKER         1209
#define IDC_CHECK_TRICKER_M             1210
#define IDC_CHECK_CLASS_ACTOR           1210
#define IDC_CHECK_CLASS_TRICKER2        1210
#define IDC_CHECK_TRICKER_W             1211
#define IDC_CHECK_CLASS_ACTOR2          1211
#define IDC_CHECK_ACTOR_M               1212
#define IDC_CHECK_ACTOR_W               1213
#define ID_MENUITEM_COPY                32771
#define ID_MENUITEM_PASTE_VALUE         32774
#define ID_MENUITEM_PASTE_NEW           32775
#define ID_MENUITEM_CSV_S1              32777
#define ID_MENUITEM_CSV_LO              32777
#define ID_BUTTON32778                  32778
#define ID_MENUITEM_CSV_SA              32778
#define ID_MENUITEM_QUESTSTEP_MODIFY    32782
#define ID_MENUITEM_QUEST_MODIFY        32783
#define ID_MENUITEM_TEXT_IMPORT         32787
#define ID_MENUITEM_TEXT_EXPORT         32788
#define ID_FILE_EXCELTXT                32789
#define ID_FILE_EXCELTXT32790           32790
#define ID_FILE_EXCELTXT_EXPORT         32791
#define ID_FILE_EXCELTXT_IMPORT         32792
#define ID_MENUITEM_EXCELTXT_EXPORT     32793
#define ID_MENUITEM_EXCELTXT_IMPORT     32794
#define ID_FILE_EXCELTXT32795           32795
#define ID_FILE_EXCELTXT32796           32796
#define ID_FILE_EXCELTXT32797           32797
#define ID_FILE_EXCELTXT32798           32798
#define ID_FILE_EXCELTXT32799           32799
#define ID_FILE_EXCELTXT32800           32800
#define ID_FILE_EXCELTXT32801           32801
#define ID_FILE_EXCELTXT32802           32802
#define ID_FILE_EXCELTXT32803           32803
#define ID_FILE_EXCELTXT32804           32804
#define ID_MENUITEM_XMLCONVERT          32806
#define ID_FILE_XMLCONVERT              32807
#define ID_FILE_XMLCONVERT32808         32808
#define ID_FILE_XMLCONVERT32809         32809
#define ID_FILE_XMLCONVERT32810         32810
#define ID_FILE_XMLCONVERT32811         32811
#define ID_FILE_XMLCONVERT32812         32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1212
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
