//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AutoPatchMan.rc
//
#define IDR_MANIFEST                    1
#define ABOUT_BOX_ID_OK                 1
#define DOWNAREA_ID_OK                  2
#define GAMESET_ID_CANCEL               3
#define GAMESET_ID_OK                   4
#define IDC_SOUND_OPTION5               5
#define IDS_MESSAGE74                   6
#define IDC_GRAPHIC_OPTION13            7
#define IDC_GRAPHIC_OPTION14            8
#define IDC_GRAPHIC_OPTION15            9
#define IDC_GRAPHIC_OPTION16            10
#define IDS_MESSAGE75                   11
#define IDS_MESSAGE76                   12
#define IDS_STRING13                    13
#define IDS_STRING14                    14
#define IDS_STRING15                    15
#define IDS_STRING16                    16
#define IDS_MESSAGE77                   16
#define IDS_MESSAGE78                   17
#define IDC_GRAPHIC_OPTION17            18
#define IDD_ABOUTBOX                    100
#define IDD_AUTOPATCHMAN_DIALOG         102
#define IDD_GAMESETDLG                  104
#define WARNING_ID_OK                   105
#define IDS_WHQL_CVD                    106
#define IDS_WHQL_UCVD                   107
#define IDS_ABOUTBOX                    108
#define IDC_GRAPHIC_OPTION              109
#define IDC_GRAPHIC_OPTION0             109
#define IDC_GRAPHIC_OPTION1             110
#define IDC_GRAPHIC_OPTION2             111
#define IDC_GRAPHIC_OPTION3             112
#define IDC_GRAPHIC_OPTION4             113
#define IDC_GRAPHIC_OPTION5             114
#define IDC_GRAPHIC_OPTION6             115
#define IDC_GRAPHIC_OPTION7             116
#define IDC_GRAPHIC_OPTION8             117
#define IDC_GRAPHIC_OPTION9             118
#define IDC_GRAPHIC_OPTION10            119
#define IDC_GRAPHIC_OPTION11            120
#define IDC_GRAPHIC_OPTION12            121
#define IDC_SOUND_OPTION                122
#define IDC_SOUND_OPTION0               122
#define IDC_SOUND_OPTION1               123
#define IDC_SOUND_OPTION2               124
#define IDC_SOUND_OPTION3               125
#define IDC_SOUND_OPTION4               126
#define IDS_MESSAGE                     127
#define IDS_MESSAGE0                    127
#define IDR_MAINFRAME                   128
#define IDS_MESSAGE1                    128
#define IDS_MESSAGE2                    129
#define IDR_MAINFRAME_CH                130
#define IDS_MESSAGE3                    130
#define IDS_MESSAGE4                    131
#define IDR_MAINFRAME_MY                132
#define IDS_MESSAGE5                    132
#define IDS_MESSAGE6                    133
#define IDS_MESSAGE7                    134
#define IDS_MESSAGE8                    135
#define IDS_MESSAGE9                    136
#define IDS_MESSAGE10                   137
#define IDS_MESSAGE11                   138
#define IDS_MESSAGE12                   139
#define IDS_MESSAGE13                   140
#define IDS_MESSAGE14                   141
#define IDS_MESSAGE15                   142
#define IDS_MESSAGE16                   143
#define IDS_MESSAGE17                   144
#define IDS_MESSAGE18                   145
#define IDS_MESSAGE19                   146
#define IDS_MESSAGE20                   147
#define IDS_MESSAGE21                   148
#define IDS_MESSAGE22                   149
#define IDS_MESSAGE23                   150
#define IDS_MESSAGE24                   151
#define IDS_MESSAGE25                   152
#define IDS_MESSAGE26                   153
#define IDS_MESSAGE27                   154
#define IDD_DIALOG_WARNING_WHQL         155
#define IDS_MESSAGE28                   156
#define IDS_MESSAGE29                   157
#define IDS_MESSAGE30                   158
#define IDS_MESSAGE31                   159
#define IDS_MESSAGE32                   160
#define IDS_MESSAGE33                   161
#define IDS_MESSAGE34                   162
#define IDS_MESSAGE35                   163
#define IDS_MESSAGE36                   164
#define IDS_MESSAGE37                   165
#define IDS_MESSAGE38                   166
#define IDS_MESSAGE39                   167
#define IDD_DIALOG_DOWNLOAD_AREA        170
#define IDD_GAMESETDLG1                 171
#define IDS_MESSAGE40                   175
#define IDD_GAMESETDLG2                 175
#define IDS_MESSAGE41                   176
#define IDS_MESSAGE42                   177
#define IDS_MESSAGE43                   178
#define IDS_MESSAGE44                   179
#define IDS_MESSAGE45                   180
#define IDS_MESSAGE46                   181
#define IDS_MESSAGE47                   182
#define IDS_MESSAGE48                   183
#define IDS_MESSAGE49                   184
#define IDS_MESSAGE50                   185
#define IDS_MESSAGE51                   186
#define IDS_MESSAGE52                   187
#define IDS_MESSAGE53                   188
#define IDS_MESSAGE54                   189
#define IDS_MESSAGE55                   190
#define IDS_MESSAGE56                   191
#define IDS_MESSAGE57                   192
#define IDS_MESSAGE58                   193
#define IDS_MESSAGE59                   194
#define IDS_MESSAGE60                   195
#define IDS_MESSAGE61                   196
#define IDS_MESSAGE62                   197
#define IDS_MESSAGE63                   198
#define IDS_MESSAGE64                   199
#define IDS_MESSAGE65                   200
#define IDS_MESSAGE66                   201
#define IDS_MESSAGE67                   202
#define IDS_MESSAGE68                   203
#define IDS_MESSAGE69                   204
#define IDS_MESSAGE70                   205
#define IDS_MESSAGE71                   206
#define IDS_MESSAGE72                   207
#define IDS_MESSAGE73                   208
#define IDI_ICON1                       210
#define IDR_MAINFRAME_TW                210
#define IDB_BITMAP_BACKIMAGE            211
#define IDI_CHECKON                     223
#define IDI_CHECK_ON                    223
#define IDI_CHECKOFF                    224
#define IDI_CHECK_OFF                   224
#define IDB_BITMAP_STARTBUTTON_DOWN     228
#define IDB_BITMAP_START_DN             228
#define IDB_BITMAP_STARTBUTTON_DIS      229
#define IDB_BITMAP_START_DIS            229
#define IDB_BITMAP_STARTBUTTON_NOR      230
#define IDB_BITMAP_START_NOR            230
#define IDB_BITMAP4                     231
#define IDB_BITMAP_STARTBUTTON_OVER     231
#define IDB_BITMAP_START_ON             231
#define IDB_BITMAP_OPTION_ON            232
#define IDB_BITMAP_OPTION_DN            233
#define IDB_BITMAP3                     234
#define IDB_BITMAP_OPTION_NOR           234
#define IDB_BITMAP_ITEM_ON              235
#define IDB_BITMAP_EVENT_DN             236
#define IDB_BITMAP_EVENT_NOR            237
#define IDB_BITMAP_EVENT_ON             238
#define IDB_BITMAP_ITEM_DW              239
#define IDB_BITMAP_ITEM_DN              239
#define IDB_BITMAP_ITEM_NOR             240
#define IDB_BITMAP_TITLEIMAGE           245
#define IDB_BITMAP_EXIT_ON              246
#define IDB_BITMAP_EXIT_DN              247
#define IDB_BITMAP_EXIT_NOR             248
#define IDB_BITMAP1                     250
#define IDB_BMP_AQUA2                   250
#define IDB_BITMAP5                     252
#define IDB_BITMAP_BACK                 252
#define IDB_BITMAP2                     253
#define IDB_BITMAP_IN                   253
#define IDB_BITMAP_PROGRESS             255
#define IDB_VERTICLE_SCROLLBAR_UPARROW  256
#define IDB_VERTICLE_SCROLLBAR_DOWNARROW 262
#define IDB_VERTICLE_SCROLLBAR_SPAN     263
#define IDB_VERTICLE_SCROLLBAR_THUMB    264
#define IDB_BITMAP_SLIDER_BACK          266
#define IDB_BITMAP_SLIDER_DRAG          267
#define IDB_COMBO_CEN                   270
#define IDB_COMBO_LEFT                  271
#define IDB_COMBO_RIGHT                 272
#define IDB_LIST_TOP                    274
#define IDB_LIST_LEFT                   275
#define IDB_BITMAP_OPTIONBACK           281
#define IDI_RADIO_ON                    282
#define IDI_RADIO_OFF                   283
#define IDB_BITMAP_SOUND_ON             284
#define IDB_BITMAP_DOWN_BACK            285
#define IDB_BITMAP_CANCEL_DN            286
#define IDB_BITMAP_CANCEL_NOR           287
#define IDB_BITMAP_CANCEL_ON            288
#define IDB_BITMAP_OK_DN                289
#define IDB_BITMAP_OK_NOR               290
#define IDB_BITMAP_OK_ON                291
#define IDB_BITMAP_SOUND_DN             292
#define IDB_BITMAP_SOUND_NOR            293
#define IDB_BITMAP_BACK_LOGO            295
#define IDB_BITMAP_RETRY_ON             296
#define IDB_BITMAP_RETRY_DN             297
#define IDB_BITMAP_RETRY_NOR            298
#define IDB_BITMAP_LIST_BACK            299
#define IDI_CHECK_DIS                   300
#define IDB_BITMAP_UPDATE_ON            301
#define IDB_BITMAP_UPDATE_DN            302
#define IDB_BITMAP_UPDATE_NOR           303
#define IDB_BITMAP_OPTION_DIS           304
#define IDB_BITMAP_RETRY_DIS            305
#define IDB_BITMAP_UPDATE_DIS           306
#define IDD_AUTOPATCHMAN_DIALOG2        313
#define IDB_BITMAP6                     314
#define IDB_BITMAP_BACK_LOGO_TW         314
#define IDB_BITMAP7                     317
#define IDB_BITMAP_BACK_LOGO_JP         317
#define IDD_DIALOG1                     318
#define IDD_DIALOG_VTC_GUARD_UPDATE     318
#define IDB_BITMAP_MANUALPATCH_DN       319
#define IDB_BITMAP_MANUALPATCH_NOR      320
#define IDB_BITMAP_manualpatch_ON       321
#define IDB_BITMAP__ON                  321
#define IDC_BUTTON_EXIT                 1002
#define IDC_BUTTON_START                1003
#define IDC_PROGRESS_ALL                1004
#define IDC_BUTTON_RETRY                1005
#define IDC_PROGRESS_CUR                1006
#define IDC_BUTTON_UPDATE               1007
#define IDC_STATIC_NOTIFY               1010
#define IDC_COMBO_RESOLUTION            1013
#define IDC_SLIDER_BGM                  1018
#define IDC_SLIDER_SFX                  1019
#define IDC_SLIDER_MAP                  1020
#define IDC_BUTTON_OPTION               1025
#define IDC_COMBO_HZ                    1026
#define IDC_BUTTON_ITEMLINK             1026
#define IDC_BUTTON_ITEM                 1026
#define IDC_BUTTON_OPTION3              1027
#define IDC_BUTTON_EVENTLINK            1027
#define IDC_BUTTON_EVENT                1027
#define IDC_CHECK_SHADOWLAND            1028
#define IDC_CHECK_REALREFLECT           1029
#define IDC_CHECK_REFRACT               1030
#define IDC_COMBO_SHADOWCHAR            1031
#define IDC_COMBO_3DALGORITHM           1032
#define IDC_BUTTON_COMPATIBLE           1033
#define IDC_CHECK_GLOW                  1034
#define IDC_CHECK_NOCHECK               1035
#define IDC_COMBO_SKINDETAIL            1036
#define IDC_CHECK_GAMECURSOR            1037
#define IDC_STATIC_ATI_LINK             1038
#define IDC_CHECK_TARGETEFFECT          1038
#define IDC_CHECK_BUFFEFFECT            1039
#define IDC_CHECK_BGM                   1040
#define IDC_LIST_LOG                    1041
#define IDC_COMBO_SKINDETAIL2           1041
#define IDC_CHECK_MAP                   1042
#define IDC_CHECK_SFX                   1043
#define IDC_COMBO_FOGRANGE              1044
#define IDC_CHECK_TEXTURE_FONT          1045
#define IDC_CHECK_PASSIVE               1046
#define IDC_CHECK_USE_HTTP              1047
#define IDC_CHECK_FRAME_LIMIT           1047
#define IDC_BUTTON_PATCH                1048
#define IDC_CHECK_CLICKEFFECT           1048
#define IDC_CHECK_WINDOWMODE            1049
#define IDC_COMBO_DEFAULTOPTION         1050
#define IDC_CHECK_3DSOUND               1051
#define IDC_READYTOSTART                1052
#define IDC_CHECK_MINEEFFECT            1052
#define IDC_RADIO_AREA1                 1053
#define IDC_CHECK_NORMALMAP             1053
#define IDC_CHECK_POSTPROCESSING        1054
#define IDC_RADIO_AREA2                 1055
#define IDC_CHECK_ALL_MINIMUM           1055
#define IDC_CHECK_WINDOWMODE2           1055
#define IDC_RADIO_AREA3                 1056
#define IDC_RADIO_AREA4                 1057
#define IDC_RADIO1                      1058
#define IDC_RADIO_AREA5                 1058
#define IDC_RADIO2                      1059
#define IDC_RADIO_AREA6                 1059
#define IDC_RADIO3                      1060
#define IDC_RADIO_AREA7                 1060
#define IDC_VER_STATIC                  1061
#define IDC_RADIO5                      1061
#define IDC_RADIO4                      1062
#define IDC_TITLE_STATIC                1063
#define IDC_RADIO6                      1063
#define IDC_AREA_STATIC                 1064
#define IDC_RADIO7                      1064
#define IDC_VIDEO_STATIC                1065
#define IDC_NVIDIA_STATIC               1066
#define IDC_ATI_STATIC                  1067
#define IDC_DISPLAY_STATIC              1068
#define IDC_GRAPHIC_STATIC              1069
#define IDD_ABOUT_BOX                   1069
#define IDC_DEFAULT_OPTION_STATIC       1070
#define IDC_FOGRANGE_STATIC             1071
#define IDC_SHADOWCHAR_STATIC           1072
#define IDC_SOUND_STATIC                1073
#define IDC_BGM_STATIC                  1074
#define IDC_MAP_STATIC                  1075
#define IDC_SFX_STATIC                  1076
#define IDC_DOWNLOAD_STATIC             1077
#define IDC_DOWNAREA_STATIC             1078
#define IDC_STATIC_NVIDIA_LINK          1079
#define IDC_SKINDETAIL_STATIC           1080
#define IDM_ABOUTBOX                    1081
#define IDC_TITLE_IMAGE                 1083
#define IDC_STATIC_DOWNLOAD             1084
#define IDC_STATIC_DOWNLOAD2            1085
#define IDC_PROGRESS_CUR_NEW            1086
#define IDC_STATIC_DOWNLOAD3            1086
#define IDC_STATIC_HOMEPAGE             1087
#define IDC_STATIC_HOMEPAGE2            1088
#define IDC_STATIC_BACK_LOGO            1089
#define IDC_NATION_STATIC               1090
#define IDC_COMBO_NATION                1092
#define IDC_MNATION_STATIC              1093
#define IDC_COMBO1                      1094
#define IDC_MNATION_COMBO               1094

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
