//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CharEdit.rc
//
#define IDOK3                           2
#define IDOK2                           3
#define ID_BUTTON_PARAMETER_INSERT      3
#define ID_BUTTON_PARAMETER_DELETE      4
#define ID_BUTTON_PARAMETER_MODIFY      5
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_SOUNDPAGE            103
#define IDR_HTML_STRIKEPAGE             104
#define IDR_HTML_ATTBONEANIEDITPAGE     105
#define IDR_MAINFRAME                   128
#define IDR_CHAREDTYPE                  129
#define IDD_DIALOG_EDIT                 130
#define IDD_DIALOG_TIMELINE             136
#define IDD_DIALOG_ANIM                 141
#define IDD_DIALOG_ANIMSET              142
#define IDR_POPUP_ANIMATION             143
#define IDD_DIALOG_FRAME                144
#define IDD_DIALOG_FRAMESET             145
#define IDR_POPUP_FRAME                 147
#define IDB_BITMAP_RGB                  155
#define IDB_BITMAP_HSB                  156
#define IDD_DIALOG_CHARPAGE             168
#define IDD_DIALOG_SKINOBJPAGE          169
#define IDD_DIALOG_SKINPIECEPAGE        170
#define IDD_DIALOG_ANIDIV               172
#define IDD_DIALOG_EFF_SINGLE           173
#define IDD_DIALOG_EFF_BLUR             174
#define IDD_DIALOG_COLORS               175
#define IDD_DIALOG_EFF_CLONEBLUR        180
#define IDD_DIALOG_EFF_REFLECTION       181
#define IDD_DIALOG_EFF_DUST             181
#define IDD_DIALOG_EFF_ATTRIBUTE        182
#define IDD_DIALOG_EFF_ELECTRICITY      183
#define IDD_DIALOG_EFF_SHOCK            183
#define IDD_DIALOG_SETMULTISLIDER       184
#define IDD_DIALOG_SETVER               185
#define IDD_DIALOG_EFF_ARROW            186
#define IDD_DIALOG_CUBEMAP              187
#define IDD_DIALOG_SPECULAR             188
#define IDD_DIALOG_EFF_SPECULAR         188
#define IDD_DIALOG_EFF_SPECULAR2        189
#define IDD_DIALOG_EFF_HIGH             190
#define IDD_DIALOG_EFF_ALPHA            191
#define IDD_DIALOG_NEON                 192
#define IDD_DIALOG_EFF_NEON             192
#define IDD_DIALOG1                     193
#define IDD_DIALOG_STRIKE               193
#define IDD_DIALOG_EFF_NOALPHA          194
#define IDD_DIALOG_EFF_REFLECTION2      195
#define IDD_DIALOG_EFF_AMBIENT          196
#define IDD_DIALOG_EFF_DOT3             197
#define IDD_DIALOG_EFF_MULTITEX         198
#define IDD_DIALOG_EFF_MARK             199
#define IDD_DIALOG_EFF_GHOSTING         200
#define IDD_DIALOG_EFFANI               201
#define IDD_DIALOG_EFFANI_SINGLE        202
#define IDD_DIALOG_EFFANI_GHOSTING      203
#define IDD_DIALOG_SOUNDSOURCE          204
#define IDD_DIALOG_MATERIAL             205
#define IDD_DIALOG_EFF_LEVEL            206
#define IDD_DIALOG_EFF_TEXDIFF          207
#define IDD_DIALOG_EFFANI_TRACE         208
#define IDD_DIALOG_EFF_PARTICLE         209
#define IDD_DIALOG_EFF_BONEPOSEFF       210
#define IDD_DIALOG_EFF_BONELISTEFF      211
#define IDD_DIALOG_EFF_USERCOLOR        212
#define IDD_DIALOG_EFF_TOON             213
#define IDD_DIALOG_EFF_NORMALMAP        214
#define IDD_DIALOG_EFFANI_FACEOFF       215
#define IDD_DIALOG_EFFKEEP              216
#define IDD_DIALOG_EFFKEEP_CTEDGE       217
#define IDD_DIALOG_EFFKEEP_CTSHADE      218
#define IDD_DIALOG_EFFKEEP_CTCOLOR      219
#define IDD_DIALOG_EFF_LINE2BONE        220
#define IDD_DIALOG_EFF_LINE2BONE_D      221
#define IDD_DIALOG_ANIBONESCALE         222
#define IDD_DIALOG_AMBIENT_MNG          223
#define IDD_DIALOG_AROUND_EFFECT        224
#define IDD_DIALOG_EDITBONE             225
#define IDD_DIALOG_EFF_NAMELIST         226
#define IDD_DIALOG_ATTBONEPAGE          227
#define IDD_DIALOG_ATTBONEANIM          229
#define IDD_DIALOG_ATTACHLINKPAGE       230
#define IDD_DIALOG_ATTACHANIEDIT        231
#define IDD_DIALOG_VEHICLEPAGE          232
#define IDD_DIALOG_EFF_OVERLAY          234
#define IDD_DIALOG_BOARDPOS             235
#define IDD_DIALOG_EFF_TOTALSHADER      236
#define IDD_DIALOG_EFFTS_NORMALMAP      237
#define IDD_DIALOG_EFFTS_TEXUPDOWN      238
#define IDD_DIALOG_EFFTS_OVERLAY        239
#define IDD_DIALOG_EFFTS_REFLECTION     240
#define IDD_DIALOG_Eff_VISUAL_MATERIAL  241
#define IDD_DIALOG_AMBIENT              242
#define IDD_DIALOG_EFF_SPLINE_SINGLE_EFF 243
#define IDD_DIALOG_LOG                  244
#define IDD_DIALOG2                     245
#define IDD_DIALOG_JIGGLE_BONE          245
#define IDD_DIALOG_EFF_WB_FLAG          246
#define IDB_BITMAP_TOOLBAR              248
#define IDB_TOOLBAR                     249
#define IDD_DIALOG_ASSET                251
#define IDD_DIALOG_SKINLOD              252
#define IDD_DIALOG_USER_BACK_SLOT       253
#define IDD_DIALOG_FOOT_COLL            254
#define IDD_DIALOG_RESOLUTION           255
#define IDD_DIALOG_JIGGLE_COLLISION     257
#define IDD_DIALOG_BONE_SETTING         258
#define IDD_DIALOG_EFF_NONE             259
#define IDD_DIALOG_SKIN_INFO            260
#define IDD_DIALOG_JIGGLE_BLEND         261
#define IDD_DIALOG_CLOTH_COLLISION      262
#define IDD_DIALOG_WEAPON_SCALE         263
#define IDD_DIALOG_BILLBOARD            264
#define IDD_DIALOG_FLYCAMPAGE           265
#define IDD_DIALOG_ANIMTABPAGE          266
#define IDD_DIALOG_MULTIANIM            267
#define IDR_POPUP_MULTIANIM             268
#define IDC_EDIT_SKINMESH               1000
#define IDC_STATIC_RGB_RECT             1000
#define IDC_EDIT_SKINBONE               1001
#define IDC_STATIC_HSB_RECT             1001
#define IDC_EDIT2                       1002
#define IDC_EDIT_START                  1002
#define IDC_EDIT_XFILE                  1002
#define IDC_EDIT_ANIKEY                 1002
#define IDC_EDIT_RED                    1002
#define IDC_EDIT_ALPHAVEL               1002
#define IDC_EDIT_MOVE                   1002
#define IDC_EDIT_SCALE                  1002
#define IDC_EDIT_SKIN_SCALE             1002
#define IDC_EDIT_TEXNAME                1002
#define IDC_EDIT_SCALE_DATA             1002
#define IDC_EDIT_SIZE1                  1002
#define IDC_EDIT_BRIGHT                 1002
#define IDC_EDIT_SETNUM                 1002
#define IDC_EDIT_VALUE1                 1002
#define IDC_EDIT_SWING                  1002
#define IDC_TREE_FRAME                  1003
#define IDC_EDIT_END                    1003
#define IDC_SPIN_RED                    1003
#define IDC_EDIT_FACT                   1003
#define IDC_EDIT_SIZE2                  1003
#define IDC_EDIT_SCALE2                 1003
#define IDC_EDIT_SKINBONE2              1003
#define IDC_EDIT_SET_HEIGHT             1003
#define IDC_EDIT_VALUE2                 1003
#define IDC_EDIT_DELAY                  1003
#define IDC_EDIT_DENSITY                1003
#define IDC_STATIC_SHEETTAP1            1004
#define IDC_EDIT_GREEN                  1004
#define IDC_EDIT_SCALE_RANDOM           1004
#define IDC_EDIT_SIZE3                  1004
#define IDC_EDIT_SCALE3                 1004
#define IDC_EDIT_VALUE3                 1004
#define IDC_EDIT_SWING_Z                1004
#define IDC_EDIT_VALUE4                 1005
#define IDC_STATIC_SHEETTAP2            1005
#define IDC_SPIN_GREEN                  1005
#define IDC_EDIT_SCALE_RATE             1005
#define IDC_EDIT_SCALE_RANDOM2          1005
#define IDC_EDIT_B_VALUE1               1005
#define IDC_LIST_ANIMATION              1006
#define IDC_EDIT_BLUE                   1006
#define IDC_EDIT_LIFE_MIN               1006
#define IDC_STATIC_SHEETTAP3            1006
#define IDC_BUTTON_ANIM_NEW             1007
#define IDC_SPIN_BLUE                   1007
#define IDC_EDIT_LIFE_MAX               1007
#define IDC_STATIC_SHEETTAP4            1007
#define IDC_BUTTON_ANIM_DELETE          1008
#define IDC_STATIC_OLD                  1008
#define IDC_EDIT_COL                    1008
#define IDC_EDIT_LIFE_MIN2              1008
#define IDC_BUTTON_ANIM_SELECT          1009
#define IDC_STATIC_NEW                  1009
#define IDC_EDIT_ROW                    1009
#define IDC_EDIT_LIFE_MAX2              1009
#define IDC_BUTTON_ANIM_SETTING         1010
#define IDC_COMBO_TYPE                  1010
#define IDC_EDIT_HUE                    1010
#define IDC_EDIT_VEL_MIN                1010
#define IDC_EDIT_SCALE_Y_E_BOTTOM       1010
#define IDC_BUTTON_LIST_ALIGN_DOWN      1010
#define IDC_BUTTON_OK                   1011
#define IDC_SPIN_HUE                    1011
#define IDC_BUTTON_ANIM_SETTING2        1011
#define IDC_BUTTON_ANIM_MIX             1011
#define IDC_EDIT_VEL_MAX                1011
#define IDC_EDIT_NAME                   1012
#define IDC_EDIT_SAT                    1012
#define IDC_BUTTON_ANIM_CONVERSION      1012
#define IDC_BUTTON_RESET_EFFECT         1012
#define IDC_SPIN_SAT                    1013
#define IDC_BUTTON_APPLY                1013
#define IDC_COMBO_TYPE2                 1013
#define IDC_COMBO_SUBTYPE               1013
#define IDC_BUTTON_RESET_EFFECT2        1013
#define IDC_BUTTON_PARTS_SAVE           1013
#define IDC_BUTTON_REMAKE_ALL_BIN       1013
#define IDC_LIST_PIECES                 1014
#define IDC_EDIT_VAL                    1014
#define IDC_EDIT_VEL_RATE               1014
#define IDC_BUTTON_BACK                 1014
#define IDC_BUTTON_ANIM_SELECT2         1014
#define IDC_BUTTON_RESET_POS            1014
#define IDC_EDIT_NAME_XFILE             1014
#define IDC_BUTTON_AUTO                 1014
#define IDC_BUTTON_ADD                  1015
#define IDC_SPIN_VAL                    1015
#define IDC_BUTTON_REMAKE_SEL_BIN       1015
#define IDC_BUTTON_OK2                  1015
#define IDC_BUTTON_DEL                  1016
#define IDC_BUTTON_ANIMLIST_EXPORT      1016
#define IDC_BUTTON_EDIT                 1017
#define IDC_COMBO_ANIM_MTYPE            1017
#define IDC_BUTTON_STATE                1018
#define IDC_COMBO_SUBTYPE2              1018
#define IDC_COMBO_ANIM_STYPE            1018
#define IDC_BUTTON_XFILESELECT          1019
#define IDC_STATIC_TIMELINE             1022
#define IDC_BUTTON_TOS                  1023
#define IDC_BUTTON_PKEY                 1024
#define IDC_BUTTON_PLAY                 1025
#define IDC_BUTTON_NKEY                 1026
#define IDC_EDIT_WIDTH_OUT              1026
#define IDC_BUTTON_EKEY                 1027
#define IDC_EDIT_RANROTATE              1027
#define IDC_EDIT_ANISKEY                1028
#define IDC_EDIT_WIDTH_IN               1028
#define IDC_EDIT_ANIEKEY                1029
#define IDC_BUTTON_FRAME_SETTING        1029
#define IDC_BUTTON_PIECE_SELECT         1029
#define IDC_BUTTON_ANI_EDIT             1029
#define IDC_EDIT_FPS                    1030
#define IDC_BUTTON_SKINFILE             1030
#define IDC_BUTTON_PIECE_DESELECT       1030
#define IDC_EDIT_TEXTURE                1030
#define IDC_BUTTON_SKINBONE             1031
#define IDC_BUTTON_SKINMESHSELECT       1031
#define IDC_BUTTON_TEXTURE              1031
#define IDC_EDIT_TEXTURE2               1031
#define IDC_EDIT_TEXTURE_OUT            1032
#define IDC_BUTTON_NEON_TEX             1032
#define IDC_EDIT_OBLIQUE_TEX            1032
#define IDC_BUTTON_SLOT_WEAPON          1032
#define IDC_EDIT_KEYWORD                1033
#define IDC_BUTTON_TEXTURE_OUT          1033
#define IDC_EDIT_MAP0                   1033
#define IDC_EDIT_NEON_TEX               1033
#define IDC_BUTTON_OBLIQUE_TEX          1033
#define IDC_BUTTON_JIGGLE_BONE          1033
#define IDC_BUTTON_COLOR_S              1034
#define IDC_EDIT_MAP1                   1034
#define IDC_LIST_PIECE                  1035
#define IDC_EDIT_MAP2                   1035
#define IDC_EDIT_MAP3                   1036
#define IDC_STATIC_ANIEND               1037
#define IDC_EDIT_MAP4                   1037
#define IDC_BUTTON_LOADOBJECT           1038
#define IDC_EDIT_MAP5                   1038
#define IDC_CHECK_LOOP                  1039
#define IDC_EDIT_MAP6                   1039
#define IDC_EDIT_ALPHAMAP               1039
#define IDC_EDIT_REFLECT_TEX            1039
#define IDC_EDIT_TEX2                   1040
#define IDC_EDIT_SRCTEX_2               1041
#define IDC_COMBO_PAGE                  1042
#define IDC_STATIC_COLOR                1042
#define IDC_EDIT_SRCTEX_3               1042
#define IDC_EDIT_CHARFILE               1043
#define IDC_EDIT_SRCTEX_4               1043
#define IDC_BUTTON_NEW                  1044
#define IDC_COMBO_BLEND                 1044
#define IDC_BUTTON_OPEN                 1045
#define IDC_SCROLLBAR_START             1045
#define IDC_COMBO_BASESET               1045
#define IDC_BUTTON_SAVE                 1046
#define IDC_SCROLLBAR_STARTVAR          1046
#define IDC_EDIT_SKINFILE               1047
#define IDC_SCROLLBAR_END               1047
#define IDC_BUTTON_ALLSAVE              1047
#define IDC_EDIT_START_F                1048
#define IDC_BUTTON_SAVE2                1048
#define IDC_BUTTON_COLLISION_OBJECT     1048
#define IDC_EDIT_ADD_HAIR_CPS           1048
#define IDC_EDIT_BONEFILE               1049
#define IDC_STATIC_START                1049
#define IDC_BUTTON_CLOTH_COLLISION      1049
#define IDC_BUTTON_BONEFILE             1050
#define IDC_EDIT_STARTVAR_F             1050
#define IDC_BUTTON_MAKEOBJ              1051
#define IDC_EDIT_END_F                  1051
#define IDC_COMBO_SkINMESH              1052
#define IDC_STATIC_STARTVAR             1052
#define IDC_LIST_EFFLIST                1053
#define IDC_STATIC_END                  1053
#define IDC_COMBO_SKINMESHTYPE          1054
#define IDC_STATIC_END4                 1054
#define IDC_BUTTON_EFFINSERT            1055
#define IDC_SCROLLBAR_END4              1055
#define IDC_COMBO_SKINMESHTYPE2         1055
#define IDC_COMBO_OBJTYPE               1055
#define IDC_BUTTON_EFFDEL               1056
#define IDC_BUTTON_ALPHA                1056
#define IDC_EDIT_END4_F                 1056
#define IDC_EDIT_FILE                   1057
#define IDC_BUTTON_EFFSTATE             1057
#define IDC_BUTTON_ALPHA2               1057
#define IDC_BUTTON_INSERT               1057
#define IDC_STATIC_SETLINE              1058
#define IDC_STATIC_MTYPE                1059
#define IDC_BUTTON1                     1060
#define IDC_BUTTON_SOUND                1060
#define IDC_BUTTON_GETSOUND             1060
#define IDC_BUTTON_VERTINSERT           1060
#define IDC_BUTTON_SELECT               1060
#define IDC_SLIDER1                     1060
#define IDC_BUTTON_COLOR                1060
#define IDC_BUTTON_TEX_CHECK            1060
#define IDC_BUTTON_DIFFUSE              1060
#define IDC_BUTTON_COLOR_1              1060
#define IDC_BUTTON_TEX_RE1              1060
#define IDC_BUTTON_TEXTURE_SEL          1060
#define IDC_BUTTON_SCALE                1060
#define IDC_BUTTON_TEX                  1060
#define IDC_BUTTON_GET1                 1060
#define IDC_BUTTON_KEYSCALE_MODIFY      1060
#define IDC_BUTTON_SAVE_EE              1060
#define IDC_ADDAMBIENT_BUTTON           1060
#define IDC_APPLY_BUTTON                1060
#define IDC_BUTTON_GETBONE              1060
#define IDC_BUTTON_POINT_2_FRONT        1060
#define IDC_LIST_STARTFRAME             1061
#define IDC_BUTTON_SOUND_DEL            1061
#define IDC_BUTTON_VERTDEL              1061
#define IDC_BUTTON_SELECT2              1061
#define IDC_BUTTON_COLOR_2              1061
#define IDC_BUTTON_TEX_RE2              1061
#define IDC_BUTTON3                     1061
#define IDC_BUTTON_GET2                 1061
#define IDC_BUTTON_KEYSCALE_INSERT      1061
#define IDC_ADDAMBIENT_BUTTON2          1061
#define IDC_AMBIENT_DEFAULT             1061
#define IDC_BUTTON_SET_HEIGHT           1061
#define IDC_BUTTON_LOADTESTCHF          1061
#define IDC_BTN_TRANS_APPLY             1061
#define IDC_BUTTON_BUFFERCOUNT          1062
#define IDC_EDIT_MID1                   1062
#define IDC_BUTTON_SELECT3              1062
#define IDC_BUTTON_COLOR_3              1062
#define IDC_BUTTON4                     1062
#define IDC_BUTTON_UP                   1062
#define IDC_COMBO_WHEREBACK             1062
#define IDC_BUTTON_COLOR3               1062
#define IDC_BUTTON_TESTANIM             1062
#define IDC_BUTTON_POINT_4_FRONT_LEFT   1062
#define IDC_EDIT_SOUND                  1063
#define IDC_BUTTON_DOWN                 1063
#define IDC_BUTTON_COLOR_OTHER          1063
#define IDC_BUTTON_LOADTESTCHF2         1063
#define IDC_BUTTON_POINT_4_FRONT_RIGHT  1063
#define IDC_BUTTON_ADD_HAIR_CPS_LOAD    1063
#define IDC_EDIT_BUFFERCOUNT            1064
#define IDC_EDIT_GLOWBRIGHT             1064
#define IDC_BUTTON_POINT_4_BACK_LEFT    1064
#define IDC_LIST_ANIDIV                 1065
#define IDC_EDIT_REFLECTACT             1065
#define IDC_BUTTON_POINT_4_BACK_RIGHT   1065
#define IDC_BUTTON2                     1066
#define IDC_BUTTON_ANIDIV               1066
#define IDC_BUTTON_TRACE                1066
#define IDC_BUTTON_EFF_SAVE             1066
#define IDC_BUTTON_MOVE_TEX1            1066
#define IDC_BUTTON_TEXTURE_FIND         1066
#define IDC_BUTTON_EFF_INSERT           1066
#define IDC_BUTTON_COLOR_INSERT         1066
#define IDC_BUTTON_LOADBONE             1066
#define IDC_BUTTON_SPOINT_INSERT        1066
#define IDC_BUTTON_FOOT_COLL            1066
#define IDC_BUTTON_CREATE_ANI_SEQUENCE  1066
#define IDC_BUTTON_TRACE_MOVE           1067
#define IDC_BUTTON_EFF_LOAD             1067
#define IDC_BUTTON_EFF_SAVE2            1067
#define IDC_BUTTON_ANIDIV2              1067
#define IDC_BUTTON_STRIKE               1067
#define IDC_BUTTON_MOVE_TEX2            1067
#define IDC_BUTTON_COLOR_DELETE         1067
#define IDC_BUTTON_TEXTURE_FIND2        1067
#define IDC_BUTTON_SPOINT_DELETE        1067
#define IDC_STATIC_VERTICS              1068
#define IDC_BUTTON_DIFFUSE_UP           1068
#define IDC_BUTTON_ANIEFF               1068
#define IDC_BUTTON_EFF_DELETE           1068
#define IDC_BUTTON_COLOR_STATE          1068
#define IDC_BUTTON_EFF_NAME             1068
#define IDC_BUTTON_SPOINT_UP            1068
#define IDC_BUTTON_DIFFUSE_DOWN         1069
#define IDC_BUTTON_ANI_SCALE            1069
#define IDC_BUTTON_BOARDPOS             1069
#define IDC_BUTTON_SPOINT_DOWN          1069
#define IDC_BUTTON_DIFFUSE_DOWN2        1070
#define IDC_BUTTON_DIFFUSE_MID          1070
#define IDC_BUTTON_IMPORT_CFG           1070
#define IDC_LIST_VERTICS                1071
#define IDC_BUTTON_XFILE_CHANGE         1071
#define IDC_CHECK_VERT_DRAW             1072
#define IDC_BUTTON_ANI_JIGGLE_BLEND     1072
#define IDC_EDIT1                       1073
#define IDC_EDIT_EFFECT_FILE            1073
#define IDC_EDIT_FACE                   1073
#define IDC_EDIT_MID2                   1073
#define IDC_EDIT_ALPHA                  1073
#define IDC_EDIT_TIME                   1073
#define IDC_EDIT_STARTKEY               1073
#define IDC_EDIT_MOVE_X                 1073
#define IDC_EDIT_FRAME                  1073
#define IDC_EDIT_WAIT                   1073
#define IDC_EDIT_POWER                  1073
#define IDC_EDIT_                       1073
#define IDC_EDIT_BONE_NAME              1073
#define IDC_EDIT_RADIUS                 1073
#define IDC_EDIT_THICKNESS              1073
#define IDC_EDIT_COLOR_TIME             1073
#define IDC_EDIT_BONE1                  1073
#define IDC_WALKSPEED_EDIT              1073
#define IDC_EDIT_BONENAME               1073
#define IDC_EDIT_BASEBONE               1073
#define IDC_EDIT_FRAMENUM               1073
#define IDC_EDIT_SPECPOWER              1073
#define IDC_EDIT_AMBIENT                1073
#define IDC_EDIT_LOG                    1073
#define IDC_EDIT_TWIST                  1073
#define IDC_EDIT_ADD_TIME               1073
#define IDC_EDIT_TYPE_VALUE_1           1073
#define IDC_EDIT_SSS_COLOR_R            1073
#define IDC_COMBO_TRACE_VERT            1074
#define IDC_EDIT_ALPHA2                 1074
#define IDC_EDIT_SPEED                  1074
#define IDC_EDIT_ENDKEY                 1074
#define IDC_EDIT_MOVE_Z                 1074
#define IDC_EDIT_BASE                   1074
#define IDC_EDIT3                       1074
#define IDC_EDIT_ONE_FRAME              1074
#define IDC_EDIT_PLAY                   1074
#define IDC_EDIT_SRCCOLOR               1074
#define IDC_EDIT_UNIT                   1074
#define IDC_EDIT_RANGE                  1074
#define IDC_EDIT_LOCAL_X                1074
#define IDC_EDIT_HEIGHT                 1074
#define IDC_EDIT_ADD_THICKNESS          1074
#define IDC_EDIT_BONE2                  1074
#define IDC_RUNSPEED_EDIT               1074
#define IDC_EDIT_TEXSPEED_MIN           1074
#define IDC_EDIT_SPECLEVEL              1074
#define IDC_EDIT_TERM                   1074
#define IDC_EDIT_ROTATE_X               1074
#define IDC_EDIT_COLOR_POWER            1074
#define IDC_EDIT_TYPE_VALUE_3           1074
#define IDC_EDIT_SSS_COLOR_G            1074
#define IDC_COMBO_EFF_TYPE              1075
#define IDC_COMBO_TRACE_VERT2           1075
#define IDC_CHECK_USE                   1075
#define IDC_EDIT_UPUP                   1075
#define IDC_EDIT_WAIT2                  1075
#define IDC_EDIT_MIN_ALPHA              1075
#define IDC_EDIT_LOCAL_Y                1075
#define IDC_EDIT_XSIZE_MIN              1075
#define IDC_EDIT_ALPHA_REF              1075
#define IDC_EDIT_BONE_NAME2             1075
#define IDC_EDIT_ROTATE_Y               1075
#define IDC_EDIT_TYPE_VALUE_2           1075
#define IDC_EDIT_SSS_COLOR_B            1075
#define IDC_EDIT_HAIR_SHIFT_V           1075
#define IDC_EDIT_OFFSET_Y               1075
#define IDC_EDIT_CUSTOM_SCNWIDTH        1075
#define IDC_EDIT_X                      1075
#define IDC_EDIT_ALPHA_UP               1076
#define IDC_STATIC_TEMP                 1076
#define IDC_COMBO_TRACE_VERT3           1076
#define IDC_EDIT_LOCAL_Z                1076
#define IDC_EDIT_ALPHA4                 1076
#define IDC_EDIT_ROTATE_Z               1076
#define IDC_EDIT_POSITION_X             1076
#define IDC_EDIT_BODY_SPEC_POWER        1076
#define IDC_EDIT_HAIR_SPEC_EXP_CAMERA   1076
#define IDC_EDIT_BILLBOARD_NAME         1076
#define IDC_EDIT_CUSTOM_SCNSIZEY        1076
#define IDC_EDIT_CUSTOM_SCNHEIGHT       1076
#define IDC_EDIT_Y                      1076
#define IDC_EDIT_ALPHA_DOWN             1077
#define IDC_EDIT_TEMP                   1077
#define IDC_COMBO_TRACE_VERT4           1077
#define IDC_EDIT_XSIZE_MAX              1077
#define IDC_EDIT_SPECULARPOWER          1077
#define IDC_EDIT_TWIST_RESTITUTION      1077
#define IDC_EDIT_POSITION_Y             1077
#define IDC_EDIT_FACE_SPEC_POWER        1077
#define IDC_EDIT_HAIR_SPEC_EXP_DIRECTION 1077
#define IDC_EDIT_Z                      1077
#define IDC_EDIT_WIDTH                  1078
#define IDC_STATIC_TEMP4                1078
#define IDC_EDIT_ALPHATIME              1078
#define IDC_COMBO_TRACE_VERT5           1078
#define IDC_EDIT_TWIST_SPRING           1078
#define IDC_EDIT_POSITION_Z             1078
#define IDC_EDIT_BODY_SPEC2_POWER       1078
#define IDC_EDIT_HAIR_SPEC_DIRECTION_INTENSITY 1078
#define IDC_EDIT_X2                     1078
#define IDC_EDIT_ROTATE                 1078
#define IDC_COMBO1                      1079
#define IDC_EDIT_FLAREPOS               1079
#define IDC_EDIT_SETRATE                1079
#define IDC_EDIT_ALPHA_DOWN2            1079
#define IDC_EDIT_ALPHA_MID              1079
#define IDC_EDIT_FLAREPOS1              1079
#define IDC_EDIT_TWIST_DAMPING          1079
#define IDC_EDIT_OFFSET_X               1079
#define IDC_CHECK_BEZIER                1080
#define IDC_EDIT_RAND                   1080
#define IDC_EDIT_DEPTH                  1080
#define IDC_COMBO_STYPE                 1080
#define IDC_COMBO2                      1080
#define IDC_COMBO_RENDER_TYPE           1080
#define IDC_COMBO_EFF                   1080
#define IDC_COMBO_S_TYPE                1080
#define IDC_EDIT_FLAREPOS2              1080
#define IDC_EDIT_SWING_RESTITUTION      1080
#define IDC_CHECK_GRAVITY               1081
#define IDC_EDIT_SIZE                   1081
#define IDC_EDIT_RATE_MID               1081
#define IDC_COMBO_OPTION_3              1081
#define IDC_COMBO_POS_2                 1081
#define IDC_EDIT_TEXROTATE2             1081
#define IDC_EDIT_SWING_SPRING           1081
#define IDC_EDIT_GRAVITY                1082
#define IDC_CHECK1                      1082
#define IDC_CHECK_SRCTEX_1              1082
#define IDC_CHECK_REFACT                1082
#define IDC_CHECK_REFRACT               1082
#define IDC_COMBO_POS_1                 1082
#define IDC_CHECK_TRANSLUCENT           1082
#define IDC_CHECK_REPEAT                1082
#define IDC_CHECK_NOSHADOW              1082
#define IDC_CHECK_NOCHARACTER           1082
#define IDC_CHECK_RANGE                 1082
#define IDC_CHECK_POS_MOVE              1082
#define IDC_CHECK_UPDOWN                1082
#define IDC_CHECK_OBLIQUE_LINE          1082
#define IDC_CHECK_SHADECOLOR            1082
#define IDC_CHECK_UPBODY                1082
#define IDC_MOVE_TESTCHECK              1082
#define IDC_EDIT_TEXROTATE1             1082
#define IDC_CHECK_SPECULAR              1082
#define IDC_CHECK_USECPS                1082
#define IDC_CHECK_CHARTEST              1082
#define IDC_CHECK_STRIKE                1082
#define IDC_CHECK_USEEFFECT1            1082
#define IDC_CHECK_AMBIENT_TEST          1082
#define IDC_EDIT_SWING_DAMPING          1082
#define IDC_CHECK_FLAREPOS              1083
#define IDC_CHECK2                      1083
#define IDC_CHECK_SRCTEX_2              1083
#define IDC_CHECK_ORIGIN                1083
#define IDC_CHECK_TIMEDAY               1083
#define IDC_CHECK_REPEAT_MOVE           1083
#define IDC_CHECK_SEQUENCE              1083
#define IDC_EDIT_YSIZE_MIN              1083
#define IDC_CHECK_CAMMOVE               1083
#define IDC_CHECK_SPECULAR2             1083
#define IDC_CHECK_USEEFFECT2            1083
#define IDC_CHECK_ATKMODE               1083
#define IDC_CHECK_USE_SPECULAR          1083
#define IDC_CHECK_ONE_COLOR             1083
#define IDC_CHECK_KEEP_SETTING          1083
#define IDC_CHECK_COLLISION             1083
#define IDC_EDIT_RAND2                  1084
#define IDC_EDIT_BLURRATE               1084
#define IDC_CHECK3                      1084
#define IDC_CHECK_SRCTEX_3              1084
#define IDC_CHECK_SRCTEX                1084
#define IDC_CHECK_ALL_ACTION            1084
#define IDC_CHECK_TIMENIGHT             1084
#define IDC_CHECK_AUTOMOVE              1084
#define IDC_CHECK_SEQUENCE2             1084
#define IDC_CHECK_ROTATE                1084
#define IDC_CHECK_GLOWTEX               1084
#define IDC_CHECK_USEEFFECT3            1084
#define IDC_CHECK_SPECULAR3             1084
#define IDC_CHECK_GLONORMAP             1084
#define IDC_CHECK_AUTOLOD               1084
#define IDC_CHECK_NAME_CHF_CFG          1084
#define IDC_CHECK_ONE_COLOR2            1084
#define IDC_CHECK4                      1085
#define IDC_CHECK_SRCTEX_4              1085
#define IDC_COMBO_OPTION_2              1085
#define IDC_CHECK_VIEW_TEX              1085
#define IDC_CHECK_COLOR_1               1085
#define IDC_CHECK_COLOR                 1085
#define IDC_CHECK_SKYFINE               1085
#define IDC_CHECK_ROTATE2               1085
#define IDC_CHECK_REMAIN                1085
#define IDC_EDIT_MESH_DIST              1085
#define IDC_CHECK_REFLECTTEX            1085
#define IDC_CHECK_USEEFFECT4            1085
#define IDC_CHECK_ABSOLUTE              1085
#define IDC_EDIT7                       1086
#define IDC_EDIT_ALPHA3                 1086
#define IDC_CHECK_COLOR_2               1086
#define IDC_CHECK_SKYSNOW               1086
#define IDC_CHECK_REMAIN2               1086
#define IDC_EDIT_TEXSPEED_MAX           1086
#define IDC_CHECK_REFLECTTEX2           1086
#define IDC_CHECK_TIMEDAY_EFF           1086
#define IDC_CHECK_SEQUENCE3             1086
#define IDC_CHECK_CREATE_RANDOM_DONT_MOVE 1086
#define IDC_CHECK_SIZE                  1087
#define IDC_CHECK_COLOR_3               1087
#define IDC_CHECK_SKYLEAVES             1087
#define IDC_EDIT_YSIZE_MAX              1087
#define IDC_CHECK_TIMENIGHT2            1087
#define IDC_CHECK_TIMENIGHT_EFF         1087
#define IDC_CHECK_USE_OVERLAY           1087
#define IDC_EDIT_SEC                    1088
#define IDC_CHECK_USE_OVERLAY2          1088
#define IDC_CHECK_ENABLE_CHANGE         1088
#define IDC_BUTTON_COLOR_E              1089
#define IDC_CHECK_SEC                   1089
#define IDC_CHECK_RAND                  1090
#define IDC_CHECK_ARROW                 1091
#define IDC_CHECK_ALPHAVEL              1091
#define IDC_CHECK_MID                   1092
#define IDC_CHECK_EFFECT                1092
#define IDC_STATIC_UP                   1093
#define IDC_STATIC_DOWN                 1094
#define IDC_STATIC_MID                  1095
#define IDC_BUTTON_HIGH                 1096
#define IDC_CHECK_MTYPE                 1097
#define IDC_COMBO_MTYPE                 1098
#define IDC_CHECK_STYPE                 1099
#define IDC_RADIO_UP                    1100
#define IDC_CHECK_KEYTIME               1100
#define IDC_RADIO_MID                   1101
#define IDC_CHECK_MOVE                  1101
#define IDC_RADIO_DOWN                  1102
#define IDC_COMBO_TRACE_VERT_MOVE       1102
#define IDC_STATIC_CENTER               1103
#define IDC_COMBO_COLOROP               1103
#define IDC_COMBO_PIECE                 1104
#define IDC_LIST_STRIKES                1105
#define IDC_EDIT_SRCTEX_1               1106
#define IDC_EDIT_TEXTURE_1              1107
#define IDC_CHECK_IN                    1108
#define IDC_BUTTON_TEXTURE_1            1108
#define IDC_CHECK_START                 1109
#define IDC_BUTTON_TEXTURE_2            1109
#define IDC_RADIO_TIME                  1109
#define IDC_EDIT_TEXTURE_2              1110
#define IDC_RADIO_FRAME                 1110
#define IDC_EDIT_DIVISION               1111
#define IDC_BUTTON_TEXTURE_3            1111
#define IDC_RADIO_ALL                   1111
#define IDC_EDIT_LENGTH                 1112
#define IDC_EDIT_TEXTURE_3              1112
#define IDC_CHECK_OUT                   1113
#define IDC_BUTTON_TEXTURE_4            1113
#define IDC_EDIT_TEXTURE_4              1114
#define IDC_EDIT_TEXTURE_IN             1115
#define IDC_BUTTON_TEXTURE_BUMP_1       1115
#define IDC_BUTTON_TEXTURE_IN           1116
#define IDC_EDIT_TEXTURE_BUMP_1         1116
#define IDC_STATIC_IN                   1117
#define IDC_BUTTON_TEXTURE_BUMP_2       1117
#define IDC_STATIC_OUT                  1118
#define IDC_EDIT_TEXTURE_BUMP_2         1118
#define IDC_CHECK_END                   1119
#define IDC_BUTTON_TEXTURE_BUMP_3       1119
#define IDC_EDIT_OUT_NUM                1120
#define IDC_EDIT_TEXTURE_BUMP_3         1120
#define IDC_COMBO_CATEGORY              1121
#define IDC_COMBO_MATRIAL               1121
#define IDC_COMBO_PLAYCONDITION         1122
#define IDC_COMBO_PLAYTYPE              1122
#define IDC_COMBO_OPTION_1              1122
#define IDC_RADIO_ATTACK                1124
#define IDC_EDIT_TEX1                   1124
#define IDC_RADIO_ATTACK_EXCEPT         1125
#define IDC_BUTTON_TEX1                 1125
#define IDC_RADIO_TEX1                  1127
#define IDC_RADIO_TEX2                  1128
#define IDC_BUTTON_COLOR1               1129
#define IDC_BUTTON_COLOR2               1130
#define IDC_LIST_MATERIAL_LIST          1130
#define IDC_COMBO_ZBIAS                 1131
#define IDC_BUTTON_COLOR4               1131
#define IDC_BUTTON_MATERIAL             1132
#define IDC_BUTTON_COLOR5               1132
#define IDC_EDIT_NORMAL_UP              1133
#define IDC_BUTTON_COLOR6               1133
#define IDC_EDIT_NORMAL_DOWN            1134
#define IDC_EDIT_NUM                    1134
#define IDC_COMBO_M_TYPE                1135
#define IDC_EDIT_CENTER_FAR             1135
#define IDC_LIST_EFF                    1136
#define IDC_EDIT_SHAKE                  1136
#define IDC_COMBO_FRAME_1               1138
#define IDC_COMBO_FRAME_2               1139
#define IDC_CHECK_SKYRAIN               1140
#define IDC_RADIO_POINT                 1141
#define IDC_RADIO_RANGE                 1142
#define IDC_LIST_SOUNDSOURCE            1143
#define IDC_RADIO_DIRECT                1143
#define IDC_CHECK_CHARMOVE              1144
#define IDC_COMBO_LEVEL                 1145
#define IDC_CHECK_CHARMOVE2             1145
#define IDC_CHECK_NEVER_DIE             1145
#define IDC_EDIT4                       1146
#define IDC_EDIT_REPEAT_TIME            1146
#define IDC_RADIO_SELECT                1148
#define IDC_RADIO_ORI                   1149
#define IDC_RADIO_USER                  1150
#define IDC_RADIO_GENERAL               1151
#define IDC_RADIO_BURN                  1152
#define IDC_RADIO_1POINT                1153
#define IDC_RADIO_2POINT                1154
#define IDC_EDIT_REPEAT_SPEED           1155
#define IDC_RADIO_MATRIX                1156
#define IDC_CHECK_SHADOW                1157
#define IDC_RADIO_VERTEX                1158
#define IDC_CHECK_ALPHA_BLEND_SRC_DEST_ALPHA 1158
#define IDC_RADIO_CUBEMAP               1159
#define IDC_STATIC_COLOROP              1160
#define IDC_STATIC_SPECPOWER            1161
#define IDC_STATIC_1                    1162
#define IDC_RADIO_TEXCOLOR              1163
#define IDC_RADIO_AMBIENT               1164
#define IDC_LIST_POINT                  1164
#define IDC_BUTTON_DELETE               1165
#define IDC_BUTTON_KEYSCALE_DELETE2     1166
#define IDC_BUTTON_GETBONENAME          1167
#define IDC_EDIT_SCALE_MIN              1168
#define IDC_BUTTON_SETTING_LOAD         1168
#define IDC_EDIT_SCALE_MAX              1169
#define IDC_BUTTON_SETTING_SAVE         1169
#define IDC_LIST_BONE                   1170
#define IDC_EDIT_SCALE_X_S              1170
#define IDC_EDIT_ROTATE_MIN             1171
#define IDC_SPIN_HEIGHT                 1171
#define IDC_EDIT_SCALE_X_E              1171
#define IDC_EDIT_ROTATE_MAX             1172
#define IDC_SPIN_RADIUS                 1172
#define IDC_EDIT_SCALE_Y_S              1172
#define IDC_SPIN_OFFSET_Y               1172
#define IDC_STATIC_WHEREBACK            1173
#define IDC_EDIT_SCALE_Y_E_TOP          1173
#define IDC_RADIO_1X                    1174
#define IDC_RADIO_2X                    1175
#define IDC_STATIC_2                    1175
#define IDC_RADIO_4X                    1176
#define IDC_EDIT_TEXTURE_NORMAL         1176
#define IDC_BUTTON_TEXTURE_NORMAL       1177
#define IDC_EDIT_TEXTURE_SPECULAR       1178
#define IDC_BUTTON_TEXTURE_SPECULAR     1179
#define IDC_BUTTON_LOAD                 1180
#define IDC_EDIT_TEXTURE_SPECULAR2      1180
#define IDC_BUTTON_TEXTURE_SPECULAR2    1181
#define IDC_BUTTON_EFF_STATE            1182
#define IDC_EDIT_TEXTURE_GLOWTEX        1182
#define IDC_BUTTON_TEXTURE_GLOWTEX      1183
#define IDC_LIST_CHARANIM               1183
#define IDC_LIST_COLOR                  1184
#define IDC_EDIT_TEXTURE_REFLECTTEX     1184
#define IDC_LIST_LINEBONE               1185
#define IDC_BUTTON_TEXTURE_REFLECTTEX   1185
#define IDC_BUTTON_SETTING              1186
#define IDC_EDIT_TEXTURE_REFLECTTEX2    1186
#define IDC_RADIO_STARTEND              1187
#define IDC_BUTTON_TEXTURE_REFLECTTEX2  1187
#define IDC_RADIO_BLUR                  1188
#define IDC_LIST_BONENAME               1188
#define IDC_RADIO_EACH                  1189
#define IDC_LIST_KEYSCALE               1189
#define IDC_BUTTON_LOAD_EE              1189
#define IDC_BUTTON_MAP0                 1190
#define IDC_RADIO_NONE                  1190
#define IDC_LIST_SKINPIECE              1190
#define IDC_RADIO_RESOLUTION_1          1190
#define IDC_BUTTON_MAP2                 1191
#define IDC_BUTTON_ALLSAVE2             1191
#define IDC_RADIO_RESOLUTION_2          1191
#define IDC_BUTTON_MAP1                 1192
#define IDC_EDIT_POS1                   1192
#define IDC_RADIO_RESOLUTION_3          1192
#define IDC_BUTTON_MAP4                 1193
#define IDC_EDIT_POS2                   1193
#define IDC_RADIO_RESOLUTION_4          1193
#define IDC_BUTTON_MAP5                 1194
#define IDC_EDIT_COL2                   1194
#define IDC_RADIO_FPS_1                 1194
#define IDC_BUTTON_MAP3                 1195
#define IDC_EDIT_ROW2                   1195
#define IDC_RADIO_AA_1X                 1195
#define IDC_BUTTON_ALPHAMAP             1196
#define IDC_BUTTON_REFLECT_TEX          1196
#define IDC_SPEED_SLIDER1               1196
#define IDC_RADIO_AA_2X                 1196
#define IDC_BUTTON_TEX2                 1197
#define IDC_SPEED_SLIDER2               1197
#define IDC_RADIO_AA_4X                 1197
#define IDC_BUTTON_SET                  1198
#define IDC_RADIO_FPS_2                 1198
#define IDC_LIST_EDITBONE               1199
#define IDC_RADIO_RESOLUTION_5          1199
#define IDC_EDIT_SCALE1                 1200
#define IDC_LIST_EDITCHAR               1200
#define IDC_EDIT_GLOWALPHA              1201
#define IDC_EDIT_GLOWSPEED              1202
#define IDC_LIST_NAME                   1203
#define IDC_EDIT_ABFFILE                1205
#define IDC_BUTTON_LOADABF              1206
#define IDC_EDIT_LINKBONENAME           1207
#define IDC_BUTTON_LOADCPS              1208
#define IDC_EDIT_CPSFILE                1209
#define IDC_EDIT_ABFFILE2               1210
#define IDC_EDIT_ABLFILE                1210
#define IDC_BUTTON_RESET1               1214
#define IDC_BUTTON_LINK_INVERSE_MATRIX  1215
#define IDC_RADIO_POSITION              1216
#define IDC_RADIO_ROTATION              1217
#define IDC_RADIO_SCALE                 1218
#define IDC_LIST_ATTANIMATION           1218
#define IDC_STATIC_NAME                 1219
#define IDC_BUTTON_LINK_MATRIX          1220
#define IDC_COMBO_ANITYPE               1221
#define IDC_RADIO_LINK_MATRIX           1221
#define IDC_BUTTON_FIND                 1225
#define IDC_SLIDER_SPECPOWER            1226
#define IDC_SLIDER_SPECLEVEL            1227
#define IDC_BUTTON_SETEDIT              1227
#define IDC_LIST_ATTSTRIKEANI           1228
#define IDC_SLIDER_ALPHA_REF            1228
#define IDC_RADIO_SHADEREFFECT1         1233
#define IDC_RADIO_SHADEREFFECT2         1234
#define IDC_RADIO_SHADEREFFECT3         1235
#define IDC_RADIO_SHADEREFFECT4         1236
#define IDC_SPIN_VALUE1                 1239
#define IDC_EDIT_B_VALUE2               1240
#define IDC_EDIT_NAME_BONE              1240
#define IDC_SPIN_VALUE2                 1241
#define IDC_SPIN_VALUE3                 1242
#define IDC_EDIT_B_VALUE3               1243
#define IDC_LIST_JOINT                  1243
#define IDC_CHECK_NONATKMODE            1244
#define IDC_COMBOBOXEX2                 1246
#define IDC_EDIT_RADIUS2                1247
#define IDC_EDIT_EFF_NUMBER             1248
#define IDC_LIST_SPLINE_POINT           1249
#define IDC_TREE_ASSET                  1251
#define IDC_STATIC_TEXTURE              1252
#define IDC_LIST1                       1252
#define IDC_STATIC_TEXTURE2             1253
#define IDC_RADIO_BOX                   1253
#define IDC_RADIO_BOX1                  1253
#define IDC_RADIO_SPHERE2               1254
#define IDC_RADIO_SYLINDER              1255
#define IDC_RADIO_CAPSULE               1255
#define IDC_STATIC_TYPE_VALUE_1         1256
#define IDC_STATIC_TYPE_VALUE_2         1257
#define IDC_STATIC_TYPE_VALUE_3         1258
#define IDC_STATIC_TYPE                 1259
#define IDC_LIST_COLLISION_MESH         1260
#define IDC_STATIC_POSITION_X           1261
#define IDC_BUTTON_BONE_SETTING         1261
#define IDC_STATIC_TYPE_VALUE_5         1262
#define IDC_BUTTON_DELETE_JOINT         1262
#define IDC_BUTTON_SKIN_SETTING         1262
#define IDC_STATIC_TYPE_VALUE_6         1263
#define IDC_BUTTON_RESET_JOINT          1263
#define IDC_BUTTON_FRAME_DOCUMENT       1263
#define IDC_BUTTON_FACE_SPEC_COLOR      1264
#define IDC_STATIC_TYPE_VALUE_7         1264
#define IDC_BUTTON_WEAPON_SCALE2        1264
#define IDC_BUTTON_BODY_SPEC_COLOR      1265
#define IDC_BUTTON_BILLBOARD            1265
#define IDC_BUTTON_BODY_SPEC2_COLOR     1266
#define IDC_RADIO_BASE                  1266
#define IDC_RADIO_HAIR                  1267
#define IDC_BUTTON_FAKE_SSS_COLOR       1267
#define IDC_STATIC_MASK_R               1268
#define IDC_STATIC_MASK_B               1269
#define IDC_STATIC_MASK_B2              1270
#define IDC_RADIO_POINT_2               1271
#define IDC_STATIC_MASK2_R              1271
#define IDC_RADIO_POINT_4               1272
#define IDC_STATIC_MASK2_R2             1272
#define IDC_BUTTON_POINT_2_BACK         1273
#define IDC_STATIC_MASK2_G              1273
#define IDC_RADIO_POINT_NONE            1274
#define IDC_STATIC_MASK2_B              1274
#define IDC_LIST_JIGGLE_BONE            1275
#define IDC_STATIC_MASK2_B2             1275
#define IDC_STATIC_HAIR_SHIFT_R         1276
#define IDC_STATIC_HAIR_MASK_G          1277
#define IDC_STATIC_HAIR_SHIFT_U         1278
#define IDC_STATIC_HAIR_SHIFT_V         1279
#define IDC_STATIC_HAIR_SPEC_EXP_R      1280
#define IDC_STATIC_HAIR_SPEC_EXP_TRT    1281
#define IDC_STATIC_HAIR_SPEC_DIRECTION_INTENSITY 1282
#define IDC_EDIT_HAIR_SHIFT_U           1283
#define IDC_BUTTON_HAIR_SPEC_COLOR      1284
#define IDC_STATIC_SPEC_DIRECTION_LIGHT 1285
#define IDC_STATIC_SPEC_CAMERA_LIGHT    1286
#define IDC_LIST_KEY_BLEND              1287
#define IDC_RADIO_CLOTH                 1287
#define IDC_STATIC_CLOTH_STRETCHING     1288
#define IDC_RADIO_ATTACH_BONE           1289
#define IDC_EDIT_CLOTH_STRETCHING       1289
#define IDC_LIST_ATTACH_BONE            1290
#define IDC_STATIC_CLOTH_HORIZONTAL     1290
#define IDC_EDIT_KEY                    1291
#define IDC_EDIT_CLOTH_HORIZONTAL       1291
#define IDC_EDIT_BLEND                  1292
#define IDC_STATIC_CLOTH_SHEARING       1292
#define IDC_EDIT_CLOTH_SHEARING         1293
#define IDC_STATIC_CLOTH_BENDING        1294
#define IDC_BUTTON_DOCUMENT             1294
#define IDC_EDIT_CLOTH_BENDING          1295
#define IDC_STATIC_CLOTH_DAMP           1296
#define IDC_RADIO_HAIR_NONE             1296
#define IDC_CHECK_NIGHT                 1297
#define IDC_EDIT_CLOTH_DAMP             1297
#define IDC_RADIO_HAIR_BASE             1297
#define IDC_STATIC_CLOTH_SOLVER_FREQUENCY 1298
#define IDC_RADIO_HAIR_NEW              1298
#define IDC_EDIT_CLOTH_SOLVER_FREQUENCY 1299
#define IDC_STATIC_HIAR                 1299
#define IDC_STATIC_HAIR                 1299
#define IDC_BUTTON_CLOTH_APPLY          1300
#define IDC_LIST_WEAPON_SCALE           1300
#define IDC_STATIC_BONE_NAME            1301
#define IDC_COMBO_TEX_WIDTH             1302
#define IDC_COMBO_TEX_HEIGHT            1303
#define IDC_SPIN_WIDTH                  1304
#define IDC_SPIN_OFFSET_X               1305
#define IDC_CHECK_CURRENTFRAME          1307
#define IDC_LIST_CAMERAANCHOR           1310
#define IDC_BUTTON_ANCHORINSERT         1311
#define IDC_BUTTON_ANCHORDELETE         1312
#define IDC_STATIC_FLYCAM_EDITGROUP_POS 1313
#define IDC_STATIC_FLYCAM_EDITGROUP_INDEX 1314
#define IDC_CHECK_CUBEMAP               1315
#define IDC_STATIC_FLYCAM_EDITGROUP_LOOKAT 1315
#define IDC_STATIC_FLYCAM_EDITGROUP_APPLY 1316
#define IDC_CHECK_CUBEMAP_SPECMAP_MASK  1317
#define IDC_ANCHORINFO                  1317
#define IDC_CHECK_NORMALMAP             1318
#define IDC_BUTTON_FLYCAM_LOAD          1318
#define IDC_CHECK_NORMALMAP2            1319
#define IDC_BUTTON_FLYCAM_SAVE          1319
#define IDC_TAB_ANIM                    1320
#define IDC_BUTTON_LIST_ALIGN_UP        1321
#define IDC_BUTTON_LIST_PLAY            1322
#define IDC_STATIC_FPS                  1322
#define IDC_BUTTON_LIST_ITEMDELETE2     1323
#define IDC_BUTTON_LIST_ITEMDELETE      1323
#define IDC_EDIT_VM_FILE                1396
#define IDC_EDIT_SRC_TEXTURE_0          1397
#define IDC_EDIT_DEST_TEXTURE_0         1398
#define IDC_EDIT_SRC_TEXTURE_1          1399
#define IDC_EDIT_DEST_TEXTURE_1         1400
#define IDC_EDIT_SRC_TEXTURE_2          1401
#define IDC_EDIT_DEST_TEXTURE_2         1402
#define IDC_EDIT_SRC_TEXTURE_3          1403
#define IDC_EDIT_DEST_TEXTURE_3         1404
#define IDC_EDIT_SRC_TEXTURE_4          1405
#define IDC_EDIT_DEST_TEXTURE_4         1406
#define IDC_EDIT_SRC_TEXTURE_5          1407
#define IDC_EDIT_DEST_TEXTURE_5         1408
#define IDC_EDIT_SRC_TEXTURE_6          1409
#define IDC_EDIT_DEST_TEXTURE_6         1410
#define IDC_EDIT_PARAMETER_X            1411
#define IDC_EDIT_PARAMETER_X2           1412
#define IDC_BUTTON_VM_FILE              1413
#define IDC_BUTTON_OPEN_TEXTURE_0       1414
#define IDC_BUTTON_RESET_TEXTURE_0      1415
#define IDC_BUTTON_OPEN_TEXTURE_1       1416
#define IDC_BUTTON_RESET_TEXTURE_1      1417
#define IDC_BUTTON_OPEN_TEXTURE_2       1418
#define IDC_BUTTON_RESET_TEXTURE_2      1419
#define IDC_BUTTON_OPEN_TEXTURE_3       1420
#define IDC_BUTTON_RESET_TEXTURE_3      1421
#define IDC_BUTTON_OPEN_TEXTURE_4       1422
#define IDC_BUTTON_RESET_TEXTURE_4      1423
#define IDC_BUTTON_OPEN_TEXTURE_5       1424
#define IDC_BUTTON_RESET_TEXTURE_5      1425
#define IDC_BUTTON_OPEN_TEXTURE_6       1426
#define IDC_BUTTON_RESET_TEXTURE_6      1427
#define IDC_STATIC_0                    1428
#define IDC_STATIC_3                    1431
#define IDC_STATIC_4                    1432
#define IDC_STATIC_5                    1433
#define IDC_STATIC_6                    1434
#define IDC_EDIT_PARAMETER_NAME         1435
#define IDC_EDIT_PARAMETER_Y            1436
#define IDC_EDIT_PARAMETER_Y2           1437
#define IDC_EDIT_PARAMETER_Z            1438
#define IDC_EDIT_PARAMETER_Z2           1439
#define IDC_LIST_PARAMETER              1446
#define IDC_EDIT_CUBEMAP_VALUE          1467
#define IDC_EDIT_SPOTSPEC_POWER         1468
#define IDC_EDIT_SPOTSPEC_MULTI         1469
#define ID_SKIN_NONINDEX                20001
#define ID_SKIN_INDEXED                 20002
#define ID_SKIN_SOFTWARE                20003
#define ID_POPUP_ADDANI                 32771
#define ID_POPUP_DELANI                 32772
#define ID_POPUP_SELECTANI              32773
#define ID_POPUP_SETANI                 32774
#define ID_POPUP_TOFRAME_VIEWMOVE       32775
#define ID_POPUP_FRAMESETTING           32776
#define ID_POPUP_FRAME                  32777
#define ID_REPLACE_CONT                 32778
#define ID_VIEW_WIREFRAME               32779
#define ID_VIEW_PLANE                   32780
#define ID_VIEWFULLSIZE                 32781
#define ID_ITEMLEVEL_DEFAULT            32782
#define ID_ITEMLEVEL_LEVEL1             32783
#define ID_ITEMLEVEL_LEVEL2             32784
#define ID_ITEMLEVEL_LEVEL3             32785
#define ID_ITEMLEVEL_LEVEL4             32786
#define ID_ITEMLEVEL_LEVEL5             32787
#define ID_ITEMLEVEL_LEVEL6             32788
#define ID_ITEMLEVEL_LEVEL7             32789
#define ID_ITEMLEVEL_LEVEL8             32790
#define ID_ITEMLEVEL_LEVEL9             32791
#define ID_ITEMLEVEL_LEVEL10            32792
#define ID_ITEMLEVEL_LEVEL11            32793
#define ID_ITEMLEVEL_LEVEL12            32794
#define ID_ITEMLEVEL_LEVEL13            32795
#define ID_VIEW_AABBBOX_VISIBLE         32798
#define ID_32799                        32799
#define ID_LOAD_BGTEX                   32801
#define ID_VIEW_BGTEX                   32802
#define ID_SAVE_SOUND_CSV               32804
#define ID_Menu                         32805
#define ID_32806                        32806
#define ID_VIEW_EFFECT_SPHERE_VISIBLE   32808
#define ID_32809                        32809
#define ID_VIEW_AMBIENT_CHANGE          32810
#define ID_32811                        32811
#define ID_TEST_TEST                    32811
#define ID_TOOLBAR_RELOAD               32811
#define ID_MENU_LOG_WINDOW              32812
#define ID_ARCHIVE                      32813
#define ID_32816                        32816
#define ID_ASSETVIEW                    32817
#define ID_32818                        32818
#define ID_VIEW_WEAPON_SLOT             32819
#define ID_RENDER_PS_3_0                32820
#define ID_RENDER_PS_2_0                32821
#define ID_RENDER_PS_1_1                32822
#define ID_RENDER_FIXED_HIGH            32823
#define ID_RENDER_FIXED                 32824
#define ID_RENDER_PS_3_0_NORMAL         32825
#define ID_RENDER_PS_3_0_HIGH_HIGH      32826
#define ID_RENDER_PS_2_0_NORMAL         32827
#define ID_32828                        32828
#define ID_VIEW_MOVE_PIECE              32829
#define ID_32830                        32830
#define ID_FIND_INVERSE_SCALE           32831
#define ID_32832                        32832
#define ID_FIND_DONT_HAVE_TEXTURE       32833
#define ID_32834                        32834
#define ID_32835                        32835
#define ID_32836                        32836
#define ID_MENU_LAND_LOAD               32837
#define ID_MENU_LAND_RENDER             32838
#define ID_MENU_LAND_ERASE              32839
#define ID_32840                        32840
#define ID_CREATE_BILLBOARD             32841
#define ID_CREATE_CHF_BILLBOARD         32842
#define ID_32843                        32843
#define ID_VIEW_BILLBOARD_RENDERING     32844
#define ID_32845                        32845
#define ID_POPUP_ADDMULTIANI            32846
#define ID_MULTIANIM_32847              32847
#define ID_POPUP_MULTIANIM_DELETE       32848
#define IDS_PROPSHT_CAPTION             61448

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        270
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1323
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
