//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GMCharEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_GMCHAREDIT_FORM             101
#define IDD_CHARSEARCH                  103
#define IDD_ITEMSEARCH                  104
#define IDD_ITEMCHANGE                  105
#define IDD_ITEMSTATISTIC               106
#define IDD_CLUBSEARCH                  107
#define IDD_GMITEMSEARCH                108
#define IDD_MONEYSTAT                   109
#define IDR_MAINFRAME                   128
#define IDR_GMCharEditTYPE              129
#define IDD_DLG_ITEM_DISGUISE           129
#define IDD_DLG_LOGIN                   130
#define IDD_DLG_SERVER_SELECT           131
#define IDD_PROPERTY_CHAR_SHEET         132
#define IDD_PROPERTY_CHAR_BASE          133
#define IDD_PROPERTY_CHAR_SKILL         134
#define IDD_PROPERTY_CHAR_PUTONITEM     135
#define IDD_PROPERTY_CHAR_INVEN         136
#define IDD_PROPERTY_CHAR_USERINVEN     137
#define IDD_DLG_SKILL_ADD               138
#define IDD_DLG_SKILL_ELEMENT_EDIT      139
#define IDD_DLG_INVEN_ELEMENT_EDIT      140
#define IDD_DLG_INVEN_ADD               141
#define IDD_ITEMCOUNT                   142
#define IDR_CONTEXT_MAIN                144
#define IDD_PROPERTY_CHAR_VEHICLE       144
#define IDD_DLG_MAKE_CRON_CHARACTER     145
#define IDD_DLG_CONFIG                  146
#define IDD_DLG_SKILL_SEARCH            147
#define IDD_PROPERTY_CHAR_QUEST         148
#define IDD_DLG_QUEST_ADD               149
#define IDD_DLG_QUEST_EDIT              150
#define IDD_ITEMCOUNT1                  151
#define IDD_SEARCH_DUPLICATION_ITEMS    151
#define IDD_PROPERTY_CHAR_PUTONITEM_1   152
#define IDD_PROPERTY_CHAR_ITEMMIX       153
#define IDD_DLG_ITEMMIX_TYPE            155
#define IDD_DLG_ITEMMIX_PRODUCT_ITEM    156
#define IDD_PROPERTY_CHAR_QUEST1        157
#define IDD_PROPERTY_CHAR_CLUB_INVEN    157
#define IDD_ITEMTRANSFER                158
#define IDD_PROPERTY_CHAR_DELETEDITEM   159
#define IDD_PROPERTY_CHAR_INVEN2        160
#define IDC_RADIO_USERID                1000
#define IDC_PROGRESS1                   1000
#define IDC_RADIO_CHANAME               1001
#define IDC_CHANGESTATIC1               1001
#define ID_EDIT_ODBC_NAME               1002
#define IDC_RADIO_USERNUM               1002
#define IDC_EDIT_ITEM_STATISTIC_CONSOLE 1002
#define IDC_RADIO_CHANUM                1003
#define IDC_PROGRESS_STAT               1003
#define IDC_EDIT_CLUB_NAME              1004
#define IDC_BUTTON_CLUB_SEARCH          1005
#define IDC_SEARCH                      1006
#define IDC_LIST_CLUB_SEARCH            1006
#define IDC_BTN_ITEM_SEARCH_STOP        1007
#define IDC_LIST_SEARCH                 1008
#define IDC_BTN_ITEM_SPECIAL_SEARCH_START 1008
#define IDC_EDIT1                       1009
#define IDC_BTN_STAT_START              1009
#define IDC_EDIT2                       1010
#define IDC_BTN_STAT_STOP               1010
#define IDC_LIST1                       1011
#define IDC_EDIT31                      1011
#define ID_EDIT_USERNAME                1012
#define IDC_EDIT23                      1012
#define IDC_BTN_GMITEM_SEARCH_START     1012
#define IDC_EDIT40                      1012
#define ID_USER_PASSWORD                1013
#define IDC_EDIT24                      1013
#define IDC_BTN_GMITEM_SEARCH_STOP      1013
#define IDC_EDIT41                      1013
#define ID_USER_PASSWORD2               1014
#define IDC_BUTTON1                     1014
#define IDC_EDIT25                      1014
#define IDC_EDIT_GMITEM_SEARCH_CONSOLE  1014
#define IDC_EDIT_LEARN_COUNT            1014
#define IDC_EDIT3                       1015
#define IDC_LIST_GMITEM_SEARCH          1015
#define IDC_EDIT42                      1015
#define IDC_BUTTON_STOP                 1015
#define IDC_EDIT_VIEW_TYPE0             1015
#define IDC_EDIT4                       1016
#define IDC_EDIT_TO_SUB                 1016
#define IDC_STATIC_GMITEM_SEARCH        1016
#define IDC_EDIT_VIEW_LEARN0            1016
#define IDC_EDIT5                       1017
#define IDC_EDIT_VIEW_CP0               1017
#define IDC_EDIT6                       1018
#define IDC_EDIT_VIEW_TYPE1             1018
#define IDC_EDIT7                       1019
#define IDC_EDIT_VIEW_LEARN1            1019
#define IDC_EDIT8                       1020
#define IDC_EDIT_VIEW_CP1               1020
#define IDC_EDIT9                       1021
#define IDC_EDIT_VIEW_TYPE2             1021
#define IDC_EDIT10                      1022
#define IDC_EDIT_VIEW_LEARN2            1022
#define IDC_EDIT11                      1023
#define IDC_BTN_MONEY_START             1023
#define IDC_EDIT_VIEW_CP2               1023
#define IDC_EDIT12                      1024
#define IDC_EDIT_VIEW_TYPE3             1024
#define IDC_EDIT13                      1025
#define IDC_EDIT_VIEW_LEARN3            1025
#define IDC_EDIT14                      1026
#define IDC_EDIT_VIEW_CP3               1026
#define IDC_EDIT17                      1027
#define IDC_COMBO_RANDOM_OPT1           1027
#define IDC_EDIT_VIEW_TYPE4             1027
#define IDC_BUTTON2                     1028
#define IDC_EDIT26                      1028
#define IDC_EDIT_RANDOM_OPT1            1028
#define IDC_EDIT_VIEW_LEARN4            1028
#define IDC_BUTTON3                     1029
#define IDC_EDIT27                      1029
#define IDC_COMBO_RANDOM_OPT2           1029
#define IDC_EDIT_VIEW_CP4               1029
#define IDC_EDIT28                      1030
#define IDC_EDIT_RANDOM_OPT2            1030
#define IDC_BTN_QUEST_EXPORT_TO_CSV     1030
#define IDC_EDIT_VIEW_TYPE5             1030
#define IDC_LIST_CHAR_EDIT_SKILL        1031
#define IDC_EDIT19                      1031
#define IDC_COMBO_RANDOM_OPT3           1031
#define IDC_CHECK_VALID                 1031
#define IDC_EDIT_VIEW_LEARN5            1031
#define IDC_EDIT20                      1032
#define IDC_LIST_SKILL_ADD              1032
#define IDC_EDIT_RANDOM_OPT3            1032
#define IDC_EDT_YEAR                    1032
#define IDC_EDIT_VIEW_CP5               1032
#define IDC_BTN_INVEN_EDIT              1033
#define IDC_EDIT15                      1033
#define IDC_COMBO_RANDOM_OPT4           1033
#define IDC_EDT_MONTH                   1033
#define IDC_EDIT_VIEW_TYPE6             1033
#define IDC_BTN_INVEN_DELETE            1034
#define IDC_EDIT16                      1034
#define IDC_EDIT_RANDOM_OPT4            1034
#define IDC_EDT_DAY                     1034
#define IDC_EDIT_VIEW_LEARN6            1034
#define IDC_BTN_INVEN_SAVE              1035
#define IDC_EDIT21                      1035
#define IDC_EDT_TIME                    1035
#define IDC_EDIT_VIEW_CP6               1035
#define IDC_BTN_INVEN_ADD               1036
#define IDC_EDIT22                      1036
#define IDC_EDT_MINUTE                  1036
#define IDC_EDIT_VIEW_TYPE7             1036
#define IDC_BTN_USER_INVEN_ADD          1037
#define IDC_EDIT29                      1037
#define IDC_BTN_DISGUISE                1037
#define IDC_EDIT_VIEW_LEARN7            1037
#define IDC_BTN_USER_INVEN_EDIT         1038
#define IDC_EDIT30                      1038
#define IDC_EDIT_VIEW_CP7               1038
#define IDC_COMBO_ADD_OPT1              1038
#define IDC_BTN_USER_INVEN_DELETE       1039
#define IDC_EDIT18                      1039
#define IDC_CHECK1                      1039
#define IDC_CHECK                       1039
#define IDC_CHECK_WEAPONS               1039
#define IDC_CHECK_ITEM_ID               1039
#define IDC_CHECK_LEARN_TYPE            1039
#define IDC_CHECK_CLUBITEM_TRANSFER     1039
#define IDC_EDIT_ADD_OPT1               1039
#define IDC_BTN_USER_INVEN_SAVE         1040
#define IDC_EDIT32                      1040
#define IDC_COMBO_YEAR                  1040
#define IDC_EDIT_VIEW_TYPE8             1040
#define IDC_COMBO_ADD_OPT2              1040
#define IDC_EDIT33                      1041
#define IDC_COMBO_MONTH                 1041
#define IDC_EDIT_VIEW_LEARN8            1041
#define IDC_EDIT_ADD_OPT2               1041
#define IDC_RADIO1                      1042
#define IDC_EDIT35                      1042
#define IDC_COMBO_DAY                   1042
#define IDC_EDIT_VIEW_CP8               1042
#define IDC_RADIO2                      1043
#define IDC_EDIT36                      1043
#define IDC_COMBO_YEAR_1                1043
#define IDC_EDIT_VIEW_TYPE9             1043
#define IDC_RADIO3                      1044
#define IDC_EDIT37                      1044
#define IDC_COMBO_MONTH_1               1044
#define IDC_EDIT_VIEW_LEARN9            1044
#define IDC_RADIO4                      1045
#define IDC_EDIT38                      1045
#define IDC_COMBO_DAY_1                 1045
#define IDC_EDIT_VIEW_CP9               1045
#define IDC_RADIO5                      1046
#define IDC_EDIT39                      1046
#define IDC_CHECK_DEFENSE               1046
#define IDC_EDIT_VIEW_TYPE10            1046
#define IDC_RADIO6                      1047
#define IDC_LIST_DEFENSE                1047
#define IDC_EDIT43                      1047
#define IDC_EDIT_VIEW_LEARN10           1047
#define IDC_RADIO7                      1048
#define IDC_CHECK3                      1048
#define IDC_CHECK_ITEMCOUNT             1048
#define IDC_EDIT_VIEW_CP10              1048
#define IDC_RADIO8                      1049
#define IDC_LIST_ITEMCOUNT              1049
#define IDC_EDIT_VIEW_TYPE11            1049
#define IDC_RADIO9                      1050
#define IDC_EDIT_VIEW_LEARN11           1050
#define IDC_RADIO10                     1051
#define IDC_LIST_WEAPONS                1051
#define IDC_EDIT_VIEW_CP11              1051
#define IDC_RADIO11                     1052
#define IDC_BTN_PUTONITEM_SAVE          1053
#define IDC_EDIT_SLOTSTATE              1053
#define IDC_BTN_PUTON_DELETE            1054
#define IDC_BTN_PUTON_CHANGE            1055
#define ID_BTN_BASE_SAVE                1056
#define IDC_RADIO12                     1056
#define ID_BTN_SKILL_SAVE               1057
#define IDC_RADIO13                     1057
#define IDC_RADIO14                     1058
#define IDC_BTN_SELECT_ITEM             1059
#define IDC_RADIO15                     1059
#define IDC_EDIT_ITEM_MAIN              1060
#define IDC_BTN_SELECT_ITEM2            1060
#define IDC_EDIT_ITEM_COUNT_CONSOLE     1060
#define IDC_RADIO16                     1060
#define IDC_EDIT_ITEM_SUB               1061
#define IDC_STATIC_TIME                 1061
#define IDC_RADIO17                     1061
#define IDC_BTN_ITEM_SEARCH_START       1062
#define IDC_RADIO18                     1062
#define IDC_EDIT_ITEM_SEARCH_CONSOLE    1063
#define IDC_LIST_VEHICLE_NUM            1063
#define IDC_RADIO19                     1063
#define IDC_EDIT_USERINVEN_MONEY        1064
#define IDC_EDIT_ITEM_MAKENUM           1064
#define IDC_EDIT_VEHICLE_NAME           1064
#define IDC_BTN_PUTON_CHANGE2           1064
#define IDC_BTN_PUTON_Save              1064
#define IDC_EDIT_ITEM_SUB2              1065
#define IDC_EDIT_ITEM_COUNT             1065
#define IDC_EDIT_VEHICLE_TYPE           1065
#define IDC_BTN_SKILL_SEARCH_SKILL_CHOOSE 1065
#define IDC_EDIT_ITEM_CHANGE_CONSOLE    1066
#define IDC_EDIT_VEHICLE_MID            1066
#define IDC_LIST_SKILL_SEARCH_CHOOSE_SKILL 1066
#define IDC_BTN_CHANGE_START            1067
#define IDC_EDIT_VEHICLE_SID            1067
#define IDC_BTN_SKILL_SEARCH_START      1067
#define IDC_BTN_CHANGE_STOP             1068
#define IDC_EDIT_VEHICLE_CREATEDATE     1068
#define IDC_STATIC_SKILL_SEARCH_PROGRESS 1068
#define IDC_EDIT_VEHICLE_DELETEDATE     1069
#define IDC_PROGRESS_SKILL_SEARCH       1069
#define IDC_EDIT_FROM_MAIN              1070
#define IDC_EDIT_VEHICLE_BATTERY        1070
#define IDC_EDIT_ITEM_MAKE_NUM          1070
#define IDC_EDIT_FROM_SUB               1071
#define IDC_EDIT_VEHICLE_BOOSTER        1071
#define IDC_EDIT_ITEM_MAKE_NUM2         1071
#define IDC_EDIT_TO_MAIN                1072
#define IDC_EDIT_VEHICLE_DELETED        1072
#define IDC_BTN_SEARCH_DUP_START        1072
#define IDC_EDIT_MAKE_CRON_NUM          1073
#define IDC_BTN_CHANGE_START2           1073
#define IDC_EDIT_VEHICLE_EQUIP          1073
#define IDC_BTN_SEARCH_DUP_STOP         1073
#define IDC_EDIT_MAKE_CRON_NAME         1074
#define IDC_SEARCH_DUP_STATIC           1074
#define IDC_EDIT34                      1075
#define IDC_EDIT_VEHICLE_PARTA_MID      1075
#define IDC_SEARCH_DUP_PPROGRESS        1075
#define IDC_EDIT_GMID                   1076
#define IDC_EDIT_VEHICLE_PARTA_SID      1076
#define IDC_EDIT_SEARCH_DUP_CONSOLE     1076
#define IDC_EDIT_SEARCH_DUP_CONSOLE2    1076
#define IDC_EDIT_GMPASSWORD             1077
#define IDC_SEARH_DUP_LIST2             1077
#define IDC_LIST_SERVER_SELECT          1078
#define IDC_EDIT_VEHICLE_PARTA_NAME     1078
#define IDC_SEARH_DUP_LIST              1078
#define IDC_EDIT_VEHICLE_PARTB_MID      1079
#define IDC_BTN_MAKE_TYPE               1079
#define IDC_EDIT_RANDOM_OPT6            1079
#define IDC_EDIT_VEHICLE_PARTB_SID      1080
#define IDC_BTN_EXCHANGE_FLAG           1080
#define IDC_RESTORE                     1080
#define IDC_LIST_QUEST_ADD              1081
#define IDC_EDIT_VEHICLE_PARTB_NAME     1081
#define IDC_BTN_SEARCH_DUP_START2       1081
#define IDC_TREE1                       1081
#define IDC_BTN_QUEST_SAVE              1082
#define IDC_EDIT_VEHICLE_PARTC_MID      1082
#define IDC_BTN_SEARCH_DUP_STOP2        1082
#define IDC_BUTTON4                     1082
#define IDC_EDIT_QUEST_NAME             1083
#define IDC_EDIT_VEHICLE_PARTC_SID      1083
#define IDC_BTN_VIEW_HISTORY            1083
#define IDC_BUTTON5                     1083
#define IDC_EDIT_QUEST_COMMENT          1084
#define IDC_EDIT_VEHICLE_PARTC_NAME     1084
#define IDC_BTN_SEARCH_DUP_STOP3        1084
#define IDC_BUTTON6                     1084
#define IDC_EDIT_INVEN2_DATE            1085
#define IDC_EDIT_VEHICLE_PARTD_MID      1085
#define IDC_EDIT_ITEM_MID               1085
#define IDC_BUTTON7                     1085
#define IDC_EDIT_VEHICLE_PARTD_SID      1086
#define IDC_EDIT_ITEM_SID               1086
#define IDC_EDIT_PRODUCT_TYPE_ID        1086
#define IDC_EDIT_VEHICLE_PARTD_NAME     1087
#define IDC_EDIT_PRODUCT_TYPE           1087
#define IDC_EDIT_INVEN2_DATE2           1088
#define IDC_BTN_DELETE_QUEST            1088
#define IDC_EDIT_VEHICLE_PARTE_MID      1088
#define IDC_EDIT_CP                     1088
#define IDC_EDIT_INVEN2_DATE3           1089
#define IDC_SEARCH_PROGRESS1            1089
#define IDC_EDIT_VEHICLE_PARTE_SID      1089
#define IDC_EDIT_MAX_WS                 1089
#define IDC_EDIT_INVEN2_DATE4           1090
#define IDC_SEARCHSTATIC1               1090
#define IDC_EDIT_VEHICLE_PARTE_NAME     1090
#define IDC_EDIT_LEARN_TIME             1090
#define IDC_EDIT_INVEN2_DATE5           1091
#define IDC_EDIT_VEHICLE_PARTF_MID      1091
#define IDC_EDIT_WS                     1091
#define IDC_EDIT_INVEN2_DATE6           1092
#define IDC_EDIT_VEHICLE_PARTF_SID      1092
#define IDC_EDIT_MAX_WS2                1092
#define IDC_BUTTON_ABLE_CP              1092
#define IDC_EDIT_INVEN2_DATE7           1093
#define IDC_EDIT_VEHICLE_PARTF_NAME     1093
#define IDC_EDIT_MAX_WSP                1093
#define IDC_EDIT_INVEN2_DATE8           1094
#define IDC_EDIT_VEHICLE_PARTA_MID2     1094
#define IDC_EDIT_MAX_WSPPER             1094
#define IDC_EDIT_INVEN2_DATE9           1095
#define IDC_EDIT_VEHICLE_PARTA_SID2     1095
#define IDC_EDIT_VIEW_SID               1095
#define IDC_EDIT_INVEN2_DATE10          1096
#define IDC_EDIT_VEHICLE_PARTA_NAME2    1096
#define IDC_EDIT_VIEW_MID               1096
#define IDC_EDIT_INVEN2_DATE11          1097
#define IDC_EDIT_VEHICLE_PARTB_MID2     1097
#define IDC_EDIT_VIEW_ID                1097
#define IDC_EDIT_INVEN2_DATE12          1098
#define IDC_EDIT_VEHICLE_PARTB_SID2     1098
#define IDC_EDIT_VIEW_RESULT_ITEM_NAME  1098
#define IDC_EDIT_INVEN2_DATE13          1099
#define IDC_EDIT_VEHICLE_PARTB_NAME2    1099
#define IDC_BUTTON_UNABLE_CP            1099
#define IDC_EDIT_INVEN2_DATE14          1100
#define IDC_EDIT_VEHICLE_PARTA_MID3     1100
#define IDC_BUTTON_ABLE_MP              1100
#define IDC_EDIT_INVEN2_DATE15          1101
#define IDC_EDIT_VEHICLE_PARTA_SID3     1101
#define IDC_BUTTON_UNABLE_MP            1101
#define IDC_EDIT_VEHICLE_PARTA_NAME3    1102
#define IDC_EDIT_CLUB_INVEN_MONEY       1102
#define IDC_EDIT_VEHICLE_PARTB_MID3     1103
#define IDC_BTN_ITEMTRANSFER_START      1103
#define IDC_EDIT_VEHICLE_PARTB_SID3     1104
#define IDC_BTN_ITEMTRANSFER_STOP       1104
#define IDC_EDIT_VEHICLE_PARTB_NAME3    1105
#define IDC_ITEMTRANSFER_PROGRESS       1105
#define IDC_EDIT_ITEMTRANSFER_CONSOLE   1106
#define IDC_LIST_ITEMTRANSFER_SEARCH    1107
#define IDC_STATIC_ITEMTRANSFER         1108
#define IDC_STATIC_ITEMTRANSFER1        1108
#define IDC_BTN_ITEM_RESTORE            1109
#define IDC_SELLITEM_LIST               1110
#define IDC_RADIO_CHARSLOT_A            1111
#define IDC_RADIO_CHARSLOT_B            1112
#define IDC_RADIO_CHARSLOT_C            1113
#define IDC_RADIO_CHARSLOT_D            1114
#define IDC_RADIO_CHARSLOT_E            1115
#define IDC_EDIT_CURRENT_SLOT           1116
#define IDC_EDIT_DAMAGE_LOW             1117
#define IDC_EDIT_DAMAGE_HIGH            1118
#define IDC_EDIT_DEFENSE                1119
#define IDC_COMBO_LINKSKILL_TYPE        1137
#define IDC_EDIT_LINKSKILL_PROBABILITY  1138
#define IDC_EDIT_LINKSKILL_MID          1139
#define IDC_EDIT_LINKSKILL_SID          1140
#define IDC_EDIT_LINKSKILL_LEVEL        1141
#define IDC_COMBO_ADD_OPT3              1142
#define IDC_COMBO_ADD_OPT4              1143
#define IDC_EDIT_ADD_OPT3               1144
#define IDC_EDIT_ADD_OPT4               1145
#define IDC_COMBO_ADD_OPT5              1146
#define IDC_COMBO_ADD_OPT6              1147
#define IDC_EDIT_ADD_OPT5               1148
#define IDC_EDIT_ADD_OPT6               1149
#define IDC_COMBO_RANDOM_OPT5           1150
#define IDC_EDIT_RANDOM_OPT5            1151
#define ID_CONTEXT1_MAKECRONCHARACTER   32771
#define ID_COMBO                        32771
#define ID_BUTTON32772                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
