//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ItemEdit.rc
//
#define IDR_MANIFEST                    1
#define ID_BUTTON_FIND                  3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ITEMEDIT_DIALOG             102
#define IDD_ALLITEMVIEW_DIALOG          103
#define IDD_ITEMPROPERTY1_DIALOG        105
#define IDD_ITEMPARENT_DIALOG           105
#define IDD_ITEMPROPERTY2_DIALOG        106
#define IDD_INPUTDATADLG                108
#define IDD_WEARINGDLG                  109
#define IDR_MAINFRAME                   128
#define IDD_ITEMPROPERTY3_DIALOG        129
#define IDD_ITEMSUIT_DIALOG             129
#define ID_MENUITEM_COPY                129
#define IDR_MENU_MAINFRAME              130
#define IDD_ITEMSUITTREE_DIALOG         130
#define ID_MENUITEM_PASTE_NEW           130
#define ID_MENUITEM_NEW                 131
#define ID_MENUITEM_PASTE_VALUE         131
#define ID_MENUITEM_LOAD                132
#define ID_MENUITEM_SAVE                133
#define IDD_DIALOG_LOG                  133
#define ID_MENUITEM_EXIT                134
#define ID_MENUITEM_SUIT                135
#define IDR_MENU_POPUP                  137
#define IDR_MENU_ITEMSUIT_POPUP         137
#define IDR_MENU_ITEMSIMPLE_POPUP       138
#define ID_MENUITEM_PARENTMODIFY        139
#define ID_MENUITEM_SIMPLEMODIFY        140
#define ID_MENUITEM_SUITMODIFY          141
#define ID_MENUITEM_ADD                 143
#define ID_MENUITEM_DEL                 144
#define IDR_TOOLBAR1                    145
#define IDD_DIALOG_EXCEL_EXPORT         145
#define IDD_DIALOG_ITEM                 147
#define IDD_ITEMEDIT_DIALOG0            148
#define IDD_ITEM_SEARCH_DIALOG          149
#define IDD_LIST_DIALOG                 150
#define IDD_ITEMPARENT_DIALOG4          151
#define IDD_ITEMSUIT_DIALOG1            152
#define IDD_ITEMSUITTREE_DIALOG1        154
#define IDD_WEARINGDLG4                 154
#define IDD_ITEMSUITTREE_DIALOG2        160
#define IDD_DIALOG_GRINDING_SIMULATOR   161
#define IDD_DIALOG_SETITEMINFO          166
#define IDD_DIALOG_SETLIST_INFO         167
#define IDD_DIALOG_CHECK                168
#define IDS_PROPSHT_CAPTION             202
#define IDC_STATIC_CONTROL              1001
#define IDC_TREE_ITEM                   1002
#define IDC_EDIT_GUID                   1005
#define IDC_EDIT_MID                    1005
#define IDC_EDIT_ITEMNAME               1006
#define IDC_EDIT_NEEDLEVEL              1007
#define IDC_CHECK1                      1008
#define IDC_CHECK_THROW                 1008
#define IDC_CHECK_PALSY                 1008
#define IDC_CHECK_INC_GRINDING          1008
#define IDC_CHECK2                      1009
#define IDC_CHECK_SWOON                 1009
#define IDC_CHECK_EVENT_SGL             1009
#define IDC_CHECK_ANITIRESET            1009
#define IDC_CHECK3                      1010
#define IDC_CHECK_BOTH                  1010
#define IDC_CHECK_PETRIFY               1010
#define IDC_EDIT_NEEDLEVELUP            1010
#define IDC_CHECK_ANITITERMINATE        1010
#define IDC_CHECK4                      1011
#define IDC_CHECK_FROZEN                1011
#define IDC_CHECK5                      1012
#define IDC_CHECK_SELLENABLE            1012
#define IDC_CHECK_DERANGE               1012
#define IDC_EDIT_SID                    1013
#define IDC_CHECK6                      1013
#define IDC_CHECK_POISON                1013
#define IDC_CHECK_BUYABLE               1014
#define IDC_CHECK7                      1014
#define IDC_CHECK_CURSE                 1014
#define IDC_CHECK_SEARCH                1014
#define IDC_EDIT_PRICE                  1015
#define IDC_CHECK_BURN                  1015
#define IDC_CHECK8                      1016
#define IDC_CHECK_FIGHTER               1016
#define IDC_CHECK_CURE_RATIO            1016
#define IDC_CHECK_GARBAGE               1016
#define IDC_CHECK9                      1017
#define IDC_CHECK_ARCHER                1017
#define IDC_CHECK_TWOH                  1017
#define IDC_EDIT_PRICE2                 1017
#define IDC_CHECK10                     1018
#define IDC_CHECK_INSTANCE              1018
#define IDC_CHECK_BIGH                  1018
#define IDC_CHECK11                     1019
#define IDC_CHECK_ARMS                  1019
#define IDC_CHECK_GRD_FIRE              1019
#define IDC_CHECK_HIGH_GRIND            1019
#define IDC_CHECK_CURE_RATIO2           1019
#define IDC_CHECK_NOT_USE_PARTS         1019
#define IDC_CHECK_RESTRICT              1019
#define IDC_CHECK_INSTANCE2             1019
#define IDC_CHECK12                     1020
#define IDC_CHECK_SPIRIT                1020
#define IDC_CHECK_GRD_ICE               1020
#define IDC_CHECK_ENABLE_COSTUM         1020
#define IDC_CHECK_TWOH2                 1020
#define IDC_CHECK_SHOW_CONTENTS         1020
#define IDC_CHECK_RESTRICT2             1020
#define IDC_CHECK_GRD_ELEC              1021
#define IDC_CHECK_DISGUISE              1021
#define IDC_CHECK_GRD_POIS              1022
#define IDC_CHECK_DISGUISE2             1022
#define IDC_CHECK_TIMELMT               1022
#define IDC_EDIT_INVENSIZEX             1023
#define IDC_CHECK_REMODEL_CARD          1023
#define IDC_CHECK_SELLENABLE2           1023
#define IDC_CHECK_STORAGE               1023
#define IDC_EDIT_INVENSIZEY             1024
#define IDC_CHECK_BROOM                 1024
#define IDC_EDIT_INVENFILE              1025
#define IDC_EDIT_COMMENT                1026
#define IDC_BUTTON_INVENFILE            1027
#define IDC_EDIT_POWER                  1028
#define IDC_EDIT_STRENGTH               1029
#define IDC_EDIT_SPIRIT                 1030
#define IDC_EDIT_DEXTERITY              1031
#define IDC_EDIT_INTELLIGENT            1032
#define IDC_STATIC_GUID                 1033
#define IDC_EDIT_REQ_PA                 1034
#define IDC_LIST_MONSTER                1034
#define IDC_STATIC_PRICE                1035
#define IDC_EDIT_REQ_SA                 1036
#define IDC_STATIC_INVENSIZEX           1037
#define IDC_CHECK_SPLIT__               1037
#define IDC_STATIC_INVENSIZEY           1038
#define IDC_BUTTON_SUITFILE             1038
#define IDC_BUTTON_WEARINGFILE          1038
#define IDC_BUTTON_WEARINGFILE_C1       1038
#define IDC_CHECK_DISGUISE3             1038
#define IDC_STATIC_COMMENT              1039
#define IDC_BUTTON_WEARINGFILE_EX_C1    1039
#define IDC_STATIC_NEEDVALUE            1040
#define IDC_STATIC_POWER                1041
#define IDC_STATIC_STRENGTH             1042
#define IDC_STATIC_SPIRIT               1043
#define IDC_STATIC_DEXTERITY            1044
#define IDC_STATIC_INTELLIGENT          1045
#define IDC_STATIC_PROPERTYFLAG         1046
#define IDC_STATIC_POWER2               1046
#define IDC_STATIC_NEEDJOB              1047
#define IDC_STATIC_KIND                 1048
#define IDC_STATIC_TYPE                 1048
#define IDC_STATIC_STRENGTH2            1048
#define IDC_COMBO_TYPE                  1049
#define IDC_EDIT_WEARINGFILE            1049
#define IDC_EDIT_WEARINGFILE_C1         1049
#define IDC_STATIC_SORNEH               1049
#define IDC_STATIC_COUNT                1050
#define IDC_EDIT_STAMINA                1050
#define IDC_EDIT_WEARINGFILE_EX_C1      1050
#define IDC_EDIT_COUNT                  1051
#define IDC_BUTTON_FIELDFILE            1051
#define IDC_STATIC_VOLUME               1052
#define IDC_EDIT_REMODEL_NUM            1052
#define IDC_EDIT_VOLUME                 1053
#define IDC_STATIC_INTELLIGENT2         1053
#define IDC_COMBO_LEVEL                 1054
#define IDC_COMBO_SUIT                  1055
#define IDC_COMBO_ITEM_TYPE             1055
#define IDC_STATIC_SORNEH2              1055
#define IDC_STATIC_LEVEL                1056
#define IDC_COMBO_SUIT2                 1056
#define IDC_COMBO_ATT_TYPE              1056
#define IDC_STATIC_SUIT                 1057
#define IDC_EDIT_FIELDFILE              1057
#define IDC_BUTTON_UPDATE_SYNC          1057
#define IDC_STATIC_DEFLEVEL             1058
#define IDC_STATIC_SUIT2                1058
#define IDC_BUTTON_WEARINGFILE_C2       1058
#define IDC_LIST_CONNETS                1058
#define IDC_BUTTON_LIST_FILE            1058
#define IDC_STATIC_SORNEH3              1058
#define IDC_STATIC_DAMLEVEL             1059
#define IDC_COMBO_DRUG_TYPE             1059
#define IDC_EDIT_WEARINGFILE_C2         1059
#define IDC_STATIC_DEFENSE              1060
#define IDC_BUTTON_WEARINGFILE_C3       1060
#define IDC_STATIC_VARMP                1061
#define IDC_STATIC_DEFENSE2             1061
#define IDC_EDIT_WEARINGFILE_C3         1061
#define IDC_EDIT_VARMP                  1062
#define IDC_BUTTON_WEARINGFILE_C4       1062
#define IDC_STATIC_REQSP                1062
#define IDC_STATIC_AVOIDRATE            1063
#define IDC_EDIT_WEARINGFILE_C4         1063
#define IDC_EDIT_DEFLEVEL               1064
#define IDC_BUTTON_EFFECTFILE           1064
#define IDC_BUTTON_WEARINGFILE_EX_C2    1064
#define IDC_EDIT_DAMLEVEL               1065
#define IDC_EDIT_EFFECTFILE             1065
#define IDC_EDIT_WEARINGFILE_EX_C2      1065
#define IDC_EDIT_DEFENSE                1066
#define IDC_BUTTON_SKIN_EFFECTFILE      1066
#define IDC_BUTTON_WEARINGFILE_EX_C3    1066
#define IDC_EDIT_AVOIDRATE              1067
#define IDC_EDIT_SKIN_EFFECTFILE        1067
#define IDC_EDIT_WEARINGFILE_EX_C3      1067
#define IDC_EDIT_DAMAGE                 1068
#define IDC_BUTTON_SKIN_TAR_EFFECTFILE  1068
#define IDC_EDIT_DAMAGE_LOW             1068
#define IDC_BUTTON_WEARINGFILE_EX_C4    1068
#define IDC_COMBO_ATTACK                1069
#define IDC_EDIT_SKIN_EFFECTFILE2       1069
#define IDC_EDIT_TAR_EFFECTFILE         1069
#define IDC_EDIT_DAMAGE_HIGH            1069
#define IDC_EDIT_WEARINGFILE_EX_C4      1069
#define IDC_BUTTON_OK                   1070
#define IDC_BUTTON_CANCEL               1071
#define IDC_COMBO_MENU                  1071
#define IDC_BUTTON_NEXT                 1072
#define IDC_BUTTON_PREV                 1073
#define IDC_COMBO_ITEMSKILLS            1074
#define IDC_EDIT_DEFENSE2               1074
#define IDC_EDIT_ATT_RANGE              1074
#define IDC_STATIC_NEEDJOB2             1074
#define IDC_STATIC_INVENICON            1074
#define IDC_EDIT_WEARFILE               1075
#define IDC_EDIT_REQSP                  1075
#define IDC_EDIT_INVENICON_X            1075
#define IDC_BUTTON_WEARFILE             1076
#define IDC_EDIT_INVENSIZEY2            1076
#define IDC_EDIT_INVENICON_Y            1076
#define IDC_STATIC_ATTACK               1077
#define IDC_RADIO_SINGLE                1077
#define IDC_BUTTON_PREV2                1077
#define IDC_STATIC_NEEDSCHOOL           1077
#define IDC_RADIO_TWO                   1078
#define IDC_RADIO_SINGLE2               1078
#define IDC_BUTTON_NEXT2                1078
#define IDC_CHECK_SCHOOL1               1078
#define IDC_BTN_CSV_SAVE                1078
#define IDC_RADIO_RIGHT                 1079
#define IDC_RADIO_TWO2                  1079
#define IDC_BUTTON_CANCEL2              1079
#define IDC_CHECK_SCHOOL2               1079
#define IDC_RADIO_LEFT                  1080
#define IDC_RADIO_RIGHT2                1080
#define IDC_BUTTON_OK2                  1080
#define IDC_CHECK_SCHOOL3               1080
#define IDC_RADIO_BOTH                  1081
#define IDC_RADIO_LEFT2                 1081
#define IDC_BUTTON_RANDOM_OPT           1081
#define IDC_STATIC_RESIST               1082
#define IDC_EDIT_RANDOM_OPT             1082
#define IDC_STATIC_FIRE                 1083
#define IDC_BUTTON_WEARINGFILE_C5       1083
#define IDC_BUTTON_WEARING_SET          1083
#define IDC_STATIC_ICE                  1084
#define IDC_EDIT_WEARINGFILE_C5         1084
#define IDC_BUTTON_GRIND_OPT            1084
#define IDC_BUTTON_SKIN_TAR_EFFECTFILE2 1084
#define IDC_BUTTON_RANDOM_OPT2          1084
#define IDC_STATIC_ELECTRIC             1085
#define IDC_COMBO_ITEM_TYPE2            1085
#define IDC_BUTTON_WEARINGFILE_C6       1085
#define IDC_BUTTON_GRINDING_SIMULATOR   1085
#define IDC_STATIC_POISON               1086
#define IDC_CHECK_EXTREME_W             1086
#define IDC_BUTTON_WEARINGFILE_EX_C5    1086
#define IDC_EDIT_FIRE                   1087
#define IDC_STATIC_COMMENT2             1087
#define IDC_EDIT_WEARINGFILE_C6         1087
#define IDC_BUTTON_GENERAL_EFFECTFILE   1087
#define IDC_EDIT_ICE                    1088
#define IDC_STATIC_COMMENT3             1088
#define IDC_BUTTON_WEARINGFILE_C10      1088
#define IDC_EDIT_GENERAL_EFFECTFILE     1088
#define IDC_EDIT_ELECTRIC               1089
#define IDC_EDIT_WEARINGFILE_C7         1089
#define IDC_BUTTON_CHECK_INFO           1089
#define IDC_EDIT_POISON                 1090
#define IDC_EDIT_MAP_MID                1090
#define IDC_BUTTON_WEARINGFILE_C13      1090
#define IDC_STATIC_DIVINE               1091
#define IDC_EDIT_SPECID                 1091
#define IDC_STATIC_FIRE2                1091
#define IDC_EDIT_WEARINGFILE_EX_C5      1091
#define IDC_EDIT_DIVINE                 1092
#define IDC_STATIC_SPECID               1092
#define IDC_STATIC_ICE5                 1092
#define IDC_BUTTON_WEARINGFILE_EX_C6    1092
#define IDC_STATIC_BODY                 1093
#define IDC_RADIO_BOTH2                 1093
#define IDC_STATIC_GEN                  1093
#define IDC_RADIO_GRIND_ARM             1093
#define IDC_EDIT_WEARINGFILE_EX_C6      1093
#define IDC_STATIC_SHORT                1094
#define IDC_COMBO1                      1094
#define IDC_COMBO_ADDON_NO              1094
#define IDC_EDIT_WEARINGFILE_C8         1094
#define IDC_ITEM_SEARCH_COMBO           1094
#define IDC_EDIT_DECOMPOSEITEM          1094
#define IDC_STATIC_LONG                 1095
#define IDC_COMBO2                      1095
#define IDC_COMBO_ADDON_TYPE            1095
#define IDC_EDIT_WEARINGFILE_C9         1095
#define IDC_SKILL_TARGET                1095
#define IDC_BUTTON_PERIODEXTENSION      1095
#define IDC_EDIT_FIRE2                  1096
#define IDC_EDIT_ADDON_VAR              1096
#define IDC_EDIT_MAP_SID                1096
#define IDC_EDIT_WEARINGFILE_C12        1096
#define IDC_EDIT_SHORT                  1097
#define IDC_EDIT_TIME_SET               1097
#define IDC_RADIO_GRIND_CLOTH           1097
#define IDC_EDIT_WEARINGFILE_EX_C7      1097
#define IDC_EDIT_LONG                   1098
#define IDC_COMBO3                      1098
#define IDC_COMBO_VARIATE               1098
#define IDC_RADIO_BRIGHT_LIGHT          1098
#define IDC_EDIT_WEARINGFILE_EX_C8      1098
#define IDC_STATIC_RESIST2              1099
#define IDC_RADIO_BRIGHT_DARK           1099
#define IDC_EDIT_WEARINGFILE_EX_C9      1099
#define IDC_EDIT_FIRE3                  1100
#define IDC_EDIT_VARIATE_VAR            1100
#define IDC_RADIO_BRIGHT_BOTH           1100
#define IDC_BUTTON_WEARINGFILE_EX_C10   1100
#define IDC_STATIC_FIRE3                1101
#define IDC_EDIT_MAP_POSX               1101
#define IDC_EDIT_WEARINGFILE_EX_C12     1101
#define IDC_STATIC_RESIST3              1102
#define IDC_EDIT_MAP_POSY               1102
#define IDC_BUTTON_WEARINGFILE_EX_C13   1102
#define IDC_STATIC_RESIST4              1103
#define IDC_BUTTON_WEARINGFILE_C7       1103
#define IDC_EDIT_PERIODEXTENSION        1103
#define IDC_COMBO4                      1104
#define IDC_COMBO_BLOW                  1104
#define IDC_STATIC_PRICE2               1104
#define IDC_BUTTON_WEARINGFILE_EX_C7    1104
#define IDC_EDIT_ADDON_RANDOMSCRIPT     1104
#define IDC_EDIT_ICE2                   1105
#define IDC_EDIT_BLOW_RATE              1105
#define IDC_COMBO_ITEM_TYPE3            1105
#define IDC_COMBO_COOL_TYPE             1105
#define IDC_BUTTON_WEARINGFILE_C14      1105
#define IDC_STATIC_ICE2                 1106
#define IDC_BUTTON_WEARINGFILE_EX_C14   1106
#define IDC_COMBO_ACTIVITY_TYPE         1106
#define IDC_EDIT_ICE3                   1107
#define IDC_EDIT_BLOW_LIFE              1107
#define IDC_BUTTON_WEARINGFILE_C15      1107
#define IDC_STATIC_ICE3                 1108
#define IDC_BUTTON_WEARINGFILE_EX_C15   1108
#define IDC_EDIT_ICE4                   1109
#define IDC_EDIT_BLOW_VALUE             1109
#define IDC_EDIT_BLOW_VALUE1            1109
#define IDC_BUTTON_WEARINGFILE_C16      1109
#define IDC_STATIC_ICE4                 1110
#define IDC_STATIC_BLOWVAR1             1110
#define IDC_BUTTON_WEARINGFILE_EX_C16   1110
#define IDC_STATIC_RESIST5              1111
#define IDC_BUTTON_WEARINGFILE_C17      1111
#define IDC_EDIT_GENID                  1112
#define IDC_STATIC_ONE_TIME_LIMIT       1112
#define IDC_EDIT_BLOW_VALUE2            1112
#define IDC_BUTTON_WEARINGFILE_EX_C17   1112
#define IDC_EDIT_LIMITGENNUM            1113
#define IDC_STATIC_ONE_TIME_LIMIT2      1113
#define IDC_EDIT_GRD_MIN                1113
#define IDC_STATIC_RESIST6              1113
#define IDC_BUTTON_WEARINGFILE_C18      1113
#define IDC_EDIT_TIME_LIMIT             1114
#define IDC_COMBO_GRINDING_TYPE         1114
#define IDC_BUTTON_WEARINGFILE_EX_C18   1114
#define IDC_EDIT_GENID3                 1115
#define IDC_EDIT_LIMIT_ONETIME          1115
#define IDC_EDIT_GRD_MAX                1115
#define IDC_COMBO_VARIATE2              1115
#define IDC_BUTTON_WEARINGFILE_C19      1115
#define IDC_STATIC_BLOWVAR2             1116
#define IDC_BUTTON_WEARINGFILE_EX_C19   1116
#define IDC_LIST_BOX                    1117
#define IDC_BUTTON_WEARINGFILE_C20      1117
#define IDC_COMBO_SKILL                 1118
#define IDC_EDIT_ELECTRIC2              1118
#define IDC_BUTTON_BOX_ADD              1118
#define IDC_BUTTON_WEARINGFILE_EX_C20   1118
#define IDC_BUTTON_BOX_DEL              1119
#define IDC_LIST_ITEM                   1119
#define IDC_BUTTON_WEARINGFILE_C21      1119
#define IDC_EDIT_POINT                  1120
#define IDC_EDIT_LMT_D                  1120
#define IDC_LIST_BOX2                   1120
#define IDC_LIST_ITEM2                  1120
#define IDC_BUTTON_WEARINGFILE_EX_C21   1120
#define IDC_STATIC_SKILLNPOINT          1121
#define IDC_EDIT_LMT_H                  1121
#define IDC_BUTTON_BOX_ADD2             1121
#define IDC_EDIT_                       1121
#define IDC_EDIT_PERCENT                1121
#define IDC_EDIT_LMT_M                  1122
#define IDC_BUTTON_BOX_DEL2             1122
#define IDC_EDIT_NUM                    1122
#define IDC_EDIT_VARIATE_VAR2           1123
#define IDC_EDIT_LMT_D2                 1123
#define IDC_EDIT_COOLTIME               1123
#define IDC_EDIT_FINDMID                1123
#define IDC_BUTTON_BOX_UP1              1124
#define IDC_EDIT_FINDSID                1124
#define IDC_BUTTON_BOX_DW1              1125
#define IDC_EDIT_ITEMDESC               1126
#define IDC_BUTTON_BOX_UP2              1126
#define IDC_EDIT_NAME                   1127
#define IDC_BUTTON_BOX_DW2              1127
#define IDC_BUTTON_STRTB_SYNC           1128
#define IDC_COMBO_GRINDING_LEVEL        1128
#define IDC_EDIT_NAME2                  1128
#define IDC_EDIT_POINT_TR_COUNT         1128
#define IDC_BUTTON_RELOAD_STRTBL        1129
#define IDC_BUTTON_BOX_EDIT2            1129
#define IDC_BTN_CSV_LOAD                1130
#define IDC_BUTTON_BOX_EDIT             1130
#define IDC_STATIC_FIRE4                1131
#define IDC_BUTTON_STRTB_SEARCH         1131
#define IDC_BTN_CSV_STRTBL_EXPORT       1131
#define IDC_EDIT_GRADE_1                1132
#define IDC_BTN_CSV_STRTBL_IMPORT       1132
#define IDC_EDIT_GRADE_2                1133
#define IDC_EDIT_X_EXP                  1134
#define IDC_EDIT_ADDON_VAR2             1135
#define IDC_STATIC_FIRE5                1136
#define IDC_EDIT_ADDON_VAR3             1137
#define IDC_STATIC_FIRE6                1138
#define IDC_EDIT2                       1139
#define IDC_EDIT_ADDON_VAR4             1139
#define IDC_SETNUM                      1139
#define IDC_STATIC_FIRE7                1140
#define IDC_EDIT_ADDON_VAR5             1141
#define IDC_CHECK_EXTREME_M             1142
#define IDC_STATIC_FIRE8                1142
#define IDC_CHECK_SCIENTIST_M           1143
#define IDC_EDIT_ADDON_VAR6             1143
#define IDC_STATIC_RESIST7              1144
#define IDC_CHECK_SCIENTIST_W           1144
#define IDC_COMBO_QUESTION              1145
#define IDC_BUTTON_WEARINGFILE_C8       1145
#define IDC_CHECK_ASSASSIN_M            1145
#define IDC_STATIC_ICE6                 1146
#define IDC_BUTTON_WEARINGFILE_C9       1146
#define IDC_CHECK_ASSASSIN_W            1146
#define IDC_EDIT_QUE_TIME               1147
#define IDC_BUTTON_WEARINGFILE_C11      1147
#define IDC_CHECK_ETC_M                 1147
#define IDC_BUTTON_WEARINGFILE_C80      1148
#define IDC_BUTTON_WEARINGFILE_C12      1148
#define IDC_CHECK_ETC_W                 1148
#define IDC_EDIT_QUE_EXP                1149
#define IDC_BUTTON_WEARINGFILE_EX_C8    1149
#define IDC_STATIC_BLOWVAR3             1150
#define IDC_STATIC_QUEVAR1              1150
#define IDC_BUTTON_WEARINGFILE_EX_C9    1150
#define IDC_CHECK_ETC_W2                1150
#define IDC_EDIT_QUE_PARAM1             1151
#define IDC_BUTTON_WEARINGFILE_EX_C12   1151
#define IDC_STATIC_BLOWVAR4             1152
#define IDC_STATIC_QUEVAR2              1152
#define IDC_EDIT_BLOW_PARAM2            1153
#define IDC_EDIT_QUE_PARAM2             1153
#define IDC_EDIT_WEARINGFILE_C10        1153
#define IDC_STATIC_ICE8                 1154
#define IDC_EDIT_WEARINGFILE_C11        1154
#define IDC_CHECK_FIGHTER_M             1155
#define IDC_EDIT_WEARINGFILE_C13        1155
#define IDC_CHECK_ARMS_M                1156
#define IDC_EDIT_WEARINGFILE_EX_C10     1156
#define IDC_CHECK_ARCHER_W              1157
#define IDC_EDIT_WEARINGFILE_EX_C13     1157
#define IDC_CHECK_SPIRIT_W              1158
#define IDC_EDIT_WEARINGFILE_C14        1158
#define IDC_CHECK_FIGHTER_W             1159
#define IDC_EDIT_WEARINGFILE_EX_C14     1159
#define IDC_CHECK_ARMS_W                1160
#define IDC_EDIT_WEARINGFILE_C15        1160
#define IDC_CHECK_ARCHER_M              1161
#define IDC_EDIT_WEARINGFILE_EX_C15     1161
#define IDC_CHECK_SPIRIT_M              1162
#define IDC_EDIT_WEARINGFILE_C16        1162
#define IDC_EDIT_WEARINGFILE_EX_C16     1163
#define IDC_EDIT_WEARINGFILE_C17        1164
#define IDC_EDIT_WEARINGFILE_EX_C17     1165
#define IDC_EDIT_WEARINGFILE_C18        1166
#define IDC_PROGRESS_EXCEL_EXPORT       1166
#define IDC_EDIT_WEARINGFILE_EX_C18     1167
#define IDC_EDIT_WEARINGFILE_C19        1168
#define IDC_EDIT_WEARINGFILE_EX_C19     1169
#define IDC_EDIT_WEARINGFILE_C20        1170
#define IDC_EDIT_WEARINGFILE_EX_C20     1171
#define IDC_ITEM_STATIC                 1172
#define IDC_EDIT_WEARINGFILE_C21        1172
#define IDC_SCROLLBAR1                  1173
#define IDC_EDIT_WEARINGFILE_EX_C21     1173
#define IDC_ITEM_SEARCH_BUTTON          1174
#define IDC_ITEM_SEARCH_EDIT            1175
#define IDC_ITEM_SEARCH_LIST            1177
#define IDC_BUTTON1                     1178
#define IDC_SEARCH_REPORT_BUTTON        1178
#define IDC_BUTTON_SEARCH_MOB           1178
#define IDC_BUTTON_ITEM_TYPE            1178
#define IDC_BUTTON_CLOSE                1178
#define IDC_SELECT_BUTTON               1178
#define IDC_BUTTON_SELECT               1178
#define IDC_BUTTON_ER                   1178
#define IDC_EDIT_NEEDLEVELDW            1179
#define IDC_BUTTON_START                1179
#define IDC_STATIC_PRESENT              1180
#define IDC_BUTTON_OPENDECOMPOSEITEM    1180
#define IDC_STATIC_RANDOM               1181
#define IDC_STATIC_PETSKINPACK          1182
#define IDC_LIST2                       1183
#define IDC_EDIT_MOB_NAME               1187
#define IDC_BUTTON_ADD_PETSKIN          1188
#define IDC_EDIT_MOB_NAME2              1189
#define IDC_EDIT_PERCENT2               1189
#define IDC_STATIC_P                    1190
#define IDC_EDIT_MOB_SCALE              1191
#define IDC_STATIC_MOB_SCALE            1192
#define IDC_BUTTON_DEL_PETSKIN          1193
#define IDC_STATIC_MOB_SKINTIME         1194
#define IDC_EDIT_MOB_SKINTIME           1195
#define IDC_RADIO_ALL                   1196
#define IDC_RADIO_MAN                   1197
#define IDC_SELECT_LIST                 1197
#define IDC_RADIO_WOMAN                 1198
#define IDC_EDIT_ITEM_TYPE              1199
#define IDC_EDIT_SUIT                   1200
#define IDC_BUTTON_SUIT                 1201
#define IDC_EDIT_ATT_TYPE               1202
#define IDC_BUTTON_ATT_TYPE             1203
#define IDC_BUTTON_ADDON_NO1            1204
#define IDC_EDIT_ADDON_TYPE1            1205
#define IDC_BUTTON_ADDON_NO2            1206
#define IDC_EDIT_ADDON_TYPE2            1207
#define IDC_BUTTON_ADDON_NO3            1208
#define IDC_EDIT_ADDON_TYPE3            1209
#define IDC_BUTTON_ADDON_NO4            1210
#define IDC_EDIT_ADDON_TYPE4            1211
#define IDC_EDIT_ADDON_VAR1             1212
#define IDC_BUTTON_VARIATE              1213
#define IDC_CHECK_EXCHANGE              1213
#define IDC_EDIT_VARIATE_TYPE           1214
#define IDC_BTN_SQL_SAVE                1214
#define IDC_BUTTON_VOLUME               1215
#define IDC_BUTTON_GRINDING_OPT         1215
#define IDC_EDIT_VOLUME_TYPE            1216
#define IDC_EDIT_GRINDING_OPT           1216
#define IDC_BUTTON_BLOW                 1217
#define IDC_EDIT_GRINDING_OPT2          1217
#define IDC_EDIT_BLOW_TYPE              1218
#define IDC_BUTTON_QUESTION             1219
#define IDC_EDIT_QUESTION_TYPE          1220
#define IDC_LIST_LOG                    1220
#define IDC_CHECK_ANTIRESET             1221
#define IDC_BUTTON_ADDON_NO5            1221
#define IDC_CHECK_ANTITERMINATE         1222
#define IDC_EDIT_ADDON_TYPE5            1222
#define IDC_BUTTON_DRUG                 1223
#define IDC_EDIT_DRUG_TYPE              1224
#define IDC_BUTTON_ADDON_NO6            1225
#define IDC_EDIT_ADDON_TYPE6            1226
#define IDC_PROGRESS2                   1227
#define IDC_ICON_IMAGE                  1228
#define IDC_EDIT_DURABILITY_MAX         1229
#define IDC_EDIT_REPAIR_PRICE           1230
#define IDC_CHECK13                     1231
#define IDC_CHECK_ENABLE_UNIQUE         1231
#define IDC_EDIT_SETID                  1231
#define IDC_EDIT_SAVE_STATE             1232
#define IDC_EDIT1                       1233
#define IDC_EDIT_SETITEM_NAME           1233
#define IDC_SKILL_RATE                  1233
#define IDC_STATIC_DRUG_VAR             1234
#define IDC_EDIT3                       1235
#define IDC_SETNAME                     1235
#define IDC_SKILL_MID                   1235
#define IDC_EDIT4                       1236
#define IDC_SETFILENAME                 1236
#define IDC_SKILL_RATE2                 1236
#define IDC_SKILL_LV                    1236
#define IDC_SKILL_SID                   1237
#define IDC_LIST5                       1244
#define IDC_LIST6                       1245
#define IDC_SET_LIST                    1246
#define IDC_BUTTON2                     1248
#define IDC_RELOAD_BUTTON               1248
#define IDC_CHECK_TRICKER_W             1249
#define IDC_CHECK_TRICKER_M             1250
#define IDC_BUTTON_XMLCONVERT           1251
#define IDC_CHECK_UNABLE_REMODEL_CARD   1251
#define IDC_BTN_EXCEL_STRTBL_EXPORT     1252
#define IDC_CHECK_BOX_WRAPPABLE         1252
#define IDC_BTN_EXCEL_STRTBL_IMPORT     1253
#define IDC_CHECK_ACTOR_M               1253
#define IDC_BUTTON_EXCEL_EXPORT         1254
#define IDC_CHECK_ACTOR_W               1254
#define IDC_CHECK_SPLIT                 1255
#define IDC_COMBO_REQ_BRIGHT            1257
#define IDC_COMBO_GRINDING_NO           1257
#define IDC_LIST_CHECK_BOX              1259
#define IDC_STATIC_ER                   1260
#define IDC_SKILL_GROUP                 1261
#define IDC_STATIC_TARGET               1262
#define IDC_STATIC_RATE                 1263
#define IDC_STATIC_MSID                 1264
#define IDC_STATIC_LV                   1265
#define IDC_BUTTON_SUBICONFILE_C1       1265
#define IDC_EDIT_SUBICONFILE_C1         1266
#define IDC_STATIC_RSET_INDEX           1266
#define IDC_BUTTON_SUBICONFILE_C2       1267
#define IDC_EDIT_SUBICONFILE_C2         1268
#define IDC_BUTTON_SUBICONFILE_C3       1269
#define IDC_EDIT_SUBICONFILE_C3         1270
#define IDC_BUTTON_SUBICONFILE_C4       1271
#define IDC_EDIT_SUBICONFILE_C4         1272
#define IDC_BUTTON_SUBICONFILE_C5       1273
#define IDC_EDIT_SUBICONFILE_C5         1274
#define IDC_BUTTON_SUBICONFILE_C6       1275
#define IDC_EDIT_SUBICONFILE_C6         1276
#define IDC_BUTTON_SUBICONFILE_C7       1277
#define IDC_EDIT_SUBICONFILE_C7         1278
#define IDC_BUTTON_SUBICONFILE_C8       1279
#define IDC_EDIT_SUBICONFILE_C8         1280
#define IDC_BUTTON_SUBICONFILE_C9       1281
#define IDC_EDIT_SUBICONFILE_C9         1282
#define IDC_BUTTON_SUBICONFILE_C10      1283
#define IDC_EDIT_SUBICONFILE_C10        1284
#define IDC_BUTTON_SUBICONFILE_C12      1285
#define IDC_EDIT_SUBICONFILE_C12        1286
#define IDC_BUTTON_SUBICONFILE_C13      1287
#define IDC_EDIT_SUBICONFILE_C13        1288
#define IDC_BUTTON_SUBICONFILE_C14      1289
#define IDC_EDIT_SUBICONFILE_C14        1290
#define IDC_BUTTON_SUBICONFILE_C15      1293
#define IDC_EDIT_SUBICONFILE_C15        1294
#define IDC_BUTTON_SUBICONFILE_C16      1295
#define IDC_EDIT_SUBICONFILE_C16        1296
#define IDC_EDIT_DAMAGE_RSET_INDEX      1296
#define IDC_BUTTON_SUBICONFILE_C17      1297
#define IDC_EDIT_DEFENSE_RSET_INDEX     1297
#define IDC_EDIT_SUBICONFILE_C17        1298
#define IDC_CHECK_DAMAGE_EDITABLE       1298
#define IDC_BUTTON_SUBICONFILE_C18      1299
#define IDC_CHECK_DEFENSE_EDITABLE      1299
#define IDC_EDIT_SUBICONFILE_C18        1300
#define IDC_EDIT_RSET_INDEX             1300
#define IDC_IDC_EDIT_DAMAGE_RSET_TYPE   1300
#define IDC_BUTTON_SUBICONFILE_C19      1301
#define IDC_EDIT_LINKSKILL_RSET_INDEX   1301
#define IDC_EDIT_SUBICONFILE_C19        1302
#define IDC_EDIT_DAMAGE_RSET_TYPE       1302
#define IDC_BUTTON_SUBICONFILE_C20      1303
#define IDC_EDIT_DEFENSE_RSET_TYPE      1303
#define IDC_EDIT_SUBICONFILE_C20        1304
#define IDC_BUTTON_SUBICONFILE_C21      1305
#define IDC_EDIT_SUBICONFILE_C21        1306
#define IDC_EDIT_DELAYTIME              2026
#define IDC_EDIT_MAGICFORCEUP           2027
#define IDC_EDIT_HIT                    2028
#define IDC_EDIT_HP                     2029
#define IDC_EDIT_HIT2                   2029
#define IDC_EDIT_INSTANCE_NUM           2029
#define IDC_EDIT_MP                     2030
#define IDC_EDIT_HIT3                   2030
#define IDC_EDIT_INSTANCE_VOLUME        2030
#define IDC_EDIT_REFELECT               2031
#define IDC_EDIT_HIT4                   2031
#define IDC_EDIT_SKILL_MID              2031
#define IDC_EDIT_COSTUME_TIME           2031
#define IDC_EDIT_INSTANCE_NUM2          2031
#define IDC_EDIT_VARHP                  2032
#define IDC_EDIT_HIT5                   2032
#define IDC_EDIT_SKILL_SID              2032
#define IDC_EDIT_SKILL_LEVEL            2033
#define IDC_STATIC_ITEMNAME             2034
#define IDC_EDIT_NEED_ACT_POINT_DW      2035
#define IDC_STATIC_NEEDLEVEL            2036
#define IDC_EDIT_NEED_CONTRIBUTION_POINT 2037
#define IDC_STATIC_NEEDLEVEL3           2038
#define IDC_EDIT_NEED_ACT_POINT_UP      2038
#define IDC_STATIC_DELAYTIME            2039
#define IDC_STATIC_NEEDLEVEL4           2039
#define IDC_EDIT_SKILL_MID2             2039
#define IDC_EDIT_PRODUCT_BOOK           2039
#define IDC_STATIC_DAMAGE               2040
#define IDC_STATIC_NEEDLEVEL5           2040
#define IDC_STATIC_ITEMNAME2            2040
#define IDC_STATIC_MAGICFORCEUP         2041
#define IDC_STATIC_NEEDLEVEL6           2041
#define IDC_STATIC_HIT                  2042
#define IDC_STATIC_HP                   2043
#define IDC_STATIC_HIT2                 2043
#define IDC_STATIC_NEEDLEVEL7           2043
#define IDC_STATIC_MP                   2044
#define IDC_STATIC_HIT3                 2044
#define IDC_STATIC_PARTS_TYPE           2044
#define IDC_STATIC_REFELECT             2045
#define IDC_STATIC_HIT4                 2045
#define IDC_STATIC_VARHP                2046
#define IDC_STATIC_HIT5                 2046
#define IDC_STATIC_HIT6                 2047
#define IDC_STATIC_STATS                2071
#define IDC_STATIC_POINT                2119
#define IDC_STATIC_SKILL                2121
#define IDC_EDIT_PET_MID                2130
#define IDC_EDIT_PET_SID                2131
#define IDC_COMBO_PET_TYPE              2132
#define IDC_COMBO_VEHICLE_TYPE          2133
#define IDC_COMBO_VEHICLE_TYPE2         2134
#define IDC_COMBO_PARTS_TYPE            2134

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1303
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
