

#pragma once

enum 
{
	// ET_CONTROL_NEXT = 5¿Ãπ«∑Œ

	MAP_SETTING_RADIO = 5 + 1,
	MAP_INFO_RADIO,
	MAP_PARTY_RADIO,
	MAP_SEARCH_RADIO,

	CHANGEMAP_MYPOS_BTN,
	CHANGEMAP_PRE_BTN,
	CHANGEMAP_NEXT_BTN,
	CHANGEMAP_BTN,
	CHANGEMAP_QUESTION_BTN,
	CHANGEMAP_ROLLOVER,

	MAP_IMAGE,


	SETTING_TAP,
	INFO_TAP,
	PARTY_TAP,
	SEARCH_TAP,



	//////////////////////////////////////////////////////////////////////////

	LARGEMAP_SCROLLBAR_H,
	LARGEMAP_SCROLLBAR_V,
	LARGEMAP_IMAGE,
	LARGEMAP_RESIZE_THUMB,
	PLAYER_MARK,
	PLAYER_MARK_DIRECTION,
	LARGEMAP_DIRECTION,
	LARGEMAP_RB_THUMB,
	LARGEMAP_LB_THUMB,
	LARGEMAP_CLOSE_BUTTON,
	BASE_CONTROLID,		
	BASE_CONTROLID_END = BASE_CONTROLID + 1000,

};

