//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EffectTool.rc
//
#define IDMENU_SELECT                   0
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_SOUND                103
#define IDR_MAINFRAME                   128
#define IDR_EFFECTTYPE                  129
#define IDS_PROPSHT_CAPTION             129
#define IDD_DIALOG_EDIT                 130
#define IDD_DIALOG_EFFEDIT              130
#define IDD_DIALOG_EFFLIFETIME          131
#define IDD_DIALOG_EFFGROUP             132
#define ID_VIEW_CURNONE                 133
#define ID_VIEW_MOVE                    134
#define ID_VIEW_ROTATE                  135
#define ID_VIEW_SCALE                   136
#define IDD_DIALOG_PARTICLE             137
#define IDD_DIALOG_DIRECTION            138
#define IDD_DIALOG_SETVER               139
#define IDD_DIALOG_COLORS               141
#define IDB_BITMAP_HSB                  142
#define IDB_BITMAP_RGB                  144
#define IDD_DIALOG1                     145
#define IDD_DIALOG_GROUND               145
#define IDD_DIALOG_SETMULTISLIDER       146
#define IDD_DIALOG_EFFMESH              147
#define IDD_DIALOG_SEQUENCE             148
#define IDD_DIALOG2                     149
#define IDD_DIALOG_GROUPPROP            149
#define IDR_MENU1                       150
#define IDR_MENU_LINEBAR                150
#define ID_VIEW_CHAR                    151
#define ID_VIEW_MAP                     152
#define IDD_DIALOG_DECAL                153
#define IDD_DIALOG_CAMERA               154
#define IDD_DIALOG_BLURSYS              155
#define IDD_DIALOG_LIGHTING             156
#define IDD_DIALOG_LIGHTNING            156
#define IDD_DIALOG_PARTICLE_HIGH        157
#define IDD_DIALOG_MOVEROTATE           158
#define ID_VIEW_PARTICLERANGE           159
#define IDD_DIALOG_EFFSKINMESH          161
#define IDD_DIALOG_WAVE                 162
#define IDD_DIALOG_POINTLIGHT           163
#define IDD_DIALOG_MOVETARGET           164
#define IDD_DIALOG_EFFMESH_TRANSFORM    165
#define IDD_DIALOG_EFFMESH_DISPLAY      166
#define IDD_DIALOG_PARTICLE_EMITTER     167
#define IDD_DIALOG_PARTICLE_PARTICLE    168
#define IDD_DIALOG_PARTICLE_DISPLAY     169
#define IDD_DIALOG_RANGE                170
#define IDD_DIALOG_SEQUENCE_DLG         171
#define IDD_DIALOG_LOG                  172
#define IDD_DIALOG_TARGETINFLUENCE      173
#define IDD_DIALOG_SCREEN               174
#define IDD_DIALOG_SOUNDSOURCE          204
#define IDC_SCROLLBAR_H                 1000
#define IDC_STATIC_RGB_RECT             1000
#define IDC_SCROLLBAR2                  1001
#define IDC_SCROLLBAR_V                 1001
#define IDC_STATIC_HSB_RECT             1001
#define IDC_STATIC_EFFTIMELINE          1002
#define IDC_EDIT_RED                    1002
#define IDC_TREE_EFFGROUP               1003
#define IDC_SPIN_RED                    1003
#define IDC_COMBO_EFFTYPE               1004
#define IDC_EDIT_GREEN                  1004
#define IDC_BUTTON_INSERT               1005
#define IDC_SPIN_GREEN                  1005
#define IDC_BUTTON_EFFSTATE             1006
#define IDC_EDIT_BLUE                   1006
#define IDC_BUTTON_EFFDEL               1007
#define IDC_SPIN_BLUE                   1007
#define IDC_STATIC_SHEETTAP             1008
#define IDC_STATIC_OLD                  1008
#define IDC_BUTTON_INSERT2              1008
#define IDC_BUTTON_MOVE_OBJ             1008
#define IDC_BUTTON_PLAY                 1009
#define IDC_STATIC_NEW                  1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON_OK                   1010
#define IDC_STATIC_POS                  1010
#define IDC_EDIT_HUE                    1010
#define IDC_BUTTON_CREATEPOS            1010
#define IDC_BUTTON_COPY                 1010
#define IDC_BUTTON_PLAY2                1011
#define IDC_SPIN_HUE                    1011
#define IDC_BUTTONOK                    1011
#define IDC_BUTTON_DOWN                 1011
#define IDC_BUTTON_PLAY3                1012
#define IDC_EDIT_SAT                    1012
#define IDC_BUTTON_PASTE                1012
#define IDC_BUTTON_INIT_DIRECT          1012
#define IDC_BUTTON_APPLY                1013
#define IDC_SPIN_SAT                    1013
#define IDC_BUTTON_TEST_TARGET          1013
#define IDC_EDIT_VAL                    1014
#define IDC_BUTTON_ANIM_SELECT          1014
#define IDC_BUTTON_APPLY2               1014
#define IDC_SPIN_VAL                    1015
#define IDC_BUTTON_CHF_LOAD             1015
#define IDC_BUTTON_TEST_ABORT           1016
#define IDC_BUTTON_OK2                  1017
#define IDC_EDIT_PARTICLE_S             1025
#define IDC_EDIT_WIDTH_OUT              1026
#define IDC_EDIT_FRAME_EFF_NAME         1027
#define IDC_EDIT_WIDTH2                 1027
#define IDC_EDIT_RANROTATE              1027
#define IDC_BUTTON_VELOCITY             1028
#define IDC_EDIT_WIDTH_IN               1028
#define IDC_BUTTON_GRAVITY              1029
#define IDC_EDIT_TEXTURE                1030
#define IDC_BUTTON_ATTRACTION           1030
#define IDC_BUTTON_TEXTURE              1031
#define IDC_BUTTON_SCALE                1032
#define IDC_EDIT_TEXTURE_OUT            1032
#define IDC_BUTTON_LIFE                 1033
#define IDC_BUTTON_ANI                  1033
#define IDC_EDIT_KEYWORD                1033
#define IDC_BUTTON_TEXTURE_OUT          1033
#define IDC_BUTTON_WAVE                 1033
#define IDC_EDIT_NEWEFF                 1033
#define IDC_BUTTON_COLOR_S              1034
#define IDC_BUTTON_COLLISION            1034
#define IDC_BUTTON_COLOR_V              1035
#define IDC_BUTTONCOLOR_E               1036
#define IDC_BUTTON_GRAVITY_MAIN         1037
#define IDC_BUTTON_HEIGHT               1037
#define IDC_BUTTON_NEWEFF               1037
#define IDC_EDIT_ANGEL                  1038
#define IDC_BUTTON_ROTATE               1038
#define IDC_BUTTON_RANGE                1039
#define IDC_EDIT_SOUND                  1039
#define IDC_EDIT_FLARE                  1039
#define IDC_EDIT_FLAREPOS               1039
#define IDC_BUTTON_RANGE_HIGH           1040
#define IDC_BUTTON_CANCEL               1041
#define IDC_BUTTON_WINDDIR              1041
#define IDC_STATIC_COLOR                1042
#define IDC_BUTTON_CENTER               1042
#define IDC_SCROLLBAR_Z                 1043
#define IDC_BUTTON_ROTATEL              1043
#define IDC_COMBO_BLEND                 1044
#define IDC_SCROLLBAR_X                 1044
#define IDC_BUTTON_SEQUENCE             1044
#define IDC_SCROLLBAR_Y                 1045
#define IDC_SCROLLBAR_START             1045
#define IDC_BUTTON_GRAVITY_MAIN_E       1045
#define IDC_BUTTON_SCALEXYZ             1045
#define IDC_COMBO_POWER                 1045
#define IDC_BUTTON_BILLUP               1045
#define IDC_SCROLLBAR_STARTVAR          1046
#define IDC_BUTTON_TEXROTATE            1046
#define IDC_BUTTON_TEX                  1046
#define IDC_BUTTON_IDC_BUTTON_TEXROTATE 1046
#define IDC_BUTTON_TEXMOVE              1046
#define IDC_SCROLLBAR_END               1047
#define IDC_BUTTON_VELOCITY2            1047
#define IDC_BUTTON_TEX_SCALE            1047
#define IDC_EDIT_MINRANGE               1047
#define IDC_BUTTON_SEQUENCE2            1047
#define IDC_EDIT_START_F                1048
#define IDC_BUTTON_MESH                 1048
#define IDC_BUTTON_HEIGHT_NO            1048
#define IDC_STATIC_START                1049
#define IDC_EDIT_TEXTURE2               1049
#define IDC_EDIT_MESH                   1049
#define IDC_BUTTON_RANDOM_PLAY          1049
#define IDC_EDIT_STARTVAR_F             1050
#define IDC_BUTTON_BILLALL              1050
#define IDC_EDIT_END_F                  1051
#define IDC_COMBO_BLEND2                1051
#define IDC_STATIC_STARTVAR             1052
#define IDC_COMBO_POWER2                1052
#define IDC_STATIC_END                  1053
#define IDC_STATIC_END4                 1054
#define IDC_SCROLLBAR_END4              1055
#define IDC_BUTTON_ALPHA                1056
#define IDC_EDIT_END_F4                 1056
#define IDC_EDIT_END4_F                 1056
#define IDC_SLIDER1                     1060
#define IDC_BUTTON_SELECT               1060
#define IDC_EDIT1                       1061
#define IDC_EDIT_FILE                   1061
#define IDC_EDIT_POWER                  1061
#define IDC_EDIT_ROTATE_Y               1061
#define IDC_EDIT_REPLAY_NUM             1061
#define IDC_EDIT_SPEED                  1061
#define IDC_EDIT_S_GUIDED_ACCEL         1061
#define IDC_EDIT_PLAY_S                 1061
#define IDC_EDIT_RADIUS                 1061
#define IDC_EDIT_LOG                    1061
#define IDC_EDIT2                       1062
#define IDC_BUTTON_READ                 1062
#define IDC_EDIT_MID1                   1062
#define IDC_EDIT_POWER2                 1062
#define IDC_EDIT_PLAY_NUM               1062
#define IDC_EDIT_ROTATE_Z               1062
#define IDC_EDIT_S_RANDOM               1062
#define IDC_EDIT_PLAY_E                 1062
#define IDC_EDIT_HEIGHT                 1062
#define IDC_EDIT3                       1063
#define IDC_EDIT_SOURCE_X               1063
#define IDC_EDIT_ROTATE_X               1063
#define IDC_BUTTON_READ2                1063
#define IDC_EDIT_S_RANDOM2              1063
#define IDC_EDIT_OBJECT_RADIUS          1063
#define IDC_EDIT_SLEEP_S                1063
#define IDC_EDIT4                       1064
#define IDC_EDIT_SOURCE_Y               1064
#define IDC_EDIT_FILE2                  1064
#define IDC_EDIT_SLEEP_E                1064
#define IDC_EDIT5                       1065
#define IDC_EDIT_SOURCE_Z               1065
#define IDC_BUTTON_READ3                1065
#define IDC_EDIT6                       1066
#define IDC_EDIT_DEST_X                 1066
#define IDC_EDIT_FILE3                  1066
#define IDC_EDIT7                       1067
#define IDC_EDIT_DIST_Y                 1067
#define IDC_EDIT8                       1068
#define IDC_EDIT_DIST_Z                 1068
#define IDC_EDIT9                       1069
#define IDC_EDIT_VELOCITY               1069
#define IDC_SPIN1                       1070
#define IDC_SPIN_SCALE                  1070
#define IDC_EDIT_CUSTOM_VEL             1070
#define IDC_EDIT_X                      1071
#define IDC_BUTTON3                     1071
#define IDC_BUTTON_DIRECTION            1071
#define IDC_EDIT_Y                      1072
#define IDC_BUTTON4                     1072
#define IDC_EDIT_START                  1072
#define IDC_EDIT_Z                      1073
#define IDC_EDIT_MID2                   1073
#define IDC_EDIT_DIRECTION_X            1073
#define IDC_EDIT_EFFECT_FILE            1073
#define IDC_EDIT_END                    1074
#define IDC_EDIT10                      1074
#define IDC_CHECK_USE                   1075
#define IDC_SPIN2                       1075
#define IDC_STATIC_LENGTH               1076
#define IDC_STATIC_TEMP                 1076
#define IDC_EDIT11                      1076
#define IDC_EDIT_TEMP                   1077
#define IDC_SPIN3                       1077
#define IDC_STATIC_TEMP4                1078
#define IDC_EDIT_DIRECTION_Y            1078
#define IDC_EDIT_ROTATE_VELOCITY        1078
#define IDC_EDIT14                      1079
#define IDC_EDIT_DIRECTION_Z            1079
#define IDC_SPIN4                       1079
#define IDC_SPIN_ROTATE_VELOCITY        1079
#define IDC_EDIT_WIDTH                  1079
#define IDC_BUTTON_WIND                 1080
#define IDC_EDIT_ROTATE_ANGLE           1080
#define IDC_CHECK_BEZIER                1080
#define IDC_STATIC_WIDTH                1080
#define IDC_CHECK_ROTATE                1081
#define IDC_CHECK_PARENT_END            1081
#define IDC_CHECK_BEZIER2               1081
#define IDC_CHECK_LOOP_RESET            1081
#define IDC_SPIN5                       1082
#define IDC_SPIN_ROTATE_ANGLE           1082
#define IDC_COMBO_DIRECTION             1083
#define IDC_BUTTON2_CANCEL              1084
#define IDC_CHECK_ROTATE2               1084
#define IDC_CHECK_SCALE                 1084
#define IDC_COMBO1                      1085
#define IDC_EDIT_MORPHNUM               1085
#define IDC_RADIO_TARGET_MOVE           1086
#define IDC_EDIT_BLUR_NUM               1086
#define IDC_RADIO_TARGET_MOVE2          1087
#define IDC_RADIO_TARGET_DISMOVE        1087
#define IDC_CHECK_MATERIAL_APPLY        1088
#define IDC_BUTTON_COLOR_E              1089
#define IDC_CHECK_ATTRACTION            1090
#define IDC_CHECK_DIRECTION             1091
#define IDC_CHECK_COLLISION             1092
#define IDC_CHECK_TEXMOVE               1092
#define IDC_CHECK_GCOLLISION            1093
#define IDC_STATIC2                     1094
#define IDC_CHECK_CENTER                1094
#define IDC_CHECK_LIGHTING              1094
#define IDC_CHECK_NOROTATE              1095
#define IDC_CHECK_NEVERDIE              1095
#define IDC_CHECK_DYNAMIC_SCALE         1095
#define IDC_CHECK_PICKING               1095
#define IDC_CHECK_HEIGHT_NO             1095
#define IDC_CHECK_TARGETPOS             1096
#define IDC_CHECK_TARGETID              1097
#define IDC_CHECK_BILLALL               1097
#define IDC_CHECK_DIRECTION2            1098
#define IDC_CHECK_BILLUP                1098
#define IDC_STATIC_LINE2                1100
#define IDC_RADIO_UP                    1100
#define IDC_RADIO_MID                   1101
#define IDC_RADIO_DOWN                  1102
#define IDC_STATIC_CENTER               1103
#define IDC_RADIO_NEVERDIE              1104
#define IDC_RADIO_TARGETPOS             1105
#define IDC_COMBO_CAMERA_SET            1105
#define IDC_RADIO_TARGETID              1106
#define IDC_BUTTON_EDITSOUND            1106
#define IDC_RADIO_TARGETPOS2            1107
#define IDC_RADIO_NOTARGET              1107
#define IDC_CHECK_LOOP                  1107
#define IDC_STATIC_SOUND                1107
#define IDC_CHECK1                      1108
#define IDC_CHECK_PARENT                1108
#define IDC_CHECK_IN                    1108
#define IDC_CHECK_PARENT_ROTATE         1108
#define IDC_RADIO_NOTARGET2             1108
#define IDC_RADIO_NOTARGET_MOV          1108
#define IDC_CHECK_NORMAL                1108
#define IDC_CHECK_TEXTURE               1108
#define IDC_CHECK_MESH                  1108
#define IDC_CHECK_MOVE                  1108
#define IDC_RADIO_AVERAGE               1108
#define IDC_CHECK_GROUND_CRASH          1108
#define IDC_CHECK_DEFAULT_POS           1108
#define IDC_CHECK_RANDOM_DIRECT         1108
#define IDC_CHECK_REPEAT                1108
#define IDC_CHECK_AUTO_AABBBOX          1108
#define IDC_EDIT_FACES                  1109
#define IDC_CHECK_START                 1109
#define IDC_CHECK_PARENT_MOVE           1109
#define IDC_CHECK_TEX                   1109
#define IDC_RADIO_SLOWFAST              1109
#define IDC_CHECK_NO_WOLRD_RS           1109
#define IDC_CHECK_GOTOCENTER            1110
#define IDC_EDIT_LIFE                   1110
#define IDC_RADIO_TARGETID2             1110
#define IDC_RADIO_FASTSLOW              1110
#define IDC_CHECK_NEWEFF                1110
#define IDC_EDIT_DIVISION               1111
#define IDC_CHECK_PARENT_ROTATE2        1111
#define IDC_CHECK_RANDOM_LIFE           1111
#define IDC_EDIT_LENGTH                 1112
#define IDC_CHECK_OUT                   1113
#define IDC_CHECK_RANROTATE             1114
#define IDC_EDIT_TEXTURE_IN             1115
#define IDC_BUTTON_TEXTURE_IN           1116
#define IDC_STATIC_IN                   1117
#define IDC_STATIC_OUT                  1118
#define IDC_EDIT_BUFFERCOUNT            1119
#define IDC_CHECK_OUT2                  1119
#define IDC_CHECK_END                   1119
#define IDC_BUTTON_HIGH                 1119
#define IDC_EDIT_OUT_NUM                1120
#define IDC_STATIC_MATRIX_MOVE          1120
#define IDC_EDIT_MAPSOUNDNAME           1121
#define IDC_COMBO_CATEGORY              1121
#define IDC_STATIC_MATRIX_EX            1121
#define IDC_STATIC_MATRIX_ROTATE        1122
#define IDC_RADIO_ABSOLUTE              1122
#define IDC_RADIO_ABSOLUTENO            1123
#define IDC_CHECK_PARENT_ROTATE_WORLD   1124
#define IDC_BUTTON_UP                   1125
#define IDC_RADIO_BILLBOARD             1126
#define IDC_RADIO_BILLDIRECT            1127
#define IDC_CHECK_BLEND_MESH            1127
#define IDC_RADIO_BILLUP                1128
#define IDC_CHECK_BLUR                  1128
#define IDC_CHECK_THROW                 1128
#define IDC_CHECK_CULLMODE              1129
#define IDC_CHECK_FROMTO                1129
#define IDC_CHECK_GROUND                1130
#define IDC_BUTTON_AREA                 1133
#define IDC_BUTTON_MOVE                 1134
#define IDC_CHECK2                      1136
#define IDC_CHECK_INITRAND              1136
#define IDC_CHECK_CUSTOM_RANDOM_Y       1136
#define IDC_CHECK_S_RANDOM              1136
#define IDC_RADIO_GROUND                1137
#define IDC_CHECK_CUSTOM_RANDOM_XZ      1137
#define IDC_BUTTON_COLOR                1138
#define IDC_BUTTON_POWER                1139
#define IDC_RADIO_RANDOM                1140
#define IDC_RADIO_WAVE                  1141
#define IDC_RADIO_EMISSION              1142
#define IDC_LIST_SOUNDSOURCE            1143
#define IDC_RADIO_COLLECT               1143
#define IDC_RADIO_VEL_DIRECT            1143
#define IDC_RADIO_TARGET                1144
#define IDC_RADIO_CUSTOM_DIR            1145
#define IDC_BUTTON_CUSTOM_DIR           1147
#define IDC_STATIC_CUSTOM_1             1148
#define IDC_RADIO_S_TARGET              1149
#define IDC_RADIO_S_DIRECT              1150
#define IDC_RADIO_A_CRASH               1151
#define IDC_RADIO_A_HIGH                1152
#define IDC_RADIO_A_TIMEOVER            1153
#define IDC_RADIO_A_DONTMOVE            1154
#define IDC_RADIO_A_CRASHS              1155
#define IDC_RADIO_E_CRASH               1156
#define IDC_RADIO_E_TIMEOVER            1157
#define IDC_RADIO_E_DONTMOVE            1158
#define IDC_CHECK_S_GUIDED              1159
#define IDC_CHECK_A_EFF                 1160
#define IDC_BUTTON_S_DIRECT             1161
#define IDC_RADIO_TARGET_LINE           1162
#define IDC_BUTTON_CULLMODE             1163
#define IDC_RADIO_TAGERT_CAMERA_MOVE    1163
#define IDC_BUTTON_DIRECT               1164
#define IDC_BUTTON_NORMAL               1165
#define IDC_TAB_TYPE                    1166
#define IDC_BUTTON_GROUND_TEX           1166
#define IDC_BUTTON_SCALE_DISABLE        1167
#define IDC_BUTTON_XYZSCALE_DISABLE     1168
#define IDC_BUTTON_TEXMOVE_DISABLE      1168
#define IDC_BUTTON_HEIGHT_DISABLE       1169
#define IDC_BUTTON_GCOLLISION           1169
#define IDC_BUTTON_SEQUENCE_DISABLE     1170
#define IDC_BUTTON_MOVE_MATRIX          1170
#define IDC_BUTTON_RANGE_HIGH_DISABLE   1170
#define IDC_BUTTON_ROTATE_MATRIX        1171
#define IDC_BUTTON_ROTATE_DISABLE       1171
#define IDC_BUTTON_ROTATE_WORLD         1172
#define IDC_BUTTON_RANGE_DISABLE        1172
#define IDC_BUTTON_THROW                1173
#define IDC_BUTTON_TEXROTATE_DISABLE    1173
#define IDC_BUTTON_DIRECT_DISABLE       1173
#define IDC_BUTTON_FROMTO               1174
#define IDC_BUTTON_GRAVITY_S_DISABLE    1174
#define IDC_BUTTON_TEX_SCALE_DISABLE    1175
#define IDC_BUTTON_GRAVITY_E_DISABLE    1175
#define IDC_RADIO_NEWEFF_FIRST          1176
#define IDC_RADIO_NEWEFF_END            1177
#define IDC_BUTTON_EFFTOTEX_START       1177
#define IDC_RADIO_NEWEFF_END2           1178
#define IDC_RADIO_NEWEFF_END_STOP       1178
#define IDC_RADIO_NUMBER16              1178
#define IDC_BUTTON_EFFTOTEX_END         1178
#define IDC_RADIO_NUMBER32              1179
#define IDC_RADIO_NUMBER64              1180
#define IDC_RADIO_TEXSIZE128            1181
#define IDC_RADIO_TEXSIZE256            1182
#define IDC_BUTTON_RH_APPLY             1182
#define IDC_LIST_CHARANIM               1183
#define IDC_BUTTON_POSRESET             1184
#define IDC_EDIT_EFFECT_NAME            1185
#define IDC_STATIC_MAX                  1186
#define IDC_STATIC_PLAY_NUM             1187
#define IDC_STATIC_POWER                1188
#define IDC_STATIC_MAX2                 1189
#define IDC_STATIC_E                    1206
#define IDC_BUTTON_GETSOUND             1207
#define IDC_BUTTON2                     1209
#define IDC_BUTTON_DEL                  1209
#define IDC_BUTTON_GROUND               1209
#define IDC_BUTTON_GOTOCENTER           1209
#define IDC_BUTTON_AABB_CLEAR           1209
#define IDC_BUTTON5                     1210
#define IDC_EDIT_MAXRANGE               1214
#define IDC_EDIT_LOOPTIME               1215
#define IDC_EDIT_MAXRANGE2              1215
#define IDC_BUTTON_FIND                 1225
#define ID_VIEW_EDITBOX                 1810
#define ID_BUTTON32772                  32772
#define ID_COMBO_MATRIX                 32774
#define ID_VIEW_CHARMOVETOPOINT         32775
#define IDMENU_COPY                     32778
#define IDMENU_PASTE                    32779
#define IDMENU_DELETE                   32780
#define ID_Menu                         32781
#define ID_LOAD_BGTEX                   32784
#define ID_VIEW_BGTEX                   32785
#define ID_32786                        32786
#define ID_MENU_LOG_WINDOW              32787
#define ID_32788                        32788
#define ID_ALL_FILE_LOADING             32789
#define ID_ARCHIVE                      32790
#define ID_ARCHIVE_M                    32791
#define ID_ARCHIVE_MOBILE               32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1189
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
