#pragma once

//#include <algorithm>
//#include <fstream>
//#include <map>
//#include <set>
//#include <string>
//#include <vector>

//#include <boost/any.hpp>
//#include <boost/archive/polymorphic_binary_iarchive.hpp>
//#include <boost/archive/polymorphic_binary_oarchive.hpp>
//#include <boost/archive/polymorphic_text_iarchive.hpp>
//#include <boost/archive/polymorphic_text_oarchive.hpp>
//#include <boost/archive/polymorphic_xml_iarchive.hpp>
//#include <boost/archive/polymorphic_xml_oarchive.hpp>
//#include <boost/bind.hpp>
//#include <boost/foreach.hpp>
//#include <boost/format.hpp>
//#include <boost/filesystem.hpp>
//#include <boost/function.hpp>
//#include <boost/functional/hash.hpp>
//#include <boost/lexical_cast.hpp>
//#include <boost/mem_fn.hpp>
//#include <boost/multi_index_container.hpp>
//#include <boost/noncopyable.hpp>
//#include <boost/ref.hpp>
//#include <boost/scope_exit.hpp>
//#include <boost/scoped_array.hpp>
//#include <boost/scoped_ptr.hpp>
//#include <boost/serialization/serialization.hpp>
//#include <boost/serialization/vector.hpp>
//#include <boost/serialization/version.hpp>
//#include <boost/tr1/memory.hpp>
//#include <boost/static_assert.hpp>
//#include <boost/thread.hpp>
//#include <boost/unordered_map.hpp>
//#include <boost/unordered_set.hpp>
//#include <boost/uuid/uuid.hpp>
//#include <boost/uuid/uuid_generators.hpp>
//#include <boost/variant.hpp>
//#include <boost/weak_ptr.hpp>