#pragma once

#include <map>
#include <vector>
#include <list>
#include <StrSafe.h>
#include "../../SigmaCore/Math/Random.h"

class gltexfile;
class GLogicFile;
class GLogicData;
namespace sc
{
	class SerialFile;
	class BaseStream;
}
namespace RandomOption
{
	enum
	{
		LENGTH_NAME = 64,
	};
	enum LOAD_TYPE
	{
		LOAD_CLIENT,
		LOAD_SERVER,
		LOAD_TOOL,
	};

	enum GENERATE
	{
		GENERATE_DROP,
		GENERATE_REMODEL,
		GENERATE_NSIZE,
	};
	const char cNameGenerate[RandomOption::GENERATE_NSIZE][8] =
	{
		"사냥",
		"개조",
	};
	enum RANDOM_OPTION
	{
		RANDOM_OPTION_NULL = 0,
		RANDOM_OPTION_RATE_DAMAGE = 1, // 공격력(비율);
		RANDOM_OPTION_RATE_DEFENCE = 2,	//	방어력(비율);
		RANDOM_OPTION_RATE_HIT = 3, // 명중(비율);
		RANDOM_OPTION_RATE_AVOID = 4, // 회피(비율);

		RANDOM_OPTION_VALUE_HP = 5, // hp 크기 변화(양);
		RANDOM_OPTION_VALUE_MP = 6, // mp 크기 변화(양);
		RANDOM_OPTION_VALUE_SP = 7, // sp 크기 변화(양);

		RANDOM_OPTION_RATE_RECOVERY_HP = 8, // hp 회복(비율);
		RANDOM_OPTION_RATE_RECOVERY_MP = 9, // mp 회복(비율);
		RANDOM_OPTION_RATE_RECOVERY_SP = 10, // sp 회복(비율);
		RANDOM_OPTION_RATE_RECOVERY_HP_MP_SP = 11, // hp, mp, sp 회복(비율);

		RANDOM_OPTION_GRIND_DAMAGE = 12, // 공격력 연마;
		RANDOM_OPTION_GRIND_DEFENCE = 13, // 방어력 연마;

		RANDOM_OPTION_RATE_RANGE_ATTACK = 14, // 공격 영역(비율);
		RANDOM_OPTION_CONSUME_SP = 15, // sp 소모(양);
		RANDOM_OPTION_VALUE_RESIST = 16, // 저항(양);

		RANDOM_OPTION_RATE_SPEED_MOVE = 17, // 이동 속도(비율);

		RANDOM_OPTION_VALUE_DAMAGE = 18, // 공격력(양);
		RANDOM_OPTION_VALUE_DEFENCE = 19, // 방어력(양);

		RANDOM_OPTION_VALUE_HIT = 20, // 명중율(양);
		RANDOM_OPTION_VALUE_AVOID = 21, // 회피율(양);

		RANDOM_OPTION_VALUE_POW = 22, // 힘(양);
		RANDOM_OPTION_VALUE_STR = 23, // 체력(양);
		RANDOM_OPTION_VALUE_SPI = 24, // 정신(양);
		RANDOM_OPTION_VALUE_DEX = 25,	 // 민첩(양);
		RANDOM_OPTION_VALUE_STA = 26, // 근력(양);

		RANDOM_OPTION_VALUE_MELEE = 27, // 격투치(양);
		RANDOM_OPTION_VALUE_RANGE = 28, // 사격치(양);
		RANDOM_OPTION_VALUE_MAGIC = 29, // 마력치(양);

		RANDOM_OPTION_VALUE_POTION_HP = 30, // 물약에 의한 hp 회복(양);
		RANDOM_OPTION_VALUE_POTION_MP = 31, // 물약에 의한 mp 회복(양);
		RANDOM_OPTION_VALUE_POTION_SP = 32, // 물약에 의한 shp 회복(양);
		RANDOM_OPTION_VALUE_KILL_CP = 33, // 몬스터 킬시 CP 변화(양);

		RANDOM_OPTION_VALUE_SKILL_GRADE_1_DURATIONTIME_ADD  = 34,
		RANDOM_OPTION_VALUE_SKILL_GRADE_2_DURATIONTIME_ADD  = 35,
		RANDOM_OPTION_VALUE_SKILL_GRADE_3_DURATIONTIME_ADD  = 36,
		RANDOM_OPTION_VALUE_SKILL_GRADE_4_DURATIONTIME_ADD  = 37,
		RANDOM_OPTION_VALUE_SKILL_GRADE_5_DURATIONTIME_ADD  = 38,
		RANDOM_OPTION_VALUE_SKILL_GRADE_6_DURATIONTIME_ADD  = 39,
		RANDOM_OPTION_VALUE_SKILL_GRADE_7_DURATIONTIME_ADD  = 40,
		RANDOM_OPTION_VALUE_SKILL_GRADE_8_DURATIONTIME_ADD  = 41,
		RANDOM_OPTION_VALUE_SKILL_GRADE_9_DURATIONTIME_ADD  = 42,
		RANDOM_OPTION_VALUE_SKILL_GRADE_10_DURATIONTIME_ADD = 43,
		RANDOM_OPTION_VALUE_SKILL_GRADE_11_DURATIONTIME_ADD = 44,
		RANDOM_OPTION_VALUE_SKILL_GRADE_12_DURATIONTIME_ADD = 45,
		RANDOM_OPTION_VALUE_SKILL_GRADE_13_DURATIONTIME_ADD = 46,
		RANDOM_OPTION_VALUE_SKILL_GRADE_14_DURATIONTIME_ADD = 47,
		RANDOM_OPTION_VALUE_SKILL_GRADE_15_DURATIONTIME_ADD = 48,
		RANDOM_OPTION_VALUE_SKILL_GRADE_16_DURATIONTIME_ADD = 49,
		RANDOM_OPTION_VALUE_SKILL_GRADE_17_DURATIONTIME_ADD = 50,
		RANDOM_OPTION_VALUE_SKILL_GRADE_18_DURATIONTIME_ADD = 51,
		RANDOM_OPTION_VALUE_SKILL_GRADE_19_DURATIONTIME_ADD = 52,
		RANDOM_OPTION_VALUE_SKILL_GRADE_20_DURATIONTIME_ADD = 53,
		RANDOM_OPTION_VALUE_SKILL_GRADE_21_DURATIONTIME_ADD = 54,
		RANDOM_OPTION_VALUE_SKILL_GRADE_22_DURATIONTIME_ADD = 55,
		RANDOM_OPTION_VALUE_SKILL_GRADE_23_DURATIONTIME_ADD = 56,
		RANDOM_OPTION_VALUE_SKILL_GRADE_24_DURATIONTIME_ADD = 57,
		RANDOM_OPTION_VALUE_SKILL_GRADE_25_DURATIONTIME_ADD = 58,

		RANDOM_OPTION_VALUE_SKILL_GRADE_1_DAMAGE_ADD  = 59,
		RANDOM_OPTION_VALUE_SKILL_GRADE_2_DAMAGE_ADD  = 60,
		RANDOM_OPTION_VALUE_SKILL_GRADE_3_DAMAGE_ADD  = 61,
		RANDOM_OPTION_VALUE_SKILL_GRADE_4_DAMAGE_ADD  = 62,
		RANDOM_OPTION_VALUE_SKILL_GRADE_5_DAMAGE_ADD  = 63,
		RANDOM_OPTION_VALUE_SKILL_GRADE_6_DAMAGE_ADD  = 64,
		RANDOM_OPTION_VALUE_SKILL_GRADE_7_DAMAGE_ADD  = 65,
		RANDOM_OPTION_VALUE_SKILL_GRADE_8_DAMAGE_ADD  = 66,
		RANDOM_OPTION_VALUE_SKILL_GRADE_9_DAMAGE_ADD  = 67,
		RANDOM_OPTION_VALUE_SKILL_GRADE_10_DAMAGE_ADD = 68,
		RANDOM_OPTION_VALUE_SKILL_GRADE_11_DAMAGE_ADD = 69,
		RANDOM_OPTION_VALUE_SKILL_GRADE_12_DAMAGE_ADD = 70,
		RANDOM_OPTION_VALUE_SKILL_GRADE_13_DAMAGE_ADD = 71,
		RANDOM_OPTION_VALUE_SKILL_GRADE_14_DAMAGE_ADD = 72,
		RANDOM_OPTION_VALUE_SKILL_GRADE_15_DAMAGE_ADD = 73,
		RANDOM_OPTION_VALUE_SKILL_GRADE_16_DAMAGE_ADD = 74,
		RANDOM_OPTION_VALUE_SKILL_GRADE_17_DAMAGE_ADD = 75,
		RANDOM_OPTION_VALUE_SKILL_GRADE_18_DAMAGE_ADD = 76,
		RANDOM_OPTION_VALUE_SKILL_GRADE_19_DAMAGE_ADD = 77,
		RANDOM_OPTION_VALUE_SKILL_GRADE_20_DAMAGE_ADD = 78,
		RANDOM_OPTION_VALUE_SKILL_GRADE_21_DAMAGE_ADD = 79,
		RANDOM_OPTION_VALUE_SKILL_GRADE_22_DAMAGE_ADD = 80,
		RANDOM_OPTION_VALUE_SKILL_GRADE_23_DAMAGE_ADD = 81,
		RANDOM_OPTION_VALUE_SKILL_GRADE_24_DAMAGE_ADD = 82,
		RANDOM_OPTION_VALUE_SKILL_GRADE_25_DAMAGE_ADD = 83,

		RANDOM_OPTION_VALUE_SKILL_GRADE_1_SKILLDILAY_DEC  = 84,
		RANDOM_OPTION_VALUE_SKILL_GRADE_2_SKILLDILAY_DEC  = 85,
		RANDOM_OPTION_VALUE_SKILL_GRADE_3_SKILLDILAY_DEC  = 86,
		RANDOM_OPTION_VALUE_SKILL_GRADE_4_SKILLDILAY_DEC  = 87,
		RANDOM_OPTION_VALUE_SKILL_GRADE_5_SKILLDILAY_DEC  = 88,
		RANDOM_OPTION_VALUE_SKILL_GRADE_6_SKILLDILAY_DEC  = 89,
		RANDOM_OPTION_VALUE_SKILL_GRADE_7_SKILLDILAY_DEC  = 90,
		RANDOM_OPTION_VALUE_SKILL_GRADE_8_SKILLDILAY_DEC  = 91,
		RANDOM_OPTION_VALUE_SKILL_GRADE_9_SKILLDILAY_DEC  = 92,
		RANDOM_OPTION_VALUE_SKILL_GRADE_10_SKILLDILAY_DEC = 93,
		RANDOM_OPTION_VALUE_SKILL_GRADE_11_SKILLDILAY_DEC = 94,
		RANDOM_OPTION_VALUE_SKILL_GRADE_12_SKILLDILAY_DEC = 95,
		RANDOM_OPTION_VALUE_SKILL_GRADE_13_SKILLDILAY_DEC = 96,
		RANDOM_OPTION_VALUE_SKILL_GRADE_14_SKILLDILAY_DEC = 97,
		RANDOM_OPTION_VALUE_SKILL_GRADE_15_SKILLDILAY_DEC = 98,
		RANDOM_OPTION_VALUE_SKILL_GRADE_16_SKILLDILAY_DEC = 99,
		RANDOM_OPTION_VALUE_SKILL_GRADE_17_SKILLDILAY_DEC = 100,
		RANDOM_OPTION_VALUE_SKILL_GRADE_18_SKILLDILAY_DEC = 101,
		RANDOM_OPTION_VALUE_SKILL_GRADE_19_SKILLDILAY_DEC = 102,
		RANDOM_OPTION_VALUE_SKILL_GRADE_20_SKILLDILAY_DEC = 103,
		RANDOM_OPTION_VALUE_SKILL_GRADE_21_SKILLDILAY_DEC = 104,
		RANDOM_OPTION_VALUE_SKILL_GRADE_22_SKILLDILAY_DEC = 105,
		RANDOM_OPTION_VALUE_SKILL_GRADE_23_SKILLDILAY_DEC = 106,
		RANDOM_OPTION_VALUE_SKILL_GRADE_24_SKILLDILAY_DEC = 107,
		RANDOM_OPTION_VALUE_SKILL_GRADE_25_SKILLDILAY_DEC = 108,
		RANDOM_OPTION_VALUE_CRITICALDAMAGE_ADD		= 109,
		RANDOM_OPTION_VALUE_CRUSHINGBLOW_ADD		= 110,
		RANDOM_OPTION_VALUE_WEARABLELEVEL_ADD		= 111,
		RANDOM_OPTION_VALUE_LIFE_PER_KILL			= 112,			// 처치시 생명력 회복률;
		RANDOM_OPTION_VALUE_MP_PER_KILL				= 113,				// 처치시 MP 회복률;
		RANDOM_OPTION_VALUE_SP_PER_KILL				= 114,				// 처치시 SP 회복률;
		RANDOM_OPTION_VALUE_HPMPSP_PER_KILL			= 115,			// 처치시 HP+MP+SP 회복률;
		RANDOM_OPTION_VALUE_ALLMPRATIO_TO_ATTACK	= 116,		// 전체 MP 비율만큼 공격력증가;
		RANDOM_OPTION_VALUE_ALLSPRATIO_TO_HP		= 117,			// 전체 SP 비율만큼 체력증가;
		RANDOM_OPTION_VALUE_ALLHITRATIO_TO_MELEE	= 118,			// 전체 명중 비율만큼 격투치 증가;
		RANDOM_OPTION_VALUE_ALLHITRATIO_TO_RANGE	= 119,			// 전체 명중 비율만큼 사격치 증가;
		RANDOM_OPTION_VALUE_ALLHITRATIO_TO_MAGIC	= 120,			// 전체 명중 비율만큼 기력치 증가;
		RANDOM_OPTION_NSIZE = 121,
	};

	const bool bValueInteger[RandomOption::RANDOM_OPTION_NSIZE] =
	{
		true, // RANDOM_OPTION_NULL = 0,
		false, // RANDOM_OPTION_RATE_DAMAGE = 1, // 공격력(비율);
		false, // RANDOM_OPTION_RATE_DEFENCE = 2,	//	방어력(비율);
		false, // RANDOM_OPTION_RATE_HIT = 3, // 명중(비율);
		false, // RANDOM_OPTION_RATE_AVOID = 4, // 회피(비율);
		true, // RANDOM_OPTION_VALUE_HP = 5, // hp 크기 변화(양);
		true, // RANDOM_OPTION_VALUE_MP = 6, // mp 크기 변화(양);
		true, // RANDOM_OPTION_VALUE_SP = 7, // sp 크기 변화(양);
		false, // RANDOM_OPTION_RATE_RECOVERY_HP = 8, // hp 회복(비율);
		false, // RANDOM_OPTION_RATE_RECOVERY_MP = 9, // mp 회복(비율);
		false, // RANDOM_OPTION_RATE_RECOVERY_SP = 10, // sp 회복(비율);
		false, // RANDOM_OPTION_RATE_RECOVERY_HP_MP_SP = 11, // hp, mp, sp 회복(비율);
		true, // RANDOM_OPTION_GRIND_DAMAGE = 12, // 공격력 연마;
		true, // RANDOM_OPTION_GRIND_DEFENCE = 13, // 방어력 연마;
		false, // RANDOM_OPTION_RATE_RANGE_ATTACK = 14, // 공격 영역(비율);
		true, // RANDOM_OPTION_CONSUME_SP = 15, // sp 소모(양);
		true, // RANDOM_OPTION_VALUE_RESIST = 16, // 저항(양);
		false, // RANDOM_OPTION_RATE_SPEED_MOVE = 17, // 이동 속도(비율);
		true, // RANDOM_OPTION_VALUE_DAMAGE = 18, // 공격력(양);
		true, // RANDOM_OPTION_VALUE_DEFENCE = 19, // 방어력(양);
		true, // RANDOM_OPTION_VALUE_HIT = 20, // 명중율(양);
		true, // RANDOM_OPTION_VALUE_AVOID = 21, // 회피율(양);
		true, // RANDOM_OPTION_VALUE_POW = 22, // 힘(양);
		true, // RANDOM_OPTION_VALUE_STR = 23, // 체력(양);
		true, // RANDOM_OPTION_VALUE_SPI = 24, // 정신(양);
		true, // RANDOM_OPTION_VALUE_DEX = 25,	 // 민첩(양);
		true, // RANDOM_OPTION_VALUE_STA = 26, // 근력(양);
		true, // RANDOM_OPTION_MELEE = 27, // 격투치(양);
		true, // RANDOM_OPTION_RANGE = 28, // 사격치(양);
		true, // RANDOM_OPTION_MAGIC = 29, // 마력치(양);
		true, // RANDOM_OPTION_VALUE_POTION_HP = 30, // 물약에 의한 hp 회복(양);
		true, // RANDOM_OPTION_VALUE_POTION_MP = 31, // 물약에 의한 mp 회복(양);
		true, // RANDOM_OPTION_VALUE_POTION_SP = 32, // 물약에 의한 shp 회복(양);
		true, // RANDOM_OPTION_VALUE_KILL_CP = 33, // 몬스터 킬시 CP 변화(양);
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_1_DURATIONTIME_ADD 스킬등급별 지속시간 증가;
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_2_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_3_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_4_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_5_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_6_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_7_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_8_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_9_DURATIONTIME_ADD  
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_10_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_11_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_12_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_13_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_14_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_15_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_16_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_17_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_18_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_19_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_20_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_21_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_22_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_23_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_24_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_25_DURATIONTIME_ADD 
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_1_DAMAGE_ADD  = 59, 스킬 등급별 데미지 증가%;
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_2_DAMAGE_ADD  = 60,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_3_DAMAGE_ADD  = 61,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_4_DAMAGE_ADD  = 62,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_5_DAMAGE_ADD  = 63,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_6_DAMAGE_ADD  = 64,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_7_DAMAGE_ADD  = 65,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_8_DAMAGE_ADD  = 66,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_9_DAMAGE_ADD  = 67,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_10_DAMAGE_ADD = 68,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_11_DAMAGE_ADD = 69,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_12_DAMAGE_ADD = 70,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_13_DAMAGE_ADD = 71,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_14_DAMAGE_ADD = 72,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_15_DAMAGE_ADD = 73,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_16_DAMAGE_ADD = 74,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_17_DAMAGE_ADD = 75,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_18_DAMAGE_ADD = 76,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_19_DAMAGE_ADD = 77,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_20_DAMAGE_ADD = 78,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_21_DAMAGE_ADD = 79,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_22_DAMAGE_ADD = 80,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_23_DAMAGE_ADD = 81,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_24_DAMAGE_ADD = 82,
		false, // RANDOM_OPTION_VALUE_SKILL_GRADE_25_DAMAGE_ADD = 83,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_1_SKILLDILAY_DEC  = 84, 등급별 딜레이 감소;
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_2_SKILLDILAY_DEC  = 85,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_3_SKILLDILAY_DEC  = 86,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_4_SKILLDILAY_DEC  = 87,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_5_SKILLDILAY_DEC  = 88,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_6_SKILLDILAY_DEC  = 89,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_7_SKILLDILAY_DEC  = 90,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_8_SKILLDILAY_DEC  = 91,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_9_SKILLDILAY_DEC  = 92,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_10_SKILLDILAY_DEC = 93,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_11_SKILLDILAY_DEC = 94,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_12_SKILLDILAY_DEC = 95,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_13_SKILLDILAY_DEC = 96,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_14_SKILLDILAY_DEC = 97,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_15_SKILLDILAY_DEC = 98,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_16_SKILLDILAY_DEC = 99,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_17_SKILLDILAY_DEC = 100,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_18_SKILLDILAY_DEC = 101,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_19_SKILLDILAY_DEC = 102,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_20_SKILLDILAY_DEC = 103,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_21_SKILLDILAY_DEC = 104,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_22_SKILLDILAY_DEC = 105,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_23_SKILLDILAY_DEC = 106,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_24_SKILLDILAY_DEC = 107,
		false,// RANDOM_OPTION_VALUE_SKILL_GRADE_25_SKILLDILAY_DEC = 108,
		false,// RANDOM_OPTION_VALUE_CRITICALDAMAGE_ADD = 109, 크리티컬 데미지 증가
		false,// RANDOM_OPTION_VALUE_CRUSHINGBLOW_ADD = 110, 강한타격 데미지 증가율
		true, // RANDOM_OPTION_VALUE_WEARABLELEVEL_DEC = 111, 착용레벨 감소;
		false,// RANDOM_OPTION_VALUE_LIFE_PER_KILL = 112, // 처치시 생명력 회복률;
		false,// RANDOM_OPTION_VALUE_MP_PER_KILL = 112, // 처치시 MP 회복률;
		false,// RANDOM_OPTION_VALUE_SP_PER_KILL = 114, // 처치시 SP 회복률;
		false,// RANDOM_OPTION_VALUE_HPMPSP_PER_KILL = 115, // 처치시 HP+MP+SP 회복률;
		false,// RANDOM_OPTION_VALUE_ALLMPRATIO_TO_ATTACK = 116,		// 전체 MP 비율만큼 공격력증가;
		false,// RANDOM_OPTION_VALUE_ALLSPRATIO_TO_HP = 117,			// 전체 SP 비율만큼 체력증가;
		false,// RANDOM_OPTION_VALUE_ALLHITRATIO_TO_MELEE = 118,			// 전체 명중 비율만큼 격투치 증가;
		false,// RANDOM_OPTION_VALUE_ALLHITRATIO_TO_RANGE = 119,			// 전체 명중 비율만큼 사격치 증가;
		false,// RANDOM_OPTION_VALUE_ALLHITRATIO_TO_MAGIC = 120,			// 전체 명중 비율만큼 기력치 증가;
	};

	const char cNameValue[RandomOption::RANDOM_OPTION_NSIZE][32] =
	{
		"null", // RANDOM_OPTION_NULL = 0,
		"공격(비율)", // RANDOM_OPTION_RATE_DAMAGE = 1, // 공격력(비율);
		"방어(비율)", // RANDOM_OPTION_RATE_DEFENCE = 2,	//	방어력(비율);
		"명중(비율)", // RANDOM_OPTION_RATE_HIT = 3, // 명중(비율);
		"회피(비율)", // RANDOM_OPTION_RATE_AVOID = 4, // 회피(비율);
		"hp 크기(양)", // RANDOM_OPTION_VALUE_HP = 5, // hp 크기 변화(양);
		"mp 크기(양)", // RANDOM_OPTION_VALUE_MP = 6, // mp 크기 변화(양);
		"sp 크기(양)", // RANDOM_OPTION_VALUE_SP = 7, // sp 크기 변화(양);
		"hp 회복(비율)", // RANDOM_OPTION_RATE_RECOVERY_HP = 8, // hp 회복(비율);
		"mp 회복(비율)", // RANDOM_OPTION_RATE_RECOVERY_MP = 9, // mp 회복(비율);
		"sp 회복(비율)", // RANDOM_OPTION_RATE_RECOVERY_SP = 10, // sp 회복(비율);
		"hp/mp/sp 회복(비율)", // RANDOM_OPTION_RATE_RECOVERY_HP_MP_SP = 11, // hp, mp, sp 회복(비율);
		"공격 연마", // RANDOM_OPTION_GRIND_DAMAGE = 12, // 공격력 연마;
		"방어 연마", // RANDOM_OPTION_GRIND_DEFENCE = 13, // 방어력 연마;
		"공격 영역(비율)", // RANDOM_OPTION_RATE_RANGE_ATTACK = 14, // 공격 영역(비율);
		"sp 소모(양)", // RANDOM_OPTION_CONSUME_SP = 15, // sp 소모(양);
		"저항(양)", // RANDOM_OPTION_VALUE_RESIST = 16, // 저항(양);
		"이동 속도(비율)", // RANDOM_OPTION_RATE_SPEED_MOVE = 17, // 이동 속도(비율);
		"공격(양)", // RANDOM_OPTION_VALUE_DAMAGE = 18, // 공격력(양);
		"방어(양)", // RANDOM_OPTION_VALUE_DEFENCE = 19, // 방어력(양);
		"명중(양)", // RANDOM_OPTION_VALUE_HIT = 20, // 명중율(양);
		"회피(양)", // RANDOM_OPTION_VALUE_AVOID = 21, // 회피율(양);
		"힘(양)", // RANDOM_OPTION_VALUE_POW = 22, // 힘(양);
		"체력(양)", // RANDOM_OPTION_VALUE_STR = 23, // 체력(양);
		"정신(양)", // RANDOM_OPTION_VALUE_SPI = 24, // 정신(양);
		"민첩(양)", // RANDOM_OPTION_VALUE_DEX = 25,	 // 민첩(양);
		"근력(양)", // RANDOM_OPTION_VALUE_STA = 26, // 근력(양);
		"격투(양)", // RANDOM_OPTION_MELEE = 27, // 격투치(양);
		"사격(양)", // RANDOM_OPTION_RANGE = 28, // 사격치(양);
		"마력(양)", // RANDOM_OPTION_MAGIC = 29, // 마력치(양);
		"hp회복[물약](양)", // RANDOM_OPTION_VALUE_POTION_HP = 30, // 물약에 의한 hp 회복(양);
		"mp회복[물약](양)", // RANDOM_OPTION_VALUE_POTION_MP = 31, // 물약에 의한 mp 회복(양);
		"sp회복[물약](양)", // RANDOM_OPTION_VALUE_POTION_SP = 32, // 물약에 의한 sp 회복(양);
		"몬스터킬시cp변화(양)", // RANDOM_OPTION_VALUE_KILL_CP = 33, // 몬스터 킬시 CP 변화(양);
		"1등급 스킬 지속시간",
		"2등급 스킬 지속시간",
		"3등급 스킬 지속시간",
		"4등급 스킬 지속시간",
		"5등급 스킬 지속시간",
		"6등급 스킬 지속시간",
		"7등급 스킬 지속시간",
		"8등급 스킬 지속시간",
		"9등급 스킬 지속시간",
		"10등급 스킬 지속시간",
		"11등급 스킬 지속시간",
		"12등급 스킬 지속시간",
		"13등급 스킬 지속시간",
		"14등급 스킬 지속시간",
		"15등급 스킬 지속시간",
		"16등급 스킬 지속시간",
		"17등급 스킬 지속시간",
		"18등급 스킬 지속시간",
		"19등급 스킬 지속시간",
		"20등급 스킬 지속시간",
		"21등급 스킬 지속시간",
		"22등급 스킬 지속시간",
		"23등급 스킬 지속시간",
		"24등급 스킬 지속시간",
		"25등급 스킬 지속시간",
		"1등급 스킬 데미지 증가율",
		"2등급 스킬 데미지 증가율",
		"3등급 스킬 데미지 증가율",
		"4등급 스킬 데미지 증가율",
		"5등급 스킬 데미지 증가율",
		"6등급 스킬 데미지 증가율",
		"7등급 스킬 데미지 증가율",
		"8등급 스킬 데미지 증가율",
		"9등급 스킬 데미지 증가율",
		"10등급 스킬 데미지 증가율",
		"11등급 스킬 데미지 증가율",
		"12등급 스킬 데미지 증가율",
		"13등급 스킬 데미지 증가율",
		"14등급 스킬 데미지 증가율",
		"15등급 스킬 데미지 증가율",
		"16등급 스킬 데미지 증가율",
		"17등급 스킬 데미지 증가율",
		"18등급 스킬 데미지 증가율",
		"19등급 스킬 데미지 증가율",
		"20등급 스킬 데미지 증가율",
		"21등급 스킬 데미지 증가율",
		"22등급 스킬 데미지 증가율",
		"23등급 스킬 데미지 증가율",
		"24등급 스킬 데미지 증가율",
		"25등급 스킬 데미지 증가율",
		"1등급 스킬 딜레이 감소",
		"2등급 스킬 딜레이 감소",
		"3등급 스킬 딜레이 감소",
		"4등급 스킬 딜레이 감소",
		"5등급 스킬 딜레이 감소",
		"6등급 스킬 딜레이 감소",
		"7등급 스킬 딜레이 감소",
		"8등급 스킬 딜레이 감소",
		"9등급 스킬 딜레이 감소",
		"10등급 스킬 딜레이 감소",
		"11등급 스킬 딜레이 감소",
		"12등급 스킬 딜레이 감소",
		"13등급 스킬 딜레이 감소",
		"14등급 스킬 딜레이 감소",
		"15등급 스킬 딜레이 감소",
		"16등급 스킬 딜레이 감소",
		"17등급 스킬 딜레이 감소",
		"18등급 스킬 딜레이 감소",
		"19등급 스킬 딜레이 감소",
		"20등급 스킬 딜레이 감소",
		"21등급 스킬 딜레이 감소",
		"22등급 스킬 딜레이 감소",
		"23등급 스킬 딜레이 감소",
		"24등급 스킬 딜레이 감소",
		"25등급 스킬 딜레이 감소",
		"크리티컬 데미지",
		"강한타격 데미지",
		"아이템 착용레벨 감소",
		"처치시 HP 회복률",
		"처치시 MP 회복률",
		"처치시 SP 회복률",
		"처치시 HP+MP+SP 회복률",
		"전체 MP 비율만큼 공격력증가",
		"전체 SP 비율만큼 체력증가",
		"전체 명중 비율만큼 격투치 증가",
		"전체 명중 비율만큼 사격치 증가",
		"전체 명중 비율만큼 기력치 증가"
	};

	class Information
	{
	public:
		bool bValueInteger;
		float fRateChoose;
		union
		{
			struct 
			{
				int valueIntegerHigh;
				int valueIntegerLow;
			};
			struct
			{
				float valueFloatHigh;
				float valueFloatLow;
			};
		};
	public:
		Information():valueIntegerHigh(0), valueIntegerLow(0)
		{
		}
	};

	class ValueTemporary
	{
	public:
		ValueTemporary(void)
			: valueIntegerHighCompare(-2100000000)
			, valueIntegerLowCompare(2100000000)
			, valueFloatHighCompare(-210000000.0f)
			, valueFloatLowCompare(210000000.0f)
		{
		}
		int valueIntegerHighCompare;
		int valueIntegerLowCompare;
		float valueFloatHighCompare;
		float valueFloatLowCompare;
	};
}


