#ifndef _POST_CLIENT_DEFINE_H_
#define _POST_CLIENT_DEFINE_H_

#pragma once

namespace GLPostClientDefine
{
	enum EMRECEIVEITEMBOXTYPE
	{
		EMRECEIVEITEMBOXTYPE_DEFAULT	= 0,
		EMRECEIVEITEMBOXTYPE_EMPTY		= 1,
		EMRECEIVEITEMBOXTYPE_SELECTED	= 2,
		EMRECEIVEITEMBOXTYPE_NEW		= 3,
	};

	enum
	{
		BOX_DEFAULT  = 0,
		BOX_EMPTY	 = 1,

		BOX_MAX		 = 2,
	};

	enum
	{
		BOXLINE_SELECTED  = 0,
		BOXLINE_NEW		  = 1,

		BOXLINE_MAX		  = 2,
	};

	enum
	{
		EMRECEIVEITEMTYPE_DEFAULT	= 0,
		EMRECEIVEITEMTYPE_RETURN	= 1,
		EMRECEIVEITEMTYPE_BILLING	= 2,
		EMRECEIVEITEMTYPE_MONEY		= 3,
	};
}

#endif
