//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MobNpcEdit.rc
//
#define IDR_MANIFEST                    1
#define IDD_MOBNPCEDIT_DIALOG           9
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_PROPSHT_CAPTION             102
#define IDD_CROWTREE_DIALOG             104
#define IDD_CROWDATA_DIALOG             105
#define IDR_MAINFRAME                   128
#define IDD_CROWATTACK_DIALOG           129
#define ID_MENUITEM_COPY                129
#define IDR_MENU_MAINFRAME              130
#define ID_MENUITEM_PASTE_NEW           130
#define ID_MENUITEM_NEW                 131
#define ID_MENUITEM_PASTE_VALUE         131
#define ID_MENUITEM_LOAD                132
#define ID_Menu                         132
#define ID_MENUITEM_SAVE                133
#define IDD_DIALOG_LOG                  133
#define ID_MENUITEM_EXIT                134
#define IDR_MENU_CROW_POPUP             137
#define ID_MENUITEM_CROWDATAMODIFY      139
#define IDD_MOBNPCEDIT_DIALOG1          139
#define IDR_MENU_MAINFRAME1             139
#define IDD_CROWATTACKTREE_DIALOG       140
#define ID_MENUITEM_CROWATTACKMODIFY    141
#define ID_MENUITEM_ADD                 143
#define ID_MENUITEM_DEL                 144
#define IDR_TOOLBAR1                    145
#define IDD_LIST_DIALOG                 150
#define IDC_STATIC_NAME                 1000
#define IDC_STATIC_CONTROL              1001
#define IDC_STATIC_TRIBE                1001
#define IDC_TREE_ITEM                   1002
#define IDC_STATIC_CROW                 1002
#define IDC_STATIC_LEVEL                1003
#define IDC_STATIC_MONEY                1004
#define IDC_STATIC_CROW3                1004
#define IDC_STATIC_GENTIME              1004
#define IDC_EDIT_MID                    1005
#define IDC_STATIC_MOVETYPE             1006
#define IDC_STATIC_CROW2                1007
#define IDC_STATIC_EXPERIENCE           1008
#define IDC_STATIC_MAINTYPE             1008
#define IDC_STATIC_HP_UP_ACT            1008
#define IDC_STATIC_LINK_MID             1008
#define IDC_STATIC_HP                   1009
#define IDC_STATIC_MP                   1010
#define IDC_STATIC_VIEWRANGE            1011
#define IDC_STATIC_SUBTYPE              1011
#define IDC_STATIC_MP2                  1012
#define IDC_EDIT_SID                    1013
#define IDC_STATIC_ATTACKPROP           1014
#define IDC_STATIC_HP_DN_ACT            1014
#define IDC_STATIC_CROW4                1015
#define IDC_STATIC_HP_DN_ACT2           1015
#define IDC_STATIC_LINK_SID             1015
#define IDC_EDIT_NAME                   1016
#define IDC_EDIT_DAMAGE                 1017
#define IDC_EDIT_DAMAGE_MIN             1017
#define IDC_STATIC_LINK_MID2            1017
#define IDC_STATIC_AVOIDRATE            1018
#define IDC_EDIT_DAMAGE2                1018
#define IDC_EDIT_DAMAGE_MAX             1018
#define IDC_STATIC_AVOIDRATE2           1019
#define IDC_EDIT_LEVEL                  1020
#define IDC_STATIC_DEFENSE              1021
#define IDC_STATIC_WALKVELO             1022
#define IDC_EDIT_MONEY                  1023
#define IDC_STATIC_WALKVELO4            1023
#define IDC_EDIT_EXPERIENCE             1024
#define IDC_STATIC_WALKVELO2            1024
#define IDC_STATIC_RANGE                1025
#define IDC_STATIC_DEFENSE2             1025
#define IDC_EDIT_HP                     1026
#define IDC_EDIT_MP                     1027
#define IDC_STATIC_SPHERE               1028
#define IDC_EDIT_SP                     1028
#define IDC_STATIC_ATTACKTYPE           1029
#define IDC_EDIT_GATHER_TIME_HIGH       1029
#define IDC_STATIC_SPECIALDAMAGETYPE    1030
#define IDC_STATIC_DEFENSE4             1030
#define IDC_STATIC_SPECIALDAMAGEVALUE   1031
#define IDC_STATIC_DEFENSE5             1031
#define IDC_STATIC_DELAY                1032
#define IDC_EDIT_GENTIME                1032
#define IDC_STATIC_GUID                 1033
#define IDC_COMBO_ATTACKTYPE            1033
#define IDC_EDIT_VIEWRANGE              1034
#define IDC_STATIC_DAMAGE               1034
#define IDC_EDIT_ATTACKPROP             1035
#define IDC_COMBO_SPECIALDAMAGETYPE     1035
#define IDC_COMBO_ELEMENT               1035
#define IDC_STATIC_WALKVELO5            1035
#define IDC_EDIT_AVOIDRATE              1036
#define IDC_EDIT_RANGE                  1036
#define IDC_EDIT_DEFENSE                1037
#define IDC_STATIC_ANIBEGINKEY          1037
#define IDC_EDIT_WALKVELO               1038
#define IDC_EDIT_SPHERE                 1038
#define IDC_STATIC_RUNVELO              1039
#define IDC_EDIT_SPECIALDAMAGEVALUE     1039
#define IDC_EDIT_DRIFF_HEIGHT           1039
#define IDC_COMBO_MAXATTACK             1040
#define IDC_EDIT_HITRATE                1040
#define IDC_COMBO_TRIBE                 1041
#define IDC_EDIT_DELAY                  1041
#define IDC_STATIC_HP_DN_ACT3           1041
#define IDC_STATIC_LINK_MID3            1041
#define IDC_COMBO_CROW                  1042
#define IDC_EDIT_ANIBEGINKEY            1042
#define IDC_STATIC_WALKVELO7            1042
#define IDC_COMBO_MOVETYPE              1043
#define IDC_STATIC_ANIENDKEY            1043
#define IDC_COMBO_ATTACKTYPE2           1043
#define IDC_COMBO_ANI_ATTACKTYPE        1043
#define IDC_EDIT_ANIENDKEY              1044
#define IDC_COMBO_BRIGHT                1044
#define IDC_STATIC_WALKVELO8            1044
#define IDC_STATIC_ANIATTACKKEYNUM      1045
#define IDC_EDIT_BODY_RAD               1045
#define IDC_COMBO_ATTACK_RANGE_TYPE     1045
#define IDC_EDIT_ANIATTACKKEYNUM        1046
#define IDC_EDIT_HP_INC                 1046
#define IDC_STATIC_ATTACKTYPE2          1046
#define IDC_LIST_ANIATTACKKEYS          1047
#define IDC_EDIT_MP_INC                 1047
#define IDC_EDIT_RUNVELO                1048
#define IDC_COMBO_MAINTYPE              1048
#define IDC_STATIC_ANIATTACKKEYS        1049
#define IDC_EDIT_SP_INC                 1049
#define IDC_BUTTON_ATTACK_KEY_DEL       1050
#define IDC_EDIT_GEN_MONEY              1050
#define IDC_COMBO_IMPACT_TAR            1050
#define IDC_COMBO_SUBTYPE               1051
#define IDC_EDIT_GEN_ITEM_MID           1051
#define IDC_EDIT1                       1052
#define IDC_EDIT_ATTACKKEY              1052
#define IDC_STATIC_SPECIALDAMAGETYPE2   1052
#define IDC_EDIT_GEN_ITEM_SID           1052
#define IDC_EDIT_SKILL_MID              1052
#define IDC_BUTTON_SKINFILE             1053
#define IDC_BUTTON_ATTACK_KEY_ADD       1053
#define IDC_BUTTON_TARGETEFFECT         1053
#define IDC_BTN_CSV_LOAD                1053
#define IDC_EDIT_SKINFILE               1054
#define IDC_BUTTON1                     1054
#define IDC_BUTTON_TALKFILE             1055
#define IDC_EDIT_TARGETEFFECT           1055
#define IDC_EDIT_TALKFILE               1056
#define IDC_EDIT_ANI_UNITKEY            1056
#define IDC_BUTTON_UPDATE_SYNC          1057
#define IDC_BUTTON_SKINFILE2            1057
#define IDC_EDIT_ACTION_DN_RATE         1057
#define IDC_LIST_CONNETS                1058
#define IDC_EDIT_GEN_MONEY_RATE         1058
#define IDC_COMBO_IMPACT_REALM          1058
#define IDC_EDIT_SKILL_SID              1058
#define IDC_STATIC_SPECIALDAMAGETYPE3   1059
#define IDC_CHECK_IS_RUN                1059
#define IDC_BUTTON_SKILL                1059
#define IDC_CHECK_IS_USE                1060
#define IDC_EDIT_GEN_ITEM_RATE          1060
#define IDC_COMBO_IMPACT_SIDE           1061
#define IDC_BUTTON_SALEFILE             1061
#define IDC_BUTTON_SALEFILE01           1061
#define IDC_EDIT_MAXATTACK              1061
#define IDC_STATIC_SPECIALDAMAGETYPE4   1062
#define IDC_EDIT_SALEFILE               1062
#define IDC_EDIT_SALEFILE01             1062
#define IDC_BUTTON_MAXATTACK_LEFT       1062
#define IDC_STATIC_DELAY2               1063
#define IDC_CHECK_ITEM_TRADE            1063
#define IDC_COMBO_CROW2                 1063
#define IDC_BUTTON_MAXATTACK_RIGHT      1063
#define IDC_EDIT_MOB_LINK_MID           1063
#define IDC_EDIT_DEC_MP                 1064
#define IDC_BUTTON_BLOW_EFFECT          1064
#define IDC_EDIT_BLOW                   1064
#define IDC_STATIC_DELAY3               1065
#define IDC_BUTTON_FALLING_EFFECT       1065
#define IDC_EDIT_DEC_SP                 1066
#define IDC_EDIT_BLOW_EFFECT            1066
#define IDC_COMBO_BLOW                  1067
#define IDC_EDIT_FALLING_EFFECT         1067
#define IDC_BUTTON_BLOW                 1067
#define IDC_STATIC_SPECIALDAMAGETYPE5   1068
#define IDC_CHECK_NO_FALL_AFTER         1068
#define IDC_STATIC_DELAY4               1069
#define IDC_BUTTON_SALEFILE2            1069
#define IDC_BUTTON_ITEMGENFILE          1069
#define IDC_BUTTON_OK                   1070
#define IDC_BUTTON_CANCEL               1071
#define IDC_BUTTON_NEXT                 1072
#define IDC_BUTTON_PREV                 1073
#define IDC_EDIT_BLOW_RATE              1074
#define IDC_EDIT_ITEMGENFILE            1074
#define IDC_STATIC_DELAY5               1075
#define IDC_CHECK1                      1075
#define IDC_CHECK_STORAGE               1075
#define IDC_CHECK_KNOCK                 1075
#define IDC_EDIT_LIFE                   1076
#define IDC_CHECK_TARSHORT              1076
#define IDC_STATIC_DELAY6               1077
#define IDC_COMBO_HP_UP_ACT             1077
#define IDC_EDIT_MOB_LINK_SID           1077
#define IDC_EDIT_BLOW_VALUE             1078
#define IDC_COMBO_HP_DN_ACT             1078
#define IDC_EDIT_GATHER_RATE            1078
#define IDC_ADDON                       1079
#define IDC_BUTTON_BIRTH_EFFECT         1079
#define IDC_STATIC_SPECIALDAMAGETYPE6   1080
#define IDC_EDIT_BIRTH_EFFECT           1080
#define IDC_STATIC_DELAY7               1081
#define IDC_BUTTON_SALEFILE02           1081
#define IDC_STATIC_RESIST               1082
#define IDC_EDIT_ADDON_VALUE            1082
#define IDC_STATIC_FIRE                 1083
#define IDC_BUTTON_SELFBODYEFFECT       1083
#define IDC_STATIC_ICE                  1084
#define IDC_BUTTON_TARGETBODYEFFECT     1084
#define IDC_STATIC_ELECTRIC             1085
#define IDC_EDIT_SELFBODYEFFECT         1085
#define IDC_STATIC_POISON               1086
#define IDC_EDIT_TARGETBODYEFFECT       1086
#define IDC_EDIT_FIRE                   1087
#define IDC_EDIT_ICE                    1088
#define IDC_EDIT_ELECTRIC               1089
#define IDC_EDIT_POISON                 1090
#define IDC_STATIC_DIVINE               1091
#define IDC_EDIT_SALEFILE02             1091
#define IDC_EDIT_DIVINE                 1092
#define IDC_BUTTON_SALEFILE03           1092
#define IDC_EDIT_SALEFILE3              1093
#define IDC_EDIT_SALEFILE03             1093
#define IDC_STATIC_SPIRIT               1094
#define IDC_EDIT_POISON2                1095
#define IDC_EDIT_SPIRIT                 1095
#define IDC_CHECK_INVISIBLE             1096
#define IDC_CHECK_RECVISIBLE            1097
#define IDC_CHECK_POSHOLD               1098
#define IDC_CHECK_DIRHOLD               1099
#define IDC_CHECK_BARRIER               1100
#define IDC_EDIT_BONUSEXP               1101
#define IDC_CHECK_BOSS                  1102
#define IDC_STATIC_RESIST4              1103
#define IDC_BUTTON_ITEMGENFILE2         1103
#define IDC_EDIT_ITEMGENFILE2           1104
#define IDC_EDIT_QITEMGENFILE           1104
#define IDC_EDIT_VIEWRANGE2             1104
#define IDC_EDIT_SCALE                  1104
#define IDC_CHECK_TARSHORT2             1105
#define IDC_CHECK_CD                    1105
#define IDC_STATIC_ICE2                 1106
#define IDC_EDIT_CROWNAME               1106
#define IDC_EDIT_BLOW_LIFE              1107
#define IDC_BUTTON2                     1107
#define IDC_BUTTON_STRTBL_SYNC          1107
#define IDC_CHECK_IGNORE_SHOCK          1107
#define IDC_STATIC_ICE3                 1108
#define IDC_BUTTON_RELOAD_STRTBL        1108
#define IDC_CHECK_DIRHOLD2              1108
#define IDC_CHECK_AUTODROPOUT           1108
#define IDC_EDIT_BLOW_VALUE1            1109
#define IDC_BTN_CSV_SAVE                1109
#define IDC_BUTTON_PREV2                1109
#define IDC_OVERLAP_CHECK               1109
#define IDC_STATIC_ICE4                 1110
#define IDC_STATIC_BLOWVAR1             1110
#define IDC_BUTTON3                     1110
#define IDC_STATIC_RESIST2              1110
#define IDC_STATIC_ICE5                 1111
#define IDC_STATIC_BLOWVAR2             1111
#define IDC_STATIC_PET_TYPE             1111
#define IDC_EDIT_BLOW_VALUE2            1112
#define IDC_STATIC_RESIST3              1112
#define IDC_EDIT_AUTODROPOUT            1113
#define IDC_EDIT_TRIBE                  1114
#define IDC_BUTTON_TRIBE                1115
#define IDC_EDIT_CROW                   1116
#define IDC_BUTTON_CROW                 1117
#define IDC_EDIT_BRIGHT                 1118
#define IDC_COMBO_BRIGHT2               1119
#define IDC_BUTTON_BRIGHT               1119
#define IDC_EDIT_PET_TYPE               1120
#define IDC_BUTTON_PET_TYPE             1121
#define IDC_EDIT_MOB_LINK_SCALE         1122
#define IDC_EDIT_MOB_LINK_MID2          1122
#define IDC_EDIT_MOB_LINK_DELAY         1123
#define IDC_EDIT_MOB_LINK_SID2          1123
#define IDC_EDIT_HP_DN_ACT              1124
#define IDC_EDIT_GATHER_TIME_LOW2       1125
#define IDC_EDIT_HP_DN_ATK_SET          1125
#define IDC_CHECK_MOB_LINK              1126
#define IDC_STATIC_RESIST5              1127
#define IDC_STATIC_ANIBEGINKEY2         1128
#define IDC_LIST_                       1128
#define IDC_LIST_HP                     1128
#define IDC_EDIT_MOB_LINK_SCALE2        1129
#define IDC_LIST_CROW_ATTACK            1129
#define IDC_STATIC_SUMMON_TYPE          1129
#define IDC_STATIC_WALKVELO6            1130
#define IDC_EDIT_GATHER_ANIM            1131
#define IDC_BUTTON_CROW_ATTACK_ADD      1131
#define IDC_EDIT_MOB_LINK_DELAY2        1132
#define IDC_EDIT_BONUSCP                1132
#define IDC_BUTTON_IMPACT_ADDON_DEL     1132
#define IDC_BUTTON_CROW_ATTACK_DEL      1132
#define IDC_STATIC_WALKVELO3            1133
#define IDC_NONDAMAGED_CHECK            1134
#define IDC_EDIT_SUMMON_TYPE            1135
#define IDC_EDIT_GATHER_TIME_LOW        1136
#define IDC_BUTTON_SUMMON_TYPE          1137
#define IDC_STATIC_SUMMON_TYPE2         1138
#define IDC_STATIC_NPC_TYPE             1138
#define IDC_EDIT_NPC_TYPE               1139
#define IDC_BUTTON_HP_DN_ACT            1140
#define IDC_BUTTON_HP_DN_ATK_SET        1141
#define IDC_BUTTON_HP_LIST_ADD          1142
#define IDC_BUTTON_HP_LIST_DEL          1143
#define IDC_CHECK_NOPENALTY             1144
#define IDC_CHECK_NOPENALTY_NORMAL      1145
#define IDC_CHECK_NOPENALTY_DEBUFF      1146
#define IDC_CHECK_NOPENALTY_LIMIT       1147
#define IDC_CHECK_NOPENALTY_STATE       1148
#define IDC_BUTTON_NPC_TYPE             1149
#define IDC_EDIT_SPECIALITEMGENFILE     1150
#define IDC_HIDENAMING_CHECK            1151
#define IDC_NONTARGETING_CHECK          1152
#define IDC_CHECK_INTERACTION_RANGE     1153
#define IDC_HIDE_TOOLTIP_CHECK          1154
#define IDC_EDIT2                       1155
#define IDC_EDIT_RESISTANCE_PROBABILITY 1156
#define IDC_STATIC_RESISTANCE_PROBABILITY 1157
#define IDC_EDIT_INTERACTION_RANGE      1158
#define IDC_EDIT_RESISTANCE_PROBABILITY2 1158
#define IDC_CHECK_RANDOMRERGEN          1159
#define IDC_CHECK_RANDOMREGEN           1160
#define IDC_CROWATTACK_TREE             1161
#define IDC_EDIT_BARRIER_RADIUS         1162
#define IDC_EDIT_BARRIER_WIDTH          1163
#define IDC_BTN_EXCEL_STRTBL_EXPORT     1164
#define IDC_BTN_EXCEL_STRTBL_IMPORT     1165
#define IDC_BUTTON_XMLCONVERT           1166
#define IDC_SELECT_LIST                 1197
#define IDC_EDIT_SKILL_SID2             2032
#define IDC_COMBO_PET_TYPE              2033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
