//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SkillEdit.rc
//
#define IDR_MANIFEST                    1
#define IDD_SKILLEDIT_DIALOG            9
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_PROPSHT_CAPTION             102
#define IDD_SKILLTREE_DIALOG            104
#define IDD_SKILLDATA_DIALOG            105
#define IDR_MAINFRAME                   128
#define ID_MENUITEM_COPY                129
#define IDD_SKILL_LEVEL_DATA_DIALOG     129
#define IDR_MENU_MAINFRAME              130
#define ID_MENUITEM_PASTE_NEW           130
#define ID_MENUITEM_NEW                 131
#define ID_MENUITEM_PASTE_VALUE         131
#define IDD_DIALOG_TRANSFORM            131
#define ID_MENUITEM_LOAD                132
#define ID_Menu                         132
#define ID_MENUITEM_SAVE                133
#define IDD_DIALOG_LOG                  133
#define IDD_DIALOG_LOG1                 133
#define ID_MENUITEM_EXIT                134
#define IDD_SKILL_LEVEL_DATA_DIALOG2    136
#define IDR_MENU_SKILL_POPUP            137
#define ID_MENUITEM_SKILL_MODIFY        139
#define IDD_SKILLTREE_DIALOG1           139
#define IDR_MENU_SKILL_POPUP1           139
#define IDD_DIALOG_SKILLVIEW            140
#define ID_MENUITEM_SKILL_LEVEL_DATA_MODIFY 141
#define ID_MENUITEM_ADD                 143
#define ID_MENUITEM_DEL                 144
#define IDR_TOOLBAR1                    145
#define IDD_DIALOG_EXCEL_EXPORT         145
#define IDD_LIST_DIALOG                 150
#define IDD_DIALOG_RECALL               151
#define IDC_STATIC_NAME                 1000
#define IDC_STATIC_CONTROL              1001
#define IDC_STATIC_REQUIRELEVEL         1001
#define IDC_TREE_ITEM                   1002
#define IDC_STATIC_CROW                 1002
#define IDC_STATIC_TARGETRANGE          1003
#define IDC_STATIC_ICON                 1004
#define IDC_EDIT_MID                    1005
#define IDC_STATIC_REQUIREEXP           1005
#define IDC_STATIC_DAMAGETYPE           1006
#define IDC_STATIC_REQUIREEXP2          1006
#define IDC_STATIC_TYPE                 1007
#define IDC_STATIC_AGE                  1007
#define IDC_STATIC_DAMAGETYPE2          1007
#define IDC_STATIC_MAINTYPE             1008
#define IDC_STATIC_RESIST               1008
#define IDC_STATIC_ICONINDEX            1009
#define IDC_STATIC_SPEC_VAR2            1009
#define IDC_STATIC_ANIMINFO             1009
#define IDC_STATIC_ICONPICTURE          1010
#define IDC_COMBO_EFF_ELMT              1010
#define IDC_STATIC_LEVEL                1010
#define IDC_STATIC_SPEC_VAR3            1010
#define IDC_STATIC_SPLIT                1010
#define IDC_STATIC_SUBTYPE              1011
#define IDC_STATIC_SPEC_VAR4            1011
#define IDC_STATIC_TARGET               1012
#define IDC_STATIC_DAMAGETYPE3          1012
#define IDC_STATIC_SKILL_MID            1012
#define IDC_EDIT_SID                    1013
#define IDC_STATIC_SKILL_SID            1013
#define IDC_STATIC_ATTACKRIGHT          1014
#define IDC_STATIC_ATTACKLEFT           1015
#define IDC_CHECK_CHK4                  1015
#define IDC_EDIT_NAME                   1016
#define IDC_EDIT_AGE                    1017
#define IDC_CHECK_PALSY                 1017
#define IDC_CHECK_SWOON                 1018
#define IDC_CHECK_CHK1                  1018
#define IDC_CHECK_PETRIFY               1019
#define IDC_CHECK_CHK2                  1019
#define IDC_EDIT_TARGETRANGE            1020
#define IDC_CHECK_CHK3                  1020
#define IDC_EDIT_GRADE                  1021
#define IDC_CHECK_CA_DAMAGE             1021
#define IDC_EDIT_REQ_SKILL_MID          1022
#define IDC_CHECK_CA_DAMAGE2            1022
#define IDC_CHECK_CA_ALL                1022
#define IDC_STATIC_DAMAGETYPE4          1023
#define IDC_CHECK_TARGET                1023
#define IDC_EDIT_REQ_SKILL_SID          1024
#define IDC_CHECK_BUF_DEL               1024
#define IDC_STATIC_DAMAGETYPE5          1025
#define IDC_EDIT_COMMENT                1026
#define IDC_EDIT_ICON_MID               1027
#define IDC_EDIT_POWER                  1028
#define IDC_STATIC_DECMANA              1028
#define IDC_EDIT_ICON_SID               1028
#define IDC_EDIT_STRENGTH               1029
#define IDC_STATIC_DELAYTIME            1029
#define IDC_STATIC_DAMAGETYPE6          1029
#define IDC_EDIT_SPIRIT                 1030
#define IDC_STATIC_APPLYRANGE           1030
#define IDC_CHECK_FROZEN                1030
#define IDC_EDIT_DEXTERITY              1031
#define IDC_STATIC_VARIATION1           1031
#define IDC_CHECK_DERANGE               1031
#define IDC_EDIT_INTELLIGENT            1032
#define IDC_STATIC_VARIATION2           1032
#define IDC_STATIC_DECMANA2             1032
#define IDC_CHECK_POISON                1032
#define IDC_STATIC_GUID                 1033
#define IDC_EDIT_REQ_POW                1033
#define IDC_EDIT_REQ_STR                1034
#define IDC_CHECK_CURSE                 1034
#define IDC_EDIT_REQ_SPI                1035
#define IDC_EDIT1                       1035
#define IDC_EDIT_DAMAGEDELAY            1035
#define IDC_EDIT_M_PART1                1035
#define IDC_EDIT_RECALLDELAY            1035
#define IDC_EDIT_MAIN_SCOPE             1035
#define IDC_ICON_PASER                  1035
#define IDC_EDIT_REQUIREEXP             1036
#define IDC_EDIT_REQ_EXP                1036
#define IDC_CHECK_BURN                  1036
#define IDC_EDIT_M_PART2                1036
#define IDC_EDIT_ACTIVITYTIME           1036
#define IDC_EDIT_MAIN_EFFECT            1036
#define IDC_EDIT_REQ_DEX                1037
#define IDC_CHECK_TARGETEFFECT_ONE      1037
#define IDC_EDIT_M_PART3                1037
#define IDC_EDIT_CREATUREMID            1037
#define IDC_EDIT_MAIN_CONDITION         1037
#define IDC_EDIT_DECMANA                1038
#define IDC_EDIT_DEC_MP                 1038
#define IDC_STATIC_DAMAGETYPE7          1038
#define IDC_EDIT_M_PART4                1038
#define IDC_EDIT_CREATURESID            1038
#define IDC_EDIT_MULTI_SCOPE            1038
#define IDC_STATIC_COMMENT              1039
#define IDC_EDIT_VARIATION1             1039
#define IDC_EDIT_VARIATION              1039
#define IDC_EDIT_M_PART5                1039
#define IDC_EDIT_MAXCREATURE            1039
#define IDC_EDIT_MULTI_EFFECT           1039
#define IDC_EDIT_REQUIRELEVEL           1040
#define IDC_COMBO_MAXSKILL_LEVEL_DATA   1040
#define IDC_EDIT_GRADE2                 1040
#define IDC_EDIT_MAXLEVEL               1040
#define IDC_EDIT_M_PART6                1040
#define IDC_EDIT_USESKILLLEVEL          1040
#define IDC_STATIC_DELAYTIME2           1040
#define IDC_EDIT_MULTI_CONDITION        1040
#define IDC_STATIC_COUNTATTACK          1040
#define IDC_COMBO_TYPE                  1041
#define IDC_EDIT_DELAYTIME              1041
#define IDC_EDIT_NAME2                  1041
#define IDC_EDIT_M_PART7                1041
#define IDC_STATIC_DAMAGETYPE8          1041
#define IDC_EDIT_AITYPE                 1041
#define IDC_COMBO_TARGET                1042
#define IDC_EDIT_VARIATION2             1042
#define IDC_COMBO_SKILL_TYPE            1042
#define IDC_EDIT_DEC_SP                 1042
#define IDC_EDIT_M_PART8                1042
#define IDC_EDIT_MULTITARGETSKILL_MID   1042
#define IDC_COMBO_DAMAGETYPE            1043
#define IDC_EDIT_APPLYRANGE             1043
#define IDC_COMBO_ELEMENT               1043
#define IDC_EDIT_W_PART1                1043
#define IDC_EDIT_MULTITARGETSKILL_SID   1043
#define IDC_STATIC_POWER                1044
#define IDC_COMBO_BLOW_TYPE             1044
#define IDC_EDIT_REQ_INT                1044
#define IDC_EDIT_W_PART2                1044
#define IDC_STATIC_ATTACKGLOVE          1044
#define IDC_EDIT_DISGUISESKILL_MID      1044
#define IDC_STATIC_STRENGTH             1045
#define IDC_STATIC_POWER2               1045
#define IDC_COMBO_IMPACT_ADDON          1045
#define IDC_EDIT_W_PART3                1045
#define IDC_EDIT_HIDDENWEAPON_MID       1045
#define IDC_STATIC_SPIRIT               1046
#define IDC_STATIC_STRENGTH2            1046
#define IDC_COMBO_SPEC_TYPE             1046
#define IDC_EDIT_W_PART4                1046
#define IDC_EDIT_REQ_SKILL_SID2         1046
#define IDC_EDIT_HIDDENWEAPON_SID       1046
#define IDC_STATIC_DEXTERITY            1047
#define IDC_STATIC_SPIRIT2              1047
#define IDC_EDIT_SKILLDESC              1047
#define IDC_EDIT_W_PART5                1047
#define IDC_COMBO_MAINTYPE              1048
#define IDC_STATIC_DEXTERITY2           1048
#define IDC_EDIT_W_PART6                1048
#define IDC_EDIT_DISGUISESKILL_SID      1048
#define IDC_STATIC_INTELLIGENT          1049
#define IDC_COMBO_SELFZONE_EFF01        1049
#define IDC_EDIT_W_PART7                1049
#define IDC_COMBO_ICONINDEX             1050
#define IDC_EDIT_REQ_LEVEL              1050
#define IDC_COMBO_SELFZONE_EFF02        1050
#define IDC_EDIT_W_PART8                1050
#define IDC_COMBO_SUBTYPE               1051
#define IDC_EDIT_INTELLIGENT3           1051
#define IDC_EDIT_REQ_STA                1051
#define IDC_COMBO_SELFZONE_EFF03        1051
#define IDC_COMBO_ATTACKLEFT            1052
#define IDC_STATIC_INTELLIGENT2         1052
#define IDC_BUTTON_TARGETEFFECT         1053
#define IDC_EDIT_BLOW_RATE              1053
#define IDC_EDIT_TARGETEFFECT           1054
#define IDC_STATIC_DECMANA3             1054
#define IDC_BUTTON_ICONFILE             1055
#define IDC_STATIC_VARIATION3           1055
#define IDC_BUTTON_TARGETEFFECT2        1055
#define IDC_STATIC_BLOWVAR1             1055
#define IDC_EDIT_ICONFILE               1056
#define IDC_EDIT_BLOW_VALUE             1056
#define IDC_EDIT_BLOW_VALUE1            1056
#define IDC_BUTTON_SELFBODYEFFECT       1057
#define IDC_EDIT_REQ_SKILL_LEVEL        1057
#define IDC_BUTTON_UPDATE_SYNC          1057
#define IDC_BUTTON_TARGETBODYEFFECT     1058
#define IDC_STATIC_VARIATION4           1058
#define IDC_LIST_CONNETS                1058
#define IDC_STATIC_REQ_MONEY            1058
#define IDC_EDIT_SELFBODYEFFECT         1059
#define IDC_EDIT_IMPACT_VAR             1059
#define IDC_EDIT_TARGETBODYEFFECT       1060
#define IDC_STATIC_APPLYRANGE2          1060
#define IDC_COMBO_DAMAGETYPE2           1061
#define IDC_COMBO_ATTACKRIGHT           1061
#define IDC_EDIT_APPLYNUM               1061
#define IDC_COMBO_IMPACT_TAR            1062
#define IDC_STATIC_APPLYRANGE3          1062
#define IDC_STATIC_SPECIALDAMAGETYPE2   1063
#define IDC_EDIT_APPLYANGLE             1063
#define IDC_COMBO_IMPACT_REALM          1064
#define IDC_STATIC_APPLYRANGE4          1064
#define IDC_STATIC_SPECIALDAMAGETYPE3   1065
#define IDC_EDIT_PIERCENUM              1065
#define IDC_COMBO_IMPACT_SIDE           1066
#define IDC_EDIT_DEC_HP                 1066
#define IDC_STATIC_SPECIALDAMAGETYPE4   1067
#define IDC_STATIC_DECMANA4             1067
#define IDC_COMBO_ROLE                  1068
#define IDC_EDIT_DEC_ARROW              1068
#define IDC_STATIC_ROLE                 1069
#define IDC_STATIC_DECMANA5             1069
#define IDC_BUTTON_OK                   1070
#define IDC_BUTTON_CANCEL               1071
#define IDC_BUTTON_NEXT                 1072
#define IDC_BUTTON_PREV                 1073
#define IDC_COMBO_APPLY                 1074
#define IDC_STATIC_VARIATION5           1074
#define IDC_STATIC_SPEC_VAR1            1074
#define IDC_STATIC_APPLY                1075
#define IDC_EDIT_SPEC_VAR1              1075
#define IDC_STATIC_VARIATION6           1076
#define IDC_BUTTON_SELFZONEEFFECT       1076
#define IDC_STATIC_BLOWVAR2             1076
#define IDC_EDIT_BLOW_VALUE2            1077
#define IDC_EDIT_SELFZONEEFFECT         1077
#define IDC_STATIC_VARIATION7           1078
#define IDC_BUTTON_TARGZONEEFFECT       1078
#define IDC_STATIC_SKILL                1078
#define IDC_EDIT_IMPACT_VAR2            1078
#define IDC_EDIT_SPEC_VAR2              1079
#define IDC_EDIT_TARGZONEEFFECT         1079
#define IDC_CHECK_CHK5                  1080
#define IDC_BUTTON_TARGZONEEFFECT2      1080
#define IDC_CHECK_CHK6                  1081
#define IDC_EDIT_TARGZONEEFFECT2        1081
#define IDC_CHECK_CHK7                  1082
#define IDC_BUTTON_TARGETBODYEFFECT2    1082
#define IDC_CHECK_CHK8                  1083
#define IDC_EDIT_TARGETBODYEFFECT2      1083
#define IDC_BUTTON_SELFZONEEFFECT2      1084
#define IDC_STATIC_APPLYRANGE5          1084
#define IDC_EDIT_SELFZONEEFFECT2        1085
#define IDC_EDIT_TARNUM                 1085
#define IDC_EDIT_DEC_CHARM              1086
#define IDC_COMBO_TARGZONE_EFF01        1086
#define IDC_STATIC_DECMANA6             1087
#define IDC_COMBO_TARGZONE_EFF02        1087
#define IDC_EDIT_DEC_EXP                1088
#define IDC_COMBO_SELFBODY_EFF01        1088
#define IDC_STATIC_DECMANA7             1089
#define IDC_COMBO_TARBODY_EFF01         1089
#define IDC_EDIT_DEC_MP_PTY             1090
#define IDC_COMBO_TARBODY_EFF02         1090
#define IDC_STATIC_DECMANA8             1091
#define IDC_COMBO_TARGET_EFF01          1091
#define IDC_EDIT_DEC_SP_PTY             1092
#define IDC_COMBO_TARGET_EFF01_POS1     1092
#define IDC_STATIC_DECMANA9             1093
#define IDC_COMBO_TARGZONE_EFF01_POS    1093
#define IDC_EDIT_DEC_HP_PTY             1094
#define IDC_COMBO_TARGZONE_EFF02_POS    1094
#define IDC_STATIC_DECMANA10            1095
#define IDC_COMBO_SELFZONE_EFF01_POS    1095
#define IDC_COMBO_SELFZONE_EFF02_POS    1096
#define IDC_EDIT_DEFENSE_SKILL_MID      1096
#define IDC_COMBO_TARGET_EFF01_POS2     1097
#define IDC_EDIT_DEFENSE_SKILL_LEVEL    1097
#define IDC_BUTTON_HOLDOUT              1098
#define IDC_EDIT_DEFENSE_SKILL_SID      1098
#define IDC_EDIT_HOLDOUT                1099
#define IDC_EDIT_DEFENSE_SKILL_LEVEL2   1099
#define IDC_EDIT_ONWARD_SUBANI          1099
#define IDC_EDIT_SKILLNAME              1100
#define IDC_STATIC_DECMANA13            1100
#define IDC_BUTTON_STRTBL_SYNC          1101
#define IDC_BUTTON_SELFZONEEFFECT4      1101
#define IDC_STATIC_DECMANA11            1101
#define IDC_STATIC_SPECIALDAMAGETYPE5   1101
#define IDC_BUTTON_RELOAD_STRTBL        1102
#define IDC_EDIT_SELFZONEEFFECT3        1102
#define IDC_EDIT_DEC_CHARM2             1102
#define IDC_EDIT_DEC_CP                 1102
#define IDC_COMBO_ACTION_TYPE           1102
#define IDC_BUTTON_EXPORT_CVS           1103
#define IDC_EDIT_EFF_ELMT               1103
#define IDC_COMBO_REMOVE_ACTION_TYPE    1103
#define IDC_CSV_SAVE                    1104
#define IDC_BUTTON_EFF_ELMT_LEFT        1104
#define IDC_STATIC_DECMANA12            1104
#define IDC_CSV_LOAD                    1105
#define IDC_BUTTON_EFF_ELMT_RIGHT       1105
#define IDC_EDIT_DEC_CP2                1105
#define IDC_EDIT_DEC_BULLET             1105
#define IDC_SPECIAL_BUTTON1             1106
#define IDC_BUTTON_TARGZONEEFFECT3      1106
#define IDC_BTN_CSV_STRTBL_IMPORT       1106
#define IDC_SPECIAL_BUTTON2             1107
#define IDC_COMBO_EFFTARGET             1107
#define IDC_SPECIAL_BUTTON3             1108
#define IDC_CHECK1                      1108
#define IDC_CHECK_GMSKILL               1108
#define IDC_CHECK_ENABLE_EVENT_SKILL    1108
#define IDC_CHECK_EXEXCEL_LV_1          1108
#define IDC_CHECK_GMSKILL2              1109
#define IDC_CHECK_EFFECT_REMOVE         1109
#define IDC_EDIT_DEC_BATTERY            1109
#define IDC_CHECK_EXEXCEL_LV_2          1109
#define IDC_EDIT3                       1110
#define IDC_EDIT_SPEC_VAR3              1110
#define IDC_CHECK_EFFECT_MOB_RATE       1110
#define IDC_CHECK_EFFECT_REMOVE2        1110
#define IDC_CHECK_EXEXCEL_LV_3          1110
#define IDC_STATIC_RESIST5              1111
#define IDC_EDIT_SPEC_VAR4              1111
#define IDC_CHECK_EXEXCEL_LV_4          1111
#define IDC_COMBO_SPECIAL               1112
#define IDC_COMBO_REMOVE_ACTION_TYPE2   1112
#define IDC_COMBO_DURATION_ATTB         1112
#define IDC_COMBO_MULEFFTARGET          1112
#define IDC_CHECK_EXEXCEL_LV_5          1112
#define IDC_BUTTON_M_OPEN1              1113
#define IDC_STATIC_RESIST6              1113
#define IDC_EDIT_SPEC_VAR5              1113
#define IDC_EDIT_TARGZONEEFFECT3        1113
#define IDC_COMBO_DURATION_ATTB2        1113
#define IDC_COMBO_INCREASE_EFF          1113
#define IDC_CHECK_EXEXCEL_LV_6          1113
#define IDC_BUTTON_M_OPEN2              1114
#define IDC_COMBO_TARGZONE_EFF03        1114
#define IDC_EDIT_TRIGGER_TYPE_LINK_MID  1114
#define IDC_CHECK_EXEXCEL_LV_7          1114
#define IDC_BUTTON_M_OPEN3              1115
#define IDC_COMBO_TARGZONE_EFF03_POS    1115
#define IDC_EDIT_TRIGGER_TYPE_LINK_SID  1115
#define IDC_CHECK_EXEXCEL_LV_8          1115
#define IDC_BUTTON_M_OPEN4              1116
#define IDC_BUTTON_SELFZONEEFFECT5      1116
#define IDC_EDIT_DEFENSE_SKILL_LEVEL3   1116
#define IDC_EDIT_TRIGGER_TYPE_LINK_LEVEL 1116
#define IDC_CHECK_EFFECT_FORCE_VISIBLE  1116
#define IDC_CHECK_EXEXCEL_LV_9          1116
#define IDC_EDIT_SKILL_MID              1116
#define IDC_EDIT_REQ_INT2               1116
#define IDC_BUTTON_M_OPEN5              1117
#define IDC_EDIT_SELFZONEEFFECT4        1117
#define IDC_EDIT_SKILL_SID              1117
#define IDC_BUTTON_M_OPEN6              1118
#define IDC_COMBO_SELFZONE_EFF03_POS    1118
#define IDC_EDIT_REQ_MONEY              1118
#define IDC_BUTTON_M_OPEN7              1119
#define IDC_CHECK_RUNCASTING            1119
#define IDC_CHECK_RUNNINGCAST           1119
#define IDC_BUTTON_M_OPEN8              1120
#define IDC_EDIT_RUNNINGCAST            1120
#define IDC_OK                          1121
#define IDC_STATIC_RESIST7              1121
#define IDC_BUTTON_TARGZONEEFFECT4      1121
#define IDC_EDIT_SKILL_TYPE             1122
#define IDC_BUTTON_W_OPEN1              1123
#define IDC_BUTTON_SKILL_TYPE           1123
#define IDC_BUTTON_W_OPEN2              1124
#define IDC_EDIT_ELEMENT                1124
#define IDC_EDIT_LEVEL_DATA             1124
#define IDC_BUTTON_W_OPEN3              1125
#define IDC_BUTTON_ELEMENT              1125
#define IDC_BUTTON_LEVEL_DATA_LEFT      1125
#define IDC_BUTTON_W_OPEN4              1126
#define IDC_EDIT_BLOW_TYPE              1126
#define IDC_BUTTON_LEVEL_DATA_RIGHT     1126
#define IDC_BUTTON_W_OPEN5              1127
#define IDC_BUTTON_BLOW_TYPE            1127
#define IDC_EDIT_IMPACT_ADDON           1128
#define IDC_BUTTON_IMPACT_ADDON_ADD     1128
#define IDC_BUTTON_IMPACT_ADDON         1129
#define IDC_LIST_IMPACT_ADDON           1129
#define IDC_EDIT_SPEC_TYPE              1130
#define IDC_LIST_SPEC_TYPE              1130
#define IDC_BUTTON_SPEC_TYPE            1131
#define IDC_BUTTON_IMPACT_ADDON_DEL     1131
#define IDC_EDIT_SPECIAL                1132
#define IDC_BUTTON_W_OPEN6              1133
#define IDC_BUTTON_SPECIAL              1133
#define IDC_LIST_SPEC_TYPE_SEL          1133
#define IDC_EDIT_MAINTYPE               1134
#define IDC_BUTTON_W_OPEN7              1135
#define IDC_BUTTON_MAINTYPE             1135
#define IDC_BUTTON_W_OPEN8              1136
#define IDC_EDIT_SUBTYPE                1136
#define IDC_BUTTON3                     1137
#define IDC_CANCEL                      1137
#define IDC_BUTTON_SUBTYPE              1137
#define IDC_EDIT_ATTACKLEFT             1138
#define IDC_BUTTON_ATTACKLEFT           1139
#define IDC_EDIT_ATTACKRIGHT            1140
#define IDC_BUTTON_ATTACKRIGHT          1141
#define IDC_BUTTON_SPEC_TYPE_ADD        1142
#define IDC_BUTTON_SPEC_TYPE_DEL        1143
#define IDC_STATIC_IMPACT_ADDON_VAR     1143
#define IDC_EDIT_VEHICLE_MAINTYPE       1144
#define IDC_STATIC_IMPACT_ADDON_VAR2    1144
#define IDC_STATIC_DEFENSE_LEVEL        1145
#define IDC_BUTTON_MAINTYPE2            1145
#define IDC_BUTTON_VEHICLE_MAINTYPE     1145
#define IDC_LIST_IMPACT_ADDON_SEL       1146
#define IDC_CHECK_ATTACKGLOVE           1146
#define IDC_CHECK_HIDDENWEAPON          1146
#define IDC_STATIC_ONWARD_SUBANI        1147
#define IDC_EDIT_ENDTIMEEFFECT          1147
#define IDC_EDIT_ANIMINFO_CFGNAME_M     1147
#define IDC_BUTTON_GATEEFFECT           1148
#define IDC_STATIC_REMOVE_ACTION_TYPE   1148
#define IDC_EDIT_GATEEFFECT             1149
#define IDC_BUTTON_SELFZONEEFFECT6      1149
#define IDC_BUTTON_SELFZONEEFFECT3      1149
#define IDC_STATIC_TRIGGER_TYPE_LINK_LEVEL 1149
#define IDC_STATIC_TRIGGER_TYPE         1149
#define IDC_BUTTON_CA_DEL               1149
#define IDC_STATIC_ADDONIDC_STATIC_ADDON 1150
#define IDC_BUTTON_SPECIAL_IMMUNE_DEL   1150
#define IDC_STATIC_DURATION_ATTB        1151
#define IDC_STATIC_TF_FORM_TYPE         1152
#define IDC_LIST_ATTACKPOINT            1152
#define IDC_STATIC_INCREASE_EFF         1153
#define IDC_EDIT_ANIMINFO_CFGNAME_W     1153
#define IDC_STATIC_SPEC_DWFLAG          1154
#define IDC_EDIT_ANIMFRAME_START_M      1154
#define IDC_EDIT_SPEC_DWFLAG            1155
#define IDC_EDIT_ANIMFRAME_MAX_M        1155
#define IDC_EDIT_ANIMFRAME_END_M        1156
#define IDC_EDIT_ANIMFRAME_MAX_W        1158
#define IDC_EDIT_ANIMFRAME_END_W        1159
#define IDC_RADIO_SPEC1                 1160
#define IDC_EDIT_ANIMFRAME_START_W      1160
#define IDC_RADIO_SPEC2                 1161
#define IDC_RADIO_SPEC3                 1162
#define IDC_RADIO_SPEC4                 1163
#define IDC_STATIC_SPEC_TOOLTIP         1164
#define IDC_STATIC_IMPACT_TOOLTIP       1165
#define IDC_PROGRESS_EXCEL_EXPORT       1166
#define IDC_LIST_MULTI_TARGET_SKILL     1167
#define IDC_LIST_MAINSKILL              1168
#define IDC_MAIN_IMAGE                  1170
#define IDC_MULTI_IMAGE                 1171
#define IDC_MAIN_SKILL_EXPLAIN          1172
#define IDC_MULTI_SKILL_EXPLAIN         1173
#define IDC_COMBO1                      1174
#define IDC_COMBO_LEVEL                 1174
#define IDC_EDIT2                       1175
#define IDC_EDIT_SAVE_STATE             1175
#define IDC_LIST1                       1176
#define IDC_SPEC_VAR_LIST               1176
#define IDC_CHECK_ONLY_ONE_STAT         1177
#define IDC_CHECK_REQ_ONLY_ONE_STAT     1177
#define IDC_BTN_EXCEL_STRTBL_EXPORT     1179
#define IDC_BTN_EXCEL_STRTBL_IMPORT     1180
#define IDC_BUTTON_XMLCONVERT           1181
#define IDC_BUTTON2                     1182
#define IDC_LIST_COUNTATTACK            1188
#define IDC_BUTTON_CA_ADD               1189
#define IDC_LIST_SPECIAL_IMMUNE         1190
#define IDC_BUTTON_SPECIAL_IMMUNE_ADD   1191
#define IDC_STATIC_MAN                  1192
#define IDC_STATIC_MAN2                 1193
#define IDC_STATIC_WOMAN                1193
#define IDC_BUTTON_LEVEL_DATA_BUNCHLEFT 1194
#define IDC_BUTTON_LEVEL_DATA_BUNCHRIGHT 1195
#define IDC_SELECT_LIST                 1197
#define IDC_BUTTON_EXCEL_EXPORT         1254
#define IDC_COMBO_REQ_BRIGHT            1257
#define IDC_STATIC_STATS                2071
#define IDC_STATIC_STATS2               2072
#define IDC_STATIC_BLOW                 2072
#define IDC_STATIC_STATS3               2073
#define IDC_STATIC_ADDON                2073
#define IDC_STATIC_STATS4               2074
#define IDC_STATIC_STATS5               2075
#define IDC_STATIC_SPEC                 2075
#define IDC_STATIC_STATS6               2076
#define IDC_STATIC_DEFAULT              2077
#define IDC_STATIC_DEFENSE_SKILL        2078
#define IDC_STATIC_STATS7               2079
#define IDC_STATIC_TRIGGER_TYPE_LINK    2081
#define IDC_STATIC_SPECIAL_IMMUNE       2082

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
