#ifndef _INTERFACE_BASE_DEFINE_H_
#define _INTERFACE_BASE_DEFINE_H_

#pragma once

#include "UIDataType.h"

enum
{
	EItemToolTipCount = 10,
	ESkillToolTipCount = 10,
	MAX_GROUP_CHAT_WINDOW_MAXCOUNT = 50, //그룹채팅 MAXROOM갯수 50개로 제한 
};

enum ET_UIGUID_INNER // 컨트롤 ID
{
    BASIC_QUICK_SKILL_SLOT = NO_ID + 1,
    QUICK_SKILL_TRAY_OPEN_BUTTON,
    QUICK_SKILL_TRAY_TAB_WINDOW,
    LEFTTOP_CONTROL_GROUP,
    BASIC_INFO_VIEW,	
    MINIMAP,
    ESCMENU_OPEN,
    QBOX_BUTTON,
    GAME_MENU_OPEN_BUTTON,
    GAME_MENU,
    MINIPARTY_OPEN,
    BASIC_CHAT_BOX,
    CHARACTER_WINDOW,
    OPTION_HW_WINDOW,
    SKILL_WINDOW,
    RENEW_SKILL_WINDOW,
    ESC_MENU,
    PARTY_WINDOW,
	PARTY_WINDOW_RENEWAL,
	PARTY_YES_NO_WINDOW,
	EXPEDITION_INVITE_WINDOW,
	PARTY_STATE_WINDOW,
	PARTY_TENDER_WINDOW,
	PARTY_TENDER_NOTIFY_BUTTON,
	PARTY_DISTRIBUTION_WINDOW,
	PARTY_DISTRIBUTION_LIST_WINDOW,
	MINI_EXPEDITION_WINDOW,
	EXPEDITION_CHECK_READY_WINDOW,
    MARKET_WINDOW,
    INVENTORY_WINDOW,
	INVENTORY_WINDOW_RENEW,
    TRADE_WINDOW,
    TRADEINVENTORY_WINDOW,
    STORAGE_WINDOW,
    SKILL_WINDOW_TO_TRAY,
    MINIPARTY_WINDOW,	
    ITEM_MOVE,
    PTOPMENU_WINDOW,
    DAMAGE_MAN,
    TARGETINFO_DISPLAY,	
	CURSOR_TARGET_INFO,
    NAME_DISPLAY_MAN,
    SUMMON_NAME_DISPLAY_MAN,
    DIALOGUE_WINDOW,
    HEADCHAT_MAN,
    ADMIN_MESSAGE_DISPLAY,
    CONFT_MODAL_WINDOW,
    MAPMOVE_DISPLAY,	
    MAPMOVE_DISPLAY_DUMMY,
	MULTIMAPMOVE_DISPLAY,
	MULTIMAPMOVE_DISPLAY_DUMMY,
    PARTY_MODAL_WINDOW,
	CHAT_GROUP_MODAL_WINDOW,
    HELP_WINDOW,
    ITEMSHOP_WINDOW,
    QUEST_WINDOW,
    QUEST_WINDOW_TEMP,
    CONFT_DISPLAY_MAN,
    INFO_DISPLAY,
    INFO_DISPLAY_EX,
    QUEST_ALARM,
    WAITSERVER_DISPLAY,
    SIMPLE_HP,
    SUMMON_HP,
    FRIEND_WINDOW,
	CHAT_GROUP_INVITE_WINDOW,
    BUS_WINDOW,
    MIN_GROUP_CHAT_WINDOW,
    SKILL_TIME_DISPLAY,
    ACADEMY_CONFT_DISPLAY,
    ITEMBANK_WINDOW,
    VNGAINSYS_WINDOW,
    VNGAINSYS_GAUGE_WINDOW,
    MAP_WINDOW,
    STORAGE_CHARGE_CARD,
    REBIRTH_DIALOGUE,
    PRIVATE_MARKET_WINDOW,
    PRIVATE_MARKET_MAKE,
    PRIVATE_MARKET_SELL_WINDOW,
    PRIVATE_MARKET_SHOW_MAN,
	PRIVATE_MARKET_SEARCH_BUY,
    CLUB_WINDOW,
    SUBMASTER_MAKE,
    SIMPLE_MESSAGE_MAN,
    CLUB_MAKE,
    SYSTEM_MESSAGE_WINDOW,
    SYSTEM_MESSAGE_WINDOW_DUMMY,
    QUESTION_ITEM_DISPLAY,
    CLUB_STORAGE_WINDOW,
    CONFT_CONFIRM,
    RECEIVE_NOTE_WINDOW,
    WRITE_NOTE_WINDOW,
    SMS_SEND_WINDOW,
    HAIRCOLORCARD_WINDOW,
    HAIRSTYLECARD_WINDOW,
    PETCOLORCARD_WINDOW,
    PETSTYLECARD_WINDOW,
    WARNING_MSG_WINDOW,
    COUNT_MSG_WINDOW,
    ITEM_REBUILD_WINDOW,	// ITEMREBUILD_MARK
	ITEM_REBUILD_RENEWAL_WINDOW, // ITEMREBUILD_MARK
    PET_WINDOW,
    PET_SKILL_WINDOW,
    PET_REBIRTH_DIALOGUE,  // Monster7j
	MINIGAME_ODD_EVEN_WINDOW,
    GAMBLE_DIALOGUE,
    GAMBLE_SELECT_DIALOGUE,
    GAMBLE_AGAIN_DIALOGUE,
    GAMBLE_ANIMATION_DIALOGUE,
    GAMBLE_RESULT_ODD_DIALOGUE,
    GAMBLE_RESULT_EVEN_DIALOGUE,
    KEY_SETTING_WINDOW,
    CHATMACRO_WINDOW,
    WEAPON_DISPLAY,
    BONUSTIME_EVENT_GAUGE,
    BONUSTIME_EVENT_DISPLAY,
    QUEST_HELPER_DISPLAY,
    VEHICLE_WINDOW,
	CAR_WINDOW,
	REARCAR_WINDOW,
    GENDER_CHANGE_WINDOW,
    THAI_CCAFE_MARK,
    ITEM_GARBAGE_WINDOW,
    ITEM_SHOP_ICON_MAN,
    ITEM_SHOP_SEARCH_WINDOW,
    ITEM_SEARCH_RESULT_WINDOW,
    SUMMON_WINDOW,
    SUMMON_POSION_DISPLAY,
    PETSKIN_MIX_IMAGE_WINDOW,
    ATTENDANCE_BOOK_WINDOW,
    FACE_CHANGE_WINDOW,
    MAP_REQUIRE_CHECK,
    CLUB_BATTLE_MODAL_WINDOW,
    TAXI_WINDOW,
    ITEM_MIX_WINDOW,
    ITEM_MIX_INVEN_WINDOW,
    GATHER_GAUGE,
    CDM_RANKING_DISPLAY,
    CDM_SAFETIME_DISPLAY,
    CHAT_OPTION_WINDOW,
    INFO_DISPLAY_LINK,
    PARTY_LINK_WINDOW,
    GRADE_DISPLAY,
    LUNCHBOX_TIME_DISPLAY,
    SYSTEMBUFF_TIME_DISPLAY,
    BIKE_WINDOW,
    VEHICLE_COLOR_CHANGE_WINDOW,
    BIKE_GET_OFF_WINDOW,
    BIKE_MESSAGE_WINDOW,
    BIKE_BOOST_WINDOW,
    STATSRESET_WINDOW,
    COSTUM_COLOR_CHANGE_WINDOW,
    PET_HUNGRY,
    POSTBOX_WINDOW,
    POSTNOTIFY_BUTTON,

    // for tutorial UI. by luxes.
    MOUSETIP_WINDOW,
    TUTORIAL_DIALOGUE_WINDOW,
    TUTORIAL_DIALOGUE_EXPLAIN_WINDOW,
    EXPLAIN_INTERFACE,
    MOUSE_CONTROL_DIR,
    TUTORIAL_INTERFACE_LEFT,
    TUTORIAL_INTERFACE_RIGHT,
    TUTORIAL_INTERFACE_UP,
    TUTORIAL_INTERFACE_DOWN,
    TUTORIAL_INTERFACE_ZOOM_IN,
    TUTORIAL_INTERFACE_ZOOM_OUT,
    BALLOON_TEXT_WINDOW,
    MINIMAP_TARGET,
    BALLOON_SPACE_BAR,
    TUTORIAL_SKIP_BUTTON,
    TUTORIAL_DAMAGE_ALARM,
    TUTORIAL_EXPLAIN_VAR_TEXT,
    TUTORIAL_VIEW_STEP,
    //

    FACEBOOK_WINDOW,
    TWITTER_WINDOW,
    SNS_WINDOW,
    ITEMPREVIEW_WINDOW,
    POINT_SHOP_WINDOW,
	DPS_WINDOW,
    PROGRESS_DISPLAY,
    STUDENTRECORD_WINDOW,
    STUDENTRECORD_NOTIFY_BUTTON,
    REBIRTH_WINDOW,
    CHATTYPE_LIST,
	COMPETITION_NOTIFY_BUTTON,
	COMPETITION_WINDOW,
	COMPETITION_TOPRANKING,
	COMPETITION_PVEUI,
    COMPETITION_PVEENTRANCECONFIRM,
    COMPETITION_PVERETRY,
	COMPETITION_PVECLEAR,
	
    POPUP_MENU,
    INFO_CTF_DISPLAY,
    CTF_RESULT_WINDOW,
    ITEM_INFOR_TOOLTIP,
    ITEM_INFOR_TOOLTIP_WEAR,
	ITEM_INFOR_TOOLTIP_LINK,
	ITEM_INFOR_TOOLTIP_DURABILITY,
    SKILL_INFOR_TOOLTIP,
	SKILL_INFOR_TOOLTIP_MULTI,
	SKILL_INFOR_TOOLTIP_LINK,
	SKILL_INFOR_TOOLTIP_DELAY_ACTION,
	NOTIFY_CTF_SPURT,
    FORCE_REBIRTH,
	RESERVED_SKILL_ANIMATION,
    DIALOGUE_WINDOW_RENEWAL,
	PRODUCT_BUTTON,
    PRODUCT_PROGRESS,
    PRODUCT_WINDOW,
	PRODUCT_RESET_WINDOW,
    REFERCHAR_WINDOW,
	DICE_WINDOW,
    NOTIFY_WINDOW,
    NOTIFY_BUTTON,
    ITEM_REPAIR_WINDOW,
	PROGESS_TIMER,
	COLOR_PROPERTY_WINDOW,
	MINIGAME_TEXASHOLDEM_WINDOW,
	MINIGAME_TEXASHOLDEM_EXCHANGE_WINDOW,
	MINIGAME_TEXASHOLDEM_WEB_WINDOW,
	DOUBLE_POINT,

	// Lotto System;
	LOTTO_MAIN_UI,
	LOTTO_BUY_LOTTO_UI,
	LOTTO_BUY_LIST_INFO,
	LOTTO_WIN_MAN_LIST_INFO,
	LOTTO_NOTIFY_BUTTON,
	LOTTO_DISPLAY_UI,

    // New Instance System
    INSTANCE_SYSTEM_MESSAGE_DISPLAY,
    INSTANCE_TIMER_MESSAGE_BOX,
    RNCDM_PROGRESS,
    RNCDM_RANK_WINDOW,
    RNCDM_CLUB_INFO,
	RNCOMPETITION_WINDOW,
	RNCDM_TOP_RANKING,
    CAPTURE_THE_FLAG_EFFECT_MAN,
    RNCOMPETITION_RESULT_WINDOW,
    GUIDANCE_AUTH_PROGRESS_UI,
    GUIDANCE_PROGRESS_INFO_UI,
    GUIDANCE_RANK_INFO_UI,
	CTI_AUTH_PROGRESS_UI,
	CTI_PROGRESS_INFO_UI,
	CTI_RANK_INFO_UI,

	// Tournament
	TOURNAMENT_DASHBOARD,
	TOURNAMENT_UI,
	TOURNAMENT_TOTO,
	TOURNAMENT_MORE_INFO,
	COMPETITION_TOURNAMENTENTRANCECONFIRM,
	COMPETITION_TOURNAMENT_OBSERVE,
	COMPETITION_TOURNAMENT_MULTY,
	COMPETITION_TOURNAMENTENTUI,
	COMPETITION_TOURNAMENTENT_BIG_RIGHT,
	COMPETITION_TOURNAMENTENT_BIG_LEFT,
	COMPETITION_TOURNAMENTENT_MINI_RIGHT,
	COMPETITION_TOURNAMENTENT_MINI_LEFT,
	COMPETITION_TOURNAMENTENT_INDICATOR,

	// Summon State
	SUMMON_STATE_DISPLAY_UI,

	// Faction Information UI
	FACTION_INFO_WINDOW,

	// World Battle Join Button
	WORLD_BATTLE_JOIN_BUTTON,

	WAIL_ENTRANCE_STATE,
	WAIL_BOARD,
	WAIL_INDICATOR,

	INVEN_ITEM_TOOLTIP_BEGIN,
	INVEN_ITEM_TOOLTIP_END = INVEN_ITEM_TOOLTIP_BEGIN + EItemToolTipCount,
    WISH_ITEM_TOOLTIP_BEGIN,
    WISH_ITEM_TOOLTIP_END = WISH_ITEM_TOOLTIP_BEGIN + EItemToolTipCount,
    MARKET_WISH_ITEM_TOOLTIP_BEGIN,
    MARKET_WISH_ITEM_TOOLTIP_END = MARKET_WISH_ITEM_TOOLTIP_BEGIN + EItemToolTipCount,

	SKILL_TOOLTIP_BEGIN,
	SKILL_TOOLTIP_END = SKILL_TOOLTIP_BEGIN + ESkillToolTipCount,

	MAX_GROUP_CHAT_WINDOW_START,
	MAX_GROUP_CHAT_WINDOW_END = MAX_GROUP_CHAT_WINDOW_START + MAX_GROUP_CHAT_WINDOW_MAXCOUNT,

	FLYCAMERACONTROL_WINDOW,
	SETITEM_PREVIEWWINDOW,

	COSTUME_STATS_WINDOW,
	SELECTIVEFORMBOX_WINDOW,
	/*add pk combo GS Version*/
	PK_COMBO_DISPLAY,

	PK_NOTIFICATION,
	
	//		ID의 끝
    MODAL_WINDOW,
};

//	PAGE ID
enum ET_UIGUID_OUTER
{
	SELECT_SERVER_PAGE = NO_ID + 1,
    SELECT_CHINA_AREA_PAGE,
    COPYRIGHT,
    CHINA_TITLE,
	LOGIN_PAGE,
    LOGIN_MARK,
    PASS_KEYBOARD,
    SELECT_CHARACTER_PAGE,
    SELECT_CHARACTER_LEFTPAGE,
	SELECT_COUNTRY_UI,
	SELECT_CONTINENT_LIST_UI,
	SELECT_COUNTRY_LIST_UI,
    CREATE_CHARACTER_PAGE,
    CREATE_CHARACTER_BUTTON_PAGE,
    CREATE_CHARACTER_WEB,
    MODAL_WINDOW_OUTER,
    OUTER_UP_IMAGE,
    OUTER_DN_IMAGE,
    FULLSCREEN_OUTER,
    FULLSCREEN_OUTER_DUMMY,
    WAIT_DISPLAY,
    SECPASS_SETPAGE,
    SECPASS_CHECKPAGE,
    MESSAGE_WINDOW,
    MESSAGE_WINDOW_DUMMY,
    OUTER_INFO_DISPLAY,
    TITLE_TEXT,
    ROTATE_CHARACTER,
    LOCK_SELECT_CHARACTER_PREVIEW_PAGE,
    SELECT_COUNTRY_CONFIRM_MODAL,
    SELECT_COUNTRY_WINDOW,
    CHARACTER_COUNTRY_CLUB_INFO,
    SELECT_CLUB_WINDOW,
	JOIN_WORLDBATTLE_BUTTON,
};

//	MODAL CALLER
enum
{
    OUTER_MODAL_CLOSEGAME = NO_ID + 1,
    OUTER_MODAL_WAITSERVERINFO,
    OUTER_MODAL_RECONNECT,
    OUTER_MODAL_WAITCONFIRM,
    OUTER_MODAL_CREATEFAILED,
    OUTER_MODAL_ALREADYCONNECT,
    OUTER_MODAL_NON_PK_CHANNEL,
    OUTER_MODAL_CONNECTCLOSED,
    OUTER_MODAL_LOGOUT,
    OUTER_MODAL_SECONDPASSWORD,
    OUTER_MODAL_CREATESUCCEED,
    OUTER_MODAL_GENERAL_LOGINFAIL,
    OUTER_MODAL_NAME_ERROR,
    OUTER_MODAL_LOGIN_WAIT_DAUM,
    OUTER_MODAL_LOGIN_WAIT_DAUM_AFTER_KEYRECEIVED,
    OUTER_MODAL_LOGIN_WAIT_DAUM_SERVERFULL,
    OUTER_MODAL_CHARACTERSTAGE_GAME_JOIN_WAIT,
    OUTER_MODAL_CHARACTERSTAGE_GAME_JOIN_FAIL,
    OUTER_MODAL_THAI_CHECK_STRING_ERROR,
    OUTER_MODAL_CHARACTER_SELECT,
    OUTER_MODAL_SUCCESS_CHANGE_COUNTRY,
    OUTER_MODAL_FAIL_CHANGE_COUNTRY,
    OUTER_MODAL_INPUT_MAKE_CLUB_NAME,
    OUTER_MODAL_MAKE_CLUB_SUCCESS,
    OUTER_MODAL_MAKE_CLUB_FAIL,
    OUTER_MODAL_JOIN_CLUB_SUCCESS,
    OUTER_MODAL_JOIN_CLUB_FAIL,
	OUTER_MODAL_JOIN_SECOUNDPASSWORD, // 2차비번
	OUTER_MODAL_JOIN_SECOUNDPASSWORD_GS, // 2차비번
	OUTER_MODAL_SHOW_COUNTRY_SELECT_LIST_UI,
	OUTER_MODAL_SELECTED_COUNTRY,
	OUTER_MODAL_RIDE_VEHICLETARGET,	
};

enum
{
    UI_UNDERATTACK = 0,
    UI_ATTACK = 1
};

//!	대련시에 키워드
enum
{
    CONFT_WIN_INDEX = 0,
    CONFT_LOSE_INDEX,
    CONFT_DRAW_INDEX
};

//!	학교
enum
{	
    SUNGMOON = 0,
    HYUNAM,
    BONGHWANG,
    INIT_SCHOOL = 100,
};

namespace UI
{
    enum
    {
        OKCANCEL,
        YESNO,
        OK,
        CANCEL,
        EDITBOX,
        EDITBOX_PETNAME,
        EDITBOX_NUMBER,
        EDITBOX_MONEY,
		EDITBOX_CHECK_PWD,
        MODAL_EDITBOX_LOTTERY,
        MODAL_FILE_NAME,
        NO_CONTROL
    };

    enum
    {	
        MODAL_INFOMATION,
        MODAL_QUESTION,
        MODAL_WARNING,
        MODAL_ERROR,
        MODAL_CRITICAL,
        MODAL_INPUT,
        MODAL_NOTITLE
    };

    enum
    {
        MODAL_CLOSEGAME = NO_ID + 1,
		MODAL_DO_NOTING,
        MODAL_TEST_MODAL,
        MODAL_INVENTORY_MONEY_TO_FIELD,   
        MODAL_PARTY_TAR,
        MODAL_PARTY_REQ_DBNUM,
        MODAL_PARTY_REQ,
		MODAL_CHAT_GROUP_TAR,
		MODAL_CHAT_GROUP_REQ,
		MODAL_EXPEDITION_REQ,
        MODAL_TRADE_REQ,
        MODAL_REBIRTH,
        //MODAL_DROPMONEY,
		MODAL_BETTINGMONEY,
        MODAL_TRADEMONEY,
        MODAL_SAVEMONEY,
        MODAL_CLUB_SAVEMONEY,
        MODAL_LOADMONEY,	
        MODAL_CLUB_LOADMONEY,
        MODAL_SPLIT_ITEM,
        MODAL_STORAGE_SPLIT_ITEM,
        MODAL_CLUB_STORAGE_SPLIT_ITEM,
        MODAL_CONFLICT_ONE_TAR,
        MODAL_CONFLICT_PARTY_TAR,
        MODAL_CONFLICT_GUILD_TAR,
        MODAL_CONFLICT_ONE_REQ,	
        MODAL_CONFLICT_PARTY_REQ,
        MODAL_CONFLICT_GUILD_REQ,
        MODAL_PILE_ITEM,
        MODAL_SERVER_STAGE,
        MODAL_BUY_ITEM,
        MODAL_SELL_ITEM,
        MODAL_QUEST_GIVEUP,
        MODAL_FRIEND_ADD,
        MODAL_FRIEND_DEL,
        MODAL_FRIEND_MOVE,
        MODAL_ADD_FRIEND_LURE_ANS,
        MODAL_DEFAULT_POS,
        MODAL_LOTTO,
        MODAL_STORAGE_CHARGE,
        MODAL_PRIVATE_MARKET_SELL,
        MODAL_PRIVATE_MARKET_BUY,
        MODAL_PRIVATE_MARKET_PILE,
		MODAL_PRIVATE_MARKET_ONLY_UI,
        MODAL_PRIVATE_MARKET_QUIT,
        MODAL_CLUB_KICK,
        MODAL_CLUB_BREAKUP,
        MODAL_CLUB_CHANGE_MARK,
        MODAL_CLUB_NICK,
        MODAL_CLUB_JOIN_ASK,
        MODAL_CLUB_JOIN,
        MODAL_CLUB_BREAKUP_CANCEL,
        MODAL_CLUB_SELFQUIT,
        MODAL_CLUB_AUTHORITY,
        MODAL_CLUB_AUTHORITY_ASK,
        CLUB_AUTHORITY_MEMBER_ASK,
        MODAL_SKILL_LEVEL_UP_CONFIRM,
        MODAL_COMMISSION,
        MODAL_FRIEND_BLOCK_ADD_N,
        MODAL_FRIEND_BLOCK_ADD_B,
        MODAL_FRIEND_BLOCK_DEL,
        MODAL_UNION_JOIN_ASK,
        MODAL_UNION_JOIN,
        MODAL_UNION_KICK,
		MODAL_UNION_WITHDRAW,
        MODAL_UNION_LEAVE,
        MODAL_UNION_BREAKUP,
        MODAL_CHAR_RENAME,
        MODAL_PET_RENAME,
        MODAL_ITEMREBUILD_MONEY,
        MODAL_ITEMREBUILD_OKQUESTION,
        MODAL_HAIRCOLOR_INFO,
        MODAL_PETCOLOR_INFO,
        MODAL_MOBILE_NUMBER,
        MODAL_KEYSETTING_ERROR,
        MODAL_RESET_SKILLSTATS,
        MODAL_GENDER_CHANGE,
        MODAL_GENDER_CHANGE_END,
        MODAL_ITEMGARBAGE_OKQUESTION,
        MODAL_RECOVERY_EXP,
        MODAL_RECOVERY_NPC_EXP,
        MODAL_CLUB_BATTLE_ASK,
        MODAL_CLUB_BATTLE_ARMISTICE,
        MODAL_CLUB_BATTLE_ARMISTICE_ASK,
        MODAL_CLUB_BATTLE_SUBMISSION,
        MODAL_ALLIANCE_BATTLE_ASK,
        MODAL_ALLIANCE_BATTLE_ARMISTICE,
        MODAL_ALLIANCE_BATTLE_ARMISTICE_ASK,
        MODAL_ALLIANCE_BATTLE_SUBMISSION,
        MODAL_ITEMMIX_OKQUESTION,
        MODAL_SKILLFACT_REMOVE,
        MODAL_SKILLFACT_LUNCHBOX_OVERWRITE,
        MODAL_VEHICLE_WITH,
        MODAL_VEHICLE_COLOR,
        MODAL_POSTBOX_PAGE_READ_BUTTON_DELETE,
        MODAL_POSTBOX_PAGE_READ_BUTTON_DELETE_CONFIRM_ATTACH,
        MODAL_POSTBOX_PAGE_READ_BUTTON_RETURN,
        MODAL_POSTBOX_PAGE_READ_BUTTON_TAKE,
        MODAL_POSTBOX_PAGE_RECEIVE_BUTTON_DELETE_CHECK,
        MODAL_POSTBOX_PAGE_RECEIVE_BUTTON_DELETE_COMMIT,
        MODAL_POSTBOX_PAGE_SEND_BUTTON_SEND_COMMISION,
        MODAL_FORCE_REBIRTH_SKILL,

        //by luxes.
        MODAL_REQ_HOLD_TO_FILED,
        MODAL_COSTUM_COLOR,
        MODAL_TUTORIAL_SKIP,
        //

        MODAL_ITEMBANK_GET_ITEM,
        MODAL_SNS_FACEBOOK_ADDFRIEND,
        MODAL_SNS_TWITTER_FOLLOW,
        MODAL_SNS_MSG,

        MODAL_SELL_ITEM_FROM_INVEN,
        MODAL_DIALOGUE_PILE_ITEM,

        MODAL_DIRECT_SELL_ITEM,

		MODAL_STORAGE_CONNECT_ITEMUSE_REQ,

        MODAL_CLUB_CD_AUTHORITY_TO_MASTER,
        MODAL_CLUB_CD_AUTHORITY_TO_MEMBER,

        MODAL_CONFIRM_CUSTOMER_CENTER,
		MODAL_INVENTORY_ITEMDECOMPOSE_OKQUESTION,

		MODAL_NPC_EXCHANGE_BUY_ITEM,

		MODAL_COSTUME_STAT_APPLY,
		MODAL_COSTUME_STAT_BASIC_HAS, // 코스튬 기본능력치가 이미 있다.
		MODAL_COSTUME_STAT_APPLIED,   // 코스튬 능력치가 이미 적용 되어 있다.

		MODAL_CONFIRM_CHANGE_COUNTRY,
		MODAL_CONFIRM_JOIN_PVP_SERVER,

		MODAL_COSTUME_STAT_RELEASE,
		MODAL_SELFORMW_SELECTITEM,

		MODAL_TEMP_ENCHANT,
    };

    enum EMMANAGECONTROL_TYPE
    {
        EMMANAGECONTROL_TYPE_NPCACTIONABLE, // NPC를 통해 부르는 컨트롤
    };

    enum EMMAPCHECK_TYPE
    {
        EMMAPCHECK_NONE			= 0,	// 비동작 상태
        EMMAPCHECK_LEVELUP		= 1,	// 레벨업으로 나가야할 경우
        EMMAPCHECK_ENTRYFAIL	= 2,	// 진입 조건 실패로 나가야할 경우
        EMMAPCHECK_LIMITTIME	= 3,	// 시간 제한으로 나가야할 경우
		EMMAPCHECK_EXPEDITION	= 4,	// 원정대가 아닌 경우
    };

    enum EMSTATSRESETWINDOW_TYPE
    {
        EMSTATSRESETWINDOW_TYPE_SKILL,
        EMSTATSRESETWINDOW_TYPE_STATS,
        EMSTATSRESETWINDOW_TYPE_STATS_SELECT,
    };

	enum EMSTATSRESETWINDOW_SKILL
	{
		EMSTATSRESETWINDOW_SKILL_GRADE = 31,
		EMSTATSRESETWINDOW_SKILL_MARBLE_MID = 104,
		EMSTATSRESETWINDOW_SKILL_GRADE_MIN = 4,
	};

    enum EMPROGRESSDISPLAY_TYPE
    {
        //! 이 순서는 출력 우선순위와 상관 있습니다.
        EMPROGRESSDISPLAY_TYPE_CTF_START,
        EMPROGRESSDISPLAY_TYPE_CTF_CAPTURED_BY_SM,
        EMPROGRESSDISPLAY_TYPE_CTF_CAPTURED_BY_HA,
        EMPROGRESSDISPLAY_TYPE_CTF_CAPTURED_BY_BH,
        EMPROGRESSDISPLAY_TYPE_CTF_STOP,
        EMPROGRESSDISPLAY_TYPE_CTF_READY,
        EMPROGRESSDISPLAY_TYPE_ACTIVITY_COMPLETE,
        EMPROGRESSDISPLAY_TYPE_ATTENDANCE_COMPLETE,
        EMPROGRESSDISPLAY_TYPE_ACTIVITY_PROGRESS,
		EMPROGRESSDISPLAY_TYPE_PUBLIC,
		EMPROGRESSDISPLAY_TYPE_RN_CDM_START,
		EMPROGRESSDISPLAY_TYPE_RN_CDM_END,
		EMPROGRESSDISPLAY_TYPE_LOTTO_START,
		EMPROGRESSDISPLAY_TYPE_LOTTO_END,
    };

	enum EMTOURNAMENTDISPLAY_TYPE
	{
		EMTOURNAMENT_TYPE_CHAR_INFO,
		EMTOURNAMENT_TYPE_VERSERS,
		EMTOURNAMENT_TYPE_HUDINFO,
		EMTOURNAMENT_TYPE_RESUALT,
		EMTOURNAMENT_TYPE_OBSERVE,
	};

	enum EMTARGETINFO_TYPE
	{
		EMTARGETINFO_TYPE_MOUSEOVER = 0,
		EMTARGETINFO_TYPE_SELECT,
	};

    typedef std::string String;
    inline CString ToString(const String& str) { return str.c_str(); }
    inline String ToString(const CString& str) { return (LPCTSTR)str; }
}

#endif
