#ifndef _NPC_TALK_CONDITION_DEFINE_H_
#define _NPC_TALK_CONDITION_DEFINE_H_

#pragma once

enum TALK_CONDITION_SAVE_TYPE
{
    DLG_CASE_CONDITION_SAVE,
    TALK_CONTROL_NPC_TALK_SAVE,
};

#endif // _NPC_TALK_CONDITION_DEFINE_H_