#pragma once

namespace MiniGame
{
#define DEFDEPTH 1.5f
#define DEFLIMIT_SPEED 1.0f
#define DEFDICE_INTERPOLATE 0.86f

	enum EMDICE_GAME_STATE
	{
		EMDICE_GAME_STATE_IDLE, // 대기중;
		EMDICE_GAME_STATE_HOLD, // 쥐고 있는중;
		EMDICE_GAME_STATE_ROLL, // 굴러가는 중;
		EMDICE_GAME_STATE_FINISH, // 결과가 나옴(시각적으로 EMDICE_STATE_IDLE과 같은 상태);
		EMDICE_GAME_STATE_LOCK, // 잠금;
		EMDICE_GAME_STATE_NSIZE,
	};

	enum EMDICE_STATE
	{
		EMDICE_STATE_IDLE,
		EMDICE_STATE_HOLD,
		EMDICE_STATE_MOVE,
		EMDICE_STATE_DETERMINE,
		EMDICE_STATE_INTERPOLATE,
		EMDICE_STATE_FINISH,
		EMDICE_STATE_NSIZE,
	};
}
