//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SpecialTool.rc
//
#define IDC_BUTTON_FIND                 3
#define IDC_BUTTON_NEXT                 4
#define IDC_BUTTON_FIND_MAPNAME         5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SPECIALTOOL_DIALOG          102
#define IDS_PROPSHT_CAPTION             103
#define IDD_ITEMMIXPAGE                 104
#define IDD_ITEMDIALOG                  105
#define IDD_ITEMMIXDATA                 106
#define IDD_TAXISTATIONPAGE             107
#define IDD_TAXIDATA                    108
#define IDD_NPCDIALOG                   109
#define IDD_MAPDIALOG                   110
#define IDD_MAPSLISTPAGE                111
#define IDD_MAPSLISTDIALOG              112
#define IDD_AUTOLEVELPAGE               113
#define IDD_AUTOLEVELPAGE5              118
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       133
#define IDR_MAIN_MENU                   133
#define IDR_TOOLBAR1                    135
#define IDD_MAPSLISTDIALOG2             139
#define IDD_WSPEDIT                     144
#define IDC_LIST_ITEMMIX                1000
#define IDC_BUTTON_ADD                  1001
#define IDC_BUTTON_EDIT                 1002
#define IDC_EDIT_ID                     1003
#define IDC_EDIT_TOOLTEXT               1004
#define IDC_BUTTON_DEL                  1005
#define IDC_EDIT_MAT01_MID              1006
#define IDC_COMBO_TOOLPAGE              1007
#define IDC_EDIT_MAT01_SID              1008
#define IDC_BUTTON_NEW                  1009
#define IDC_EDIT_FIND_MID               1010
#define IDC_BUTTON_CSVSAVE              1010
#define IDC_EDIT_MAT02_MID              1011
#define IDC_BUTTON_CSVLOAD              1011
#define IDC_BUTTON_LOAD                 1012
#define IDC_EDIT_FIND_SID               1013
#define IDC_LIST_MAPSLIST               1014
#define IDC_STATIC_CONTROL              1015
#define IDC_LIST_AUTO_LEVEL             1015
#define IDC_EDIT_MAT02_SID              1016
#define IDC_BUTTON_AUTOLEVEL_ADD        1016
#define IDC_LIST_TAXISTATION            1017
#define IDC_BUTTON_AUTOLEVEL_DEL        1017
#define IDC_EDIT_MAT03_MID              1018
#define IDC_BUTTON_AUTOLEVEL_LOADOLD    1018
#define IDC_BUTTON_OLDLOAD              1019
#define IDC_CHECK_DAY1                  1019
#define IDC_CHECK_DAY2                  1020
#define IDC_EDIT_BASIC_CHARGE           1021
#define IDC_CHECK_DAY3                  1021
#define IDC_EDIT_SID                    1022
#define IDC_CHECK_DAY4                  1022
#define IDC_EDIT_MAT03_SID              1023
#define IDC_CHECK_DAY5                  1023
#define IDC_EDIT_SID2                   1023
#define IDC_EDIT_RATE_ITEM_DROP         1023
#define IDC_BUTTON_SAVE                 1024
#define IDC_CHECK_DAY6                  1024
#define IDC_CHECK_USE                   1025
#define IDC_CHECK_DAY7                  1025
#define IDC_EDIT_MID                    1026
#define IDC_EDIT_EVENT_MAP_MID          1026
#define IDC_EDIT_MAT04_MID              1027
#define IDC_EDIT_EVENT_MAP_SID          1027
#define IDC_EDIT_RATE_EXP_DROP          1027
#define IDC_EDIT_MAP_MID                1028
#define IDC_EDIT_EVENT_MAP_GATE         1028
#define IDC_EDIT_MAP_NAME               1029
#define IDC_EDIT_EVENT_HALLMAP_MID      1029
#define IDC_EDIT_MAT04_SID              1030
#define IDC_EDIT_EVENT_HALLMAP_SID      1030
#define IDC_EDIT_MAP_SID                1031
#define IDC_EDIT_STARTTIME_HOUR         1031
#define IDC_CHECK_MAP_USE               1032
#define IDC_EDIT_STARTTIME_MIN          1032
#define IDC_EDIT_MAT05_MID              1033
#define IDC_EDIT_ENDTIME_HOUR           1033
#define IDC_BUTTON_MAP_EDIT             1034
#define IDC_EDIT_ENDTIME_MIN            1034
#define IDC_EDIT_FILENAME               1035
#define IDC_EDIT_POS1_X                 1035
#define IDC_BUTTON_FIND_ID              1036
#define IDC_EDIT_POS1_Y                 1036
#define IDC_EDIT_MAT05_SID              1037
#define IDC_EDIT_POS2_X                 1037
#define IDC_EDIT_MAP_XPOS               1038
#define IDC_EDIT_POS2_Y                 1038
#define IDC_LIST_NPC                    1039
#define IDC_EDIT_POS3_X                 1039
#define IDC_EDIT_FIELDSERVER            1040
#define IDC_EDIT_POS3_Y                 1040
#define IDC_EDIT_RESULT_MID             1041
#define IDC_EDIT_POS4_X                 1041
#define IDC_EDIT_MAP_YPOS               1042
#define IDC_EDIT_POS4_Y                 1042
#define IDC_EDIT_BGM                    1043
#define IDC_EDIT_POS5_X                 1043
#define IDC_EDIT_RESULT_SID             1044
#define IDC_EDIT_POS5_Y                 1044
#define IDC_EDIT_NPC_MID                1045
#define IDC_BUTTON_AUTOLEVEL_SET        1045
#define IDC_LIST_MAP                    1046
#define IDC_CHECK_EVENT_PVP             1046
#define IDC_EDIT_LOADING_IMAGE          1047
#define IDC_CHECK_EVENT_USE             1047
#define IDC_EDIT_RATE                   1048
#define IDC_EDIT_EVENT_NAME             1048
#define IDC_EDIT_NPC_SID                1049
#define IDC_LIST_AUTOLEVEL_CMD          1049
#define IDC_CHECK_PEACEZONE             1050
#define IDC_BUTTON_COMMNAD_ADD          1050
#define IDC_BUTTON_MAT01_EDIT           1051
#define IDC_BUTTON_COMMNAD_DEL          1051
#define IDC_BUTTON_NPC_EDIT             1052
#define IDC_BUTTON_COMMNAD_UP           1052
#define IDC_CHECK_COMMISSION            1053
#define IDC_BUTTON_COMMNAD_DOWN         1053
#define IDC_LIST_ITEM                   1054
#define IDC_EDIT_CMDTIME_HOUR           1054
#define IDC_EDIT_PRICE                  1055
#define IDC_EDIT_CMDTIME_MIN            1055
#define IDC_CHECK_PROHIBIT_TAXI_CARD    1055
#define IDC_EDIT_CHARGE                 1056
#define IDC_COMBO_COMMAND               1056
#define IDC_EDIT_DELAY                  1056
#define IDC_CHECK_PROHIBIT_TELEPORT_CARD 1056
#define IDC_CHECK_PKENABLE              1057
#define IDC_BUTTON_COMMNAD_EDIT         1057
#define IDC_EDIT_FINDSID                1058
#define IDC_BUTTON_AUTOLEVEL_CSVSAVE    1058
#define IDC_CHECK_PKMAP                 1058
#define IDC_BUTTON_MAT02_EDIT           1059
#define IDC_EDIT_CMD_MSG                1059
#define IDC_CHECK_UI_MAP_INFO           1059
#define IDC_EDIT_MAPNAME                1060
#define IDC_BUTTON_AUTOLEVEL_CSVLOAD    1060
#define IDC_NEED_LEARN                  1060
#define IDC_CHECK_FREEPK                1061
#define IDC_RANDOM_OPTION               1061
#define IDC_BUTTON_UP                   1062
#define IDC_CHECK_EXPEDITION_MAP        1062
#define IDC_EDIT_FINDMID                1063
#define IDC_CHECK_PROHIBIT_RECALL       1063
#define IDC_BUTTON_MAT03_EDIT           1064
#define IDC_CHECK_PROHIBIT_RECALL2      1064
#define IDC_CHECK_PROHIBIT_CURE         1064
#define IDC_EDIT_NPCNAME                1065
#define IDC_EDIT_NPC_NAME               1065
#define IDC_EDIT_DEFENSE                1065
#define IDC_CHECK_PROHIBIT_DROP_ITEM    1065
#define IDC_CHECK_ITEMDROP              1066
#define IDC_BUTTON_DOWN                 1067
#define IDC_CHECK_PROHIBIT_CURE2        1067
#define IDC_CHECK_PROHIBIT_RELEASE      1067
#define IDC_BUTTON_MAT04_EDIT           1068
#define IDC_CHECK_PROHIBIT_RELEASE2     1068
#define IDC_CHECK_MACRO                 1068
#define IDC_CHECK_FRIENDCARD            1069
#define IDC_EDIT_ATTACK                 1069
#define IDC_EDIT_FIND_MAPNAME           1070
#define IDC_CHECK_MACRO2                1070
#define IDC_CHECK_PRISON                1070
#define IDC_BUTTON_MAT05_EDIT           1071
#define IDC_BUTTON1                     1071
#define IDC_BUTTON_CONVERT_TO_LUA       1071
#define IDC_BUTTON_AUTOLEVEL_CONVERT_TO_LAYER 1071
#define IDC_CHECK_PRISON2               1071
#define IDC_CHECK_CHANGECHARSLOT        1071
#define IDC_CHECK_RESTART               1072
#define IDC_WSPEDIT                     1072
#define IDC_BUTTON_AUTOLEVEL_CONVERT_TO_LAYER2 1072
#define IDC_BUTTON_RESULT_EDIT          1073
#define IDC_CHECK_PETACTIVITY           1074
#define IDC_EDIT_LEVEL                  1074
#define IDC_EDIT_MAT01_NUM              1075
#define IDC_TypeList                    1075
#define IDC_CHECK_EXPDROP               1076
#define IDC_EDIT_WSP                    1076
#define IDC_EDIT_MAT02_NUM              1077
#define IDC_EDIT_PER                    1077
#define IDC_CHECK_VEHICLEACTIVITY       1078
#define IDC_EDIT_WS                     1078
#define IDC_EDIT_MAT03_NUM              1079
#define IDC_CHECK_CLUBBATTLEZONE        1080
#define IDC_EDIT2                       1080
#define IDC_EDIT_TYPE                   1080
#define IDC_EDIT_MAT04_NUM              1081
#define IDC_COMBO_INSTANCE_TYPE         1081
#define IDC_CHECK_INSTANTMAP            1082
#define IDC_EDIT_MAT05_NUM              1083
#define IDC_COMBO2                      1083
#define IDC_CHECK_QBOXDROP              1084
#define IDC_EDIT_RESULT_NUM             1085
#define IDC_CHECK_LUNCHBOXFORBID        1085
#define IDC_CHECK_CPRESET               1086
#define IDC_CHECK_CPRESET2              1087
#define IDC_CHECK_UI_MAP_SELECT         1087
#define IDC_CHECK_UI_MAP_SELECT2        1088
#define IDC_CHECK_PARTY_MAP             1088
#define IDC_CHECK_PM_OPENABLE           1089
#define IDC_CHECK_PM_OPENABLE2          1090
#define IDC_CHECK_CULL_BY_OBJECT        1090
#define IDC_CHECK_REBIRTHBLOCK          1091
#define IDC_CHECK_PARTY_MAP3            1092
#define IDC_CHECK_SPARRING              1092
#define IDC_CHECK_REBIRTHBLOCK2         1093
#define IDC_CHECK_ENABLESWITCHMOB       1094
#define IDC_BUTTON_CONVERT_XML          1095
#define IDC_CHECK_ENABLESWITCHMOB2      1095
#define IDC_CHECK_CHANGESCHOOL          1095
#define ID_FILE_NEWFILE                 32771
#define ID_FILE_LOADFILE                32772
#define ID_FILE_SAVEFILE                32774
#define ID_FILE_EXIT                    32775
#define ID_FILE_LOADFILE_OLD            32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
