//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LevelEdit.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DIALOG_MOBSETPAGE           103
#define IDD_DIALOG_MOBSCHEDULEPAGE      104
#define IDD_DIALOG_LANDMARK             107
#define IDR_MAINFRAME                   128
#define IDR_LevelEditTYPE               129
#define IDS_PROPSHT_CAPTION             129
#define IDD_DIALOG_LEVELEDIT            131
#define IDD_DIALOG_LEVELMAINPAGE        132
#define IDD_DIALOG_MOBSETPAGE1          133
#define IDD_DIALOG_CROWTREE             134
#define IDD_DIALOG_LEVELREQUIREPAGE     135
#define IDD_DIALOG_ITEMTREE             136
#define IDD_DIALOG_SKILLTREE            137
#define ID_VIEW_CAMERA_CHAR             138
#define IDD_DIALOG_GATE_LIST            138
#define ID_VIEW_CAMERA_TO               139
#define ID_VIEW_SELECT_MOBSCH           140
#define IDD_DIALOG_QUEST                143
#define IDD_DIALOG_ETCFUNC              144
#define IDD_DIALOG_COLORS               145
#define IDB_BITMAP_HSB                  146
#define IDB_BITMAP_RGB                  147
#define IDD_DIALOG_EFFECTLIST           148
#define IDR_ACCELERATOR1                149
#define IDD_DIALOG_COLLISION            150
#define IDD_DIALOG_SINGLEEFF            206
#define IDD_DIALOG_LANDGATE             213
#define IDC_EDIT_FILENAME               1000
#define IDC_STATIC_RGB_RECT             1000
#define IDC_BUTTON_FILENAME             1001
#define IDC_STATIC_HSB_RECT             1001
#define IDC_EDIT_WLDFILENAME            1002
#define IDC_STATIC_SHEETTAP             1002
#define IDC_TREE_ITEM                   1002
#define IDC_EDIT_RED                    1002
#define IDC_COMBO_PAGE                  1003
#define IDC_BUTTON_WLDFILENAME          1003
#define IDC_SPIN_RED                    1003
#define IDC_EDIT_GREEN                  1004
#define IDC_BUTTON_NAVI_FILENAME        1004
#define IDC_EDIT_DIV                    1005
#define IDC_SPIN_GREEN                  1005
#define IDC_COMBO_DIV                   1006
#define IDC_EDIT_BLUE                   1006
#define IDC_BUTTON_CREATETREE           1007
#define IDC_SPIN_BLUE                   1007
#define IDC_CHECK_RENDQUAD              1008
#define IDC_STATIC_OLD                  1008
#define IDC_CHECK_CROWSCH               1009
#define IDC_STATIC_NEW                  1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON_MOVE                 1010
#define IDC_BUTTON_RENDGEN              1010
#define IDC_BUTTON_ITEM                 1010
#define IDC_BUTTON_LANDEFF1             1010
#define IDC_EDIT_HUE                    1010
#define IDC_BUTTON_NAME_CONVERT         1010
#define IDC_BUTTON_GATEEFF              1010
#define IDC_EDIT_NAVI_FILENAME          1010
#define IDC_BUTTON_SKILL                1011
#define IDC_BUTTON_EDIT                 1011
#define IDC_BUTTON_LANDEFF2             1011
#define IDC_SPIN_HUE                    1011
#define IDC_BUTTON_NAVI_FILENAME_DELETE 1011
#define IDC_BUTTON_NAVI_FILENAME_CLEAR  1011
#define IDC_CHECK_RENDGENPOS            1012
#define IDC_BUTTON_COM_QUEST            1012
#define IDC_EDIT_SAT                    1012
#define IDC_BUTTON_GATEEFF_CLEAR        1012
#define IDC_EDIT_LEVEL                  1013
#define IDC_SPIN_SAT                    1013
#define IDC_EDIT_ITEM_MID               1014
#define IDC_LIST_EFFECT                 1014
#define IDC_EDIT_VAL                    1014
#define IDC_EDIT_ITEM_SID               1015
#define IDC_SPIN_VAL                    1015
#define IDC_EDIT_SKILL_MID              1016
#define IDC_BUTTON_OK                   1017
#define IDC_EDIT_SKILL_SID              1017
#define IDC_EDIT_LEVEL2                 1018
#define IDC_EDIT_COM_QUEST_MID          1019
#define IDC_BUTTON_ITEM2                1019
#define IDC_EDIT_COM_QUEST_SID          1020
#define IDC_EDIT_ITEM_MID2              1020
#define IDC_COMBO_LIVING                1021
#define IDC_COMBO_BRIGHT                1022
#define IDC_CHECK_PARTY_AGREE           1023
#define IDC_COMBO_LEVEL                 1024
#define IDC_BUTTON_SAVE_SET             1025
#define IDC_BUTTON_ACT_QUEST            1026
#define IDC_EDIT_ACT_QUEST_MID          1027
#define IDC_EDIT_ITEM_SID2              1027
#define IDC_EDIT_ACT_QUEST_SID          1028
#define IDC_BUTTON_ITEM3                1028
#define IDC_EDIT_LIVING                 1029
#define IDC_EDIT_BRIGHT                 1030
#define IDC_EDIT_ITEM_NAME              1031
#define IDC_BUTTON_CANCEL               1032
#define IDC_EDIT_SKILL_NAME             1032
#define IDC_EDIT_TIME                   1033
#define IDC_BUTTON_GATEID_PC_REGEN      1033
#define IDC_EDIT_NAME                   1033
#define IDC_EDIT_ITEM_NAME2             1033
#define IDC_LIST_GATE                   1034
#define IDC_BUTTON_BUS_LOCATION         1034
#define IDC_EDIT_NAME_GAMEINTEXT        1034
#define IDC_EDIT_ITEM_MID3              1034
#define IDC_BUTTON_CREATE               1035
#define IDC_BUTTON_RESET_ITEM           1035
#define IDC_EDIT_NAME_INDEX             1035
#define IDC_BUTTON_DELETE               1036
#define IDC_BUTTON_RESET_SKILL          1036
#define IDC_BUTTON_MODIFY               1037
#define IDC_EDIT_COMQUEST               1037
#define IDC_LIST_LANDMARK               1038
#define IDC_EDIT_PROCQUEST              1038
#define IDC_BUTTON_RESET_QUEST_COM      1039
#define IDC_LIST_QUEST                  1039
#define IDC_BUTTON_RESET_QUEST_PROC     1040
#define IDC_EDIT1                       1040
#define IDC_EDIT_COPY_MOBNAME           1040
#define IDC_EDIT_LIMITTIME1             1040
#define IDC_EDIT_XML_NAME_KEY           1040
#define IDC_EDIT_MINUS_X                1040
#define IDC_WEEK_CHECK1                 1041
#define IDC_EDIT_LIMITTIME2             1041
#define IDC_BUTTON_RESET_ITEM2          1041
#define IDC_EDIT_PLUS_X                 1041
#define IDC_WEEK_CHECK2                 1042
#define IDC_CHECK_LIMITTIME             1042
#define IDC_EDIT_ITEM_SID3              1042
#define IDC_WEEK_CHECK3                 1043
#define IDC_EDIT_CONCAM1                1043
#define IDC_EDIT_ITEM_NAME3             1043
#define IDC_WEEK_CHECK4                 1044
#define IDC_CHECK_CONCAM                1044
#define IDC_BUTTON_RESET_ITEM3          1044
#define IDC_EDIT_MINUS_Z                1044
#define IDC_WEEK_CHECK5                 1045
#define IDC_EDIT_CONCAM2                1045
#define IDC_BUTTON_ITEM4                1045
#define IDC_EDIT_PLUS_Z                 1045
#define IDC_WEEK_CHECK6                 1046
#define IDC_EDIT_CONCAM3                1046
#define IDC_EDIT_ITEM_MID4              1046
#define IDC_EDIT_ROTATION_Y             1046
#define IDC_WEEK_CHECK7                 1047
#define IDC_EDIT_CONCAM4                1047
#define IDC_EDIT_ITEM_SID4              1047
#define IDC_EDIT_RADIUS                 1047
#define IDC_CHECK_LANDEFF               1048
#define IDC_CHECK_MINIMAP               1048
#define IDC_EDIT_ITEM_NAME4             1048
#define IDC_LIST_LANDEFF                1049
#define IDC_BUTTON_RESET_ITEM4          1049
#define IDC_CHECK_LIMITTIME2            1050
#define IDC_CHECK_REENTRYLIMIT          1050
#define IDC_BUTTON_ITEM5                1050
#define IDC_BUTTON_CONFIRM              1051
#define IDC_EDIT_ITEM_MID5              1051
#define IDC_BUTTON_CONCAM               1052
#define IDC_EDIT_ITEM_SID5              1052
#define IDC_STATIC_CONCAM1              1053
#define IDC_EDIT_ITEM_NAME5             1053
#define IDC_EDIT_CONCAM5                1054
#define IDC_BUTTON_RESET_ITEM5          1054
#define IDC_EDIT_CONCAM8                1055
#define IDC_EDIT_CONCAM6                1056
#define IDC_EDIT_CONCAM7                1057
#define IDC_CHECK_CONCAM2               1058
#define IDC_EDIT_CONCAM9                1059
#define IDC_CHECK_MOBCHASE              1060
#define IDC_CHECK_MOBCHASE2             1061
#define IDC_COMBO_LANDEFF               1062
#define IDC_EDIT_LANDEFF                1063
#define IDC_EDIT_RENDGENPOS_NUM         1063
#define IDC_SPIN_RENDGENPOS_NUM         1064
#define IDC_EDIT_RENDGENPOS_DIST        1065
#define IDC_SPIN_RENDGENPOS_DIST        1066
#define IDC_STATICRENDGENPOS_NUM        1067
#define IDC_STATIC_RENDGENPOS_NUM       1067
#define IDC_STATIC_RENDGENPOS_DIST      1068
#define IDC_CHECK_REGENONCE             1069
#define IDC_BUTTON_MULTIMODIFY          1070
#define IDC_CHECK_CIRCLE                1071
#define IDC_EDIT_REENTRYLIMIT           1072
#define IDC_BUTTON_COLOR                1073
#define IDC_CHECK_EACH_REGEN            1074
#define IDC_CHECK1                      1075
#define IDC_CHECK_GATEEFF               1075
#define IDC_CHECK_FOR                   1075
#define IDC_CHECK_FORCE_EXIT            1075
#define IDC_CHECK_VIEW_NAME             1075
#define IDC_COMBO_MOBLAYER              1076
#define IDC_BUTTON_MOBLAYER_ADD         1077
#define IDC_BUTTON_MOBLAYER_DEL         1078
#define IDC_EDIT_SCALE                  1079
#define IDC_LIST1                       1080
#define IDC_EDIT_SCALE2                 1080
#define IDC_EDIT_ACTIVITYAREA           1080
#define IDC_STATIC_SCALE                1081
#define IDC_STATIC_EFFECT               1082
#define IDC_STATIC_SCALE2               1082
#define IDC_STATIC_GATEEFF              1083
//#define IDC_STATIC_INFLUENCEY           1083
#define IDC_GATETO_LIST                 1084
#define IDC_EDIT_ACTIVITYAREA2          1084
//#define IDC_EDIT_INFLUENCEY             1084
#define IDC_BUTTON_ADD_GATE             1085
#define IDC_BUTTON_DELETE_GATE          1086
#define IDC_EDIT2                       1087
#define IDC_EDIT_XML_NAME_INDEX         1087
#define IDC_EDIT_REGEN_MIN              1088
#define IDC_RADIO_PLANE                 1089
#define IDC_RADIO_BOX                   1090
#define IDC_LIST_MOBSET                 1091
#define IDC_LIST_SCHEDULE               1091
#define IDC_RADIO_CYLINDER              1091
#define IDC_LIST_MOBSELECT              1092
#define IDC_LIST_COLLISION              1092
#define IDC_STATIC_TYPE                 1093
#define IDC_STATIC_MINUS_X              1094
#define IDC_STATIC_MINUS_Z              1095
#define IDC_STATIC_PLUS_X               1096
#define IDC_STATIC_PLUS_Z               1097
#define IDC_STATIC_ROTATION_Y           1098
#define IDC_STATIC_RADIUS               1099
#define IDC_CHECK_REND                  1107
#define IDC_EDIT_FINDSTR                1117
#define IDC_EDIT_TOGATEID               1119
#define IDC_EDIT_GATEID2                1120
#define IDC_COMBO_ACTION                1121
#define IDC_BUTTON_DEL                  1177
#define IDC_BUTTON_NEW                  1178
#define IDC_BUTTON_SEARCH               1197
#define IDC_BUTTON_ADD                  1199
#define IDC_STATIC_PAGELINE             1200
#define IDC_BUTTON_EFFAPPLY             1201
#define IDC_STATIC_LAYER_NUMBER         1202
#define IDC_BUTTON_TEST                 1203
#define IDC_BUTTON_TEST2                1204
#define IDC_BUTTON_CHAR                 1204
#define IDC_BUTTON_STOP                 1204
#define IDC_STATIC_S                    1205
#define IDC_STATIC_E                    1206
#define IDC_BUTTON_CSV_EXPORT           1207
#define IDC_BUTTON_CSV_IMPORT           1208
#define IDC_BUTTON_SAVEFILE             1211
#define IDC_BUTTON5                     1213
#define IDC_BUTTON_NAME                 1213
#define IDC_BUTTON_LIVING               1213
#define IDC_CHECK_IN                    1213
#define IDC_BUTTON_LEVEL                1214
#define IDC_BUTTON_LOADFILE             1215
#define IDC_BUTTON_BRIGHT               1215
#define IDC_BUTTON_SCHEDULE             1217
#define IDC_EDIT_MOBNAME                1218
#define IDC_EDIT_GROUPNAME              1219
#define IDC_BUTTON_SKIN                 1220
#define IDC_BUTTON_CROWID               1220
#define IDC_EDIT_SKIN                   1221
#define IDC_EDIT_MID                    1221
#define IDC_EDIT_REGEN                  1222
#define IDC_BUTTON_REGEN                1223
#define IDC_EDIT_SID                    1224
#define IDC_BUTTON_REGEN2               1225
#define IDC_EDIT_GATEID_PC_REGEN        1226
#define IDC_EDIT_GATEID_PC_REGEN2       1227
#define IDC_EDIT_BUS_LOCATION           1227
#define IDC_EDIT_REGEN_TIME1            1228
#define IDC_EDIT_REGEN_TIME2            1229
#define IDC_BUTTON_GROUPNAME            1230
#define IDC_EDIT_REGEN_MAX              1231
#define IDC_EDIT_REGEN2                 1231
#define IDC_EDIT_GEN_DX                 1235
#define IDC_EDIT_GEN_DY                 1236
#define IDC_STATIC_GATEID               1237
#define IDC_STATIC_CREATEPOS            1238
#define IDC_STATIC_MAPID                1239
#define IDC_STATIC_GATEID2              1240
#define IDC_CHECK_OUT                   1242
#define IDC_STATIC_GATEFLAGS            1243
#define IDC_BUTTON_CLONE                1244
#define IDC_CHECK_LEADER                1245
#define IDC_EDIT_GATEEFF                1245
#define IDC_CHECK_LEADER2               1246
#define IDC_CHECK_GROUP_REGEN           1246
#define IDC_BUTTON_APPLY                2011
#define ID_VIEW_CURNONE                 32771
#define ID_VIEW_SELECT                  32772
#define ID_VIEW_MOVE                    32773
#define ID_VIEW_ROTATE                  32774
#define ID_VIEW_SCALE                   32775
#define ID_BUTTON32776                  32776
#define ID_VIEW_BOXEDIT                 32780
#define ID_COMBO_MATRIX                 32781
#define ID_BUTTON32782                  32782
#define ID_VIEW_ALL_90                  32782
#define ID_FILE_ALL_CSVSAVE             32785
#define ID_FILE_ALL_CSVLOAD             32789
#define ID_FILE_CSVSAVE                 32790
#define ID_FILE_CSVLOAD                 32791
#define ID_32792                        32792
#define ID_IMPORT_LAYER                 32793
#define ID_ACCELERATOR32794             32794
#define ID_ACCELERATOR_SAVE             32794
#define ID_32796                        32796
#define ID_VIEW_NAVIGATION_MESH         32797
#define ID_32798                        32798
#define ID_IMPORT_LAYER_EXCEPT_EFFECT   32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
