#include "stdafx.h"
#include "./OldUi/StudentRecord/ActivityGrade.cpp"
#include "./OldUi/StudentRecord/ActivityHelpWindow.cpp"
#include "./OldUi/StudentRecord/ActivityListButton.cpp"
#include "./OldUi/StudentRecord/ActivityListSlot.cpp"
#include "./OldUi/StudentRecord/ActivityMainPage.cpp"
#include "./OldUi/StudentRecord/ActivitySalesItemList.cpp"
#include "./OldUi/StudentRecord/ActivitySalesItemWindow.cpp"
#include "./OldUi/StudentRecord/ActivityWindowPage.cpp"
#include "./OldUi/StudentRecord/AttendanceAward.cpp"
#include "./OldUi/StudentRecord/AttendanceCalendar.cpp"
#include "./OldUi/StudentRecord/AttendanceContents.cpp"
#include "./OldUi/StudentRecord/AttendanceDayList.cpp"
#include "./OldUi/StudentRecord/AttendancePage.cpp"
#include "./OldUi/StudentRecord/AttendanceTask.cpp"
#include "./OldUi/StudentRecord/StudentRecordNotifyButton.cpp"
#include "./OldUi/StudentRecord/StudentRecordObject.cpp"
#include "./OldUi/StudentRecord/StudentRecordWindow.cpp"
#include "./OldUi/StudentRecord/StudentRecordWindowRequest.cpp"
#include "./OldUI/StudentRecord/RnAttendancePage/RnattendanceQuestSlot.cpp"
#include "./OldUI/StudentRecord/RnAttendancePage/RnattendanceDayInfo.cpp"
#include "./OldUI/StudentRecord/RnAttendancePage/RnattendanceCalender.cpp"
#include "./OldUI/StudentRecord/RnAttendancePage/RnattendanceDayBox.cpp"
#include "./OldUI/StudentRecord/RnAttendancePage/RnattendanceDateBox.cpp"


