#include "stdafx.h"
#include "./OldUI/Competition/CompetitionNotifyButton.cpp"
#include "./OldUI/Competition/CompetitionObject.cpp"
#include "./OldUI/Competition/CompetitionTopRanking.cpp"
#include "./OldUI/Competition/CompetitionWindow.cpp"
#include "./OldUI/Competition/CTFBattle.cpp"
#include "./OldUI/Competition/CTFHistory.cpp"
#include "./OldUI/Competition/CTFPage.cpp"
