//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GenItemTool.rc
//
#define ID_REVISE_CLEAR                 3
#define ID_REVISE_SAVE                  4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SPECIALTOOL_DIALOG          102
#define IDD_GENITEMTOOL_DIALOG          102
#define IDS_PROPSHT_CAPTION             103
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   133
#define IDR_TOOLBAR1                    135
#define IDD_MAPSLISTDIALOG2             139
#define IDD_GENITEMSEARCHPAGE           146
#define IDD_DIALOG1                     147
#define IDD_DIALOG_SKILL_INFO           147
#define IDD_DIALOG_LINKLOST             148
#define IDD_DIALOG_SELECT_DATA          149
#define IDD_DIALOG_REVISE               150
#define IDC_EDIT_TOOLTEXT               1004
#define IDC_COMBO_TOOLPAGE              1007
#define IDC_BUTTON_EXPORT_TO_CSV        1010
#define IDC_BUTTON_RELOAD               1012
#define IDC_BUTTON_LINKLOSTDATA         1013
#define IDC_STATIC_CONTROL              1015
#define IDC_CHECK_PROHIBIT_RECALL2      1064
#define IDC_EDIT_NPCNAME                1065
#define IDC_BUTTON1                     1071
#define IDC_BUTTON_SEARCH               1071
#define IDC_BUTTON_SELEC_RELOAD         1071
#define IDC_BUTTON_LINKLOST_ITEM_FIND   1071
#define IDC_BUTTON_REVISE_FIND          1071
#define IDC_BUTTON_LINKLOST_SPECID_FIND 1072
#define IDC_BUTTON_LINKLOST_GENITEMFILE_FIND 1073
#define IDC_BUTTON_LINKLOST_CROW_FIND   1074
#define IDC_EDIT2                       1080
#define IDC_EDIT_CROW_NAME              1080
#define IDC_COMBO_CROW_NAME             1080
#define IDC_EDIT_LINKLOST_SPECID        1080
#define IDC_EDIT_REVISE_ITEMNAME        1080
#define IDC_EDIT_ITEM_NAME              1081
#define IDC_COMBO_ITEM_NAME             1081
#define IDC_EDIT_ITEMID_MID             1081
#define IDC_CHECK_INSTANTMAP            1082
#define IDC_EDIT_ITEMID_SID             1082
#define IDC_COMBO2                      1083
#define IDC_CHECK_CPRESET2              1087
#define IDC_CHECK_UI_MAP_SELECT2        1088
#define IDC_CHECK_PM_OPENABLE2          1090
#define IDC_CHECK_PARTY_MAP3            1092
#define IDC_LIST2                       1094
#define IDC_LIST_SKILL_INFO             1094
#define IDC_LIST_SPECID_ITEM            1094
#define IDC_LIST_GENITEM                1095
#define IDC_STATIC_ID                   1096
#define IDC_STATIC_NAME                 1097
#define IDC_EDIT_CROW_MID               1098
#define IDC_EDIT_ITEM_MID               1099
#define IDC_EDIT_CROW_SID               1100
#define IDC_EDIT_ITEM_SID               1101
#define IDC_EDIT_GEN_ITEM               1102
#define IDC_COMBO_GEN_ITEM              1102
#define IDC_EDIT_GEN_SPEC_ID            1103
#define IDC_STATIC_ID2                  1104
#define IDC_STATIC_NAME2                1105
#define IDC_LIST_LINKLOST_GENITEMFILE   1107
#define IDC_BUTTON_FINDWORD_CROWNAME    1109
#define IDC_LIST_LINKLOST_CROW          1110
#define IDC_BUTTON_FINDWORD_ITEMNAME    1110
#define IDC_LIST_LINKLOST_SPECID        1111
#define IDC_BUTTON_FINDWORD_GENITEMNAME 1111
#define IDC_LIST_LINKLOST_ITEM          1112
#define IDC_LIST_NOUSE_SPECID           1115
#define IDC_EDIT_LINKLOST_ITEMNAME      1116
#define IDC_EDIT_LINKLOST_ITEM_SID      1117
#define IDC_EDIT_LINKLOST_ITEM_MID      1118
#define ID_BUTTON_SELECT                1118
#define ID_BUTTON_DELETE                1119
#define IDC_EDIT_LINKLOST_CROW_SID      1120
#define ID_BUTTON_CLEAR                 1120
#define IDC_EDIT_LINKLOST_GENITEMFILENAME 1121
#define IDC_EDIT_INPUT_NAME             1121
#define IDC_EDIT_LINKLOST_CROW_MID      1122
#define IDC_LIST_SELECT_DATA            1122
#define IDC_EDIT_LINKLOST_CROWNAME      1123
#define IDC_LIST_FINDWORD               1123
#define ID_BUTTON_COMPLETE              1124
#define IDC_BUTTON2                     1124
#define IDC_BUTTON_LINKLOST_CSV         1124
#define IDC_BUTTON_REVISE_SEARCH_ITEM   1124
#define IDC_BUTTON_FILEEDIT             1124
#define IDC_EDIT_GENITEMFILENAME        1125
#define IDC_LIST_INFO_GENITEMFILE       1125
#define IDC_LIST_INFO_GENITEMFILE_ANNOTATION 1126
#define IDC_EDIT_SPECID_SINGLE          1127
#define IDC_EDIT_RESULT                 1128
#define IDC_EDIT_REVISE_GENRATE         1129
#define IDC_EDIT_REVISE_GENNUM_NUM      1130
#define IDC_EDIT_REVISE_GENNUM_RATE     1131
#define IDC_EDIT_REVISE_GENDATA_SPECID  1132
#define IDC_EDIT_REVISE_GENDATA_RATE    1133
#define IDC_EDIT_REVISE_SKILLID_MID     1134
#define IDC_EDIT_REVISE_SKILLID_SID     1135
#define IDC_EDIT_REVISE_ANNOTATION      1136
#define IDC_CHECK_REVISE_SKILLFACT      1137
#define ID_REVISE_DELETE                1138
#define IDC_BUTTON_REVISE_INPUT_GENRATE 1139
#define IDC_BUTTON_REVISE_INPUT_GENNUM  1140
#define IDC_BUTTON_REVISE_INPUT_GENDATA 1141
#define IDC_BUTTON_REVISE_INPUT_ANNOTATION 1142
#define STATIC_ANNOTATION               1145
#define IDC_STATIC_REVISE               1146
#define IDC_STATIC_REVISE_FILENAME      1147
#define ID_FILE_NEWFILE                 32771
#define ID_FILE_LOADFILE                32772
#define ID_FILE_SAVEFILE                32774
#define ID_FILE_EXIT                    32775
#define ID_FILE_LOADFILE_OLD            32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
