//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorldEdit.rc
//
#define ID_VIEW_TILE_DEL                0
#define ID_BUTTON_PARAMETER_INSERT      3
#define ID_BUTTON_PARAMETER_DELETE      4
#define ID_BUTTON_PARAMETER_MODIFY      5
#define IDD_ABOUTBOX                    100
#define IDR_HTML_WATEREFFEDIT           102
#define IDD_BGMEDIT_DIALOG              105
#define IDD_DIALOG_BGMEDIT              105
#define IDD_DIALOG_COLLISIONMAP         106
#define IDR_HTML_LIGHTMAPEFFEDIT        107
#define IDR_MAINFRAME                   128
#define IDR_WORLDETYPE                  129
#define IDS_PROPSHT_CAPTION             129
#define IDD_DIALOG_EDITFORM             130
#define IDR_SHADER1                     131
#define IDR_SHADER2                     132
#define IDR_SHADER3                     133
#define IDR_SHADER4                     134
#define IDR_POPUP_FRAME                 147
#define IDD_DIALOG_EXPORT               148
#define ID_FRAME_SELECTNAVIMESH         149
#define IDD_DIALOG_WATEREFFEDIT         151
#define IDD_DIALOG_TILING               151
#define IDD_DIALOG_FRAME                152
#define IDD_DIALOG_COLORS               153
#define IDB_BITMAP_RGB                  155
#define IDB_BITMAP_HSB                  156
#define IDD_DIALOG_LIGHT                157
#define IDD_DIALOG_DOT3                 159
#define IDD_DIALOG_ENV                  160
#define IDD_DIALOG_RIVER                160
#define IDD_DIALOG_FUR                  165
#define IDD_DIALOG_DIRECTION            167
#define IDD_DIALOG_SPRITE               168
#define IDD_DIALOG_FRAMESTATE           169
#define IDD_DIALOG_RAINPOINT            170
#define IDD_DIALOG_GRASS                171
#define IDD_DIALOG_REPLACEFRAME         172
#define IDD_DIALOG_ENVIRON2             173
#define IDD_DIALOG_SHADOW               173
#define IDD_DIALOG_ANISET               174
#define IDD_DIALOG_CLOTH                175
#define IDD_DIALOG_BLURC                177
#define ID_MENUITEM_SETTING_SAVE        179
#define ID_MENUITEM_SETTING_LOAD        180
#define IDD_DIALOG_LOADSET_LOG          180
#define ID_VIEW_EDITPANEL               181
#define ID_VIEW_MOVETOFRAME             182
#define ID_VIEW_MOVETOPOINT             183
#define IDD_DIALOG_WEATHER              184
#define IDD_DIALOG_CHECKINTEGRITY       187
#define ID_MENUITEM_CHECKINTEGRITY      188
#define IDD_DIALOG_KOSMO                190
#define IDD_DIALOG_NATURE               192
#define IDD_DIALOG_WATERLIGHT           193
#define IDD_DIALOG_RENDERSTATE          194
#define IDD_DIALOG_WATER2EFFEDT         195
#define IDB_BITMAP_CUBEMAP              200
#define IDD_DIALOG_CUBEMAP              201
#define IDD_DIALOG_CAMERA               202
#define IDD_DIALOG_SOUND                203
#define IDD_DIALOG_SOUNDSOURCE          204
#define IDD_DIALOG_SINGLEEFF            206
#define IDD_DIALOG_NATUREPAGE           208
#define IDD_DIALOG_SPORE                209
#define IDD_DIALOG_SETMULTISLIDER       210
#define IDD_DIALOG_LANDSKINOBJ          211
#define ID_VIEW_EDITBOX                 212
#define IDD_DIALOG_LANDGATE             213
#define IDD_DIALOG2                     214
#define IDD_DIALOG_WEATHERFORM          214
#define IDD_DIALOG_SPECULAR             215
#define IDD_DIALOG_RENDERLIGHT          216
#define IDD_DIALOG_MULTITEX             217
#define IDD_DIALOG_NEON                 218
#define IDD_DIALOG_SETVER               219
#define IDD_DIALOG_REFLECT              220
#define ID_221                          221
#define ID_222                          222
#define ID_FILE_PIECE_LOAD              223
#define IDD_DIALOG1                     224
#define IDD_DIALOG_SPEC_REFLECT         224
#define IDD_DIALOG_LIGHTMAP             225
#define IDD_DIALOG_FOG                  225
#define IDD_DIALOG_GLOW                 226
#define IDD_DIALOG_TILE                 227
#define IDD_DIALOG_MBE_CREATE           227
#define IDD_DIALOG_MAPEDIT_GRID         228
#define IDD_DIALOG_MAPEDIT              229
#define IDD_DIALOG_MAPEDIT_HEIGHT       230
#define IDD_DIALOG_MAPEDIT_TILE         232
#define IDD_DIALOG_MAPEDIT_PIECE        233
#define IDD_DIALOG_TEXTURE_SET          234
#define IDD_DIALOG_PIECE_SINGLEEFF      235
#define IDD_DIALOG_PIECE_TEXEFF         236
#define IDD_DIALOG_PIECE_MANAGER        237
#define IDD_DIALOG_PIECE_MORPH          238
#define IDD_DIALOG_TEX_MULTI            239
#define IDD_DIALOG_TEX_DLG              240
#define IDD_DIALOG_CAMCOLL              241
#define IDD_DIALOG_TEX_VISUAL_MATERIAL  242
#define IDD_DIALOG_PIECE_POINT          243
#define IDD_DIALOG_PIECE_DLG            244
#define IDD_DIALOG_PIECE_PREVIEW        245
#define IDD_DIALOG_SKYBOXMAN            246
#define IDD_DIALOG_TEX_PIECE_VM_VIEWER  247
#define IDD_DIALOG_WATERSURF            248
#define IDD_DIALOG_PIECE_MESH_STATE     249
#define IDD_DIALOG_PROGRESS_BAR         250
#define IDD_DIALOG_ASSET                251
#define IDB_BITMAP_TOOLBAR              252
#define IDD_DIALOG_MINIMAP              253
#define IDD_DIALOG_OCCLUSION            254
#define IDD_DIALOG_EXPORT_MINI          255
#define IDD_DIALOG_PREFAB               260
#define IDD_DIALOG_CUBE_MAP             261
#define IDD_DIALOG_SHADOW_LIGHT         262
#define IDC_STATIC_RGB_RECT             1000
#define IDC_TREE_FRAME                  1001
#define IDC_STATIC_HSB_RECT             1001
#define IDC_EDIT_XFILE                  1002
#define IDC_EDIT_RED                    1002
#define IDC_BUTTON_XFILEOPEN            1003
#define IDC_SPIN_RED                    1003
#define IDC_EDIT_PIECE                  1003
#define IDC_EDIT_XFILE_LIGHTMAP         1003
#define IDC_EDIT_EXPORT_FACECOUNT       1004
#define IDC_EDIT_GREEN                  1004
#define IDC_EDIT_PIE_NAME               1004
#define IDC_BUTTON_EXPORT               1005
#define IDC_SPIN_GREEN                  1005
#define IDC_PROGRESS_EXPORT             1006
#define IDC_EDIT_BLUE                   1006
#define IDC_BUTTON_EXPORT_CANCEL        1007
#define IDC_SPIN_BLUE                   1007
#define IDC_BUTTON_EXPORT_OK            1007
#define IDC_EDIT_MAX_BLUE               1007
#define IDC_BUTTON_OPEN                 1007
#define IDC_COMBO_EFFECT                1008
#define IDC_STATIC_OLD                  1008
#define IDC_BUTTON_EXPORT_              1008
#define IDC_BUTTON_EXPORT_CHECKINTEGRITY 1008
#define IDC_EDIT_VISIBLE_RADIUS         1008
#define IDC_STATIC_NEW                  1009
#define IDC_EDIT_LIGHTMAP_NAME          1009
#define IDC_EDIT_INVISIBLE_RADIUS       1009
#define IDC_BUTTON_EFFECTMODIFIY        1010
#define IDC_EDIT_HUE                    1010
#define IDC_STATIC_POS                  1010
#define IDC_EDIT_LIGHTMAP_DETAIL        1010
#define IDC_EDIT_RADIOSITY_PASS         1010
#define IDC_EDIT_SLOPE_RATE             1010
#define IDC_BUTTON_EFFECTSTATE          1011
#define IDC_SPIN_HUE                    1011
#define IDC_BUTTON_POS                  1011
#define IDC_BUTTON_SELECTFILE           1011
#define IDC_BUTTON_WATER_FORCE          1011
#define IDC_BUTTON_EDIT                 1011
#define IDC_EDIT_RADIOSITY_REFLECTANCE  1011
#define IDC_BUTTON_EFFECTADD            1012
#define IDC_EDIT_SAT                    1012
#define IDC_BUTTON_APPLY2               1012
#define IDC_BUTTON_WATER_FORCE2         1012
#define IDC_BUTTON_ALPHA                1012
#define IDC_BUTTON_SINGLE_REPLACEOBJ    1012
#define IDC_EDIT_RADIOSITY_FOG_POWER    1012
#define IDC_BUTTON_EFFECTCHANGE         1013
#define IDC_BUTTON_EFFECTCHANGEADD      1013
#define IDC_SPIN_SAT                    1013
#define IDC_BUTTON_DIR                  1013
#define IDC_EDIT_RADIOSITY_FOG_BLEND    1013
#define IDC_LIST_EFFECT                 1014
#define IDC_EDIT_VAL                    1014
#define IDC_BUTTON_RANGE                1014
#define IDC_BUTTON_SEQUENCE02           1014
#define IDC_EDIT_RAD_FOG_R              1014
#define IDC_BUTTON_FRAMESTATE           1015
#define IDC_EDIT_FRAME_EFF_NAME         1015
#define IDC_SPIN_VAL                    1015
#define IDC_EDIT_RAD_FOG_G              1015
#define IDC_BUTTON_THETA_ANGLLE         1015
#define IDC_STATIC_SHEETTAP             1016
#define IDC_BUTTON_EFFECTSTATE2         1016
#define IDC_BUTTON_EFFECTDELETE         1016
#define IDC_EDIT_RAD_FOG_B              1016
#define IDC_BUTTON_PHI_ANGLLE           1016
#define IDC_BUTTON_OK                   1017
#define IDC_EDIT_RAD_FOG_ALL            1017
#define IDC_BUTTON_FALL_OFF_ANGLE       1017
#define IDC_EDIT_SIZEZ                  1018
#define IDC_BUTTON_LOAD                 1018
#define IDC_EDIT_AMBIENT_R              1018
#define IDC_EDIT_SIZEX                  1019
#define IDC_BUTTON_PEF_LOAD             1019
#define IDC_EDIT_AMBIENT_G              1019
#define IDC_EDIT_SELSIZEZ               1020
#define IDC_EDIT_AMBIENT_B              1020
#define IDC_EDIT_SELSIZEX               1021
#define IDC_EDIT_AMBIENT_ALL            1021
#define IDC_EDIT_HEIGHT                 1022
#define IDC_EDIT_AMBIENT_B2             1022
#define IDC_EDIT_RADIOSITY_FOG_LENGTH   1022
#define IDC_EDIT_VELOCITY               1023
#define IDC_EDIT_HEIGHT2                1023
#define IDC_EDIT_RAINY                  1023
#define IDC_EDIT_ROTATION_Y             1023
#define IDC_EDIT_DEPTH                  1024
#define IDC_EDIT_VELOCITY_Y             1024
#define IDC_EDIT_ROTATION_SPEED         1024
#define IDC_EDIT_DIFFUSE_APHA           1025
#define IDC_EDIT_REFRACTION_RATE        1025
#define IDC_EDIT_VELOCITY_Z             1025
#define IDC_EDIT_DIFFUSE_R              1026
#define IDC_EDIT_TEXTURE_MOVE_VELOCITY  1026
#define IDC_EDIT_DIFFUSE_G              1027
#define IDC_EDIT_DIFFUSE_MAX_X          1027
#define IDC_EDIT_DIFFUSE_MAX_RED        1027
#define IDC_EDIT_DIFFUSE_B              1028
#define IDC_EDIT_TEXTURE_NAME           1028
#define IDC_EDIT_DIFFUSE_MAX_RED2       1028
#define IDC_CHECK_WIREFRAME             1029
#define IDC_EDIT_DIFFUSE_MIN_X          1029
#define IDC_EDIT_DIFFUSE_MIN_RED        1029
#define IDC_EDIT_TEXTURE                1030
#define IDC_CHECK_WIREFRAME2            1030
#define IDC_EDIT_DIFFUSE_MIN_RED2       1030
#define IDC_BUTTON_TEXTURE              1031
#define IDC_EDIT_REFRECTION_TEXTURE     1031
#define IDC_BUTTON_CANCEL               1032
#define IDC_EDIT_POSX                   1033
#define IDC_EDIT_TEXTURE_REFLECT        1033
#define IDC_EDIT_TEXTURE2               1033
#define IDC_EDIT_VER                    1033
#define IDC_EDIT_SCALE_X                1033
#define IDC_BUTTON_SAVE                 1033
#define IDC_EDIT_HEIGHT_MIN             1033
#define IDC_EDIT_MAP0                   1033
#define IDC_EDIT_SOUND                  1033
#define IDC_EDIT_NAME                   1033
#define IDC_EDIT_FILENAME               1033
#define IDC_EDIT_LIFETIME               1033
#define IDC_EDIT_TIME                   1033
#define IDC_EDIT_KEYWORD                1033
#define IDC_EDIT_FILE                   1033
#define IDC_EDIT_MOVETEXU               1033
#define IDC_EDIT_BASE_U                 1033
#define IDC_EDIT_DIRECT                 1033
#define IDC_LIST_SKYBOX                 1033
#define IDC_EDIT_POSY                   1034
#define IDC_LIST_LIGHT                  1034
#define IDC_BUTTON_TEXTURE2             1034
#define IDC_EDIT_DAMPING                1034
#define IDC_EDIT_BUTTER_RATE            1034
#define IDC_CHECK_WIREFRAME3            1034
#define IDC_CHECK_REFRECTION            1034
#define IDC_EDIT_MAP1                   1034
#define IDC_EDIT_MOVETEXV               1034
#define IDC_EDIT_BASE_V                 1034
#define IDC_EDIT_POINT                  1034
#define IDC_BUTTON_PEF_SAVE             1034
#define IDC_EDIT_CUR_NAME               1034
#define IDC_EDIT_POSZ                   1035
#define IDC_BUTTON_CREATE               1035
#define IDC_BUTTON_TEXTURE3             1035
#define IDC_EDIT_RATE_X                 1035
#define IDC_EDIT_WIND_CON               1035
#define IDC_EDIT_FLOWER_RATE            1035
#define IDC_EDIT_MAP2                   1035
#define IDC_BUTTON_TEXTURE_SRC          1035
#define IDC_BUTTON_TEXTURE_FILTER       1035
#define IDC_EDIT_SCALETEXU              1035
#define IDC_EDIT_MESH                   1035
#define IDC_EDIT_ROTX                   1036
#define IDC_BUTTON_DELETE               1036
#define IDC_EDIT_RATE_Y                 1036
#define IDC_EDIT_TEXTURE_DETAIL         1036
#define IDC_EDIT_FLOWER_TEXTURE         1036
#define IDC_EDIT_MAP3                   1036
#define IDC_BUTTONCOLOR                 1036
#define IDC_EDIT_TEXTURE_SRC            1036
#define IDC_EDIT_ADD01_U                1036
#define IDC_EDIT_TEX_FILTER             1036
#define IDC_EDIT_SCALETEXV              1036
#define IDC_EDIT_ROTY                   1037
#define IDC_BUTTON_MODIFY               1037
#define IDC_EDIT_RATE_Z                 1037
#define IDC_EDIT_TEXTURE3               1037
#define IDC_BUTTON_TEXTURE6             1037
#define IDC_EDIT_WIND_FORCE             1037
#define IDC_EDIT_MAP4                   1037
#define IDC_EDIT_ADD01_V                1037
#define IDC_BUTTON_EDIT_MODE            1037
#define IDC_BUTTON_DELETE_ALL           1037
#define IDC_BUTTON_LOOK_CUBEMAP         1037
#define IDC_EDIT_ROTZ                   1038
#define IDC_CHECK_LIGHTINGENABLE        1038
#define IDC_BUTTON_TEXTURE4             1038
#define IDC_EDIT_GRAVITY_FORCE          1038
#define IDC_EDIT_DIFFUSE_GREEN          1038
#define IDC_EDIT_MAP5                   1038
#define IDC_EDIT_HIGH                   1038
#define IDC_EDIT_ADD02_U                1038
#define IDC_EDIT_TEX_NIGHT              1038
#define IDC_BUTTON_COLOR_1              1038
#define IDC_BUTTON_MODIFY2              1038
#define IDC_BUTTON_CHANGE_PIE15         1038
#define IDC_EDIT_WAVECYCLE              1039
#define IDC_EDIT_TEXTURE4               1039
#define IDC_EDIT_LAW                    1039
#define IDC_EDIT_ADD02_V                1039
#define IDC_EDIT_TEX_NOW                1039
#define IDC_BUTTON_TONIGHT              1039
#define IDC_BUTTON_COLOR_2              1039
#define IDC_BUTTON_INVERSE_UV           1039
#define IDC_BUTTON_CHANGE_PIE16         1039
#define IDC_BUTTON_REFRESH              1039
#define IDC_BUTTON_CREATE_LOCAL_CUBE_MAP 1039
#define IDC_COMBO_LIGHTTYPE             1040
#define IDC_BUTTON_TEXTURE5             1040
#define IDC_EDIT_MAXX                   1040
#define IDC_EDIT_SIZE01_U               1040
#define IDC_BUTTON_COLOR_3              1040
#define IDC_BUTTON_MESH_MODIFY          1040
#define IDC_BUTTON_CREATE_GLOBAL_CUBE_MAP 1040
#define IDC_EDIT_LPOSY                  1041
#define IDC_EDIT_MINX                   1041
#define IDC_EDIT_SIZE01_V               1041
#define IDC_BUTTON_TODAY                1041
#define IDC_BUTTON_COLOR_4              1041
#define IDC_BUTTON_ADD_HEIGHT           1041
#define IDC_EDIT_LPOSZ                  1042
#define IDC_BUTTON_COLOR_5              1042
#define IDC_EDIT_DIRX                   1043
#define IDC_SCROLLBAR_Z                 1043
#define IDC_EDIT_MAXZ                   1043
#define IDC_BUTTON_COLOR_6              1043
#define IDC_EDIT_DIRY                   1044
#define IDC_SCROLLBAR_X                 1044
#define IDC_EDIT_MINZ                   1044
#define IDC_EDIT_SIZE02_U               1044
#define IDC_BUTTON_COLOR_7              1044
#define IDC_EDIT_DIRZ                   1045
#define IDC_SCROLLBAR_Y                 1045
#define IDC_SCROLLBAR_START             1045
#define IDC_EDIT_SCALE_V3               1045
#define IDC_EDIT_SIZE02_V               1045
#define IDC_EDIT_RAIN_TEXTURE           1045
#define IDC_BUTTON_COLOR_8              1045
#define IDC_EDIT_RANGE                  1046
#define IDC_EDIT_DIRX2                  1046
#define IDC_SCROLLBAR_STARTVAR          1046
#define IDC_BUTTON_RAIN_TEXTURE         1046
#define IDC_BUTTON_COLOR_9              1046
#define IDC_EDIT_DR                     1047
#define IDC_EDIT_DIRY2                  1047
#define IDC_EDIT_MINRANGE               1047
#define IDC_SCROLLBAR_END               1047
#define IDC_BUTTON_COLOR_10             1047
#define IDC_EDIT_LM_DDP                 1047
#define IDC_EDIT_THETA                  1047
#define IDC_EDIT_DG                     1048
#define IDC_EDIT_DIRZ2                  1048
#define IDC_EDIT_START_F                1048
#define IDC_BUTTON_COLOR_CHANGE         1048
#define IDC_EDIT_PHI                    1048
#define IDC_EDIT_DB                     1049
#define IDC_STATIC_START                1049
#define IDC_EDIT_RANGE4                 1049
#define IDC_EDIT_FALL_OFF               1049
#define IDC_EDIT_AR                     1050
#define IDC_EDIT_DR2                    1050
#define IDC_EDIT_STARTVAR_F             1050
#define IDC_BUTTON_COLOR_11             1050
#define IDC_EDIT_AG                     1051
#define IDC_EDIT_DG2                    1051
#define IDC_EDIT_END_F                  1051
#define IDC_BUTTON_COLOR_12             1051
#define IDC_EDIT_AB                     1052
#define IDC_EDIT_DB2                    1052
#define IDC_STATIC_STARTVAR             1052
#define IDC_BUTTON_COLOR_13             1052
#define IDC_EDIT_SR                     1053
#define IDC_EDIT_ALPHAUP                1053
#define IDC_STATIC_END                  1053
#define IDC_BUTTON_COLOR_14             1053
#define IDC_EDIT_SG                     1054
#define IDC_EDIT_ALPHADOWN              1054
#define IDC_EDIT_LENGTH                 1054
#define IDC_STATIC_END4                 1054
#define IDC_EDIT_SB                     1055
#define IDC_EDIT_ALPHAUP2               1055
#define IDC_SCROLLBAR_END4              1055
#define IDC_BUTTON_DIFFUSE              1056
#define IDC_EDIT_ALPHA_B                1056
#define IDC_EDIT_END4_F                 1056
#define IDC_BUTTON_AMBIENT              1057
#define IDC_BUTTON_DIFFUSE2             1057
#define IDC_BUTTON_SPECULAR             1058
#define IDC_EDIT_ALPHADOWN2             1058
#define IDC_EDIT_RADIUS                 1058
#define IDC_EDIT_LPOSX                  1059
#define IDC_EDIT_CLEAR                  1059
#define IDC_BUTTON_REFLECT              1059
#define IDC_BUTTON_DIFFUSE_LSC          1059
#define IDC_CHECK_ENABLELIGHT           1060
#define IDC_SLIDER1                     1060
#define IDC_BUTTON_BUMP                 1060
#define IDC_BUTTON_GLOW                 1061
#define IDC_BUTTON_AMBIENT_LSC          1061
#define IDC_BUTTON_LIGHTADD             1062
#define IDC_EDIT_MID1                   1062
#define IDC_BUTTON_COLOR                1062
#define IDC_BUTTON_MULTITEX             1062
#define IDC_CHECK_ENABLE_PL_NIGHT       1062
#define IDC_LIGHTEDITSEP                1063
#define IDC_BUTTON_COLOR_RANDOM         1063
#define IDC_BUTTON_LIGHTAPPLY           1064
#define IDC_LIGHTEDITSEP2               1064
#define IDC_BUTTON_LIGHTCANCEL          1065
#define IDC_COMBO_EDITTYPE              1065
#define IDC_CHECK_SHADOW                1066
#define IDC_BUTTON_COLOR_INSERT         1066
#define IDC_EDIT_SHADOWRATE             1067
#define IDC_BUTTON_COLOR_STATE          1068
#define IDC_EDIT_CLOUDLOOPADD           1069
#define IDC_EDIT_CLOUDDIS               1070
#define IDC_SLIDER11                    1070
#define IDC_EDIT_CLOUDMULTI             1071
#define IDC_EDIT_SIZE                   1071
#define IDC_EDIT_X                      1071
#define IDC_SLIDER12                    1071
#define IDC_CHECK_CLOUD                 1072
#define IDC_EDIT_Y                      1072
#define IDC_EDIT_START                  1072
#define IDC_CHECK_REFLECT               1073
#define IDC_EDIT_Z                      1073
#define IDC_EDIT_MID2                   1073
#define IDC_EDIT_COLOR_TIME             1073
#define IDC_STATIC_SHADOWLINE           1074
#define IDC_EDIT_END                    1074
#define IDC_EDIT_MOVE_X                 1074
#define IDC_EDIT_SIN_CYCLE_TIME         1074
#define IDC_STATIC_CLOUDLINE            1075
#define IDC_EDIT_MOVE_Y                 1075
#define IDC_EDIT_SIN_POWER              1075
#define IDC_STATIC_REPLINE              1076
#define IDC_STATIC_TEMP                 1076
#define IDC_EDIT_MOVE_Z                 1076
#define IDC_EDIT_SIN_ADD                1076
#define IDC_EDIT_CLOUDLOOP              1077
#define IDC_EDIT_TEMP                   1077
#define IDC_EDIT_TEXTURE_SHADOW         1078
#define IDC_STATIC_TEMP4                1078
#define IDC_EDIT_SPEED                  1079
#define IDC_EDIT_LAYER                  1080
#define IDC_CHECK_DOT3                  1080
#define IDC_EDIT_SNOW_SIZE              1080
#define IDC_EDIT_DARK_SPEED_U           1080
#define IDC_EDIT_SPEED_Y                1080
#define IDC_EDIT_OFFSET                 1081
#define IDC_EDIT_LEAVES_SIZE            1081
#define IDC_EDIT_DARK_SPEED_V           1081
#define IDC_CHECK_BASE                  1082
#define IDC_EDIT_LEAVES_SIZE2           1082
#define IDC_EDIT_FLASH_SPEED            1082
#define IDC_EDIT_SINGLE_REPLACEOBJ      1082
#define IDC_CHECK_MEM                   1083
#define IDC_CHECK_MEMB                  1083
#define IDC_EDIT_SET_FRAME              1083
#define IDC_BUTTON2_CANCEL              1084
#define IDC_EDIT_POWER                  1084
#define IDC_EDIT_LIGHTNAME              1084
#define IDC_BUTTON_FRAME_DEL            1084
#define IDC_BUTTON_TEXTURE_READ         1084
#define IDC_BUTTON_TARGET               1084
#define IDC_CHECK_REFRACT               1084
#define IDC_CHECK_DARK                  1084
#define IDC_CHECK_SRCTEX                1084
#define IDC_STATIC_DOT3                 1085
#define IDC_BUTTON_CYCLONE              1085
#define IDC_BUTTON_REFRECTION           1085
#define IDC_BUTTON_FROM                 1085
#define IDC_CHECK_FLASH                 1085
#define IDC_EDIT_LIGHT_SHAFTS_DECAY     1085
#define IDC_EDIT_TEXTURE_DOT3           1086
#define IDC_STATIC_DETAIL               1086
#define IDC_BUTTON_CYCLONE2             1086
#define IDC_BUTTON_LIGHTING             1086
#define IDC_EDIT_LIGHT_SHAFTS_LAST      1086
#define IDC_CHECK_COLOR                 1087
#define IDC_EDIT_LIGHT_SHAFTS_DIR_X     1087
#define IDC_EDIT_LIGHT_SHAFTS_DIR_Y     1088
#define IDC_EDIT_LIGHT_SHAFTS_DIR_Z     1089
#define IDC_LIST_MESH                   1091
#define IDC_LIST_FRAMES                 1091
#define IDC_LIST_POINT                  1091
#define IDC_LIST_CHECKINTEGRITYLOG      1091
#define IDC_LIST_SEARCH_RESULT          1091
#define IDC_LIST_MAPSOUND               1091
#define IDC_LIST_MOBSET                 1091
#define IDC_LIST_SCHEDULE               1091
#define IDC_LIST_CHECKINTEGRITYLOG2     1092
#define IDC_BUTTON_MESHSTATE            1093
#define IDC_STATIC_MESHLINE             1094
#define IDC_COMBO_MESHSTATE             1095
#define IDC_EDIT_FRAMENAME              1096
#define IDC_STATIC_LISTLINE             1097
#define IDC_EDIT_CENTER_X               1098
#define IDC_BUTTON_MESHSTATE_OK         1098
#define IDC_STATIC_COMCOLL_ENABLE       1098
#define IDC_EDIT_CENTER_Y               1099
#define IDC_EDIT_CENTER_Z               1100
#define IDC_RADIO_UP                    1100
#define IDC_EDIT_DISTANCE               1101
#define IDC_RADIO_MID                   1101
#define IDC_EDIT_WIDTH                  1102
#define IDC_EDIT_BILL_SCALE             1102
#define IDC_RADIO_DOWN                  1102
#define IDC_CHECK_BILLBOARD             1103
#define IDC_STATIC_CENTER               1103
#define IDC_EDIT_TEX_NUM                1104
#define IDC_EDIT_TEX_X                  1104
#define IDC_EDIT_TEX_Y                  1105
#define IDC_CHECK_RAIN                  1105
#define IDC_EDIT_TEX_TIME               1106
#define IDC_EDIT_RATE                   1106
#define IDC_CHECK_RAIN_DOING            1106
#define IDC_EDIT_ALPHA                  1107
#define IDC_CHECK_RANGE_REND            1107
#define IDC_CHECK_REPLACEFRAME          1107
#define IDC_CHECK_RANGE                 1107
#define IDC_EDIT_ALPHAA                 1107
#define IDC_CHECK_TEX                   1107
#define IDC_CHECK_AUTO                  1107
#define IDC_CHECK_ANILOOP               1107
#define IDC_CHECK_LOOP                  1107
#define IDC_CHECK_NAVIVIEW              1107
#define IDC_CHECK_MANUAL                1107
#define IDC_CHECK_REND                  1107
#define IDC_CHECK_TEXROTATE             1107
#define IDC_CHECK_NEARLIGHT             1107
#define IDC_CHECK_LIGHT                 1107
#define IDC_CHECK_DIRECT                1107
#define IDC_EDIT_RATE3                  1108
#define IDC_EDIT_SCALE                  1108
#define IDC_BUTTON_REPLACE              1108
#define IDC_EDIT_SCALEA                 1108
#define IDC_EDIT_ALPHA4                 1108
#define IDC_EDIT_MAX_ALPHA              1108
#define IDC_EDIT_RATE2                  1108
#define IDC_EDIT_COLORPOWER             1108
#define IDC_CHECK_POINT                 1108
#define IDC_EDIT_REPLACE                1109
#define IDC_EDIT_SCALEB                 1109
#define IDC_EDIT_ALPHA2                 1109
#define IDC_EDIT_SCALE2                 1109
#define IDC_EDIT_TEXROTATE              1109
#define IDC_EDIT_R_SCALE_MIN            1109
#define IDC_EDIT_LIGHT_SHAFTS_WEIGHT    1109
#define IDC_STATIC_REPLACELINE          1110
#define IDC_EDIT_ALPHAB                 1110
#define IDC_EDIT_ALPHA3                 1110
#define IDC_EDIT_R_SCALE_MAX            1110
#define IDC_BUTTON_REPLACE_SET          1111
#define IDC_BUTTON_FRAMESEARCH          1112
#define IDC_EDIT_RATEDOWN               1112
#define IDC_EDIT_OBJFILE                1113
#define IDC_EDIT_SKYSCALEA              1113
#define IDC_BUTTON_REPLACE_PROCESSING   1114
#define IDC_EDIT_SKYSCALEB              1114
#define IDC_STATIC_FILELINE             1115
#define IDC_EDIT_SPEEDA                 1116
#define IDC_BUTTON_SINGLE_REPLACEOBJ_APPLY 1116
#define IDC_EDIT_FINDSTR                1117
#define IDC_EDIT_SPEEDB                 1117
#define IDC_EDIT_SCALE_Y                1119
#define IDC_EDIT_NUM                    1119
#define IDC_EDIT_FLOWER_ROW             1119
#define IDC_EDIT_WATER_HEIGHTSPEED      1119
#define IDC_EDIT_REFLECTION_ALPHA       1119
#define IDC_EDIT_CAMERA_NAME            1119
#define IDC_EDIT_BUFFERCOUNT            1119
#define IDC_EDIT_MAPMAINID              1119
#define IDC_EDIT_TOGATEID               1119
#define IDC_EDIT3                       1120
#define IDC_EDIT_12                     1120
#define IDC_STATIC_ANILINE              1120
#define IDC_STATIC_FRAMESTATELINE       1120
#define IDC_EDIT_FLOWER_COL             1120
#define IDC_EDIT_WATER_FORCE_X          1120
#define IDC_EDIT_TEXTURE_X              1120
#define IDC_EDIT_SIN_CYCLE              1120
#define IDC_EDIT_TARGETPOS_NAME         1120
#define IDC_EDIT_MAPSUBID               1120
#define IDC_EDIT_GATEID2                1120
#define IDC_EDIT_DETAIL_TEX             1120
#define IDC_EDIT_MAP                    1120
#define IDC_EDIT4                       1121
#define IDC_EDIT_13                     1121
#define IDC_COMBO1                      1121
#define IDC_COMBO_ANITYPE               1121
#define IDC_COMBO                       1121
#define IDC_EDIT_BUTTER_HEIGHT_UP       1121
#define IDC_COMBO_FILLMODE              1121
#define IDC_EDIT_WATER_TYPE_Y           1121
#define IDC_EDIT_TEXTURE_Z              1121
#define IDC_EDIT_CAMERAPOS_NAME         1121
#define IDC_EDIT_MAPSOUNDNAME           1121
#define IDC_COMBO_ACTION                1121
#define IDC_COMBO_CATEGORY              1121
#define IDC_COMBO_EX_SEARCH             1121
#define IDC_COMBO_SS_SIZE               1121
#define IDC_COMBO_MATRIAL               1121
#define IDC_COMBO_GRID_NUM              1121
#define IDC_COMBO_EFF                   1121
#define IDC_COMBO_TEXEFF                1121
#define IDC_COMBO_SAMPLING              1121
#define IDC_EDIT_LIGHTMAP_X             1121
#define IDC_COMBO_TEXSIZE               1121
#define IDC_EDIT6                       1122
#define IDC_EDIT_14                     1122
#define IDC_RADIO_DOT3                  1122
#define IDC_EDIT_BUTTER_HEIGHT_DOWN     1122
#define IDC_EDIT_WATER_TYPE_Z           1122
#define IDC_EDIT_TEXTURE_X2             1122
#define IDC_EDIT_DIFFUSE_RED            1122
#define IDC_EDIT_ANI_SKEY               1122
#define IDC_COMBO_FILLMODE2             1122
#define IDC_COMBO_TYPE                  1122
#define IDC_COMBO_LIGHTMAP_TYPE         1122
#define IDC_EDIT_LIGHTMAP_Y             1122
#define IDC_EDIT7                       1123
#define IDC_EDIT_21                     1123
#define IDC_RADIO_DETAIL                1123
#define IDC_EDIT_BUTTER_RANGE           1123
#define IDC_COMBO_LIGHTING              1123
#define IDC_EDIT_DIFFUSE_MAX_Y          1123
#define IDC_EDIT_DIFFUSE_MAX_GREEN      1123
#define IDC_EDIT_ANI_SETSKEY            1123
#define IDC_EDIT8                       1124
#define IDC_RADIO_REFL                  1124
#define IDC_RADIO_REFLECT               1124
#define IDC_EDIT_BUTTER_SPEED           1124
#define IDC_EDIT_DIFFUSE_MAX_Z          1124
#define IDC_EDIT_DIFFUSE_MAX_ALPHA      1124
#define IDC_EDIT_ANI_EKEY               1124
#define IDC_EDIT_ROLLOFF                1124
#define IDC_EDIT_23                     1125
#define IDC_EDIT_TEXTURE_CLOUD          1125
#define IDC_EDIT_BUTTER_WIDTH           1125
#define IDC_EDIT_DIFFUSE_MIN_Y          1125
#define IDC_EDIT_DIFFUSE_MIN_GREEN      1125
#define IDC_EDIT_ANI_SETEKEY            1125
#define IDC_EDIT10                      1126
#define IDC_EDIT_24                     1126
#define IDC_COMBO_OBJTYPE               1126
#define IDC_EDIT_VERTEX_NUM             1126
#define IDC_EDIT_BUTTER_HEIGHT          1126
#define IDC_EDIT_DIFFUSE_MIN_Z          1126
#define IDC_EDIT_DIFFUSE_MIN_BLUE       1126
#define IDC_EDIT_DOPPLER                1126
#define IDC_BUTTON_POINTSELECT          1127
#define IDC_EDIT_BUTTER_NUM             1127
#define IDC_COMBO_DESTBLEND             1127
#define IDC_EDIT_DIFFUSE_MAX_BLUE       1127
#define IDC_RADIO_CH                    1128
#define IDC_RADIO_STOP                  1128
#define IDC_EDIT_BUTTER_NUM2            1128
#define IDC_EDIT_FLOWER_NUM             1128
#define IDC_BUTTON_POINTRESET           1128
#define IDC_EDIT_DIFFUSE_MIN_ALPHA      1128
#define IDC_RADIO_PLAY                  1129
#define IDC_EDIT_DIFFUSE_MAX_GREEN2     1129
#define IDC_BUTTON_POINTSELECT2         1130
#define IDC_BUTTON_POINTDELETE          1130
#define IDC_COMBO_COLORARG1             1130
#define IDC_EDIT_DIFFUSE_MAX_ALPHA2     1130
#define IDC_EDIT11                      1131
#define IDC_EDIT_31                     1131
#define IDC_EDIT_DIFFUSE_MIN_GREEN2     1131
#define IDC_BUTTON_PART_DELETE          1131
#define IDC_EDIT12                      1132
#define IDC_EDIT_32                     1132
#define IDC_EDIT_COEFFICIENT            1132
#define IDC_EDIT_DIFFUSE_MIN_BLUE2      1132
#define IDC_EDIT13                      1133
#define IDC_EDIT_33                     1133
#define IDC_BUTTON_GRAVDIR              1133
#define IDC_EDIT_DIFFUSE_MAX_BLUE2      1133
#define IDC_EDIT14                      1134
#define IDC_EDIT_34                     1134
#define IDC_BUTTON_WINDDIR              1134
#define IDC_EDIT_DIFFUSE_MIN_ALPHA2     1134
#define IDC_EDIT_41                     1135
#define IDC_EDIT_TEXTURE_Z2             1135
#define IDC_EDIT_42                     1136
#define IDC_EDIT_43                     1137
#define IDC_EDIT18                      1138
#define IDC_EDIT_44                     1138
#define IDC_RADIO_EDIT                  1139
#define IDC_CHECK2                      1140
#define IDC_CHECK_USE                   1140
#define IDC_COMBO_ALPHABLEND            1140
#define IDC_CHECK_RENDER_RANGE          1140
#define IDC_CHECK_FREESET               1140
#define IDC_CHECK_SNOW                  1140
#define IDC_CHECK_TEX_DRAW              1140
#define IDC_CHECK_SEE                   1140
#define IDC_CHECK_SPEED                 1140
#define IDC_CHECK_CAMCOLL               1140
#define IDC_CHECK_NORMAL                1140
#define IDC_CHECK_DECAL_NORMAL          1140
#define IDC_CHECK_SHADER_3_0            1140
#define IDC_EDIT_LOADSET_LOG            1141
#define IDC_COMBO_ALPHAOP               1141
#define IDC_CHECK_SNOW_DOING            1141
#define IDC_CHECK_COLOR_DRAW            1141
#define IDC_CHECK_SPEED2                1141
#define IDC_CHECK_NIGHTLIGHT            1141
#define IDC_EDIT_BLURADD                1142
#define IDC_CHECK_ADD01                 1142
#define IDC_LIST2                       1143
#define IDC_LIST_EXPORT_LOG             1143
#define IDC_LIST_CAMERA                 1143
#define IDC_LIST_SOUNDSOURCE            1143
#define IDC_CHECK_ADD02                 1143
#define IDC_LIST_DATA                   1143
#define IDC_LIST_TEXDXT                 1143
#define IDC_LIST_SURF                   1143
#define IDC_RADIO_RAIN                  1144
#define IDC_COMBO_COLOROP               1144
#define IDC_RADIO_SNOW                  1145
#define IDC_EDIT_RAINNUM                1146
#define IDC_COMBO_ALPHAARG2             1146
#define IDC_BUTTON_DIFF_F               1147
#define IDC_COMBO_CULLMODE              1147
#define IDC_BUTTON_DIFF_B               1148
#define IDC_COMBO_ZENABLE               1148
#define IDC_EDIT_ALPHA_F                1149
#define IDC_COMBO_SRCBLEND              1149
#define IDC_STATIC_NAVI_NAME            1150
#define IDC_COMBO_COLORARG2             1150
#define IDC_STATIC_CHECKINTEGRITY1      1151
#define IDC_COMBO_ALPHAARG1             1151
#define IDC_STATIC_CHECKINTEGRITYCOUNT  1152
#define IDC_STATIC_CHECKINTEGRITY2      1153
#define IDC_STATIC_CHECKINTEGRITYCOUNT2 1154
#define IDC_STATIC_CHECKINTEGRITY_ISLAND_COUNT 1154
#define IDC_BUTTON_POINT_DELETE         1156
#define IDC_BUTTON_POINT_ADD            1157
#define IDC_BUTTON_POINT_ADD2           1158
#define IDC_BUTTON_CIRCLE               1158
#define IDC_EDIT_BUTTER_TEXTURE         1158
#define IDC_BUTTON_LINE                 1159
#define IDC_EDIT_TEXTURE_BILL           1159
#define IDC_EDIT_TEXTURE_01             1160
#define IDC_EDIT_WIDTH1                 1161
#define IDC_EDIT_TEXTURE_02             1161
#define IDC_EDIT_HEIGHT1                1162
#define IDC_EDIT_WIDTH2                 1163
#define IDC_EDIT_THIS_RATE              1163
#define IDC_EDIT_TEXTURE_MOVE           1163
#define IDC_EDIT_THIS_NUM               1164
#define IDC_EDIT_TEXTURE_ROTATE         1164
#define IDC_BUTTON_TEXTURE_ROTATE       1165
#define IDC_BUTTON_TEXTURE_MOVE         1166
#define IDC_MONTHCALENDAR1              1167
#define IDC_LIST_REPLACE                1167
#define IDC_BUTTON_DIFFUSE_MAX_COLOR    1168
#define IDC_BUTTON_DIFFUSE_MIN_COLOR    1169
#define IDC_BUTTON_WATERTYPE_PROPERTY   1170
#define IDC_BUTTON_DIFFUSE_MAX_COLOR2   1170
#define IDC_BUTTON_HEIGHT               1171
#define IDC_BUTTON_DIFFUSE_MIN_COLOR2   1171
#define IDC_COMBO_WATERTYPE             1172
#define IDC_EDIT_COL                    1173
#define IDC_EDIT_ROW                    1174
#define IDC_EDIT_HEIGHT_MAX             1175
#define IDC_BUTTON_DEL                  1177
#define IDC_BUTTON_REFLECTION           1178
#define IDC_BUTTON_NEW                  1178
#define IDC_BUTTON_DIRECTION            1179
#define IDC_LIST_COLOR                  1184
#define IDC_RADIO_MAX                   1186
#define IDC_RADIO_MIN                   1187
#define IDC_BUTTON_MAP0                 1190
#define IDC_BUTTON_MAP2                 1191
#define IDC_BUTTON_MAP1                 1192
#define IDC_BUTTON_MAP4                 1193
#define IDC_BUTTON_MAP5                 1194
#define IDC_BUTTON_MAP3                 1195
#define IDC_SPIN1                       1196
#define IDC_SPIN_ALPHA                  1196
#define IDC_BUTTON_SEARCH               1197
#define IDC_STATIC_ANI_LINE             1198
#define IDC_BUTTON_ADD                  1199
#define IDC_STATIC_PAGELINE             1200
#define IDC_RADIO_FREECAMERA            1201
#define IDC_BUTTON_EFFAPPLY             1201
#define IDC_RADIO_TARGETCAMERA          1202
#define IDC_BUTTON_TEST                 1203
#define IDC_STATIC_CARNAME              1204
#define IDC_STATIC_S                    1205
#define IDC_STATIC_E                    1206
#define IDC_BUTTON_GETSOUND             1207
#define IDC_BUTTON1                     1208
#define IDC_BUTTON2                     1209
#define IDC_BUTTON3                     1210
#define IDC_CHECK_ENABLESOUND           1211
#define IDC_BUTTON_SAVEFILE             1211
#define IDC_BUTTON4                     1212
#define IDC_CHECK4                      1213
#define IDC_CHECK_ENALBE_NEW_SOUND      1213
#define IDC_BUTTON5                     1213
#define IDC_CHECK_IN                    1213
#define IDC_EDIT_MAXRANGE               1214
#define IDC_EDIT_LOOPTIME               1215
#define IDC_BUTTON_LOADFILE             1215
#define IDC_EDIT_VELOCITY_X             1216
#define IDC_BUTTON_SCHEDULE             1217
#define IDC_EDIT_MAXRANGE2              1217
#define IDC_EDIT_VOLUME                 1217
#define IDC_EDIT_MOBNAME                1218
#define IDC_BUTTON_SKIN                 1220
#define IDC_EDIT_SKIN                   1221
#define IDC_EDIT_REGEN                  1222
#define IDC_BUTTON_REGEN                1223
#define IDC_BUTTON_FIND                 1225
#define IDC_BUTTON_                     1226
#define IDC_BUTTON_CUR_FIND             1226
#define IDC_BUTTON_PREVIEW_RIGHT        1226
#define IDC_RADIO_FLAT                  1227
#define IDC_BUTTON_PREVIEW_RIGHT2       1227
#define IDC_RADIO_SLANT                 1228
#define IDC_EDIT_SEC                    1229
#define IDC_LIST_SKINOBJ                1230
#define IDC_BUTTON_SKINOBJAPPLY         1231
#define IDC_LIST_GATE                   1232
#define IDC_EDIT_MID                    1233
#define IDC_EDIT_SID                    1234
#define IDC_EDIT_GEN_DX                 1235
#define IDC_EDIT_GEN_DY                 1236
#define IDC_STATIC_GATEID               1237
#define IDC_STATIC_CREATEPOS            1238
#define IDC_STATIC_MAPID                1239
#define IDC_STATIC_GATEID2              1240
#define IDC_CHECK_OUT                   1242
#define IDC_STATIC_GATEFLAGS            1243
#define IDC_BUTTON_CLONE                1244
#define IDC_RADIO_BUMP                  1245
#define IDC_RADIO_NORMAL                1246
#define IDC_CHECK_PLAYMODE              1247
#define IDC_EDIT_BUMPALPHA              1248
#define IDC_EDIT_REFLECT_ALPHA          1248
#define IDC_RADIO_ALL                   1249
#define IDC_EDIT_REFLECT_POWER          1249
#define IDC_RADIO_ALPHA                 1250
#define IDC_STATIC_SELECT               1251
#define IDC_STATIC_TEXTURE              1252
#define IDC_BUTTON_FILE                 1253
#define IDC_STATIC_REFLECT_TEX          1253
#define IDC_STATIC_TEXTURE2             1253
#define IDC_BUTTON_PLAY                 1254
#define IDC_BUTTON_PIECE                1254
#define IDC_BUTTON_STOP                 1255
#define IDC_BUTTON_CLEAR                1256
#define IDC_BUTTON_FILE2                1257
#define IDC_BUTTON_VOLUME               1257
#define IDC_BUTTON_LIGHT                1257
#define IDC_STATIC_TEXTURE_SRC          1259
#define IDC_BUTTON_TEXTURE_ADD01        1260
#define IDC_BUTTON_TEXTURE_ADD02        1261
#define IDC_BUTTON_SEQUENCE01           1262
#define IDC_CHECK_SEQUENCE01            1263
#define IDC_BUTTON_FRAME_DOCUMENT       1263
#define IDC_BUTTON_DIRECTION_LIGHT_DOCUMENT 1263
#define IDC_CHECK_SEQUENCE02            1264
#define IDC_BUTTON_MAKESS               1266
#define IDC_BUTTON_TESTSS               1267
#define IDC_CHECK_USESS                 1268
#define IDC_EDIT_TEX_DAYTIME            1269
#define IDC_BUTTON_TEX_NIGHT            1270
#define IDC_BUTTON_TEX_DAYTIME          1271
#define IDC_BUTTON_CREATE_UV            1272
#define IDC_BUTTON_TEX_NIGHT2           1273
#define IDC_BUTTON_TEX_NOW              1273
#define IDC_PROGRESS1                   1273
#define IDC_PROGRESS_COLLISION          1273
#define IDC_STATIC_PERCENT              1274
#define IDC_EDIT_IDC_EDIT_FINDSTR_EX    1275
#define IDC_EDIT_FINDSTR_EX             1275
#define IDC_EDIT_SCALE_U                1276
#define IDC_EDIT_SCALE_V                1277
#define IDC_CHECK_NIGHTANDDAY           1278
#define IDC_EDIT_DARK_SCALE_U           1278
#define IDC_EDIT_TIME_VBR               1279
#define IDC_EDIT_DARK_SCALE_V           1279
#define IDC_CHECK_DAYPOINTOFF           1280
#define IDC_EDIT_FLASH_SCALE_U          1280
#define IDC_EDIT_TIME_VBR2              1281
#define IDC_EDIT_FLASH_SCALE_V          1281
#define IDC_BUTTON_TIMESET              1282
#define IDC_EDIT_REFLECT_TEX            1283
#define IDC_BUTTON_REFLECT_TEX          1284
#define IDC_CHECK_LEAVES                1287
#define IDC_CHECK_LEAVES_DOING          1288
#define IDC_CHECK_ACTIVE                1289
#define IDC_EDIT_LEAVES_SPEED           1291
#define IDC_BUTTON_DARK_DIFFUSE         1293
#define IDC_EDIT_DARK_TEX               1294
#define IDC_BUTTON_DARK_TEX             1295
#define IDC_BUTTON_FLASH_TEX            1296
#define IDC_CHECK_DAY                   1296
#define IDC_EDIT_FLASH_TEX              1297
#define IDC_CHECK_DAY2                  1297
#define IDC_CHECK_NIGHT                 1297
#define IDC_CHECK_SPORE                 1297
#define IDC_BUTTON_FLASH_DIFFUSE        1298
#define IDC_CHECK_FIREFLY               1298
#define IDC_EDIT_DENSITY                1298
#define IDC_CHECK_ENABLE                1299
#define IDC_BUTTON_DIFFUSE_NIGHT        1301
#define IDC_RADIO_TRANS_LIGHT           1302
#define IDC_RADIO_OCEANE                1303
#define IDC_CHECK_SKY                   1304
#define IDC_CHECK_DAY_NIGHT             1305
#define IDC_CHECK_SUN_MOON              1306
#define IDC_BUTTON_DIFFUSE_DAY          1308
#define IDC_CHECK_SKY_CLOUD             1309
#define IDC_CHECK_RANGE_SETTING2        1311
#define IDC_CHECK_RANGE_SETTING         1311
#define IDC_CHECK1                      1311
#define IDC_CHECK_REFLECT_NEW           1311
#define IDC_CHECK_SELECT_MATERIAL       1311
#define IDC_CHECK_SAME_HEIGHT           1311
#define IDC_CHECK_LENGTH                1311
#define IDC_CHECK_TILE                  1311
#define IDC_CHECK_RANDOM                1311
#define IDC_CHECK_NEWUV                 1311
#define IDC_CHECK_EACH_RENDER           1311
#define IDC_CHECK_DSP_NAME              1311
#define IDC_CHECK_PICK_POS              1311
#define IDC_SNOW_CHECK                  1311
#define IDC_CHECK_NEWEFFECT             1311
#define IDC_CHECK_LIGHTMAP              1311
#define IDC_CHECK_ALPHA_BLEND           1311
#define IDC_CHECK_MY_ROOM_TEST          1311
#define IDC_CHECK_RANDOMROTATE          1311
#define IDC_CHECK_DMSLM                 1311
#define IDC_CHECK_FIELD                 1311
#define IDC_CHECK_ENABLE_LIGHTMAP       1311
#define IDC_CHECK_CAST_SHADOW           1311
#define IDC_CHECK_NEW_XFILE             1311
#define IDC_BUTTON_GETMATERIAL_D        1312
#define IDC_CHECK_RANDOM_SPEED          1312
#define IDC_RAIN_CHECK                  1312
#define IDC_CHECK_UNBAKED_LIGHTMAP      1312
#define IDC_CHECK_DONT_LM_S_CAST        1312
#define IDC_CHECK_RENDER_NAME           1312
#define IDC_CHECK_BLUR_OFF              1312
#define IDC_CHECK_LIGHTMAP2             1312
#define IDC_CHECK_RAN_1_0_EXPORT        1312
#define IDC_CHECK_PIECE                 1312
#define IDC_CHECK_SLOPE                 1312
#define IDC_BUTTON_GETMATERIAL_F        1313
#define IDC_CHECK_MODULATE2X            1313
#define IDC_RAIN_CHECK2                 1313
#define IDC_LEAVE_CHECK                 1313
#define IDC_CHECK_NO_DXT1               1313
#define IDC_CHECK_RAN_1_0               1313
#define IDC_CHECK_FIELD3                1313
#define IDC_CHECK_CHAR                  1313
#define IDC_LIST_MATERIALS              1314
#define IDC_CHECK_RADIOSITY             1314
#define IDC_CHECK_CAMERA_COLLISION      1314
#define IDC_CHECK_ANI_START_TIME_ZERO   1314
#define IDC_CHECK_ANI_PLAY_ONCE         1314
#define IDC_BUTTON_CHANGE               1315
#define IDC_CHECK_CUBEMAP               1315
#define IDC_CHECK_LIGHTMAP3             1315
#define IDC_CHECK_ONE_CELL              1315
#define IDC_BUTTON_MATERIAL_UP          1316
#define IDC_CHECK_GLOSSINESS            1316
#define IDC_BUTTON_MATERIAL_DOWN        1317
#define IDC_CHECK_SPOTSPEC_MASK         1317
#define IDC_CHECK_CUBEMAP_SPECMAP_MASK  1317
#define IDC_BUTTON_TILE_DRAW            1318
#define IDC_CHECK_GLOSSINESS2           1318
#define IDC_CHECK_NORMALMAP             1318
#define IDC_BUTTON_TILE_DELETE          1319
#define IDC_EDIT_HEIGHT_VALUE           1323
#define IDC_BUTTON_GROUND               1324
#define IDC_BUTTON_UNEVEN               1325
#define IDC_BUTTON_UP                   1326
#define IDC_BUTTON_DOWN                 1327
#define IDC_BUTTON_RELATIVE_HEIGHT      1328
#define IDC_BUTTON_ABSOLUTE_HEIGHT      1329
#define IDC_EDIT_DETAIL_SCALE           1334
#define IDC_BUTTON_INSERT               1337
#define IDC_BUTTON_FILE_SAVE            1338
#define IDC_BUTTON_INSERT_SPT           1338
#define IDC_BUTTON_FILE_LOAD            1339
#define IDC_EDIT_FILE_TILES             1341
#define IDC_RADIO_X                     1342
#define IDC_RADIO_Y                     1343
#define IDC_RADIO_Z                     1344
#define IDC_EDIT_AXIS_VALUE             1345
#define IDC_EDIT_BLUSH_SCALE            1346
#define IDC_BUTTON_DETAIL_TEX           1347
#define IDC_BUTTON_QURD                 1348
#define IDC_EDIT1                       1350
#define IDC_BUTTON_GAME                 1351
#define IDC_EDIT_FLOWTEX                1351
#define IDC_EDIT_COLOR_POWER_NIGHT      1351
#define IDC_EDIT_POS_Y                  1351
#define IDC_EDIT_PLANE_HEIGHT           1351
#define IDC_EDIT_LM_TEXTURE_SIZE_Y      1351
#define IDC_EDIT_MIN_Z                  1351
#define IDC_EDIT_POS_Z                  1352
#define IDC_EDIT_SURF_SPEED             1352
#define IDC_EDIT_MAX_X                  1352
#define IDC_EDIT_MAX_Z                  1353
#define IDC_LIST_EFF                    1355
#define IDC_EDIT_SURF_ACCELERATION      1355
#define IDC_BUTTON_XFILE_LOAD           1356
#define IDC_EDIT_SURF_SLEEP_TIME        1356
#define IDC_BUTTON_EFF_DELETE           1357
#define IDC_EDIT_ALPHA_ADD              1357
#define IDC_BUTTON_EFF_STATE            1358
#define IDC_EDIT_ALPHA_SUB_TIME         1358
#define IDC_EDIT2                       1359
#define IDC_BUTTON_EFF_INSERT           1359
#define IDC_BUTTON_SINGLE_EFF           1360
#define IDC_EDIT_ALPHA_SUB              1360
#define IDC_BUTTON_FRAME_RENDER         1361
#define IDC_EDIT_ADD_HEIGHT             1361
#define IDC_BUTTON_STATIC_RENDER        1362
#define IDC_TREE_PIECE                  1363
#define IDC_BUTTON_TEXTURE_EFF          1363
#define IDC_EDIT_SIDE_LINE_INTERVAL     1363
#define IDC_EDIT_ROTATE_X               1364
#define IDC_BUTTON_TEXTURE_EFF2         1364
#define IDC_BUTTON_MORPH                1364
#define IDC_EDIT_ROTATE_Y               1365
#define IDC_BUTTON_XFILE_LOAD_LIGHTMAP  1365
#define IDC_BUTTON_MATERIAL_SETTING     1365
#define IDC_EDIT_ROTATE_Z               1366
#define IDC_BUTTON_MESH_STATE           1366
#define IDC_BUTTON_XFILE_DELETE_LIGHTMAP 1366
#define IDC_BUTTON_COLOR_DELETE         1369
#define IDC_BUTTON_RESET_RADIUS         1369
#define IDC_BUTTON_TEXTURE_SETTING      1370
#define IDC_BUTTON_COLOR_TIME_APPLY     1370
#define IDC_BUTTON_TEXEFF               1371
#define IDC_BUTTON_SIN_APPLY            1371
#define IDC_BUTTON_LIGHTMAP             1372
#define IDC_BUTTON_PIECE_TEX_VM_VIEW    1372
#define IDC_BUTTON_SLOPE                1372
#define IDC_BUTTON_SNAP_BASE            1373
#define IDC_BUTTON_MINIMAP              1373
#define IDC_BUTTON_MAKE_MINIMAP         1373
#define IDC_RADIO_HARD_ALPHA            1374
#define IDC_BUTTON_SNAP_MOVE            1374
#define IDC_BUTTON_OCCLUSION_CULLING    1374
#define IDC_BUTTON_VIEW_SIMULATION_POSITION 1374
#define IDC_RADIO_SOFT_ALPHA            1375
#define IDC_BUTTON_VIEW_OCTREE_BOX      1375
#define IDC_BUTTON_CUR_POS1             1375
#define IDC_BUTTON_CUBE_MAP             1375
#define IDC_RADIO_OPACITY               1376
#define IDC_BUTTON_CUR_POS2             1376
#define IDC_EDIT_TEXT                   1377
#define IDC_BUTTON_RESET_FADE           1377
#define IDC_RADIO_SOFT_ALPHA2           1378
#define IDC_RADIO_SOFT_ALPHA3           1379
#define IDC_EDIT_SPECULAR               1380
#define IDC_RADIO_SPECULAR              1381
#define IDC_RADIO_DEFAULT               1382
#define IDC_EDIT_CUBE                   1383
#define IDC_RADIO_GLOW                  1384
#define IDC_LIST_TEXVIEW                1385
#define IDC_RADIO_BASE                  1386
#define IDC_BUTTON_PIE_LOAD             1386
#define IDC_RADIO_BLEND_BASE            1386
#define IDC_BUTTON_PIE_SAVE             1387
#define IDC_EDIT_PED_NAME               1388
#define IDC_EDIT_PEF_NAME               1388
#define IDC_RADIO_FRAME                 1391
#define IDC_RADIO_POINT                 1392
#define IDC_EDIT_SRCTEX                 1394
#define IDC_BUTTON_SRCTEX               1395
#define IDC_BUTTON_FLOWTEX              1396
#define IDC_EDIT_VM_FILE                1396
#define IDC_STATIC_FLOWTEX              1397
#define IDC_EDIT_SRC_TEXTURE_0          1397
#define IDC_STATIC_SPEED                1398
#define IDC_EDIT_DEST_TEXTURE_0         1398
#define IDC_STATIC_ALPHA                1399
#define IDC_STATIC_SPEED2               1399
#define IDC_EDIT_SRC_TEXTURE_1          1399
#define IDC_LIST_TEXEFF                 1400
#define IDC_EDIT_DEST_TEXTURE_1         1400
#define IDC_BUTTON_STATE                1401
#define IDC_EDIT_SRC_TEXTURE_2          1401
#define IDC_EDIT_SPEED_X                1402
#define IDC_EDIT_DEST_TEXTURE_2         1402
#define IDC_BUTTON_STATE2               1402
#define IDC_BUTTON_VMFX_RELOAD          1402
#define IDC_EDIT_CLICK_TEX              1403
#define IDC_EDIT_SRC_TEXTURE_3          1403
#define IDC_LIST_LIGHTEX                1404
#define IDC_EDIT_DEST_TEXTURE_3         1404
#define IDC_EDIT_PARTCOUNT              1405
#define IDC_EDIT_SRC_TEXTURE_4          1405
#define IDC_EDIT_DISAPPEAR1             1406
#define IDC_SLIDER_PRIORITY             1406
#define IDC_EDIT_DEST_TEXTURE_4         1406
#define IDC_EDIT_DISAPPEAR2             1407
#define IDC_STATIC_PRIORITY             1407
#define IDC_EDIT_SRC_TEXTURE_5          1407
#define IDC_BUTTON_ROTATE_L90           1407
#define IDC_EDIT_FALLSPEED1             1408
#define IDC_LIST_CAMCOLL_ENABLE         1408
#define IDC_EDIT_DEST_TEXTURE_5         1408
#define IDC_BUTTON_ROTATE_L15           1408
#define IDC_EDIT_FALLSPEED2             1409
#define IDC_LIST_CAMCOLL_DISABLE        1409
#define IDC_EDIT_SRC_TEXTURE_6          1409
#define IDC_BUTTON_ROTATE_R15           1409
#define IDC_EDIT_RAIN_PARTCOUNT         1410
#define IDC_STATIC_CAMCOLL_DISABLE      1410
#define IDC_EDIT_DEST_TEXTURE_6         1410
#define IDC_BUTTON_ROTATE_R90           1410
#define IDC_EDIT_RAIN_DISAPPEAR1        1411
#define IDC_BUTTON_CAMCOLL_UP           1411
#define IDC_BUTTON_ROTATE_RANDOM        1411
#define IDC_EDIT_PARAMETER_X            1411
#define IDC_EDIT_RAIN_DISAPPEAR2        1412
#define IDC_CAMCOLL_BUTTON_DOWN         1412
#define IDC_BUTTON_CAMCOLL_DOWN         1412
#define IDC_BUTTON_HEIGHT_UP10          1412
#define IDC_LIST_PIECE                  1412
#define IDC_EDIT_PARAMETER_X2           1412
#define IDC_EDIT_RAIN_FALLSPEED1        1413
#define IDC_BUTTON_VM_FILE              1413
#define IDC_BUTTON_HEIGHT_UP1           1413
#define IDC_EDIT_RAIN_FALLSPEED2        1414
#define IDC_BUTTON_OPEN_TEXTURE_0       1414
#define IDC_BUTTON_HEIGHT_DOWN1         1414
#define IDC_EDIT_LEAVES_PARTCOUNT       1415
#define IDC_BUTTON_RESET_TEXTURE_0      1415
#define IDC_BUTTON_HEIGHT_DOWN10        1415
#define IDC_EDIT_LEAVES_DISAPPEAR1      1416
#define IDC_BUTTON_OPEN_TEXTURE_1       1416
#define IDC_BUTTON_HEIGHT_PICK          1416
#define IDC_EDIT_LEAVES_DISAPPEAR2      1417
#define IDC_BUTTON_RESET_TEXTURE_1      1417
#define IDC_BUTTON_ROTATE_INIT          1417
#define IDC_EDIT_LEAVES_FALLSPEED1      1418
#define IDC_BUTTON_OPEN_TEXTURE_2       1418
#define IDC_BUTTON_HEIGHT_RESET_ALL     1418
#define IDC_EDIT_RAIN_FALLSPEED4        1419
#define IDC_EDIT_LEAVES_FALLSPEED2      1419
#define IDC_BUTTON_RESET_TEXTURE_2      1419
#define IDC_BUTTON_TIME_APPLY           1419
#define IDC_BUTTON_OPEN_TEXTURE_3       1420
#define IDC_BUTTON_FLOAT_ZERO           1420
#define IDC_BUTTON_RESET_TEXTURE_3      1421
#define IDC_BUTTON_OPEN_TEXTURE_4       1422
#define IDC_BUTTON_ROTATE_L5            1422
#define IDC_BUTTON_RESET_TEXTURE_4      1423
#define IDC_BUTTON_LIGHT_SHAFTS_APPLY   1423
#define IDC_BUTTON_ROTATE_R5            1423
#define IDC_BUTTON_OPEN_TEXTURE_5       1424
#define IDC_BUTTON_RESET_TEXTURE_5      1425
#define IDC_BUTTON_PREVIEW_LEFT         1425
#define IDC_BUTTON_OPEN_TEXTURE_6       1426
#define IDC_EDIT_ANGLE                  1426
#define IDC_BUTTON_RESET_TEXTURE_6      1427
#define IDC_BUTTON_SETANGLE             1427
#define IDC_STATIC_0                    1428
#define IDC_BUTTON_PREVIEW_LEFT2        1428
#define IDC_STATIC_1                    1429
#define IDC_STATIC_2                    1430
#define IDC_STATIC_3                    1431
#define IDC_STATIC_4                    1432
#define IDC_STATIC_5                    1433
#define IDC_STATIC_6                    1434
#define IDC_SLIDER_ATT0                 1435
#define IDC_EDIT_PARAMETER_NAME         1435
#define IDC_SLIDER_ATT1                 1436
#define IDC_EDIT_PARAMETER_Y            1436
#define IDC_SLIDER_ATT2                 1437
#define IDC_EDIT_PARAMETER_Y2           1437
#define IDC_EDIT_PARAMETER_Z            1438
#define IDC_STATIC_ATT                  1439
#define IDC_EDIT_PARAMETER_Z2           1439
#define IDC_STATIC_ENABLE_PL            1441
#define IDC_EDIT_PL_END_LINE            1442
#define IDC_STATIC_END_LINE             1443
#define IDC_EDIT_COLOR_POWER_DAY        1444
#define IDC_EDIT_PL_END_LINE_LIMIT      1444
#define IDC_EDIT_POS_X                  1445
#define IDC_STATIC_END_LINE3            1445
#define IDC_LIST_PARAMETER              1446
#define IDC_EDIT_PIECE_SCALE            1446
#define IDC_EDIT_OCTREEBOX_LENGTH       1446
#define IDC_STATIC_END_LINE2            1446
#define IDC_BUTTON_SCALE_APPLY          1447
#define IDC_EDIT_OVER_LIGHTING          1447
#define IDC_LIST_TEX_PIECE_VM           1448
#define IDC_STATIC_END_LINE4            1448
#define IDC_EDIT_LM_TEXTURE_SIZE_X      1449
#define IDC_LIST1                       1450
#define IDC_PROGRESS                    1451
#define IDC_EDIT_LIGHTMAP_UV_INDEX      1452
#define IDC_EDIT_SIMULATION_DETAIL_LENGTH 1453
#define IDC_BUTTON_BAKE                 1454
#define IDC_STATIC_TEXT                 1455
#define IDC_BUTTON_BAKE_THIS_PLACE      1455
#define IDC_STATIC_                     1456
#define IDC_RADIO_DECAL_ALPHABLEND      1456
#define IDC_STATIC_TIME                 1457
#define IDC_RADIO_DECAL_MULTIPLY        1457
#define IDC_STATIC_QUERY_DELAY          1458
#define IDC_RADIO_DECAL_ADD             1458
#define IDC_STATIC_TIME_E               1459
#define IDC_RADIO_DECAL_NULL            1459
#define IDC_EDIT_TEXTURE_SIZE           1459
#define IDC_STATIC_7                    1460
#define IDC_RADIO_DECAL_ORDER_1         1460
#define IDC_EDIT_TEXTURE_SIZE2          1460
#define IDC_EDIT_GLOBAL_CUBEMAP_SIZE    1460
#define IDC_STATIC_TIME_R               1461
#define IDC_RADIO_DECAL_ORDER_2         1461
#define IDC_RADIO_DECAL_ORDER_3         1462
#define IDC_RADIO_DECAL_ALPHATEST       1463
#define IDC_RADIO_AMBIENT_CUBE          1464
#define IDC_RADIO_VOXEL_COLOR           1465
#define IDC_RADIO_LIGHTMAP              1466
#define IDC_EDIT_CUBEMAP_VALUE          1467
#define IDC_BUTTON_CUBEMAP              1468
#define IDC_BUTTON_CUBEMAP_SET          1468
#define IDC_EDIT_SPOTSPEC_POWER         1468
#define IDC_STATIC_FADE                 1469
#define IDC_EDIT_SPOTSPEC_MULTI         1469
#define IDC_STATIC_VISIBLE_RADIUS       1470
#define IDC_STATIC_INVISIBLE_RADIUS     1471
#define IDC_CHECK_DIRECTION_LIGHT       1472
#define IDC_BUTTON_APPLY                2011
#define IDC_BUTTON_CHECKGROUND          2012
#define IDC_BUTTON_APPLY3               2013
#define IDC_BUTTON_TEXTEXPORT           2013
#define IDC_RADIO_PUSH                  5000
#define IDC_RADIO_DONTMOVE              5001
#define IDC_EDIT_MIN_X                  5021
#define IDC_STATIC_TEX_SIZE             5023
#define IDC_RADIO_LEFT                  5028
#define IDC_RADIO_RIGHT                 5029
#define IDC_EDIT_PLANE_WIDTH            5030
#define IDC_EDIT_POINT_INTERVAL         5031
#define IDC_RADIO_BLEND_ADD             5084
#define IDC_RADIO_BLEND_ALPHA           5085
#define IDC_RADIO_BLEND_LIGHT_SHAFTS    5086
#define IDC_EDIT_LIGHT_SHAFTS_DIR_SET   5093
#define IDC_TREE_ASSET                  5094
#define IDC_EDIT_PREFAB_SCALE           5108
#define IDC_BUTTON_PREFAB_SCALE         5109
#define ID_VIEW_FRAME                   10001
#define ID_VIEW_OCTREE                  10002
#define ID_VIEW_NAVIMESH                10003
#define ID_VIEW_PIECE                   10004
#define ID_VIEW_CURNONE                 20001
#define ID_VIEW_SELECT                  20002
#define ID_VIEW_MOVE                    20003
#define ID_VIEW_ROTATE                  20004
#define ID_VIEW_SCALE                   20005
#define ID_VIEW_SELECTPOINT             20006
#define ID_CHAR_MOVE                    20007
#define ID_VIEW_CHARMOVETOPOINT         20008
#define IDC_EDIT9                       21125
#define IDC_EDIT_11                     24589
#define ID_FRAME                        32772
#define ID_VIEW_BOXLINE                 32773
#define ID_VIEW_WIREFRAME               32774
#define ID_VIEW_MOVETO_ANIBOX           32775
#define ID_MENUITEM_EXPORT              32780
#define ID_MENUITEM_EXPORTSAVE          32781
#define ID_MENUITEM_EXPORTLOAD          32782
#define ID_MENUITEM_EXPORTINFOVIEW      32783
#define ID_MENUITEM_EXPORT_PIECE        32797
#define ID_BUTTON_COLLISIONMAP          32800
#define ID_VIEW_TILE_DRAW               32801
#define ID_VIEW_TILE_GET                32802
#define ID_VIEW_TILE_DELETE             32803
#define ID_32806                        32806
#define ID_MENUITEM_VRML_LOAD           32807
#define ID_MENUITEM_VRML_SAVE           32808
#define ID_COMBO_MATRIX                 32809
#define ID_BUTTON_ALL_90                32810
#define ID_VIEW_ALL_90                  32810
#define ID_VIEW_FPS_VISIBLE             32813
#define ID_VIEW_PIECECHECK              32815
#define ID_GAME_TEST                    32818
#define ID_MAP_FARAWAY                  32821
#define ID_FRAME_SELECTCAMCOLLMESH      32827
#define ID_32828                        32828
#define ID_CHECK_MIPMAP                 32829
#define ID_32830                        32830
#define ID_32831                        32831
#define ID_32832                        32832
#define ID_32833                        32833
#define ID_VIEW_RENDER_TEXTURE_LIGHTMAP 32834
#define ID_VIEW_RENDER_LIGHTMAP         32835
#define ID_VIEW_RENDER_LIGHTMAP_CHECKER 32836
#define ID_CHECK_RENDER_TEXTURE_LIGHTMAP 32837
#define ID_CHECK_RENDER_LIGHTMAP        32838
#define ID_CHECK_RENDER_LIGHTMAP_POINT  32839
#define ID_CHECK_RENDER_LIGHTMAP_CHECKER 32840
#define ID_32840                        32841
#define ID_32842                        32842
#define ID_LIGHTMAP_DETAIL              32843
#define ID_32844                        32844
#define ID_EXPORT2XFILE                 32845
#define ID_32846                        32846
#define ID_LOADING_LIGHTMAP_CHECKER_TEXTURE 32847
#define ID_TOOLBAR_RELOAD               32848
#define ID_Menu                         32849
#define ID_ARCHIVE                      32850
#define ID_ASSETVIEW                    32851
#define ID_TOOLBAR_SPEC_CAM             32853
#define ID_32855                        32855
#define ID_VIEW_CONSOLE_VISIBLE         32856
#define ID_32857                        32857
#define ID_VIEW_CHAR_CHANGE             32858
#define ID_PSF_SAVE                     32860
#define ID_ENTER                        32861
#define ID_PSF_SAVEAS                   32862
#define ID_32864                        32864
#define ID_VIEW_FOG_OFF                 32865
#define ID_32866                        32866
#define ID_LOD_OFF                      32867
#define ID_32868                        32868
#define ID_32869                        32869
#define ID_MENUITEM_PREFAB_LOAD         32870
#define ID_MENUITEM_PREFAB_SAVE         32871
#define ID_VIEW_PREFAB                  32872
#define ID_32873                        32873
#define ID_RADIOSITY_SETTING_INFO       32874
#define ID_32875                        32875
#define ID_32876                        32876
#define ID_32877                        32877
#define ID_CHECK_WATER_RT_REFLECTION    32878
#define ID_CHECK_WATER_CUBEMAP          32879
#define ID_CHECK_WATER_DIFFUSE_TEXTURE  32880
#define ID_32881                        32881
#define ID_CHANGE_TEMP_CUBEMAP          32882
#define ID_32883                        32883
#define ID_32884                        32884
#define ID_RENDER_PS_3_0_HIGH           32885
#define ID_RENDER_PS_3_0                32886
#define ID_RENDER_PS_2_0                32887
#define ID_RENDER_PS_1_1                32888
#define ID_RENDER_FIXED                 32889
#define ID_TOOLBAR_SMALL_REFRESH        32890
#define ID_RENDER_CHAR_SS               32891
#define ID_RENDER_CHAR_DEFAULT          32892
#define ID_32891                        32893
#define ID_32893                        32894
#define ID_32895                        32895
#define ID_32897                        32897
#define ID_EXPORT2NAVIGATIONMESH        32898
#define ID_32899                        32899
#define ID_INSTANCING_OFF               32900
#define IDC_EDIT_22                     41124
#define ID_ASSET_VIEW                   51234

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        263
#define _APS_NEXT_COMMAND_VALUE         32901
#define _APS_NEXT_CONTROL_VALUE         1473
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
