#ifndef _RAN_PARAM_DEFINE_H_
#define _RAN_PARAM_DEFINE_H_

#pragma once

// enum EMSERVICE_TYPE
// {
//     EMSERVICE_DEFAULT		= 0,
//     EMSERVICE_KOREA			= 1,
//     EMSERVICE_FEYA			= 2,
//     EMSERVICE_MALAYSIA_CN	= 3,
//     EMSERVICE_MALAYSIA_EN	= 4,
//     EMSERVICE_JAPAN			= 5,
//     EMSERVICE_THAILAND		= 6,
//     EMSERVICE_CHINA			= 7,
//     EMSERVICE_INDONESIA		= 8,
//     EMSERVICE_PHILIPPINES	= 9,
//     EMSERVICE_VIETNAM		= 10,
//     EMSERVICE_GLOBAL		= 11,	//	글로벌 서비스
// };

// SHOTCUT KEY
enum
{
    SHOTCUT_INVEN = 0,
    SHOTCUT_CHAR,
    SHOTCUT_SKILL,
    SHOTCUT_PARTY,
    SHOTCUT_QUEST,
    SHOTCUT_CLUB,
    SHOTCUT_FRIEND,
    SHOTCUT_MAP,
    SHOTCUT_ITEMBANK,
    SHOTCUT_RUN,
    SHOTCUT_HELP,
    SHOTCUT_PET,
    SHOTCUT_ATTACKMODE,
    SHOTCUT_PKMODE,
    SHOTCUT_POINT_SHOP,
    SHOTCUT_CHATMACRO,
    SHOTCUT_QBOX,
    SHOTCUT_SNS,
};

// 주변 캐릭터 Detail 타입
enum EM_AROUND_DETAILTYPE
{
    EM_AROUND_ORIG = 0, 
    EM_AROUND_BASE,
    EM_AROUND_BOARD,

    EM_AROUND_ONLYNAME,

    EM_AROUND_SIZE
};

//	스킬 타입 UI 표시 범위
enum EM_SKILLTYPE_UI
{
    EM_SKILLTYPE_PARTY	= 0,
    EM_SKILLTYPE_ALL,
    EM_SKILLTYPE_NONE,
    EM_SKILLTYPE_SIZE,
};

#endif // _RAN_PARAM_DEFINE_H_